CenterForOpenScience/ember-osf-web

app/user-quickfiles/controller.js
app/user-quickfiles/template.hbs

To add a link to the user's profile and a message below that informs users about files being publicly accessible on the Quick Files app.
- Turned the user's name into a link that will take you to their profile page on the OSF
- Added wording below the user's name that tells the users about files being public
Still kept the computed function in order to render the page's title with the right text.

Add notice to users about public files/add link to user profile

---

app/application/route.js
config/environment.js

An ember-osf-web side fix for version's dates to use UTC format:
https://openscience.atlassian.net/browse/EOSF-769
To format moment to use UTC format for all dates by default.

[EOSF-769] Globally set moment format

---

app/user-quickfiles/controller.js

When opening a file, if it doesn't yet have a guid, request one from the API, then transition to file detail route for the file.

[EOSF-767] Get guid from API then transition when guid not set

---

app/file-detail/controller.js

When a file doesn't yet have a guid, get one from the API and then transition instead of using file_redirect.

[EOSF-769] Get guid then transition instead of file_redirect

---

app/file-detail/controller.js
app/file-detail/template.hbs
app/styles/app.scss
package.json
tests/unit/file-detail/controller-test.js
yarn.lock

https://openscience.atlassian.net/browse/EOSF-770
To add edit features to the file-detail page on quickfiles.
- Add edit button to button bar, only accessible if the user is the owner of the files and if the files are actually editable
- Add delete button.  On click, delete button takes user back to quickfiles home page after deleting that file
- Add edit pane.  Will show the text of the file and is editable by the user/owner.  When the user clicks `Revert`, the text will go back to the way it was before their edits.  When they click `Save`, the updates will save as a new revision and the model will update with the new data.
Edit 10/25:
- Buttons were formatted to copy what it looks like currently on staging osf.io.  The only buttons with `btn-primary` class are `Download` and the …

[EOSF-770] Add edit features to file-detail page

---

app/file-detail/template.hbs

There are three ways to close the delete modal on the file-detail page: clicking the `x` and `Close` buttons or by clicking off of the modal.  At the moment, only the button clicks are being properly handled; when clicking off of the modal it will not change the value of the `open` computed value and will not be able to re-open the modal.
Add the `onHidden` property to the modal to use the `closeDeleteModal` function when the modal is hidden (mainly via clicking off of the modal itself).
None
https://openscience.atlassian.net/browse/EOSF-770

[EOSF-770] Add action for clicking off of the delete modal

---

app/file-detail/template.hbs
package.json
yarn.lock

To add more properties to the file-browser on the file-detail page.  Properties added via https://github.com/CenterForOpenScience/ember-osf/pull/300#pullrequestreview-76130320
Set `multiple` to `false`, `unselect` to `false`, and `openOnSelect` to `true`.
https://openscience.atlassian.net/browse/EOSF-711

[EOSF-711] Update file-browser on file-detail page to take more properties

---

app/user-quickfiles/route.js
app/user-quickfiles/template.hbs
package.json
yarn.lock

Prevent the dropped file from being loaded into the browser when dropped outside of the drop zone.
Added global dragover and drop listeners that prevent default action and effects if the target is not the drop zone. 
Make sure this works in all browsers.
https://openscience.atlassian.net/browse/EOSF-921

[EOSF-921] prevent open in browser on drop outside dropzone

---

app/file-detail/controller.js
package.json
yarn.lock

Use the mime-types library (plus our extensions) to determine mime type for editability.
* Added ember-browserify
* Added mime-types
* Extend mime-types with custom type mapping and use it to look up mime type.
* .rtf will not be editable because mime-types >= 2.1.0 prefers application/rtf over text/rtf
* Make sure all text file types are editable.
https://openscience.atlassian.net/browse/EOSF-912

[EOSF-912] Add mime-types library and extend it to include custom types.

---

app/user-quickfiles/controller.js
app/user-quickfiles/template.hbs
tests/unit/user-quickfiles/controller-test.js

To remove the `Files uploaded here are publicly accessible and easy to share with others using the share link.` message if the user is not the owner of the quickfiles.
Add conditional to check if the user is the owner of the files to determine whether or not to show the message.
https://openscience.atlassian.net/browse/EOSF-925

[EOSF-925] Remove file upload message if not owner of files

---

app/file-detail/template.hbs
yarn.lock

To move some of the buttons around on the file-detail page to match the OSF file-detail page.
Moved `Download` and `Share` buttons.
https://openscience.atlassian.net/browse/EOSF-927

[EOSF-927] Move buttons around on file-detial page to match OSF

---

app/file-detail/template.hbs

Currently there aren't any icons on the SHA2 and MD5 headers on the revisions table.  We should add them to match the revisions table used on the normal OSF.
Add headers and ember-bootstrap pop-overs to match the OSF revisions table.
https://openscience.atlassian.net/browse/EOSF-910

[EOSF-910] Add icons and tooltips to revisions table headers

---

app/file-detail/controller.js
app/file-detail/route.js
app/file-detail/template.hbs
app/user-quickfiles/controller.js
app/user-quickfiles/route.js
config/environment.js
tests/unit/file-detail/controller-test.js
tests/unit/user-quickfiles/controller-test.js
tests/unit/user-quickfiles/route-test.js
yarn.lock

Upon the initial release of Quick Files, it would be great to monitor how things are being used.  This PR will add analytics to parts of Quick Files in order to track this.
Added analytics to:
- Upload drag and drop
- Upload button
- Copy share link
- Page visit by user who isn't the owner
- Download by user who isn't the owner
- Download zip by user who isn't the owner
- Upload by drag and drop
- Twitter share button
- Facebook share button
- LinkedIn share button
- Email share button
- Copy share link
- Page visit by user who isn't the owner
- Download by user who isn't the owner
https://openscience.atlassian.net/browse/EOSF-873
Is also related to the ember-osf PR: https://github.com/CenterForOpenScience/ember-osf/pull/298

[EOSF-873] Add analytics to Quick Files

---

app/file-detail/template.hbs

Currently quickfiles will show the tags widget to non-contributors even if there aren't any.  On the current OSF, the tags widget will not show up if this is the case.  We should add a conditional to only show the tags widget if there are tags in order to make things more consistent.  
Added conditional to check if there are tags/if the user can edit to decide if the tags widget should show or not.
If the user is a contributor, the tags widget will show up like normal on the page:
But if they are not the contributor and there aren't any tags, the widget will not show:
https://openscience.atlassian.net/browse/EOSF-937

[EOSF-937] Only show tags widget if there are tags for non-contributors

---

app/file-detail/controller.js
app/file-detail/template.hbs
app/styles/app.scss
app/user-quickfiles/controller.js
yarn.lock

When clicking on the version number link on the landing page, the user should be taken to the file-detail page with the revisions table shown.  This currently doesn't happen.  
Add a `shown` query parameter that toggles between views.  This makes it easier to link and go to a specific view.
https://openscience.atlassian.net/browse/EOSF-909
Relates to: 
https://github.com/CenterForOpenScience/ember-osf/pull/310

[EOSF-909] Add properties to toggle between view, edit, and revision views

---

app/user-quickfiles/route.js

The position of the `afterModel` hook on the `user-quickfiles` route is throwing linting errors.  `afterModel` should be moved to be right after the `model` hook to get rid of the error.
Moved the position of the afterModel call
https://openscience.atlassian.net/browse/EOSF-873

[EOSF-873] Move afterModel hook to after the model in user-quickfiles

---

app/styles/app.scss

In the case that a user enters in a ridiculously long tag, the tag won't break onto a new line.  Instead, the tag will just stretch out of the bounds of the tag widget.  We should make the tag break onto new line(s) when needed.
Add more styling to tags to prevent tags from going out of the tag-widget if there are REALLY long words.
https://openscience.atlassian.net/browse/EOSF-949

[EOSF-949] Add overflow-wrap and max-width to tags

---

app/components/quickfile-nav/template.hbs
app/styles/app.scss
yarn.lock

When viewing quickfiles on smaller devices, the navbar displays weird behavior.  The navbar should have styling changes that match expected behavior.
- Set a `min-height` of elements to keep height of navbar consistent
- Set `margin-left` for extra small screens to keep the element centered and off of the side
- Set `padding-left` and `padding-right` to add more space between text and element's boundary
- Add `line-height` to keep text centered vertically
** In the case of long names, more of the name will be displayed up to the edge of the page before overflowing
** Once it gets to a certain point, it will overflow hidden
https://openscience.atlassian.net/browse/EOSF-924

[EOSF-924] Make navbar more mobile friendly

---

app/file-detail/template.hbs
yarn.lock

Currently a user can drag and drop files onto the file-browser window in the file-detail page.  We should make the file-browser a static component that does not have a dropzone widget in it when it is in the small view.
In related ember-osf PR, added conditional computed alias of edit to determine if the dropzone widget should be enabled.  This PR passes through `dropzone=false` to the component to force the dropzone not to load.
This should be able to handle both drag/drop and clickable features of the dropzone widget on the file-detail page.  Users should not be able to do either of these methods on the file-detail page.
https://openscience.atlassian.net/browse/EOSF-951

[EOSF-951] Remove dropzone on file-detail page

---

app/index.html

If users do not have JavaScript enabled on their browser, ember-osf pages are displayed as blank white pages.  This will add an error message on the page that lets the user know what is happening and how to enable JavaScript to use the site.
- Added `<noscript>` message
https://openscience.atlassian.net/browse/EOSF-889

[EOSF-889] Add noscript message if javascript is disabled

---

app/file-detail/controller.js

When a user goes to the detail page for a quick file, there is a URL parameter that determines which view the user will be shown.  In the case that there isn't a URL parameter, the view breaks.  This will fix the issue by defaulting to the main view in the case that there isn't a parameter given.
- Default the controller to use the main view in the case that there isn't anything passed in
https://openscience.atlassian.net/browse/EOSF-909

[EOSF-909] Fix url param issue on file-detail

---

app/file-detail/controller.js

If the revision is changed on a file, that same number will persist as the revision number when switching between files.
- Revert `revision` to `null` when switching between files.
https://openscience.atlassian.net/browse/EOSF-962

[EOSF-962] Revert revision to null when switching between files

---

app/file-detail/route.js

Fix revision numbers persisting through route transitions.
Add a reset on the controller's routes to change `revision` back to `null`.
https://openscience.atlassian.net/browse/EOSF-962

[EOSF-962] Set revision number back to null on transition

---

app/index.html

Fix `noscript` message when JavaScript is disabled.
Change the wording of the `noscript` message to say: `For full functionality of this site it is necessary to enable JavaScript. Here are instructions for enabling JavaScript in your web browser.`
https://openscience.atlassian.net/browse/EOSF-889

[EOSF-889] Fix noscript message when JavaScript is disabled

---

app/file-detail/controller.js
app/file-detail/template.hbs
app/styles/app.scss

To remove the need for template lint exceptions for [triple-curlies](https://github.com/rwjblue/ember-template-lint/blob/master/docs/rule/triple-curlies.md) and [invalid-interactive](https://github.com/rwjblue/ember-template-lint/blob/master/docs/rule/invalid-interactive.md) on the file-detail page.
Also to make the mfr url box the same height as it's copy button.
- Used `htmlSafe` when making html strings to remove the `{{{  }}}`'s
- Added a role of `button` to the version number
- Also added a height of `33px` to the mfr url input box so that it is the same height as the copy button
https://openscience.atlassian.net/browse/EOSF-965

[EOSF-965] Remove need for lint exceptions on file-detail page

---

.stylelintrc.yml
CHANGELOG.md

Alphabetizing properties doesn't significantly improve readability. More importantly, I want to be able to add comments for related things. For example:
```css
.MyButton {
/* This is wacky */
background-color: rebeccapurple;
color: gray(30);
/* Reset styles */
border: none;
margin: 0;
width: auto;
overflow: visible;
}
```
Ignore the alphabetical property rule in stylelint
No ticket

Ignore alphabetical properties rule in stylelint

---

CHANGELOG.md
app/router.js
tests/unit/application/controller-test.js
tests/unit/application/route-test.js
tests/unit/quickfiles/route-test.js

Add analytics tracking to all route transitions in ember-osf-web, so we can tell whether people are using quickfiles.
Add logic to the router to track route transitions, à la [ember-metrics docs](https://github.com/poteto/ember-metrics#usage)
On initial load and each page transition, check that a GET request is made to https://www.google-analytics.com/collect with appropriate query params.
https://openscience.atlassian.net/browse/EMB-125

[EMB-125] Add analytics tracking for all route transitions

---

app/locales/ja/config.ts
app/locales/ja/translations.ts

Make a sample of the language profile for multilingual correspondence.
I made a new translations.ts under "ja" directory.
I needs to be updated when the English text on OSF increases.
- [*] DRY

Make a transcription profile in Japanese for "/ember-osf-web/app/locales"

---

app/application/route.ts
app/file-detail/controller.ts
app/index.html
app/utils/i18n/missing-message.js
package.json
yarn.lock

Adds translation support for the browser's preferred or default language, with fallback to the default locale. Follow-up from #83 by @Yusuke-KOMIYAMA 
- Adds dependency for automatically injecting the i18n service
- Overrides the default missing translation helper to fallback to the defaultLocale (defined in the configuration). The implementation is based on comments from jamesarosen/ember-i18n#256
- Better prerender support (had to update the application route anyway)
To test, add Japanese to the top of the languages in your browser preferences (Chrome/Firefox).
https://openscience.atlassian.net/browse/EMB-140

[EMB-140] i18n improvements

---

app/application/route.ts

Fixes the issue when you log out and log back in then go to your user-quickfiles page.
* Move application route beforeModel hook back to `Route.extend` defintiion
Log out, log back in, check the affected routes.
https://openscience.atlassian.net/browse/EMB-152
In order for beforeModel to bubble with this._super, it must be in the `Route.extend` definition.

[EMB-152] Move application route beforeModel hook to Route.extend

---

app/components/noteworthy-and-popular-project/template.hbs
tests/integration/components/noteworthy-and-popular-project/component-test.js

Make the New and Noteworthy as well as the Popular project lists show contributors on the dashboard
Pass the contributor information into the contributor list components instead of, say, the node information.
Before:
After:
Should be side-effect free.
https://openscience.atlassian.net/browse/EMB-164

[EMB-164] Show Popular contributors

---

app/components/new-project-modal/template.hbs
app/dashboard/controller.ts

Prevent reload of nodes when a user exits the new project modal on dashboard via the 'cancel' button.
Explicitly set reload as true or false when attached the `closeModal` action to a button, otherwise it will always be true to the presence of mouse event as the first default argument, even though reload is set to be false when no arguments are passed.
Exit the new project modal on dashboard via all the available option, both post and prior to actually creating a node. Make sure the nodes list is reloaded post-successful node creation, and is preserved otherwise.
https://openscience.atlassian.net/browse/EMB-166

[EMB-166] Explicitly pass 'reload' value for closeModal action on new-project-modal

---

app/application/template.hbs
app/locales/en/translations.ts
app/locales/ja/translations.ts
app/locales/zh/translations.ts
app/support/styles.scss
app/support/template.hbs

Product feedback changes to the support page
* Increases box shadow to compensate for the white background
* Makes links bold for readability
* Fix a typo in English translation and remove "for free".
N/A
https://openscience.atlassian.net/browse/EMB-109

[EMB-109] Support page fixes from demo

---

.eslintrc.js
app/adapters/osf-adapter.ts
app/authenticators/osf-cookie.js
app/components/dropzone-widget/component.js
app/components/file-browser/component.js
app/helpers/build-secondary-nav-links.js
app/services/file-manager.js
app/utils/load-relationship.js
app/utils/outside-click.js
node-tests/compile-and-test-translations.js
node-tests/translations-test.js
package.json
tests/integration/components/file-editor/component-test.js
tests/unit/adapters/osf-adapter-test.js
tests/unit/helpers/build-secondary-nav-links-test.js
yarn.lock

Reactivate some useful linting rules which were disabled over the weekend.
- Use `typescript` eslint plugin
- Enable [`typescript/no-unused-vars`](https://github.com/nzakas/eslint-plugin-typescript/blob/master/docs/rules/no-unused-vars.md)
- Switch the `no-unused-vars` override back to disable for type declaration files (`*.d.ts`), instead of all `.ts` files
- Reenable rules:
- [no-confusing-arrow](https://eslint.org/docs/rules/no-confusing-arrow)
- [indent-legacy](https://eslint.org/docs/rules/indent-legacy)
- [arrow-parens](https://eslint.org/docs/rules/arrow-parens)
- [ember/named-functions-in-promises](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/named-functions-in-promises.md) (as a warning)
- Fix new errors from those rules (mostly just `eslint --fix`)
- …

[No ticket] Reinstate some useful linting rules

---

app/components/file-browser/template.hbs

Move button is shown when not editing
Add an edit check
https://openscience.atlassian.net/browse/EMB-129

[EMB-129] Don't show move button when not editing

---

package.json
yarn.lock

The navbar has recently been changed to use flexbox styling instead of what we had before.
This PR updates `package.json` to use the latest merge commit for these changes in osf-style.  Will need to be updated to point to version after changes pass QA and are in an official release.
https://openscience.atlassian.net/browse/IN-95

[IN-95][Ember-OSF-Web] Update to use latest navbar changes in osf-style

---

CHANGELOG.md
app/components/new-navbar-auth-dropdown/component.js
app/components/new-navbar-auth-dropdown/styles.scss
app/components/new-navbar-auth-dropdown/template.hbs
app/components/new-osf-navbar/template.hbs

To update the format of the navbar to use changes in the latest `osf-style`
- Move  the `navbar-toggle collapsed` button to the right of the other elements in its container
- Added `secondary-nav-dropdown` class to the `new-navbar-auth-dropdown` component
- Changed classes and element tags to match styles needed for long name truncation
Just check that long names do not break to a new line.  It should truncate based on how much space it has in the navbar.
https://openscience.atlassian.net/browse/IN-95

[IN-95][Ember-OSF-Web] Update navbar to fit changes in osf-style

---

app/components/file-share-button/component.ts

Fix issue where share url query string is double encoded
Remove `encodeURIComponent()` on file download url
Make sure share link is valid
N/A

Let Handlebars encode the mfrUrl query string

---

app/components/file-browser/template.hbs
app/components/loading-indicator/template.hbs
app/dashboard/controller.ts
app/dashboard/styles.scss
app/dashboard/template.hbs

Improve the loading experience between request as users filter/sort their projects on dashboard. 
- Searching (filtering) now introduces a new loader, inside the input bar, when a filter is being requested
- Searching and sorting no longer replace current items with a loading icon. Instead, the current elements are less opaque and unable to be interacted with for the duration of the request.
https://openscience.atlassian.net/browse/EMB-168

[EMB-168] Improve between-requests loading experience in dashboard project viewer

---

package.json
yarn.lock

Fix the sign-up button height:
Update osf-style dependency to a commit with the fix.

[Fix] Update osf-style to fix sign-up button height

---

app/guid-file/controller.ts
app/guid-file/template.hbs
app/models/file.ts

Empty files (like a text file that had everything erased)  would cause the file editor to not show.
Make getContents a task, and check if fileText is null once completed, not if exists (since '' is falsy)
https://openscience.atlassian.net/browse/EMB-127

[EMB-127] Use task to get loading instance of file getContents to not show while loading

---

app/components/file-browser/component.js

Make edit behavior synchronous to current user's permission by hooking (indirectly) to the session service.
Make edit computed property check when currentUser changes (which in turn is computed from the session) as well as user is loaded.
Whoever merges this, feel free to close the branch, accidentally pointed to cos's branch rather than mine.
https://openscience.atlassian.net/browse/EMB-128

[EMB-128] Make edit computed property reload when currentUser does 

---

app/dashboard/controller.ts

Projects with HTML special characters in their title could not be filtered properly, as they are stored encoded (and presented as such through the api).
Encode HTML special chars to allow for proper filtering.
https://openscience.atlassian.net/browse/EMB-182

[EMB-182] Convert html special chars before filtering

---

app/components/institution-carousel/template.hbs

Show institutions that are not the first institution on the dashboard
Reverted some for loops to what they were before a change
Before:
After:
Shouldn't be any side effects, although I have a suspicion we may not be checking for 5 projects per institution and we're showing all of the insitutions regardless.
https://openscience.atlassian.net/browse/EMB-184

[EMB-184] Show slides and institutions

---

app/application/route.ts
app/components/file-browser/component.ts
app/dashboard/controller.ts
app/guid-user/quickfiles/route.ts
app/instance-initializers/prerender.ts
app/resolve-guid/resolved-guid-route.ts
app/router.ts
app/services/current-user.ts
app/services/ready.ts
tests/unit/application/controller-test.ts
tests/unit/application/route-test.ts
tests/unit/dashboard/route-test.js
tests/unit/guid-file/controller-test.ts
tests/unit/guid-user/quickfiles/controller-test.ts
tests/unit/guid-user/quickfiles/route-test.ts
tests/unit/instance-initializers/prerender-test.ts
tests/unit/quickfiles/route-test.ts
tests/unit/services/ready-test.ts

Wait to set `window.prerenderReady = true` until all relevant data loading and rendering has finished.
- Add `ready` service that allows different parts of the app to report when they're done loading, and delaying actions until the whole app is ready.
- `blocker = ready.block()`: Blocks ready actions until `blocker.done()` is called.
- `ready.get('isReady')`: Boolean set to `true` when all blockers are done and all rendering activity has settled.
- `ready.ready()`: Promise that resolves when `isReady` is set to true.
- Once the initial load is complete and `ready.isReady` is true, the service stops doing anything and `ready.block()` returns blockers with no-op methods.
- Use `ready` service to set `window.prerenderReady` once the initial transition has completed and all data has loaded …

[EMB-180] Set `prerenderReady` when ready

---

app/components/osf-navbar/component.ts
app/components/osf-navbar/home-links/component.ts
app/components/osf-navbar/home-links/template.hbs
app/components/osf-navbar/template.hbs

Make the secondary nav close when clicking on internal ember-osf-web links
- Add action handler to home-links component for closing the nav
- Add action to *ahem* List Item surrounding the links to catch the click
- *ahem* Disable the template linting rule for ^^^
- Fix close secondary nav on nav-bar to work for clicking the home link
If we hate adding an action to the `<li>` tags, I could put a span around the button and attach the action to that instead, but trying to do it on the clickAction handler of the link-to helper just wasn't working; instead it would cause a full page reload.
https://openscience.atlassian.net/browse/EMB-195

[EMB-195] Close secondary nav when using link-to on nav bar items

---

app/application/route.ts
app/components/dashboard-item/component.ts
app/components/file-browser-item/component.ts
tests/unit/application/route-test.ts

We're displaying times in UTC. Legacy OSF uses the browser's local timezone. We should do that.
Don't explicitly set UTC.

Use browser's timezone, not UTC

---

app/components/file-browser/styles.scss
app/components/file-browser/template.hbs
app/components/file-list-item/styles.scss
app/components/file-list-item/template.hbs
app/components/file-list/styles.scss
app/components/file-version/template.hbs
app/components/sort-button/styles.scss
app/dashboard/styles.scss
app/dashboard/template.hbs
app/guid-file/styles.scss
app/guid-file/template.hbs
app/styles/_global.scss

Fix up some CSS issues from Emberizing/Refactoring
* Table sort button alignment (Dashboard and Quickfiles)
* File detail page, file name truncation
* Copy button height / alignment
* MFR spacing (added margin to the bottom of the last row)
https://openscience.atlassian.net/browse/EMB-197

[EMB-197] Fix some CSS

---

.eslintrc.js
app/components/file-renderer/component.ts
app/components/file-renderer/template.hbs
package.json
tests/.eslintrc.js

Show loading indicator when switching files on Quick File File Detail.
Reset loader state when the file download link changes.
Loading indicator should now show on initial load and when switching files.
https://openscience.atlassian.net/browse/EMB-137

[EMB-137] reset loader state on file change

---

app/components/file-browser/styles.scss
app/components/sort-button/styles.scss
app/dashboard/styles.scss

Set file-browser to `vertical-align: bottom`, but this should have no real impact.
The dashboard header should now be aligned for all browsers:
https://openscience.atlassian.net/browse/EMB-197

[EMB-197] Table header alignment -> bottom

---

app/components/dashboard-item/component.ts

Fix a bug in dashboard item ancestry, where a private parent would prevent the root from showing.
If a node's parent is not visible to the current user, sometimes the parent relation's id will have the parent guid, while other times the id will be null. For that reason, don't use the parent id to tell whether a node has ancestors at all. Instead, check whether the node is its own root.
If the user:
- **can** see a node
- **cannot** see the node's parent
- **can** see the node's root
then the displayed dashboard item should be `root / node` instead of just `node`
https://openscience.atlassian.net/browse/EMB-190

[EMB-190][Fix] Don't assume null parentId means no ancestors

---

app/home/controller.ts
app/locales/en/translations.ts
app/locales/ja/translations.ts
app/locales/zh/translations.ts
app/models/user-registration.ts

Unhandled 400 API error if the the email address is already registered
* Add an exclusion to the model and push the current email address into the exclusions array
* Update translations with the appropriate message
* Decorators for home controller
Slightly different message and placement of the message from production, but this follows the standard ember-cp-validations workflow and shows it under the invalid email field instead of at the bottom of the form.
To test, simply try to register with an existing email and you should see the error message under the first email field.
https://openscience.atlassian.net/browse/EMB-211

[EMB-211] Handle email already registered error in signup on home page

---

app/components/validated-input/component.ts

reCAPTCHA error message not shown
Boolean _or_ operator (`||`) takes precedence over the ternary operator `? :`
use defaultTo
order imports
As previously stated in #180 this is a separate issue from handling 400 errors from the API.
https://openscience.atlassian.net/browse/EMB-215

[EMB-215] validated-input: ternary -> boolean, use defaultTo, condense imports

---

ember-cli-build.js
package.json
tsconfig.json
yarn.lock

Get TypeScript source maps working AND use them for code coverage.
* update tsconfig.json to emit inline source maps and sources
* enable inline source maps for babel
* use bleeding edge ember-cli-code-coverage, which includes https://github.com/kategengler/ember-cli-code-coverage/pull/164
n/a
n/a

Update config to get TypeScript source maps working

---

app/dashboard/controller.ts

We lost the loading indication on the dashboard filter, and also there was an edge case where if you had projects and filtered all of them out, when you cleared the filter, it would show the "You should make a project" state rather than a loading state.
1. Add back in proper tracking of "loading" state
2. Ensure that we don't show the "you have no projects" if the filter task is running
Should be much better now.
https://openscience.atlassian.net/browse/EMB-228

[EMB-228] Restore loading indication and fix edge case

---

app/dashboard/controller.ts

Any change to the dashboard filtering/sorting should cause a dim. This ensures that
1. Move the loading set out of the filtering wrapper and into the task that actually does the filtering.
This should be all better for any similar cases.
https://openscience.atlassian.net/browse/EMB-228
- ~[ ] testable and includes test(s)~
- ~[ ] changes described in `CHANGELOG.md`~

[EMB-228] Dim dashboard projects on sort

---

app/models/osf-model.ts
app/serializers/contributor.ts
app/serializers/review-action.ts

Neither contributors nor noteworthy/popular projects are showing up on the dashboard.
- Map contributor `users` in the API to `user` in ember models.
- Move `OsfModel.queryHasManyTask` to the prototype. For some reason `this.get('queryHasManyTask')` would return undefined otherwise.
Look at the dashboard, check there are contributors in the project list and noteworthy/popular projects below.
https://openscience.atlassian.net/browse/EMB-232

[EMB-232] Dashboard bugfixes

---

package.json
yarn.lock

Needed to swap out the reCAPTCHA url for China
Upgrade ember-g-recaptcha to 0.7.0
N/A

Upgrade ember-g-recaptcha to support alternate jsUrl for China

---

app/components/dropzone-widget/component.ts

Fix silent failing of multiple file and directory drops in quickfiles (dropzone-widget).
Fix the context of this.i18n.
https://openscience.atlassian.net/browse/EMB-236

[EMB-236] Fix dropzone error messages by correcting i18n context'

---

app/components/dropzone-widget/component.ts
app/components/file-list/component.ts
app/components/project-selector/component.ts
app/components/validated-input/component.ts
app/utils/default-to.ts
tests/unit/utils/default-to-test.ts

Fix the types fo the `defaultTo` utility, which were allowing invalid default values.
* adjust `defaultTo` types to not let invalid default values through
* fix invalid `defaultTo` usage with default values
Should not change behavior.
n/a

Fix defaultTo types

---

app/components/institution-carousel/component.ts
app/components/institution-carousel/template.hbs

On the institutional carousel, we were not handling the case where the number of institutions equaled the size of the slide. This corrects the two major problems from that.
1. Don't show controls if institutions.length > itemsPerSlide
2. Only subtract those numbers for offset if the institutions length is less than, not equal to, the items per slide
Note: I tried to do `@gt` instead of `@computed` but those decorators need values and not keys for the second parameter.
Should work for cases where there are more, the same, and fewer institutions on the server as there are items per slide.
https://openscience.atlassian.net/browse/EMB-234

[EMB-234] Handle institutions == slide length

---

app/components/osf-footer/styles.scss
app/styles/_global.scss

Footer in the middle of the page kind of looks weird, so let's fix it
Just CSS flexbox
It should always be at the bottom, but not covering any content
N/A

Make footer always go the 

---

app/helpers/get-ancestor-descriptor.ts

Locally (though, for some reason, not on staging) I'm getting the "You attempted to access a property of an ObjectProxy without using .get()" error when trying to move a Quick File (specifically, when trying to choose a project). I traced it back to overeager ungetting in the `get-ancestor-descriptor` helper (guilty).
use .get() for ObjectProxies in `get-ancestor-descriptor` helper
Ancestor descriptors should always work.
n/a

use .get() for ObjectProxies in get-ancestor-descriptor

---

.eslintrc.js
tests/unit/adapters/metaschema-test.ts

Use non-legacy indent rule. We can use this everywhere except `config/environment.d.ts`, because of https://github.com/eslint/typescript-eslint-parser/issues/458.
* only use legacy indent for [config/environment.d.ts](231/files#diff-e4403a877d80de653400d88d85e4801aR31)
* fix comment indentation in [tests/unit/adapters/metaschema-test.ts](231/files#diff-2b453e563c9892bb2fb49b62c6adf16eR7)
n/a
n/a

Use non-legacy indent

---

app/guid-file/template.hbs

Quick File tags weren't showing for unauthenticated users
Remove if block around tags widget that hid it from unauthenticated users. There's already a condition on the component to not let people edit tags if they're not contributors, so hiding the tags was just a step too far. Everyone deserves tags.
Shouldn't be. 
https://openscience.atlassian.net/browse/EMB-251

[EMB-251] Tags for everyone

---

app/components/file-browser/styles.scss
app/components/file-list/styles.scss

The height of the file-list component on the file detail page is not set properly, causing issues with the scrollbars (and the element itself) to overflow onto other elements
Generally, the scrollbars only show up if you're connected to a traditional mouse (vice a trackpad), but to enable the scrollbars (always) on OS X, go to System Preferences > General.
https://openscience.atlassian.net/browse/EMB-197

[EMB-197] Fix scrolling issues with flexbox

---

app/components/contributor-list/component.ts
app/serializers/osf-serializer.ts
tests/integration/components/contributor-list/component-test.ts

Embeds no longer receive meta
Contributor-links does not show true total of contributors
Make embeds keep their meta, and contributor-links using meta.total
Make sure nodes with more than 10 projects show the proper number of contributors on ` and x more ` in the dashboard
https://openscience.atlassian.net/browse/EMB-250

[EMB-250] Allow embeds to keep meta

---

app/guid-file/template.hbs

Pull back a bit on showing tags. If the quickfiles user is not the same as the current user, tags should show if there are tags on a quick file, but should not show if there are no tags. If the current user is the quickfiles user, the tag widget should always show.
1. Revert previous change (i.e. put the if statement back)
2. Change the second half of the or condition to use a real property, and not a property that was changed at some point in the last couple of months.
This one should be much better. Although wouldn't it be awesome if we knew that we tried to access an invalid property or variable in a template?
https://openscience.atlassian.net/browse/EMB-251

[EMB-251] Nuanced tag display

---

app/components/file-browser/template.hbs
app/guid-file/styles.scss
app/guid-file/template.hbs

Long quick filenames don't wrap in the title of the file detail page or in the "delete multiple modal".
https://openscience.atlassian.net/browse/EMB-248

[EMB-248] Handle long quick filenames

---

app/session-stores/application.ts
types/ember-simple-auth/session-stores/session-storage.d.ts

ember-simple-auth stores session information in localStorage by default. This causes issues when closing and re-opening the browser. Our cookies are session-based, so it's appropriate to use sessionStorage in this case.
Implements the session-store from ember-simple-auth (See https://github.com/simplabs/ember-simple-auth#sessionstorage-store)
Steps to reproduce the current error:
1. Log in (wait for redirect back to OSF)
2. Clear cookies
3. Force quit browser (Alt + Right click in Dock)
4. Go to an ember page
5. You should see the logged in Navbar and if you click on Home, it will take you to a broken dashboard page
After applying this fix, you should see the normal logged out pages.
N/A

[EMB-256] Use session storage instead of local storage

---

app/models/osf-model.ts
package.json
yarn.lock

Upgrade to [ember-cli-typescript 1.3.0](https://github.com/typed-ember/ember-cli-typescript/releases/tag/v1.3.0)
* upgrade to ember-cli-typescript 1.3.0
* adjust type wrangling of argument to `adapterFor()` in `OsfModel.queryHasMany()`
N/A
N/A

Upgrade ember-cli-typescript

---

app/components/osf-logo/styles.scss
app/home/styles.scss
app/home/template.hbs
package.json
yarn.lock

FIx home logo + animation for IE and Edge
* Reverts #249 and #251
* Add autoprefixer for CSS
* IE and Edge don't respect the `calc` function inside transform: rotate (possibly other places), so just use sass for that.
https://openscience.atlassian.net/browse/EMB-261

[EMB-261] Fix OSF logo CSS for IE & Edge, add autoprefixer

---

app/components/noteworthy-and-popular-project/styles.scss
app/components/noteworthy-and-popular-project/template.hbs

fix overflowing long names in new & noteworthy
Use `display: block` for byline spans so they enforce the `prevent-overflow` class.
Make sure it works for names of all lengths.
https://openscience.atlassian.net/browse/EMB-264

[EMB-264] fix overflowing long names in new & noteworthy

---

.eslintrc.js
app/components/dashboard-item/component.ts
app/components/file-browser/component.ts
app/components/maintenance-banner/component.ts
app/components/osf-navbar/auth-dropdown/component.ts
app/components/project-selector/component.ts
app/components/sign-up-form/component.ts
app/dashboard/controller.ts
app/guid-file/controller.ts
app/guid-file/route.ts
app/guid-user/quickfiles/controller.ts
app/guid-user/quickfiles/route.ts
app/home/controller.ts
app/models/osf-model.ts
app/resolve-guid/resolved-guid-route.ts
app/router.ts
app/services/analytics.ts
app/services/current-user.ts
app/services/ready.ts
app/utils/i18n/missing-message.ts
tests/integration/components/file-list-item/component-test.ts
tests/integration/components/file-list/component-test.ts
tests/integration/components/file-renderer/component-test.ts
tests/integration/components/new-project-modal/component-test.ts
tests/integration/components/sort-button/component-test.ts
tests/integration/components/validated-input/component-test.ts
tests/unit/models/user-registration.ts
tests/unit/serializers/user-registration-test.ts
tests/unit/services/analytics-test.ts
tslint.json

Anonymous functions should be consistent with their spacing. `function()`, not `function ()`.
Lint it up.
There wasn't a rule enabled for this before because eslint and tslint rules conflicted on generator functions. If they're changed to expect `function *(` instead of `function* (`, they can live in harmony.
n/a

Enforce consistent spacing before function parens

---

package.json
yarn.lock

We were pinned to commit because https://github.com/kategengler/ember-cli-code-coverage/commit/77b5b9201060d634d281f64a5bb7b412773a8b89 which is necessary for TypeScript support had not yet been included in a release. It is now included in ember-cli-code-coverage 1.0.0-beta.4.
Upgrade to ember-cli-code-coverage 1.0.0-beta.4
n/a
n/a

Upgrade to ember-cli-code-coverage 1.0.0-beta.4

---

package.json
yarn.lock

ember-power-select 2.0.0 has been released, so we should use it.
Upgrade to ember-power-select 2.0.0
n/a
n/a

Use stable version of ember-power-select

---

.eslintrc.js
types/ember-simple-auth/mixins/data-adapter-mixin.d.ts
types/ember-sinon-qunit/test-support/test.d.ts

The `no-restricted-globals` rule really doesn't apply with regard to TypeScript declaration files, so disable it for them.
Disable no-restricted-globals for declaration files
n/a
n/a

Disable no-restricted-globals for declaration files

---

package.json
yarn.lock

Current version of lint-staged complains when used with Node 10
Upgrade to latest lint-staged for Node 10 support
n/a
n/a

Upgrade to latest lint-staged for Node 10 support

---

app/dashboard/controller.ts
app/guid-user/quickfiles/controller.ts
app/home/controller.ts

These properties are all initialized in setupController, so they should be marked as such instead. In the case `filter` in the dashboard controller. It is initialized to `null` in setupController, so it does not not need to be initialized here.
Mark controller properties inited in setupController as inited
n/a
n/a

Mark controller properties inited in setupController as inited

---

CHANGELOG.md
app/application/route.ts
config/environment.d.ts
config/environment.js

Enable i18n locales with config
* get `i18n.enabledLocales` config by splitting `ENABLED_LOCALES` env variable on comma and space.
* check that detected browser locale is in `i18n.enabledLocales` before setting it
Only `en` and `en-US` locales are enabled by default.
n/a

Enable i18n locales with config

---

package.json
types/@ember-decorators/data.d.ts
yarn.lock

Simplify our overrides of `@ember-decorators/data` types now that https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25282 has been released.
* Use latest @types/ember-data
* Use DS.AttrOptions and DS.RelationshipOptions
n/a
n/a

Simplify ember decorators data types

---

app/components/contributor-list/component.ts
app/components/contributor-list/contributor/template.hbs
app/components/node-blurb/styles.scss
app/guid-node/forks/template.hbs
app/institutions/styles.scss
app/institutions/template.hbs

- Remove images for very small screens in the institutions landing page
- Make non-registered users not show up as links for contributor lists
- Make spacing better on contributor list

Fix contirbutor-list links, spacing, and small screens for institutions landing page

---

app/components/osf-navbar/component.ts
app/const/service-links.ts
app/router.ts
config/environment.d.ts
config/environment.js

Improve types for route feature flags and add the missing forks route flag. These changes will restrict references to only known route flags, but you can typecast to string index type to still allow lookup based on a variable (e.g. transition target route name, as demonstrated in `app/router.ts`).
Improve types for route feature flags and add the missing forks route flag.
Each route flag key will need to be added to `config/environment.d.ts`
n/a

Better feature flag types and add forks route flag

---

app/home/template.hbs

Fix bug with youtube modal:
- On the logged out home page, click on the youtube link, a modal will pop up. Close the modal using the `x` 
- Click on the support page on the toolbar
-  Click back on the home page using the toolbar
- The modal pops back up (it shouldn't)
https://openscience.atlassian.net/browse/EMB-296

[EMB-296] Add explictly making modalOpen false when hiding modal

---

CHANGELOG.md
app/adapters/osf-adapter.ts
app/application/template.hbs
app/components/tos-consent-banner/component.ts
app/components/tos-consent-banner/styles.scss
app/components/tos-consent-banner/template.hbs
app/locales/en/translations.ts
app/locales/ja/translations.ts
app/locales/zh/translations.ts
app/models/user.ts
app/router.ts
app/serializers/osf-serializer.ts
app/services/current-user.ts
tests/integration/components/tos-consent-banner/component-test.ts
types/ember-data-factory-guy/index.d.ts

Add a banner to ask users to consent to Terms of Service.
* add `acceptedTermsOfService` to `user` model
* add Terms of Service consent banner
* added `tos-consent-banner` component
* added tracking of when to show it to currentUser service
* added `tos-consent-banner` to application template
* added check that relationships exist before iterating on them (osf-serializer)
* make sure record snapshot exists before getting links (for mocked models)
* more ember-data-factory-guy types
* added integration tests for `tos-consent-banner` component
Make sure it does not display for logged out users, displays for existing users that have not consented, and does not display for users that have consented.
https://openscience.atlassian.net/browse/EMB-304

[EMB-304] GDPR ToS consent banner

---

lib/osf-components/addon/components/validated-input/component.ts

Today treating the `computed` export from `@ember/object` as a namespace for computed macros works because of the way the module shims happen to be implemented, but there's no guarantee in the future that that will continue to work.
This switches to pulling the macros by name from `@ember/object/computed` to future-proof the import, as well as being compatible with planned updates to `@types/ember`.
N/A
N/A

Import Ember.computed.* macros directly

---

lib/osf-components/addon/components/osf-navbar/auth-dropdown/component.ts
lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs

Avoid a [CAS error](https://openscience.atlassian.net/browse/SVCS-821) when multiple tabs try to log out at the same time.
When the user clicks the logout button, navigate to `/logout` **without** first invalidating the ember-simple-auth session. When CAS redirects back to the app, the session will [fail to restore and be invalidated](https://github.com/CenterForOpenScience/ember-osf-web/blob/develop/app/authenticators/osf-cookie.ts#L56). Then, all other open tabs will log themselves out.
If the browser doesn't get back to the ember app after logging out, other tabs might still think they're logged in. This is unlikely to happen.
https://openscience.atlassian.net/browse/EMB-196

[EMB-196] When logging out, only bother CAS once.

---

CHANGELOG.md
config/environment.d.ts
config/environment.js

By default, `ember-cli-mirage` enables mirage in development mode (it's always enabled in testing mode and never enabled in production). This can be useful for developing without needing to start the backend or before a back-end feature has been implemented, but not something we want on by default. This adds a flag to enable mirage in development (disabled by default) that can be set via an environment variable or `config/local.js`.
Add a flag to enable mirage in development environment.
n/a
n/a

Add flag to enable mirage in development mode

---

app/models/user.ts
app/services/current-user.ts

https://github.com/CenterForOpenScience/osf.io/commit/3a0227d0dc3b67460e4ae5e1661ff8d09334ca8c changed accepted_terms_of_service to be more correct (always a boolean), but caused the TOS Consent Banner to prematurely show a validation error. This unsets the property if falsy to avoid premature validation.
* Unset acceptedTermsOfService when falsy
* No longer allow null for user.acceptedTermsOfService
Make sure consent banner does not prematurely validate.
https://openscience.atlassian.net/browse/EMB-304

[EMB-304] Unset acceptedTermsOfService when falsy

---

CHANGELOG.md
app/models/user-registration.ts

The fullName field length validation was set to 255 when it should have been 200. Also, email was not being validated for length at all.
* Adjust max length for fullName on user-registration validation
* Add max length validation to email1 field
Double-check length validations.
https://openscience.atlassian.net/browse/EMB-308

[EMB-308] fix username length validation on landing page

---

tests/integration/components/tos-consent-banner/component-test.ts

Re-enable test disabled in hotfix to master.
* Re-enable show ToS Consent banner test
n/a
n/a

Re-enable show ToS Consent banner test

---

CHANGELOG.md
lib/osf-components/addon/components/sign-up-form/component.ts
lib/osf-components/addon/components/sign-up-form/template.hbs
tests/acceptance/logged-out-home-page-test.ts

Only show captcha when form is valid to avoid submission of captcha with invalid data and reset captcha if server invalidates.
* Only show captcha when form is valid
* Adjust logged out home page acceptance test to expect this
The captcha won't appear until all fields are valid and ToS consent box is checked (e.g. form is ready to submit). Invalidating the form at this point will cause the captcha to disappear (regardless of if it has been completed). Once the form is valid again, the captcha is reset.
Double check there is no case where user is unable to submit when they should or able to submit when they shouldn't.
https://openscience.atlassian.net/browse/EMB-307

[EMB-307] Only show captcha when form is valid

---

CHANGELOG.md
app/index.html
config/environment.d.ts
config/environment.js
ember-cli-build.js

Serve assets for production builds from `/ember_osf_web/` while serving from `/` in development.
* make assets prefix configurable
* set to /ember_osf_web/ for prod builds
* use assets prefix for finding lazy-loaded engines assets
n/a
n/a

Make assets prefix configurable and set to /ember_osf_web/ for prod builds

---

app/home/styles.scss
app/home/template.hbs
lib/osf-components/addon/components/file-browser-item/styles.scss
lib/osf-components/addon/components/file-browser/styles.scss
lib/osf-components/addon/components/file-list-item/styles.scss
lib/osf-components/addon/components/file-version/styles.scss
lib/osf-components/addon/components/inline-list/component.ts
lib/osf-components/addon/components/maintenance-banner/component.ts
lib/osf-components/addon/components/maintenance-banner/styles.scss
lib/osf-components/addon/components/sign-up-form/styles.scss
lib/osf-components/addon/components/sign-up-form/template.hbs
tests/integration/components/contributor-list/component-test.ts

Fix CSS regressions
* Remove maintenance banner bottom margin
* Remove goodbye banner bottom margin
* Fix password strength indicator and other sign-up form CSS tweaks
* Move signUp anchor up
* Kill wrapper div for inline-list component
* Fix left padding on QF detail file list
* Fix padding for QF file-version buttons
* Fix file browser padding issues
I did some additional CSS tweaking to get things looking like production.
https://openscience.atlassian.net/browse/EMB-298

[EMB-298] fix css regressions

---

CHANGELOG.md
config/environment.d.ts
config/environment.js
ember-cli-build.js

Disable lint-on-build and sourcemap generation by default to speed up build times in default config. Devs can enable each locally by setting `LINT_ON_BUILD` and/or `SOURCEMAPS_ENABLED` to a truthy value.
* Made `config.lintOnBuild` false by default and changed ENV var name to `LINT_ON_BUILD`
* Added `SOURCEMAPS_ENABLED` ENV var to control sourcemap generation (disabled by default)
Faster builds!
n/a

Disable lint-on-build and sourcemap generation by default

---

CHANGELOG.md
config/environment.js
lib/assets-prefix-middleware/index.js
lib/assets-prefix-middleware/package.json
package.json
tests/test-helper.ts

Because of https://github.com/CenterForOpenScience/osf.io/pull/8371/files#diff-758f58f82207e3674b3105d2b3d4ce7aR1679 we can't server Ember assets from `/assets/` (even in development) when serving through Flask, so this sets the default to `/ember_osf_web/` for all builds (not just production). The `ASSETS_PREFIX` remains configurable and can be set to `'/'` locally for directly serving on 4200. Additionally, this PR strips the `/ember_osf_web` prefix from the asset manifest so that test will continue to run, whether run in the development environment with `localhost:4200/tests` or in the test environment via `ember test`.
* Set default assets prefix to /ember_osf_web/ for all environments
* Add express middleware to serve assets from assets prefix
* Set assets prefix to `/` in test …

Use ember osf web asset prefix for all builds

---

lib/osf-components/addon/components/file-browser-item/component.ts
lib/osf-components/addon/components/file-browser-item/styles.scss
lib/osf-components/addon/components/file-browser/component.ts
lib/osf-components/addon/components/file-browser/styles.scss
lib/osf-components/addon/components/file-browser/template.hbs

QA found a couple of style issues when there are no existing items:
* progress indicator not showing for first uploaded file
* mis-alignment of first file while uploading
This PR also fixes an issue with alignment of Quick Files header columns with item columns and vertical centering of item text.
* Refactor file-browser template to use the same "uploading" section whether or not there existing items
* Apply bootstrap container class to file-browser items to keep them at a fixed width regardless of the presence of a scrollbar
* Increase top padding to better vertically center text.
* Localize some local classes.
Check first file upload with no existing items and upload with existing items. Also check file list with more items than will fit vertically so that a scrollbar appears. …

[EMB-298] Fix Quick Files alignment/style issues

---

config/environment.d.ts
config/environment.js
package.json
yarn.lock

Anonymize IPs sent to google analytics
Switch ember-metrics to a cos-fork that allows setting fields, and configure it to add anonymizeIp: true
Main visible effect: Requests sent to google analytics now have the query param `aip=1`.
https://openscience.atlassian.net/browse/EMB-326

[EMB-326] Set `anonymizeIp` true for google analytics

---

CHANGELOG.md
lib/osf-components/addon/components/node-navbar/component.ts
lib/osf-components/addon/components/node-navbar/styles.scss
lib/osf-components/addon/components/node-navbar/template.hbs

Prevent node-navbar from overlapping banners.
* Move node-navbar buffer inside wormhole and adjust to height
Make sure it works with various (and no) banners enabled.
n/a

Move node-navbar buffer inside wormhole and adjust to height

---

lib/analytics-page/addon/application/styles.scss

The analytics tab has three bootstrap columns that are also flexwrapped. That causes them to do this:
Remove the wrap so that it looks like
Tested in the browser by modifying the CSS, not yet tested locally because docker. Should be _fine_.

Remove unnecessary and overzealous wrapping

---

.travis.yml
CHANGELOG.md
app/application/controller.ts
app/application/template.hbs
config/environment.js
lib/handbook/config/environment.js
lib/handbook/index.js

Auto-deploy handbook to GitHub pages when travis runs for the `develop` branch
* make `rootURL` configurable via environment variable
* make `MIRAGE_ENABLED` environment variable apply to all build environments except `test`
* use `assetsPrefix` for handbook `assetsUrlPath`
* enable lazy loading for handbook engine
* configure Travis to build and deploy the handbook to GitHub pages as a separate build stage that is only run for the `develop` branch
Example build with deploy: https://travis-ci.org/jamescdavis/ember-osf-web/builds/397410596
(when this build ran, was configured to deploy for `deploy_github_pages` branch, since changed to `develop`)
Deployed to: https://jamescdavis.github.io/ember-osf-web/handbook
Example build on branch that shouldn't deploy: …

Auto-deploy handbook to GitHub pages

---

CHANGELOG.md
app/app.ts
app/locales/en/translations.ts
app/locales/ja/translations.ts
app/locales/zh/translations.ts
lib/analytics-page/addon/application/template.hbs
lib/analytics-page/addon/engine.js
lib/analytics-page/package.json
lib/osf-components/addon/components/simple-paginator/template.hbs
tests/assertions/has-text.ts
tests/assertions/includes-text.ts
tests/assertions/not-has-text.ts
tests/assertions/not-includes-text.ts
tests/integration/components/simple-paginator/component-test.ts

Set `<title>` on the analytics page, and make pagination controls more old-browser-friendly.
Pass everything needed for the `{{title}}` helper to work into the `analytics-page` engine, then use `{{title}}`.
Use `&gt;` and `&lt;` instead of font-awesome chevrons:
Pagination controls on the forks page and analytics links popup are affected.
The title on the analytics page should now be "OSF | [node title] Analytics" instead of just "OSF".
https://openscience.atlassian.net/browse/EMB-334

[EMB-334] Analytics title, pagination controls

---

.vscode/settings.json
.watchmanconfig
README.md

Changes based on Visual Studio Code [settings.json](https://github.com/Microsoft/vscode/blob/master/.vscode/settings.json) file.
Exclude `node_modules` from watchman, *cough* 1.3 GB or 1.5 million files... [discussion](https://facebook.github.io/watchman/docs/install.html#mac-os-file-descriptor-limits)
Document OSX [kernel file limitations](https://facebook.github.io/watchman/docs/install.html#mac-os-file-descriptor-limits) and a fix since I personally got bit by this one... and I'm running OSX 10.13.5...

Tidy up development settings

---

CHANGELOG.md
app/dashboard/controller.ts
app/guid-file/controller.ts
app/guid-file/template.hbs
app/guid-user/quickfiles/controller.ts
app/institutions/controller.ts
app/institutions/route.ts
app/institutions/template.hbs
app/locales/en/translations.ts
app/locales/ja/translations.ts
app/locales/zh/translations.ts
app/services/analytics.ts
lib/osf-components/addon/components/file-browser/component.ts
lib/osf-components/addon/components/file-list-item/component.ts
lib/osf-components/addon/components/file-list-item/template.hbs
lib/osf-components/addon/components/file-version/component.ts

Send analytics events for page views and user actions that should have been tracked all along
New events:
* Dashboard page:
* `Dashboard - Search projects`
* Quick files detail page:
* `Quick Files - Filter file browser`
* `Quick Files - Delete file`
* `Quick Files - Open delete modal`
* `Quick Files - Close delete modal`
* `Quick Files - Change view - edit`
* `Quick Files - Change view - revision`
* `Quick Files - Change view - view`
* `Quick Files - Change view - view_edit`
* `Quick Files - Save`
* `Quick Files - Open file`
* `Quick Files - Add tag`
* `Quick Files - Remove tag`
* `Quick Files - Search by tag`
* `File version - Download`
* `File version - Change version`
* Institutions landing page
* Page view
* `Institutions - Search`
* `Institutions - Next page`
* `Institutions - …

[EMB-333] Add missing analytics events

---

lib/handbook/addon/docs/template.hbs

No point linking to handbook pages that just say "TODO"

Remove empty handbook pages from the side nav

---

CHANGELOG.md
app/adapters/banner.ts
app/dashboard/template.hbs
app/home/template.hbs
app/models/banner.ts
app/serializers/banner.ts
lib/osf-components/addon/components/scheduled-banner/component.ts
lib/osf-components/addon/components/scheduled-banner/styles.scss
lib/osf-components/addon/components/scheduled-banner/template.hbs
lib/osf-components/addon/components/scheduled-banner/x-maybe-link/component.ts
lib/osf-components/addon/components/scheduled-banner/x-maybe-link/template.hbs
lib/osf-components/app/components/scheduled-banner/component.ts
lib/osf-components/app/components/scheduled-banner/x-maybe-link/component.ts
mirage/config.js
tests/unit/models/banner-test.ts

When a banner is created in the admin, display it on the landing page (home/dashboard).
* Add `banner` model/adapter/serializer, for fetching `/_/banners/current/`
* Add `scheduled-banner` component, to display that banner on the dashboard and home page
* Should have exactly the same behavior as the banner in registries and preprints
https://openscience.atlassian.net/browse/EMB-314

[EMB-314] Display a banner from the API

---

CHANGELOG.md
config/environment.d.ts
config/environment.js
lib/osf-components/addon/components/maintenance-banner/component.ts
lib/osf-components/addon/components/maintenance-banner/template.hbs

Ensure that the maintenance banner respects the cookies that the OSF sets and also sets those cookies. This will let people dismiss the maintenance banner from either place and not see it pop back up again for a day.
1. Add a cookie to the settings
2. Modify the `maintenance-banner` component to like and use cookies
3. Modify the `maintenance-banner` template to send an action to set the cookie
Should be fairly side-effect free. Dismissing the status banner of legacy OSF should be reflected in ember-osf-web pages and vice-versa.

[EMB-327] Keep maintenance banner dismissed

---

app/locales/en/translations.ts
app/locales/ja/translations.ts
app/locales/zh/translations.ts
lib/osf-components/addon/components/osf-footer/template.hbs

Remove the google plus footer from the footer
1. Remove from footer
2. Remove translations strings related to google plus
Before
After
Nobody may go to our google plus site any more.
https://openscience.atlassian.net/browse/EMB-319

[EMB-319]Remove google plus from the footer

---

app/session-stores/application.ts
config/environment.d.ts
config/environment.js
types/ember-simple-auth/session-stores/adaptive.d.ts

When an embosf page is open in one tab and preprints (or maybe reviews?) in another tab, they try to store different auth data in local storage, using the same key. This causes an infinite loop of each app clobbering the other's data and making API requests, until one of the tabs is closed.
This might have been causing subtle, strange bugs in preprints, but it's hard to say what they might have looked like.
Configure ember-simple-auth's AdaptiveStore, changing the local storage key used.
- Open the dashboard and preprints in separate tabs (same environment, same browser)
- Open the devtools network tab in either/both tabs
- Previously, there would be repeated requests to `/v2/` (in embosf) or `/v2/users/me` (in preprints). Now, all should be calm. …

[EMB-351] Change local storage key used by ember-simple-auth

---

CHANGELOG.md
config/environment.js

Enable sourcemaps by default. It turns out the babel config setting of `sourceMaps: 'inline'` [just means adding the sourceMappingURL comment to the bottom of the outputted JS](https://babeljs.io/docs/en/babel-core.html#options), so this is safe to do in all environments. The TypeScript compiler is configured to inline sourcemaps (and sources), but Babel uses these to generate and external `.map` file. Sourcemaps in prod/test/stagings are needed for Sentry grouping as well as aid in debugging.
Babel sourcemap generation can be disabled locally, if so desired, to speed up build times, by setting `SOURCEMAPS_ENABLED: false` in `config/local.js`, but the speed-up is fairly negligible (see build time table below). 
You may also wish to set `inlineSourceMap` and `inlineSources` to `false` in …

Enable sourcemaps by default

---

app/metrics-adapters/keen.ts

Stop keen from saving IP Addresses
Added the line to the keen adapter per https://keen.io/docs/streams/ip-to-geo-enrichment/#ip-anonymization
You should notice in the staging public keen bucket, new page view counts from embosf pages will not have IP Addresses after this is merged.
https://openscience.atlassian.net/browse/EMB-346

[EMB-346] No IP address tracking

---

lib/handbook/addon/docs/components/bs-alert/demo-danger-hidden/template.hbs
lib/handbook/addon/docs/components/bs-alert/demo-info/template.hbs
lib/handbook/addon/docs/components/bs-alert/demo-warn-no-dismiss/template.hbs
lib/handbook/addon/docs/components/bs-alert/template.md
lib/handbook/addon/docs/template.hbs
lib/handbook/addon/routes.js
lib/handbook/index.js
lib/handbook/package.json

Make our docs slightly more complete with the `#bs-alert` component.
Add a bs-alert component with a couple of examples and a link to the docs
Shouldn't have too many side effects, really. Test with the handbook enabled on localhost:4200/handbook/docs/

Add #bs-alert to handbook

---

app/models/base-file-item.ts

`tsc --watch` (but not just `tsc` or `ember build`) is giving:
```
app/models/base-file-item.ts(42,9): error TS7022: 'isFile' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
app/models/base-file-item.ts(42,9): error TS7023: 'isFile' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
```
Refactoring to use native getters here prevents this.
Use native getters instead of `get` from `@ember/object`.
Should be no change, but maybe double-check that quick files functions properly?
N/A

Use native getters in BaseFileItem

---

.eslintrc.js
app/serializers/review-action.ts

Enable all the ember linting rules we can because...we can.
Enable the following linting rules:
* [ember/new-module-imports](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/new-module-imports.md)
* [ember/no-attrs-in-components](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-attrs-in-components.md)
* [ember/no-old-shims](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-old-shims.md)
Add one "exception" for `ember/no-attrs-in-components` because it apparently doesn't know what a component is.
Better code?
N/A
N/A

Enable more ember linting rules

---

CHANGELOG.md
mirage/fixtures/nodes.js
mirage/scenarios/default.js
tests/acceptance/dashboard-test.ts

No more icky Fixtures. Only Factories.
1. Delete fixtures directory
2. Update default scenario to use node factory instead of fixtures for NNW and Popular nodes
3. Update tests to use node factory instead of fixtures for NNW and Popular nodes
No need to test. Developer-only changes
N/A

Remove mirage fixtures

---

mirage/scenarios/default.js

Tests break if you set `POPULAR_LINKS_NODE` and/or `NEW_AND_NOTEWORTHY_LINKS_NODE` locally
Use the values from the ember config, which has the proper defaults in it
N/A
N/A
No QA needed
None

Get new & noteworth + popular node IDs from config

---

CHANGELOG.md
ember-cli-build.js

Never strip ember-test-selectors (even in production builds), because we want to use them for Selenium tests.
Add
```js
'ember-test-selectors': {
strip: false,
},
```
to `ember-cli-build.js`
Slightly larger bundle.
N/A
Should start seeing `data-test-*` attributes on elements that have been marked with them.
Try:
```js
document.querySelector('[data-test-quick-search-input]');
```
on the dashboard.
N/A

Don't strip ember-test-selectors from production builds

---

CHANGELOG.md
mirage/config.ts
mirage/factories/file.ts
mirage/factories/user.ts
mirage/models/user.js
mirage/serializers/application.ts
mirage/serializers/file.ts
mirage/serializers/node.ts
mirage/serializers/root.ts
mirage/serializers/user.ts
mirage/views/root.ts
mirage/views/user.ts
types/ember-cli-mirage/index.d.ts
types/osf-api.d.ts

Make mirage for ember-osf-web more complete. Note: you cannot go directly to a file detail page because the guid resolver could use a little extra work to handle that properly (and probably other guid situations). The details for that are available at 
https://openscience.atlassian.net/browse/EMB-379
1. Add support for non-relationship links
2. Add support for files
3. Replace user serialization on root with call to user serializer
4. Allow `type` and `id` on relationships to serialize correctly
No QA; this is all developer-facing
https://openscience.atlassian.net/browse/EMB-3368

[EMB-368] Add mirage support for files, user files, and root

---

app/guid-node/forks/controller.ts
app/guid-node/forks/template.hbs
app/guid-node/registrations/controller.ts
app/guid-node/registrations/template.hbs
app/guid-registration/forks/controller.ts
app/guid-registration/forks/template.hbs
lib/osf-components/addon/components/node-list/component.ts
lib/osf-components/addon/components/node-list/template.hbs
lib/osf-components/addon/components/paginated-list/base-data-component.ts

Fix a bug introduced in #387 that broke reloading paginated lists.
Alternative fix to #393 
The problem is we want `paginated-list/*` to own their data and be in charge of loading logic, to avoid duplication, but also want to trigger a reload from the parent scope. The solution used here is calling an action to send a bound function upward:
```hbs
{{paginated-list/... bindReload=(action (mut this.reload))}}
```
From the parent scope, `this.reload()` will trigger a reload.
This pattern of passing component actions upward could get messy if used more generally, though. We should probably avoid it in most circumstances. It seems acceptable in this specific situation: Telling a data-loading component to refresh itself.

[no-ticket] Fix creating registrations and forks

---

CHANGELOG.md
mirage/config.ts

Handbook search is currently non-functional because mirage is intercepting the request for the search index JSON file. This configures to Mirage to pass through all requests on the current domain, allowing dynamic load of any file in `dist`.
Mirage: pass through all requests on current domain
Shouldn't be any.
n/a
No QA needed.
n/a

[No Ticket] Fix handbook search

---

.template-lintrc.js
CHANGELOG.md

The upgrade to ember* 3.4 included upgrading ember-cli-template-lint to [1.0.0-beta.1](https://github.com/ember-template-lint/ember-cli-template-lint/blob/master/CHANGELOG.md#v100-beta1) (which ember-new-output [shows us](https://github.com/ember-cli/ember-new-output/blob/v3.4.3/package.json#L35) we would get with `ember new` using ember-cli 3.4). This version depends on [ember-template-lint 1.0.0-beta.2](https://github.com/ember-template-lint/ember-template-lint/blob/master/CHANGELOG.md#v100-beta2), which, along with [ember-template-lint 1.0.0-beta.1](https://github.com/ember-template-lint/ember-template-lint/blob/master/CHANGELOG.md#v100-beta1), includes quite a few new rules in the recommended set. This PR adds a bit of configuration for this new ruleset.
- Configure the …

[no ticket] Fix up template-lint rules

---

.template-lintrc.js
package.json
yarn.lock

ember-cli-template-lint 1.0 beta doesn't seem to be ready for prime time (despite being the default for ember-cli 3.4)
* `yarn upgrade ember-cli-template-line@^0.7.6`
* removed `attribute-indentation` rule config
n/a
n/a
n/a
n/a

Downgrade to ember-cli-template_lint 0.7.6

---

config/environment.d.ts
config/environment.js
lib/osf-components/addon/components/join-osf-banner/component.ts
lib/osf-components/addon/components/join-osf-banner/styles.scss
lib/osf-components/addon/components/join-osf-banner/template.hbs

In safari, you can dismiss the "join OSF" banner once, but then it comes back and is unkillable.
- Wrap the banner in an `{{#unless}}` block, so it's not even in the DOM if it's been previously dismissed.
- Make the dismissal a nice animated slide down, like on legacy.
- Move the local storage key into the config, rather than a hardcoded string.
n/a
n/a
Of course test in safari, and probably worth checking the new downward animation works in at least one other browser too.
- Open a private/incognito window
- Go to an embosf project page, like forks or analytics
- The "join osf" banner should slide up gracefully
- Isn't it sad that our first impression to most people has the cookie banner obscuring our pitch?
- Dismiss the "join osf" banner, it should slide down just as gracefully
- …

[EMB-374] Make join-osf-banner stay dead in safari

---

app/home/template.hbs
lib/osf-components/addon/components/sign-up-form/template.hbs
tests/acceptance/logged-out-home-page-test.ts

Fix premature Terms of Use checkbox validation on sign up form.
* `s/messagesShown/showMessages/` in `validated-input/checkbox` invocation in `sign-up-form` component
* expand logged-out-home-page acceptance test to check for premature validation (and that validation errors appear after clicking sign up without filling in any fields)
Shouldn't be.
n/a
Should make sure there is no premature validation on the sign up form.

[EMB-377] Fix premature ToU checkbox validation and add tests for validation behavior

---

lib/app-components/addon/helpers/sort.ts
lib/app-components/app/helpers/sort.js
lib/collections/addon/components/collection-metadata/template.hbs
lib/collections/addon/components/discover-page/facets/checklist/component.ts
tests/engines/app-components/integration/helpers/sort-test.ts

Product wants collection-metadata choices (alpha) sorted
* Add a sort helper, for the submit/edit page collection-metadata component
* Sort options on the discover page
None
None
Choices will be sorted in alphabetical order (e.g. status, collected type, etc)
None

Sort collection-metadata choices

---

lib/app-components/addon/components/branded-navbar/styles.scss

Prevent branded-navbar overflow
Add height of 50px to the container div
None

Fixed-height container for the branded-navbar at 50px

---

CHANGELOG.md
lib/handbook/addon/docs/components/panel/demo-args/template.hbs
lib/handbook/addon/docs/components/panel/demo-blocks/template.hbs
lib/handbook/addon/docs/components/panel/demo-mix/template.hbs
lib/handbook/addon/docs/components/panel/template.md
lib/handbook/addon/docs/template.hbs
lib/handbook/addon/routes.js
lib/osf-components/addon/components/panel/component.ts
lib/osf-components/addon/components/panel/template.hbs
lib/osf-components/addon/components/panel/x-body/component.ts
lib/osf-components/addon/components/panel/x-body/template.hbs
lib/osf-components/addon/components/panel/x-footer/component.ts
lib/osf-components/addon/components/panel/x-footer/template.hbs
lib/osf-components/addon/components/panel/x-heading/component.ts
lib/osf-components/addon/components/panel/x-heading/template.hbs
lib/osf-components/app/components/panel/component.js
lib/osf-components/app/components/panel/x-body/component.js
lib/osf-components/app/components/panel/x-footer/component.js
lib/osf-components/app/components/panel/x-heading/component.js
tests/integration/components/panel/component-test.ts

Add a component that is a general-use abstraction of bootstrap panels. This will be used immediately for the account settings page.
- Components:
- `panel` - a general-use abstraction of bootstrap panels
- Tests:
- `panel` component integration test
- Handbook:
- `panel` component
None.
n/a
This will be tested as part of the account settings page.
https://openscience.atlassian.net/browse/EMB-369

[EMB-369] panel component

---

app/guid-file/template.hbs

The tags widget was being completely hidden (instead of just read only) on quick files file detail when the current user did not have edit permissions.
* check `file.tags` instead of `tags` when determining if tags widget should render
* change `showAdd` to be based on `canEdit` rather than always `true`
* use angle bracket invocation for the tags widget
Unlikely.
n/a
The tags widget on quick file file detail pages should be tested. It should always appear for the owner of the quick file, appear in read-only mode for non-owners when a quick file has tags, and not appear at all for non-owners when a quick file has no tags. Cross browser testing is not necessary. This should be low risk.

[EMB-377] Check file.tags instead of tags and calculate showAdd correctly

---

lib/osf-components/addon/components/hyper-link/component.ts
lib/osf-components/addon/components/osf-navbar/auth-dropdown/component.ts
lib/osf-components/addon/components/osf-navbar/auth-dropdown/styles.scss
lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
lib/osf-components/addon/components/osf-navbar/component.ts
lib/osf-components/addon/components/osf-navbar/styles.scss
lib/osf-components/addon/components/osf-navbar/template.hbs
lib/osf-components/addon/components/osf-navbar/x-links/component.ts
lib/osf-components/addon/components/osf-navbar/x-links/template.hbs
tests/integration/components/osf-navbar/auth-dropdown/component-test.ts
yarn.lock

On small screens, the navbar collapses into a hamburger menu. When the user clicks a link in the expanded menu, the menu should collapse.
Add actions to various navbar components to notify `osf-navbar` that a link was clicked, so it can appropriately collapse.
There were a couple tiny CSS bugs I couldn't resist fixing while I was digging into the navbar:
On tablet screens, the auth dropdown hangs off the side of the page. No more!
On mobile screens, the auth dropdown is cut off and you have to scroll down to log out. Maybe hiding the exit was intentional, but if someone wants out I think it's nicer to let them go.
n/a
n/a
Mainly needs testing on mobile- and tablet-size screens, but would be good to check desktop as well. I found it easiest to go back and forth between the dashboard, …

[EMB-377] Collapse navbar when a link is clicked

---

CHANGELOG.md
lib/analytics-page/addon/application/controller.ts
lib/analytics-page/addon/application/template.hbs
lib/osf-components/addon/components/node-card/component.ts
lib/osf-components/addon/components/node-card/template.hbs

Fix project links modal issues identified in [EMB-377](https://openscience.atlassian.net/browse/EMB-377) (Problem 6)
* Add readOnly parameter to `node-card` component to force-hide the dropdown controls (currently only shown for forks)
* Use `paginated-list/has-many` directly w/ readOnly=true for links modal
Should be isolated to "Links to this project" modal since `readOnly` defaults to false.
n/a
Make sure projects listed on "Link to this project" modal display correctly. Forks should not have dropdown controls in this view. Should also spot-check project registrations page and forks page, which both use the `node-card` component and it's logic for displaying the dropdown controls has been slightly refactored.

[EMB-377] fix project links modal

---

app/guid-node/registrations/template.hbs

Fix error with draft registrations reloading after delete
* Make sure first argument to doReload is 1 (page number)
* Use angle bracket invocation for draft registration card
n/a
n/a
Make sure draft registrations list reloads properly after deleting one.

[EMB-377] Fix draft registrations reloading after delete

---

CHANGELOG.md
mirage/config.ts
mirage/factories/root.ts
mirage/factories/user.ts
mirage/fixtures/regions.ts
mirage/scenarios/default.ts
mirage/serializers/file.ts
mirage/serializers/root.ts
mirage/serializers/user.ts
mirage/views/node.ts
mirage/views/wb.ts
types/ember-cli-mirage/index.d.ts

Pull mirage-only things from the Create Project refactor into its own PR
1. Give mirage regions
2. Teach mirage to move files
3. Make it possible to create Mirage users with files without them being logged in
4. All the feature flags are enabled, not just route feature flags
5. When creating nodes, add the current user as a contributor to the node
This is dev-only; no user facing changes, so no QA
Ultimately this is for https://openscience.atlassian.net/browse/EMB-359

Let mirage create nodes and more

---

mirage/config.ts
mirage/views/osf-resource.ts

Make it harder to screw up the mirage config (do I type `developer-app`, `developer-apps`, `developerApps`, or `developerApp`?)
Add more restrictive types to `osfResource` and `osfNestedResource`, so they now expect a model name from `ModelRegistry`. It will automatically camelize/pluralize the model name to get the collection in mirage.
This will mildly mess with anyone with a WIP that adds mirage routes.
Also you might be alerted to a broken thing and have to fix it.
n/a
n/a
n/a

[no ticket] Better types for osfResource, osfNestedResource

---

.mergify.yml

Let's try this.
Configure [mergify](https://mergify.io) for this repo to auto-merge PRs that:
* target the `develop` branch or `release/*` branches
* pass Travis CI
* have at least one approval
* have no changes requested
* do not have the [`no merge`](https://github.com/CenterForOpenScience/ember-osf-web/labels/no%20merge) label
All ur PRs are belong to `develop`.
n/a
n/a
n/a

Configure mergify.io

---

.mergify.yml

Mergify's docs are less than stellar.
From Mergify support:
> We can see that "status-success" and "approved-reviews-by" conditions do 
not match.
>
> For "status-success", I'm guessing the CI is 
> "continuous-integration/travis-ci/pr"
> instead of "continuous-integration/travis-ci"
> 
> For "approved-reviews-by", only user "jamescdavis" have review the PR, 
> not "front-end".
> But maybe "front-end" is a team ? if yes, you should prefix it with "@" 
> (approved-reviews-by=@front-end).
* prefix team name with `@`
* append `/pr` to `status-success`
Can haz merge now?
n/a
n/a
n/a

Configure mergify properly for team and travis

---

CHANGELOG.md
app/locales/en/translations.ts
app/models/user-registration.ts
lib/osf-components/addon/components/sign-up-form/component.ts

Distinguish between already registered and blacklisted emails
- Components:
- `sign-up-form` - Distinguish between already registered and invalid (e.g. blacklisted) emails
- Models:
- `user-registration` - added invalid email validation and `addInvalidEmail` method
None.
n/a
Should check that appropriate messages are given for attempting to register a user with an email address that is already in use and an email address that uses a blacklisted domain.
https://openscience.atlassian.net/browse/EMB-347

[EMB-347] fix: distinguish between already registered and blacklisted emails

---

app/register/controller.ts
app/register/template.hbs

The #show_login at the end of the orcid url needs to be unencoded.
Move the #show_login to the template.
None.
`ember_auth_register`
Orcid login from the sign up page should work now.
https://openscience.atlassian.net/browse/EMB-347

[EMB-347] fix(register): don't encode #show_login in orcid url

---

ember-cli-build.js

Let you use Mirage in local development, not just in tests.
Modify the ember-cli-build file to add seedrandom everywhere if mirage is enabled
No QA
No ticket

[No ticket] Make seedrandom available to all

---

CHANGELOG.md
app/register/controller.ts
config/environment.d.ts
config/environment.js

We need to bounce off CAS first before we go to ORCID.
Go to CAS with redirectOrcid=true instead of ORCID directly.
none
`ember_auth_register`
ORCID sign up should full work now.
https://openscience.atlassian.net/browse/EMB-347

[EMB-347] fix(register): let CAS redirect to ORCID

---

.mergify.yml

Prevent automatic merge of PRs with `WIP` in the title. Mergify is implemented in python and [uses its standard `re` library to match](https://github.com/Mergifyio/mergify-engine/blob/30489adbd7724d631b66158c49d710e4efb6eff3/mergify_engine/rules/filter.py#L82). This RegEx will match the string `WIP` case insensitively` (using python's `re.IGNORECASE` does not appear to be possible) with word boundaries on either side.
All of these will prevent merge:
* `WIP really great stuff`
* `this is WIP and is really great`
* `[WIP] really great stuff`
* `really great stuff [WIP]`
* `really great stuff (WIP)`
* `wip really great stuff`
* `WiP really great stuff`
These will not:
* `this will wipe your HD`
* `swipe right to indicate superficial approval of the project`
Added Mergify *negated* condition …

[no ticket] chore(mergify): prevent merge if PR title contains WIP

---

tests/acceptance/guid-node/registrations-test.ts

These snapshots are probabilistically diffing and we won't care about them soon anyways.
Remove the snapshot from
n/a
n/a
There will be no Percy snapshots for the Prereg Challenge modal.
n/a

chore(tests): remove Percy snapshot for prereg challenge modal

---

app/home/route.ts
app/home/template.hbs
config/environment.d.ts
config/environment.js
lib/osf-components/addon/components/osf-navbar/template.hbs
lib/osf-components/addon/components/osf-navbar/x-links/template.hbs
mirage/scenarios/default.ts
tests/acceptance/logged-out-home-page-test.ts

Keep the logout banner/query parameter from showing up on visits to the landing page within the embosf app.
1. Clear the goodbye query parameter in the home page route's `resetController` hook (per https://guides.emberjs.com/v1.10.0/routing/query-params/ )
2. Test (with Percy snapshot so we can see if the goodbye banner changes)
3. Add a local override to easily change the default scenario to be logged out.
4. Add some test selectors, because test selectors are nice
The acceptance test I wrote covers the steps from the ticket:
1. Log into the OSF
2. Log out of the OSF (See that you wind up on the logged out landing page)
3. Click "support" in the navbar to navigate to the support page
4. Click "OSFHome" to navigate back home
https://openscience.atlassian.net/browse/EMB-391

[EMB-391] Ensure that logout banner won't reappear on home page

---

lib/osf-components/addon/components/new-project-modal/styles.scss
lib/osf-components/addon/components/new-project-modal/template.hbs
lib/osf-components/addon/components/new-project-navigation-modal/template.hbs
tests/integration/components/new-project-navigation-modal/component-test.ts

1. Make it possible to scroll the Create a Project dialog on the quickfiles page (and everywhere it's used in the future)
2. In the "Go to project" dialog, always say, "Go to project," rather than, "Go to new project" because that's more correct
1. Add a local class to the Create a project dialog that gives it `overflow-y: auto !important;`
2. Change the translation key for the button
The original request was to have it decide whether it was a new project or not and say something different each time, but after a brief chat with Sara, that was deemed Not Worth the Effort.
https://openscience.atlassian.net/browse/EMB-359

[EMB-359] AD from QA for Move to Project

---

.template-lintrc.js
CHANGELOG.md
lib/osf-components/addon/components/bs-alert/template.hbs
lib/osf-components/addon/components/contributor-list/contributor/template.hbs
lib/osf-components/addon/components/contributor-list/template.hbs
lib/osf-components/addon/components/cookie-banner/template.hbs
lib/osf-components/addon/components/dashboard-item/template.hbs
lib/osf-components/addon/components/delete-button/template.hbs
lib/osf-components/addon/components/delete-node-modal/template.hbs
lib/osf-components/addon/components/draft-registration-card/template.hbs

Eliminate implicit this in templates. This may take several PRs to try to minimize potential merge conflicts.
For the files changed:
1. Use `this.` or `@` for parameter usage so we know where the data is coming from
2. Update to angle-bracket invocation (might not be comprehensive for this pass, but later files are converted) because `data-test` selectors don't lint with curly-brace invocation 
I don't think we're percying placeholders, so a quick scan a node registrations page (draft registrations tab) that has draft registrations to make sure placeholders still work wouldn't be a bad idea.
https://openscience.atlassian.net/browse/EMB-528

[EMB-528] Eliminate implicit this in templates 1/?

---

CHANGELOG.md
app/models/user-registration.ts
app/register/controller.ts
app/register/template.hbs
lib/osf-components/addon/components/sign-up-form/component.ts

Branded sign ups should send branded emails.
- Components:
- `sign-up-form` - accept `campaign` as an optional argument and set on `user-registration` model
- Models:
- `user-registration` - added `campaign` property
None expected.
`ember_auth_register`
Should test that registering a user from a branded sign up page sends a branded verification email.
https://openscience.atlassian.net/browse/EMB-478

[EMB-478] send campaign with user registration

---

CHANGELOG.md
lib/collections/addon/components/collections-submission/template.hbs
lib/osf-components/addon/components/contributor-list/component.ts
lib/osf-components/addon/components/contributor-list/template.hbs
lib/osf-components/addon/components/inline-list/component.ts
lib/osf-components/addon/components/inline-list/template.hbs

Modify the `contributor-list` component so that it takes an optional `truncated` boolean param which defaults to `true`. If `truncated` is set to `false`, then we show the complete list.
In `contributor-list/template.hbs`, conditionals are added.
Make sure all of the contributors' last names appear on the list.
Also checks and see if other places using the `contributor-list` component (e.g. the dashboard page) shows the truncated form.
https://openscience.atlassian.net/browse/EMB-491

[EMB-491][Collections] Remove truncating of contributor list

---

config/environment.d.ts
config/environment.js
lib/registries/addon/components/registries-registration-type-facet/component.ts

As part of prereg winddown, inactive registration schemas will be returned by the API by default. This is good, and makes an old hack on the registries discover page unnecessary.
When the `enable_inactive_schemas` flag is enabled, don't manually append ERPC to the "OSF Registration Type" facet at `/registries/discover`. However, since ERPC should be included in the API response, there's no visible change.
n/a
`enable_inactive_schemas`
When the flag is enabled, check ERPC isn't in there twice.
https://openscience.atlassian.net/browse/EMB-466

[hotfix][EMB-466] Don't add ERPC to registries providers

---

CHANGELOG.md
app/router.ts
app/settings/account/template.hbs
app/settings/template.hbs
config/environment.js

Add the accounts settings page.
- Add `account` route
- Add the account route to the settings side navbar
- Create template for accounts settings
N/A
N/A
N/A
https://openscience.atlassian.net/browse/EMB-369

[EMB-369][Embosf] Add account settings page

---

config/environment.d.ts
config/environment.js
ember-cli-build.js
lib/handbook/addon/docs/dev-env/template.md

A couple of build optimizations. These shave about 10s off the initial build time.
* made building of tests in `development` environment conditional (and disabled by default)
* only include babel polyfill in production builds
* by default, `/tests` won't work for `ember serve` (can re-enable by setting `TESTS_ENABLED: true` in `config/local.js`)
* can't develop on IE 11 (but why would you?)
n/a
n/a
n/a

Dev build optimizations

---

CHANGELOG.md
ember-cli-build.js
package.json
yarn.lock

`dart-sass` does not currently handle the IE CSS hacks [present](https://github.com/twbs/bootstrap-sass/blob/bb7dbf8af72b455b51936bc07e51efcaf6220bcc/assets/stylesheets/bootstrap/_dropdowns.scss#L14) [in](https://github.com/twbs/bootstrap-sass/blob/bb7dbf8af72b455b51936bc07e51efcaf6220bcc/assets/stylesheets/bootstrap/_carousel.scss#L200) [bootstrap-sass](https://github.com/twbs/bootstrap-sass/blob/bb7dbf8af72b455b51936bc07e51efcaf6220bcc/assets/stylesheets/bootstrap/_forms.scss#L64).
```
broccoliBuilderErrorStack: CssSyntaxError: /path/to/ember-osf-web/assets/ember-osf-web.css:5:55309: Missed semicolon
...caret{width:0;height:0;margin-left:2px;border-top:4px dashed;border-top:4px solid \;border-right:4px solid transparent;border-left:4px solid transparent}...
^ offending character
``` …

chore: revert back to using node-sass

---

lib/app-components/addon/components/license-picker/template.hbs
lib/app-components/addon/components/project-contributors/template.hbs
lib/app-components/addon/components/project-metadata/template.hbs
lib/app-components/addon/components/subject-picker/template.hbs
lib/app-components/addon/components/submit-section-buttons/template.hbs
lib/app-components/addon/components/submit-section/active/template.hbs
lib/collections/addon/components/collection-metadata/template.hbs
lib/collections/addon/components/collection-search-result/node/template.hbs
lib/collections/addon/components/collection-search-result/template.hbs
lib/collections/addon/components/collection-subjects-list/template.hbs
types/ember-cli-mirage/index.d.ts

Update noted template files to use single quotations instead of double and remove trailing commas in mirage types file.
- Change double quotes to single
- Remove trailing commas in `ember-cli-mirage` types file
N/A
N/A
N/A
N/A

Change double-string quotes to single, remove trailing commas

---

CHANGELOG.md
app/resolve-guid/route.ts
package.json
tests/acceptance/resolve-guid-test.ts

Remove guid regex test from resolve-guid route because we have old guids that violate it.
- Routes:
- `resolve-guid` - remove guid regex test because we have old guids that violate it
`/something_that_doesn't_look_like_a_guid` will round-trip to the API
n/a
Make sure we can still get to all guid routes:
* `/<node-guid>/registrations`
* `/<node-guid>/forks`
* `/<node-guid>/analytics`
* `/<registration-guid>/forks`
* `/<registration-guid>/analytics`
* `/<user-guid>/quickfiles`
* `/<quick-file-guid>`
n/a

[hotfix] remove guid regex test from resolve-guid route

---

.travis.yml

Exclude release tags from Travis builds because they are always == `master` and these builds waste Travis and Percy resources.
Remove release tag pattern from Travis test stage condition.
n/a
n/a
n/a
n/a

don't run a Travis build for tags

---

CHANGELOG.md
package.json

Updating changelog and bumping version now so we continue merging to `develop` without conflicts.

Start 19.1.0 release

---

CHANGELOG.md
app/dashboard/route.ts
app/goodbye/route.ts
app/guid-node/forks/route.ts
app/guid-node/registrations/route.ts
app/guid-registration/forks/route.ts
app/guid-user/quickfiles/route.ts
app/home/route.ts
app/register/route.ts
app/services/analytics.ts
app/settings/tokens/edit/route.ts
app/settings/tokens/index/route.ts
app/support/route.ts
lib/analytics-page/addon/application/route.ts
package.json

Add missing page tracking to active routes.
- Routes
- `goodbye` - add page tracking
- `guid-node.forks` - accurately report resource privacy and type when page tracking
- `guid-node.registrations` - accurately report resource privacy and type when page tracking
- `guid-registration.forks` - add page tracking
- `guid-user.quickfiles` - add resource type to page tracking
- `settings.tokens.create` - add page tracking
- `settings.tokens.edit` - - add page tracking
- `settings.tokens.index` - add page tracking
- Engines:
- `analytics-page` - accurately report resource privacy and type when page tracking
Analytics page resource types are now pluralized, which is inconsistent with how they were being reported (but consistent with API resource types).
n/a
Need to make sure all routes have page …

[hotfix] add missing page tracking

---

CHANGELOG.md
app/locales/en/translations.ts
app/models/developer-app.ts
app/settings/developer-apps/template.hbs
app/settings/tokens/template.hbs
app/validators/http-url.ts
lib/osf-components/addon/components/panel/component.ts
lib/osf-components/addon/components/panel/styles.scss
lib/osf-components/addon/components/panel/template.hbs
mirage/factories/developer-app.ts
tests/acceptance/settings/developer-apps-page-test.ts
types/ember-cp-validations/index.d.ts
types/ember-validators/format.d.ts

Fixes for issues identified by QA:
* long developer app names overflow the panel (especially on small screens)
* incorrect validation for urls
This also fixes [EMB-552 - Long token names do not wrap on laptops or smaller screens](https://openscience.atlassian.net/browse/EMB-552).
* prevent text overflow outside panel component
* use panel component for developer apps
* use panel component for personal access tokens
* add custom httpUrl validator
* use httpUrl validator for developer apps
* adjust developer apps test and mirage factory to always use https for callback urls
Should be none.
`ember_user_settings_apps_page`
This fixes the issues identified in QA testing of [EMB-342](https://openscience.atlassian.net/browse/EMB-342), and also fixes …

[EMB-342][EMB-552] developer app fixes

---

app/guid-file/template.hbs
lib/osf-components/addon/components/file-browser/template.hbs

Clicking anywhere except on a bootstrap button caused the share panel to go away. Clicking on a bootstrap button (and thus, and OsfButton) did not. This ensures that the share popover goes away.
1. Add `@bubble=true` to relevant `OsfButton`s
2. Remove unused `id`s from html elements.
https://openscience.atlassian.net/browse/EMB-533

[EMB-533] Bubble events from bootstrap buttons

---

app/guid-node/registrations/template.hbs
lib/osf-components/addon/components/node-navbar/link/template.hbs
lib/osf-components/addon/components/quickfile-nav/template.hbs
tests/integration/components/node-navbar/component-test.ts
tests/integration/components/node-navbar/link/component-test.ts
tests/integration/components/quickfile-nav/component-test.ts
tests/integration/helpers/osf-link-router-stub.ts

Try to make node-navbar links to registrations tab work. Should totally work.
Replaced some `#link-to`s with `Link`s.
N/A

Replace guid-based `link-to`s with `Link`s

---

config/environment.js

Make node-registration pages accessible from within the ember app on environments without the waffle flag set.
Remove the feature flag.
`ember-project-registrations-page` will no longer be necessary.
On staging, go to a node's analytics page, then click on the registrations tab. If it works, this worked.
N/A

Remove unnecessary and irksome flag

---

config/environment.js

Enable registries by default in dev environment since mirage turns on the waffle flag and we link to it in the nav bar (it errors if disabled).
set `REGISTRIES_ENABLED = true,` in `config/environment.js`
The registries engine will always be enabled.
n/a
n/a
n/a

Enable registries by default

---

CHANGELOG.md
app/models/collected-metadatum.ts
app/models/collection.ts
app/models/developer-app.ts
app/models/file.ts
app/models/guid.ts
app/models/node.ts
app/models/osf-model.ts
app/models/user.ts
app/resolve-guid/route.ts
app/serializers/osf-serializer.ts
app/utils/get-href.ts
app/utils/get-related-href.ts
app/utils/tuple.ts
app/validators/node-license.ts
lib/collections/addon/components/collection-metadata/component.ts
lib/collections/addon/components/collections-submission/component.ts
lib/osf-components/addon/components/file-browser/component.ts
lib/osf-components/addon/helpers/get-ancestor-descriptor.ts
types/osf-api.d.ts

The `links` attribute and `relationshipLinks` alias on `osf-model` were both typed `any`, which is less than ideal. This PR gives these proper types and deals with the consequences of that. It extends the links types for models (`file`, `user`, `developer-app`) that have extra resource-type-specific links. It also types `apiMeta` while we're there.
- Utils:
- `getHref` - get an href from a `Link`
- `getRelatedHref` - get an href from a `Relationship`
- Models:
- `osf-model` - use proper types for `links` and `relationshipLinks` attributes
- `file` - extend `links` types to include links specific to files
- `user` - extend `links` types to include links specific to users
- `developer-app` - extend `links` types to include links specific to developer apps
- `collection` - improve types for …

Improve links types

---

app/models/provider.ts
app/services/theme.ts

Small bug where missing styles in collections cause the app to fail to render.
Check to see if assets exist, if not return default styles.
Not that I know of.
The localhost:5000/collections pages need to be tested (with created collections).
- Need to test if, no styles are provided on new collection, does the page crash.
- If styles are provided, do they render correctly?
- Small risk, worst case is default styles always load (but I doubt this will happen).

[NoTicket] app breaks when styles not specified in collections

---

CHANGELOG.md
config/environment.d.ts
config/environment.js
mirage/scenarios/default.ts

Make local development faster for most cases (and no slower for the rest) by allowing the mirage default scenario to be more easily configurable. Cuts the load time in half using default settings.
1. Split up mirage scenarios into functions
2. Add an environment variable to define which scenarios to load (with a good default)

Reduce load time in local/handbook

---

.travis.yml
CHANGELOG.md
app/services/analytics.ts
config/environment.d.ts
config/environment.js
lib/osf-components/addon/components/osf-mode-footer/component.ts
lib/osf-components/addon/components/osf-mode-footer/template.hbs
package.json
yarn.lock

Now that https://github.com/samselikoff/ember-cli-mirage/pull/1376 has been merged and released, we can resume using a production build for the handbook deploy on github pages. This PR also makes changes to the dev banner so that it's display is controlled by a config var `showDevBanner` rather than `devMode`. This allows us to turn it on for the handbook production build and it will be off for CI tests and not pollute Percy snapshots. A small change was also made to allow toast-on-click analytics to function in production builds so that, in staging environments, we can turn this on to easily test analytics.
- Services
- `analytics` - allow toast-on-click to be used in production builds (when enabled in dev banner)
- Components	- Components
- `osf-mode-footer` - show dev banner based on …

Prod build for handbook

---

app/app.ts
lib/collections/addon/components/collection-metadata/component.ts
lib/collections/addon/components/collections-submission/component.ts
lib/collections/addon/components/collections-submission/template.hbs
lib/collections/addon/engine.js
lib/collections/addon/guid/edit/controller.ts
lib/collections/addon/guid/edit/route.ts
lib/collections/addon/guid/edit/template.hbs
lib/collections/addon/submit/template.hbs

The main purpose of this PR is to allow users to start from any point on the edit page.
This PR also fixes the problem where `Discard Changes` for `Collection Metadata` section clears all metadata instead of reverting to the saved state.
Respectively,
- `savedSections` in the `collections-submission` component denotes which section of the edit form has been "saved" (meaning the `Continue` or `Save and Continue` button for that section has been clicked). Therefore, for the edit view, we set it all sections, enabling users to be able to click any section to edit.
- Also change the `isPageDirty` logic to look at `hasDirtyAttributes` of the `collected-metadatum` model.
- Add `initialCollectedMetadatumProperties` to `collection-metadata` component to save initial properties so that we can …

[EMB-512][Collections] Allow users to start from wherever they want on edit page

---

mirage/helpers.ts
types/ember-cli-mirage/index.d.ts

Map relationship types to `ModelInstance` so that we can get type checking on `server.create()`.
- map relationship types to `ModelInstance`
- use stronger types in mirage helpers
n/a
n/a
n/a
n/a

Improve mirage server.create() types

---

app/locations/guid-mixin.ts
app/utils/clean-url.ts
app/utils/transition-target-url.ts
config/environment.js
tests/unit/locations/auto-guid-test.ts
tests/unit/locations/none-guid-test.ts
tests/unit/utils/clean-url-test.ts

Forks and registrations links are not forcing a reload so ending up on a blank page instead of the appropriate legacy detail page.
- move cleanURL to a utility
- pass transition target URLs through cleanURL
- add route flag for guid-node.index
- add route flag for old registration detail page
Shouldn't be any
Related flags are:
- `ember_project_detail_page`
- `ember_old_registration_detail_page`
but they should both be off or not exist at this point.
Need to make sure links on project forks and registrations tabs go to detail pages and not blank pages.
n/a

Fix links on forks and registrations pages

---

app/locations/history.ts
tests/unit/locations/history-fragment-test.ts

When you go to a URL like /guid/#summary, the viewport should scroll to the element with id="summary" once the app has rendered.
This was previously implemented, but was only tested at `localhost:4200` and broke when the app is proxied through our web server. Trailing slashes :(
- Refactor our `HistoryLocation` to be more idiomatic/readable/testable, so the time I spent understanding "why" doesn't go to waste.
- Fix and test handling of trailing slashes.
n/a
n/a
Probably easiest to test on the registries overview page:
1. Click on a header in the registration form (e.g. "Summary")
2. Verify that the browser's viewport scrolls to that header, and the URL has the name of the header in the fragment (e.g. `/guid#summary`)
3. Reload the page
4. Repeat step 2 -- should scroll to the same header …

[EMB-581] fix navigating with URL fragment

---

app/locales/en/translations.ts
app/models/node.ts
lib/registries/addon/components/registries-navbar/template.hbs
lib/registries/addon/overview/children/template.hbs
lib/registries/addon/overview/comments/template.hbs
lib/registries/addon/overview/links/template.hbs
lib/registries/addon/overview/template.hbs
mirage/scenarios/default.ts

Fix a handful of little bugs on the registries overview page that didn't seem worth the overhead of ticketing or reviewing separately.
- fix `node.isRoot`, which works with mirage but is always `false` with the real API
- fix logout in the registries navbar
- display linked registrations on the "links" page (previously only showed linked projects/components)
- fix an error in the `registrations` mirage scenario
- add page titles to the registries overview page and its subroutes
n/a
n/a

[no ticket] 5 little fixes -- registries overview

---

CHANGELOG.md
config/environment.js

- Bump osf api version: 2.8 -> 2.13
N/A

[No ticket] Bump OSF api version: 2.8 -> 2.14

---

lib/registries/addon/components/registries-states/is-public/component.ts

Never set `withdrawn` directly, let the backend handle it.
Front-end follow-up to [PLAT-1333](https://openscience.atlassian.net/browse/PLAT-1333)
When the user triggers a withdrawal, set `pending_withdrawal: true` instead of `withdrawn: true`, since the withdrawal has to be confirmed before it's actually withdrawn.
n/a
Withdrawal should *work*.
n/a

[no ticket] fix: withdraw registration via pending_withdrawal

---

.travis.yml
README.md
scripts/handbook_deploy.sh

There was unauthorized use of a personal access token, which has been remediated. Builds on develop are now failing because of this. All of the necessary settings have been updated on GitHub and Travis CI.
Do **not** commit any changes to the Travis CI configuration without DevOps review and approval.
* Update travis config to use a deploy key instead of a personal access token
* Add instructions in the README
N/A
N/A
N/A
None

Use deploy key for handbook deploy

---

lib/app-components/addon/components/subject-picker/component.ts

Fix subject picker.
The way we deep copy `currentSubjects` does not work on a array of objects. Therefore we change the way we deep copy. And instead of deep copying the `currentSubjects` to `tempSubjects`, we copy it to `initialSubjects`, which works the same.
https://openscience.atlassian.net/browse/EMB-495

[EMB-495] Deep copy `currentSubjects`.

---

lib/registries/addon/components/registration-form-view/component.ts
lib/registries/addon/components/registration-form-view/x-file/component.ts
lib/registries/addon/components/registration-form-view/x-file/styles.scss
lib/registries/addon/components/registration-form-view/x-file/template.hbs

Registries overview: 
Fix: uploaded files are not displayed on the registration form view 
N/A
N/A
Register a project using a schema that required file uploads such as Registered Reports,
make sure the file names are displayed on the registration overview
[EMB-587](https://openscience.atlassian.net/browse/EMB-587)

[EMB-587] Fix displaying files names in form view

---

lib/registries/addon/components/registries-metadata/template.hbs
tests/engines/registries/acceptance/overview/overview-test.ts

Allow admin to edit registration tags
- Make editable by users with admin permission.
- Add test
N/A
`ember-registries-detail-page`
[EMB-565](https://openscience.atlassian.net/browse/EMB-565)

[EMB-565] Allow admin to edit registration tags

---

config/environment.js
lib/registries/addon/components/registries-banner/component.ts
lib/registries/addon/components/registries-banner/template.hbs
lib/registries/addon/components/registries-overview-menu/component.ts
lib/registries/addon/components/registries-overview-menu/template.hbs
lib/registries/addon/components/registries-states/actions-trigger/component.ts
lib/registries/addon/components/registries-states/actions-trigger/template.hbs
lib/registries/addon/components/registries-states/component.ts
lib/registries/addon/components/registries-states/is-embargoed/component.ts
lib/registries/addon/components/registries-states/is-public/component.ts
lib/registries/addon/components/registries-states/template.hbs
lib/registries/addon/components/sharing-icons/component.ts
lib/registries/addon/components/sharing-icons/dropdown/component.ts
lib/registries/addon/components/sharing-icons/dropdown/template.hbs
lib/registries/addon/components/sharing-icons/sharing-anchor/template.hbs
lib/registries/addon/components/sharing-icons/template.hbs
lib/registries/addon/overview/controller.ts
lib/registries/addon/overview/route.ts
lib/registries/addon/overview/template.hbs
mirage/config.ts
mirage/views/collection.ts
tests/acceptance/guid-file/file-detail-test.ts
tests/engines/registries/acceptance/overview/overview-test.ts

Fix issues with social sharing links.
Fix image url og tag
- og:image tag had a bad url. Do not append `assetsPrefix` on the image asset location url.
- Upon clicking a link in the sharing links on the overview toolbar, the dropdown closes.
- sharing links on the overview toolbar had `undefined` in the share url as registration title and description were being retrieved on `node` while `registration` is passed in.
- registries banner `embargoEnddate` was wrong.
N/A
On the overview menu, expand the social sharing dropdown.
Click on linkedin, facebook (if any), twitter make sure, you will be take to share post
page on the platform, make sure that the osf logo image, registration title show.
[EMB-442](https://openscience.atlassian.net/browse/EMB-442)

[EMB-442] Fix overview toolbar bugs

---

app/models/registration.ts
lib/registries/addon/components/registries-banner/component.ts
lib/registries/addon/components/registries-overview-menu/component.ts
lib/registries/addon/components/registries-states/actions-trigger/component.ts
lib/registries/addon/components/registries-states/component.ts
lib/registries/addon/components/registries-states/template.hbs
tests/engines/registries/acceptance/overview/overview-test.ts
tests/unit/models/registration-test.ts

To refactor and add tests to the registry model state function. 
1) Add tests around the function to guarantee functionality.
2) Refactor state function.
To refactor this function I ideally wanted to get rid of the complex if statement. Main reasons for this is that is first hard to read / reason about what's going on and changing it could cause it to break. It is also packing a lot of logic into a relatively small space that also increases the complexity of understanding.
The current function basically acts as a hash map. It maps a boolean value to a RegistrationState and then, if the bool is true, it returns that value. It is also doing the if / or statements within each hashmap section so there's a bit of a mixing of this hashmap with the various if logic.
So I basically made this …

[MAIN] Refactor.registries.states

---

app/adapters/citation-style.ts
app/locales/en/translations.ts
app/models/citation-style.ts
app/serializers/citation-style.ts
lib/osf-components/addon/components/citation-viewer/component.ts
lib/osf-components/addon/components/citation-viewer/template.hbs
lib/osf-components/addon/components/copyable-text/component.ts
lib/osf-components/app/components/citation-viewer/component.js
lib/osf-components/package.json
lib/registries/addon/components/registries-metadata/component.ts
lib/registries/addon/components/registries-metadata/template.hbs
mirage/config.ts
mirage/factories/citation-style.js
mirage/fixtures/citation-styles.ts
mirage/scenarios/default.ts
mirage/serializers/registration.ts
mirage/views/citation.ts
mirage/views/utils/index.ts
tests/integration/components/citation-viewer/component-test.ts
types/ember-power-select/test-support.d.ts

Add a citation viewer to the registries overview page.
Add `<CitationViewer>` component, use it in the overview page sidebar.
Note: Getting citations is done with manual ajax requests instead of using the ember-data store. The store gets confused when multiple things have the same ID (each citation is at `/v2/registrations/<guid>/citations/<citation-style>`, which by json:api implies all citations of the same style have the same ID). Bypassing it seemed the reasonable route here.
Updated `<CopyableText>` to use `analytics.trackFromElement` when it's not given an `analyticsScope`. This shouldn't break anything.
Page only visible with `ember_registries_detail_page`
Test that:
- the default citations (APA, MLA, Chicago) load correctly
- searching for other citation styles works as you'd …

[EMB-448] Citations widget

---

app/styles/_global.scss
lib/osf-components/addon/components/copyable-text/template.hbs

Tooltips on the citation widget show up in the wrong place:
Turns out, the tooltip's location is limited to the `body` element, and we style `body` to be exactly the height of the browser viewport. This means that when you need to scroll down to see the button, the tooltip will pop up higher on the page:
Replacing `body`'s `height` with `min-height` solves this problem while preserving the "footer at the bottom" behavior that motivated that style in the first place.
While investigating, I noticed the tooltip acting weird in a distracting way as the mouse moves. Made it not react to mouse events, so it always stays up for 3 seconds after you click, then disappears.
If there's anywhere we depend on `body` being *smaller* than the content of the page... well, we should be ashamed of …

[ENG-184] Tooltip positioning fix

---

app/application/styles.scss
app/styles/_global.scss

The change in #624 actually broke the "footer at the bottom" behavior I thought it preserved.
Changing `height: 100%` to `min-height: 100%` broke because it creates a circular dependency; the parent's height depends on the height of its children, and the child's height depends on the height of its parent.
Instead of a chain of `100%`s passing the viewport height parent-to-child all the way down to the application div, just use `min-height: 100vh` directly on the app div and let `html` and `body` do what they naturally do. This solves the issue in #624 (because `body` can grow with its content) without breaking footer behavior (because the app div won't shrink smaller than the viewport).
Having fewer global styles is a win.
n/a
Easiest to test by zooming out on a short page (support is a …

[no ticket] Fix footer at the bottom w/o limiting body

---

lib/registries/addon/overview/route.ts
tests/engines/registries/acceptance/overview/overview-test.ts

Add citation_doi to head meta tags, ignore promise rejections loading meta tags.
- Update tests
- Ignore errors when building/loading head meta tags
- Please make sure `citation_doi` shows in head meta 
[ENG-176](https://openscience.atlassian.net/browse/ENG-176)

[ENG-176] Add citation_doi to head meta tags

---

CHANGELOG.md
app/adapters/user-password.ts
app/locales/en/translations.ts
app/models/user-password.ts
app/serializers/user-password.ts
app/settings/account/-components/change-password/component.ts
app/settings/account/-components/change-password/template.hbs
app/settings/account/template.hbs
lib/osf-components/addon/components/password-strength-bar/component.ts
lib/osf-components/addon/components/password-strength-bar/styles.scss
lib/osf-components/addon/components/password-strength-bar/template.hbs
lib/osf-components/app/components/password-strength-bar/component.js
mirage/config.ts
mirage/views/user-password.ts
package.json
tests/acceptance/settings/account/change-password-test.ts
tests/integration/components/password-strength-bar/component-test.ts
tests/integration/routes/settings/account/-components/change-password-test.ts
types/ember-toastr/index.d.ts
yarn.lock

Adds the password widget to the account settings page
- create `password-widget` component
- create `password-strength-bar` component
The password widget:
If there are validations that need to be met on the new password, it will show:
Otherwise it will give hints:
There are 5 different statuses that can show for the password strength bar:
Very weak:
Weak:
So-so:
Good:
Great!:
N/A
N/A
- This will affect the account settings page.
- There are two different validations for the 'New Password' field that are combined into one message.  If the actual form field isn't valid, it will show what the user needs for it to be valid (at least 8 characters, can't be the same as what's entered in the 'Current Password').  If the validations requirements are met for that field, it will show password …

[EMB-572] Password widget

---

lib/osf-components/addon/components/osf-link/template.hbs
lib/osf-components/addon/components/osf-navbar/auth-dropdown/component.ts
lib/registries/addon/components/navbar/template.hbs
lib/registries/addon/components/registries-navbar/template.hbs
tests/engines/registries/integration/components/registries-navbar/component-test.ts

Change the nav links on the registries navbar to use `osf-link` so that they support specifying a route to transition to along with query parameters.
* allow classes to pass-through to `a` tag in `osf-link`
* use `osf-link` for registries nav links
* for the "Join" link, specify the `register` route and query parameters instead of an href
* use the `cleanURL` util to remove any "--" url components (in this case, `/--registries`) from the sign up next url
* fix up `registries-navbar` integration test to work with `osf-link` join
None expected.
n/a
Should make sure registries nav links have retained desired style and behavior.
n/a

Fix registries-navbar join link

---

app/models/registration.ts
mirage/factories/registration.ts

https://percy.io/Center-for-Open-Science/ember-osf-web/builds/1780593/view/115932618/1280?browser=chrome&mode=diff alerted me (🎉for Percy!) to an issue where the "Date withdrawn" was always the current date, even after this was fixed to always use a date in the past:
https://github.com/CenterForOpenScience/ember-osf-web/blob/58a002a789c1c3b1e7bafb08a375981ff854a7ba/mirage/factories/registration.ts#L51-L53
This turns out to be because the `registration` model did not even have a `dateWithdrawn` attribute.
* add `dateWithdrawn` attribute to `registration` model
* initialize `dateWithdrawn` to `null` in the `registration` mirage factory
None.
n/a
n/a
n/a

fix: add dateWithdrawn attribute to registration model and factory

---

tests/engines/registries/acceptance/overview/index-test.ts

The tombstone tests should use traits to get registrations in proper states rather than setting the state manually.
* create registration in mirage with `isWithdrawn` trait for withdrawn tombstone test
* create registration in mirage with `isArchiving ` trait for archiving tombstone test
none
n/a
n/a
n/a

use traits for registration tombstone tests

---

app/models/user-setting.ts
app/settings/account/-components/security/component.ts
app/settings/account/-components/security/template.hbs
mirage/views/user-setting.ts

Fix the problem where the QR code is not recognized by 2FA apps such as Authy and Google Authenticator.
Fix the problem where clicking `Enable` after entering the correct verification code doesn't do anything.
Also fix the problem where configure button is disabled after clicking the close button on top right of the modal.
According to [Google Authenticator's doc](https://github.com/google/google-authenticator/wiki/Key-Uri-Format), the QR code should encode a URI in this format:
`otpauth://TYPE/LABEL?PARAMETERS`
In our case, the `TYPE` should be `totp`, the `LABEL` should be `OSF:<primary-email-address>` and `PARAMETERS` should be `secret=<secret>`.
Changes the `verification` field on `user-settings` model to `twoFactorVerification`, because the API expects `two_factor_verification` to be …

[ENG-243] Fix QR code.

---

app/authenticators/osf-cookie.ts

The a_b_testing flag for the logged out homepage is currently in a conditional to only show on development environments.
- Move the a_b_testing flag outside of dev conditional so it can be seen in the osf-dev-footer on staging/prod
N/A
N/A
The flag should show now show up on the feature tab on the osf-dev-footer.  It should work and switch the homepage between versions A and B.
N/A

[fix] Move a_b_testing flag outside of dev environment conditional

---

config/environment.js
lib/osf-components/addon/components/osf-mode-footer/component.ts
lib/osf-components/addon/components/osf-mode-footer/styles.scss
lib/osf-components/addon/components/osf-mode-footer/template.hbs
tests/integration/components/hero-banner/component-test.ts

Better formatting for the feature flags tab in the dev mode footer modal:
* arrange feature flags in columns
* underscore and sort feature flag names
* rename home page version B feature flag so it cleanly converts back to snake_case
none
It lets you toggle all of them!
n/a
n/a

Dev footer feature flag formatting

---

CHANGELOG.md
app/meetings/index/route.ts
app/meetings/template.hbs
app/router.ts
config/environment.js
lib/osf-components/addon/components/osf-navbar/component.ts
tests/acceptance/meetings/index-test.ts

Create meetings index route.
- Routes:
- `meetings` - parent route for meetings
- `meetings.index` - meetings landing page
- Tests:
- Acceptance:
- `meetings/index`
- Components:
- `osf-navbar` - detect active OSF service for any non-engine service
Shouldn’t be any.
`ember_meetings_page`
n/a
https://openscience.atlassian.net/browse/ENG-470

[ENG-470] create meetings index route

---

app/settings/account/-components/change-password/component.ts
app/settings/account/-components/change-password/template.hbs
lib/osf-components/addon/components/password-strength-bar/component.ts
lib/osf-components/addon/components/password-strength-bar/template.hbs
tests/integration/routes/settings/account/-components/change-password-test.ts

To remove double validation messages on the `password-strength-bar` and always provide a message when the password does not pass validation.
- Move logic from the `password-strength-bar` to the `change-password` widget.
- Refactor logic to determine when to show the `password-strength-bar`'s message.
- Add a message to be shown when password strength is weak, but the checker does not provide a warning.
- Display `password-strength-bar` with the `warning` color (orange) when validation passes, but the password is mediocre.
`N/A`
`N/A`
This should fix the double validation messages on the `password-strength-bar`.  Please make sure that it works when editing the `new password` field as well as when editing the `existing password` field.
This also add a validation message to be displayed when …

[ENG-448][ENG-447] Fix password-strength-bar double validation message and failure to display message for weak passwords

---

CHANGELOG.md
app/authenticators/osf-cookie.ts
app/utils/leaf-vals.ts
tests/unit/utils/leaf-vals-test.ts

The API only lists enabled feature flags and thus disabled flags are not initialized in `ember-feature-flags`. Initializing disabled feature flags found in config makes them available in the dev banner features tab so that they can be enabled from here for testing.
- Utilities:
- `leaf-vals` - get values of all leaves in an object tree
- Tests:
- Unit:
- `leaf-vals` utility
- Authenticators:
- `osf-cookie` - initialize any disabled feature flags found in config
None expected
It initializes them.
No QA needed, but this will make some things easier to test.
n/a

Initialize all feature flags

---

CHANGELOG.md
app/adapters/meeting.ts
app/locales/en/translations.ts
app/meetings/index/-components/meetings-list/component.ts
app/meetings/index/-components/meetings-list/styles.scss
app/meetings/index/-components/meetings-list/template.hbs
app/meetings/index/template.hbs
app/models/meeting.ts
app/serializers/meeting.ts
lib/osf-components/addon/components/paginated-list/layout/template.hbs
lib/osf-components/addon/components/paginated-list/x-header/component.ts
lib/osf-components/addon/components/paginated-list/x-header/template.hbs
lib/osf-components/addon/components/paginated-list/x-item/template.hbs
lib/osf-components/app/components/paginated-list/x-header/component.js
mirage/config.ts
mirage/factories/meeting.ts
mirage/scenarios/default.ts
tests/integration/components/paginated-list/x-header/component-test.ts
tests/integration/routes/meetings/index/-components/meetings-list/component-test.ts
tests/unit/models/meeting-test.ts

Add the meetings list to the meetings index page.
- Models:
- `meeting` - for OSF Meetings
- Adapters:
- `meeting` - in private namespace
- Serializers:
- `meeting`
- Components:
- `meetings/index/components/meetings-list` - meetings list for the meetings index page
- Tests:
- Integration:
- `meetings-list
- Mirage:
- `meeting` factory
- private `meetings` endpoint
- meetings scenario
- Components:
- `osf-navbar` - detect active OSF service for any non-engine service
- `paginated-list`
- add ability to provide a header row
- add splattributes to item
None expected.
`ember_meetings_page`
Should behave as expected. Search is debounced to avoid an API hit for each letter hit.
https://openscience.atlassian.net/browse/ENG-473

[ENG-473] meetings landing page meeting list

---

config/environment.js

Add the meetings scenario to the default list of enabled mirage scenarios for testing.
Add the meetings scenario to the default list of enabled mirage scenarios for testing.
None.
n/a
This will enable testing of the meetings list at: https://centerforopenscience.github.io/ember-osf-web/meetings
https://openscience.atlassian.net/browse/ENG-473

[ENG-473] add meetings mirage scenario to default

---

app/settings/account/-components/connected-emails/template.hbs
lib/osf-components/addon/components/node-list/template.hbs
lib/osf-components/addon/components/paginated-list/layout/template.hbs
lib/osf-components/package.json

The changes made in #667 cause issue with paginated lists. Namely, on Account Settings - Connected Emails, the "empty" message is [always displayed](https://percy.io/Center-for-Open-Science/ember-osf-web/builds/1888952/view/122829898/1280?mode=diff&browser=chrome&snapshot=122829898) (and [displayed twice if there are no alternate or unconfirmed emails](https://percy.io/Center-for-Open-Science/ember-osf-web/builds/1888952/view/122829884/1280?mode=diff&browser=chrome&snapshot=122829884)). [Extra space was also injected when the list was empty](https://percy.io/Center-for-Open-Science/ember-osf-web/builds/1888952/view/122829058/1280?mode=diff&browser=chrome&snapshot=122829058) in most invocations of paginated-list.
* in the `connected-emails` component, use the `empty` closure component …

[ENG 473] fix paginated list

---

app/guid-node/registrations/styles.scss
app/guid-node/registrations/template.hbs

#671 [was successful](https://percy.io/Center-for-Open-Science/ember-osf-web/builds/1895204) in restoring almost all of the paginated list formatting to match what is on `master`, but one small issue with the bottom margin on the registrations tab registration list [persists](https://percy.io/Center-for-Open-Science/ember-osf-web/builds/1895204/view/123256124/1280?mode=diff&browser=chrome&snapshot=123256124). This PR solves this by removing the extraneous `ul` wrapper from the draft registrations list (which was adding a 15px bottom margin in the wrong place) and instead adding a 15px bottom margin to the whole registration tab container.
*  remove extraneous `ul` wrapper on draft registrations list
* add 15px bottom margin to registrations container
None expected.
n/a
n/a …

[ENG-473] fix registrations tab paginated list

---

CHANGELOG.md
app/adapters/external-identity.ts
app/locales/en/translations.ts
app/models/external-identity.ts
app/serializers/external-identity.ts
app/settings/account/-components/connected-identities/component.ts
app/settings/account/-components/connected-identities/styles.scss
app/settings/account/-components/connected-identities/template.hbs
app/settings/account/template.hbs
mirage/config.ts
mirage/factories/external-identity.ts
mirage/scenarios/default.ts
mirage/serializers/external-identity.ts
tests/integration/routes/settings/account/-components/connected-identities-test.ts
tests/unit/adapters/external-identity-test.ts
tests/unit/models/external-identity-test.ts
tests/unit/serializers/external-identity-test.ts

Add a connected identities component to account settings.
* `external-identity` model/adapter/serializer
* `connected-identities` component
* `external-identity` mirage things
* integration test for `connected-identities` component
* `connected-identities` component to `settings/account` route (and changed all component invocation int his template to use angle brackets)
None expected.
`ember_user_settings_account_page`
This component was missing from `/settings/account`. It can be tested on stagings by connecting an ORCID account to an OSF account. ORCID is currently the only external identity available for the OSF, but the component was implemented to support any number of external identities. Once this PR is merged, this functionality can be tested against fake data at: …

[ENG-456] connected identities

---

app/locales/en/translations.ts
app/models/node.ts
lib/osf-components/addon/components/editable-field/category-manager/component.ts
lib/osf-components/addon/components/editable-field/category-manager/template.hbs
lib/osf-components/addon/components/editable-field/institutions-manager/component.ts
lib/osf-components/addon/components/editable-field/tags-manager/component.ts
lib/osf-components/addon/components/institution-select-list/component.ts
lib/osf-components/addon/components/node-category-picker/component.ts
lib/osf-components/addon/components/node-category-picker/template.hbs
lib/osf-components/addon/components/node-category/component.ts
lib/osf-components/addon/components/node-category/template.hbs
lib/osf-components/app/components/editable-field/category-manager/component.js
lib/osf-components/app/components/node-category-picker/component.js
lib/osf-components/app/components/node-category/component.js
lib/registries/addon/components/registries-metadata/template.hbs
lib/registries/addon/components/registries-tags-widget/component.ts
mirage/factories/node.ts
tests/engines/registries/acceptance/overview/overview-test.ts

Make registration category admin-editable
- Add `node-categories` and `category-manager` component
- Add tests
- Only admin should be able to edit registration category
- Make sure all the categories show in the dropdown (except current category which shows
in the dropdown trigger).
- Check for errors upon saving edits.
[ENG-364](https://openscience.atlassian.net/browse/ENG-364)

[ENG-364] Editable category

---

app/settings/account/-components/security/component.ts

Currently if you have two factor authentication enabled but not confirmed, the account settings page would not show the QR code for 2FA. The problem lies with the fact that we only load primary emails upon clicking the `Configure` button.
Perform the `loadPrimaryEmail` task in `init()`. Inside the task, use `component.set()` instead of native setters because native setter doesn't trigger recompute of dependent computed properties.
Enable 2FA on the account settings page but do not confirm. Then refresh the page and make sure the QR code shows up.
https://openscience.atlassian.net/browse/ENG-503

[ENG-503] load primary email on init; use component.set() instead of native setter to trigger recompute

---

mirage/factories/comment.ts

Make comment dates relative to now since they are always displayed as relative dates. This will eliminate jitter in Percy snapshots as seen [here](https://percy.io/Center-for-Open-Science/ember-osf-web/builds/1973449/view/128309897/1280?mode=diff&browser=chrome&snapshot=128309897).
make created and modified dates relative to now in `comment` mirage factory
None expected.
n/a
No QA needed.
n/a

mirage: make comment dates relative to now

---

app/application/controller.ts
app/application/route.ts
app/services/current-user.ts
app/utils/param.ts
app/utils/url-parts.ts
lib/osf-components/addon/components/banners/view-only-link/component.ts
lib/osf-components/addon/components/citation-viewer/component.ts
lib/osf-components/addon/components/osf-link/component.ts
lib/osf-components/addon/components/osf-navbar/x-links/hyper-link/x-anchor/component.ts
lib/registries/addon/components/registration-form-view/component.ts
lib/registries/addon/components/registries-metadata/template.hbs
mirage/factories/node.ts
mirage/factories/utils.ts
mirage/serializers/application.ts
mirage/serializers/node.ts
tests/acceptance/guid-file/file-detail-test.ts
tests/acceptance/new-home-test.ts
tests/acceptance/view-only-link-test.ts
tests/engines/registries/acceptance/overview/view-only-link-test.ts
tests/unit/utils/param-test.ts
tests/unit/utils/url-parts-test.ts

Fix some VOL bugs
- Anonymized registration forms might be missing answers to questions. Update `registration-form-view` parser to handle missing answers gracefully.
- New util: `addPathSegment` for adding a segment to a URL's path
- Consolidated utils for manipulating URL parts in `utils/url-parts`
- Update `citation-viewer` to behave correctly with view-only links
- use `addPathSegment` to build URL with `view_only` query param
- hide citation widget for anonymized view
- Add a non-`undefined` default value for the `view_only` query param
- Update mirage to handle AVOLs *slightly* more true-to-life
For some reason, adding a default value for `view_only` also fixed a long-standing bug on `guid-file` and a shorter-standing one on `new-home`: query params were sometimes displayed in the …

[ENG-458][ENG-544][ENG-545][ENG-550] VOL followup

---

app/meetings/detail/-components/meeting-detail-header/styles.scss
app/meetings/detail/-components/meeting-detail-header/template.hbs
app/meetings/detail/-components/meeting-submissions-list/template.hbs
app/meetings/detail/styles.scss
app/meetings/detail/template.hbs
app/meetings/index/-components/meetings-footer/styles.scss
app/models/meeting-submission.ts
mirage/factories/meeting-submission.ts
mirage/serializers/meeting-submission.ts
tests/integration/routes/meetings/detail/-components/meeting-submissions-list/component-test.ts

Implement some small fixes:
- Put meeting detail page toggle button and conference link on the same line.
- Hide download link and count of a submission if the project doesn't have a download link.
- Make meeting landing page footer link not clickable again.
- Change `category` to `meetingCategory` on `meeting-submission` model.
https://openscience.atlassian.net/browse/ENG-476
https://openscience.atlassian.net/browse/ENG-474

[ENG-476][ENG-474] Fix small issues

---

app/meetings/index/-components/meetings-list/template.hbs

Only show meeting dates when they are defined.
Only show meeting dates when they are defined.
Should be none.
`ember_meetings_page`
I've implemented this so that the ` - ` separator still displays when only one date is defined so that it is clear which date it is.
https://openscience.atlassian.net/browse/ENG-564

[ENG-564] fix: only show dates when they are defined

---

app/settings/account/-components/connected-emails/styles.scss
app/settings/account/-components/connected-emails/template.hbs

use padding instead of negative margins to prevent overlap
* use padding instead of negative margins to prevent overlap
* use `OsfButton`
* remove unnecessary tags
None expected
`ember_user_settings_account_page`
Should fix issue where buttons overlap email addresses on very small screens.
https://openscience.atlassian.net/browse/ENG-578

refactor: use padding instead of negative margins to prevent overlap

---

app/locales/en/translations.ts
lib/osf-components/addon/components/editable-field/description-manager/component.ts
lib/osf-components/addon/components/editable-field/description-manager/template.hbs
lib/osf-components/addon/components/editable-field/institutions-manager/component.ts
lib/osf-components/addon/components/editable-field/institutions-manager/template.hbs
lib/osf-components/addon/components/editable-field/tags-manager/component.ts
lib/osf-components/addon/components/institution-select-list/component.ts
lib/osf-components/addon/components/institution-select-list/template.hbs
lib/osf-components/addon/components/institutions-list/template.hbs
lib/osf-components/addon/components/node-description-editable/component.ts
lib/osf-components/addon/components/node-description-editable/styles.scss
lib/osf-components/addon/components/node-description-editable/template.hbs
lib/osf-components/addon/components/node-description/component.ts
lib/osf-components/addon/components/node-description/styles.scss
lib/osf-components/addon/components/node-description/template.hbs
lib/osf-components/app/components/editable-field/description-manager/component.js
lib/osf-components/app/components/node-description-editable/component.js
lib/osf-components/app/components/node-description/component.js
lib/registries/addon/components/registries-metadata/component.ts
lib/registries/addon/components/registries-metadata/template.hbs
lib/registries/addon/components/registries-tags-widget/component.ts
lib/registries/addon/components/registries-tags-widget/template.hbs
tests/engines/registries/acceptance/overview/overview-test.ts
tests/integration/components/institution-select-list/component-test.ts
tests/integration/components/institutions-list/component-test.ts

Add editable description to registries overview
- Allow admin to edit registration's description
- Add test
[ENG-375](https://openscience.atlassian.net/browse/ENG-375)

[ENG-375] Editable description

---

CHANGELOG.md
app/meetings/detail/-components/meeting-submissions-list/template.hbs
tests/integration/routes/meetings/detail/-components/meeting-submissions-list/component-test.ts

Download count sorting will be removed from the back end, so need to remove it from the front end.
* remove meetings submission list download count sorting
* modify integration test to not check submission list download count sorting
None expected.
`ember_meetings_detail_page`
Make sure sorting by download count is not available.
https://openscience.atlassian.net/browse/ENG-578

[ENG-590] remove meetings submission list download count sorting

---

app/adapters/registration-provider.ts
app/locales/en/translations.ts
app/models/registration-provider.ts
app/models/registration.ts
app/serializers/registration-provider.ts
app/services/theme.ts
lib/osf-components/addon/components/editable-field/license-manager/component.ts
lib/osf-components/addon/components/editable-field/license-manager/template.hbs
lib/osf-components/addon/components/validated-input/power-select/component.ts
lib/osf-components/addon/components/validated-input/power-select/template.hbs
lib/osf-components/app/components/editable-field/license-manager/component.js
lib/registries/addon/components/license-viewer/component.ts
lib/registries/addon/components/license-viewer/styles.scss
lib/registries/addon/components/license-viewer/template.hbs
lib/registries/addon/components/registries-license-picker/component.ts
lib/registries/addon/components/registries-license-picker/styles.scss
lib/registries/addon/components/registries-license-picker/template.hbs
lib/registries/addon/components/registries-metadata/styles.scss
lib/registries/addon/components/registries-metadata/template.hbs
lib/registries/addon/overview/route.ts
mirage/config.ts
mirage/factories/registration.ts
mirage/fixtures/registration-providers.ts
mirage/scenarios/default.ts
mirage/serializers/registration-provider.ts
mirage/serializers/registration.ts
tests/engines/registries/acceptance/overview/overview-test.ts

Add editable license field
- Rename `registry-provider` to `registration-provider`
- Add `<RegistriesLicensePicker>` component
- Update mirage setup
- Fix `<LicenseText>` component to display to wrap text correctly.
[[EMB-562]](https://openscience.atlassian.net/browse/EMB-562)

[EMB-562] Add editable license field

---

CHANGELOG.md
app/meetings/index/-components/meetings-list/component.ts

Sort meetings by submission count (descending) by default.
Set default sort on `meetings-list` component to be: `-submissions_count`
None expected.
`ember_meetings_page`
Make sure meetings are sorted by submission count (descending) by default.
https://openscience.atlassian.net/browse/ENG-627

[ENG-627] sort meetings by submission count by default

---

CHANGELOG.md
app/meetings/detail/-components/meeting-submissions-list/template.hbs
app/models/meeting-submission.ts
mirage/factories/meeting-submission.ts
tests/integration/routes/meetings/detail/-components/meeting-submissions-list/component-test.ts

Rename meeting-submission `created` field to `dateCreated` to match the API
- Models:
- `meeting-submission` - renamed `created` to `dateCreated` to match API
- Components:
- `meetings`
- `detail`
- `meeting-submissions-list` - renamed `created` to `dateCreated` and `date_created` to match API
- Tests:
- Integration:
- `meetings`
- `detail`
- `meeting-submissions-list` - renamed `created` to `dateCreated` and `date_created` to match API
- Mirage:
- `meeting-submission` factory - renamed `created` to `dateCreated` to match API
None expectd
`ember_meetings_detail_page`
Make sure `Date created` column matches the `date_created` in the API response.
https://openscience.atlassian.net/browse/ENG-629

[ENG-629] rename meeting-submission field: created to dateCreated

---

CHANGELOG.md
app/meetings/detail/-components/meeting-detail-header/template.hbs
tests/integration/routes/meetings/detail/-components/meeting-detail-header/component-test.ts

An undefined start date would result in "Invalid date" in the detail header.
- Tests:
- Integration:
- `meetings`
- `detail`
- `meeting-detail-header` - add tests for location and dates
- Components:
- `meetings`
- `detail`
- `meeting-detail-header` - only attempt to display dates when defined
None expected.
`ember_meetings_detail_page`
An empty start date should not result in "Invalid date" being displayed.
https://openscience.atlassian.net/browse/ENG-631

[ENG-631] handle missing dates on meeting detail header

---

lib/registries/addon/components/registration-form-view/x-options/styles.scss
lib/registries/addon/components/registration-form-view/x-options/template.hbs

Change the default bullet points of user-selectable options in the registry to checkmarks.
Change to the x-options template
Add CSS file to x-options
The bullet points for user-selectable options (ie: Design Plan > Study Type or Blinding) in the registry overview has been changed to be a checkmark. 
Please double-check that it looks ok across browsers and devices. 
Lists of uploaded files should not have the checkmark.
https://openscience.atlassian.net/browse/ENG-514

[ENG-514]Change bullet points to checkmarks for registry options

---

lib/registries/addon/components/side-nav/styles.scss
lib/registries/addon/components/side-nav/x-link/styles.scss
lib/registries/addon/components/side-nav/x-link/template.hbs
lib/registries/addon/styles/variables.scss

Re-style the active route in the sidenav component.
- Update to side-nav/x-link component so label text is in a wrapper div. 
- Update to CSS to match mockup.
Please double-check if it looks acceptable on mobile screens and across browsers. Collapsed behavior should have the labels hidden until hovering over the icons. The text should "poke through" the side-bar. There is an issue in Safari that has been reported here: https://openscience.atlassian.net/browse/EOSF-1053
The active link should be a lighter blue than before, and also have rounded edges with a bit of white-space on the sides.
Expanded:
Collapsed view:
Collapsed Hover:
Expanded:
Collapsed:
Collaped Hover:
https://openscience.atlassian.net/browse/ENG-509

[ENG-509] Change styling for sidenav

---

app/locales/en/translations.ts
app/models/registration.ts
app/utils/doi.ts
lib/osf-components/addon/components/editable-field/publication-doi-manager/component.ts
lib/osf-components/addon/components/editable-field/publication-doi-manager/template.hbs
lib/osf-components/addon/components/node-publication-doi-editable/component.ts
lib/osf-components/addon/components/node-publication-doi-editable/styles.scss
lib/osf-components/addon/components/node-publication-doi-editable/template.hbs
lib/osf-components/addon/components/node-publication-doi/component.ts
lib/osf-components/addon/components/node-publication-doi/template.hbs
lib/osf-components/app/components/editable-field/publication-doi-manager/component.js
lib/osf-components/app/components/node-publication-doi-editable/component.js
lib/osf-components/app/components/node-publication-doi/component.js
lib/registries/addon/components/registries-license-picker/template.hbs
lib/registries/addon/components/registries-metadata/template.hbs
mirage/factories/registration.ts
tests/engines/registries/acceptance/overview/overview-test.ts
tests/unit/utils/doi-test.ts

Add admin editable publication doi
- Add tests
- Add publication DOI editable field with validation
- Add publication DOI manager component
-  Add `extractDOI` helper
[ENG-393](https://openscience.atlassian.net/browse/ENG-393)

[ENG-393] Add admin editable publication doi

---

app/home/-components/integrations-section/template.hbs
tests/acceptance/logged-out-homepage-test.ts

We shouldn't have a `get-started-button` on the bottom of the integrations-section for this round of testing.
- Remove the `get-started-button` from the integrations-section
`N/A`
`N/A`
This will only remove the button from one part of the logged-out homepage
`N/A`

Remove get-started-button from bottom of integrations section

---

CHANGELOG.md
app/locales/en/translations.ts
app/styles/_components.scss
lib/osf-components/addon/components/osf-navbar/template.hbs

To improve the experience of users using screen readers.
- use `img` tag with alt text for navbar OSF logo instead of background CSS image
None expected.
n/a
This is minor change that should result in no visual difference. Percy should catch any visual regressions in Chrome, but cross-browser testing would be good. I've tested locally on Chrome, Firefox, and Safari. This is low risk.
n/a

[ENG-673] use img tag with alt text for OSF logo in nav bar

---

lib/osf-components/addon/components/sign-up-policy/template.hbs

The links on `/register` currently do not go outside of the page (both links go to the current link).  They should go to our github pages for both the privacy policy and terms and conditions, respectively.
- Changing `@termsLink` and `@privacyPolicyLink` to use `this` instead works in referring to the correct link.
`N/A`
`N/A`
This shouldn't affect anything outside of the links on the `/register` page, so just making sure that the links now go to the correct page instead of whatever the current URL is.
https://openscience.atlassian.net/browse/ENG-657

[ENG-657] Fix links for Privacy Policy and Term and Conditions

---

lib/osf-components/addon/components/new-project-modal/template.hbs
lib/osf-components/addon/components/sign-up-form/template.hbs
lib/osf-components/package.json
lib/registries/addon/components/registries-header/template.hbs
lib/registries/addon/components/registries-provider-facet/template.hbs
lib/registries/addon/components/registries-registration-type-facet/template.hbs
lib/registries/addon/discover/template.hbs
lib/registries/package.json
package.json
tests/engines/registries/integration/components/x-dummy/component-test.ts

`ember-test-selectors` is currently tripping up components that are tag-less, and is breaking the handbook.
- Remove `ember-test-selectors`
- Fix components to use `(html-attributes ...)` to fix tests
`N/A`
`N/A`
This shouldn't have any visible affects, please make sure that the affected areas still look/act as intended.
https://openscience.atlassian.net/browse/ENG-695

[ENG-695] Remove ember-test-selectors

---

app/locales/en/translations.ts
lib/osf-components/addon/components/node-description/component.ts
lib/osf-components/addon/components/node-description/styles.scss
lib/osf-components/addon/components/node-description/template.hbs
lib/registries/package.json
package.json
tests/engines/registries/acceptance/overview/overview-test.ts
tests/integration/components/node-description/component-test.ts
yarn.lock

Have  long descriptions get truncated after a certain threshold. A button 
- Set a height limit (currently 50px) to the description text area. 
- If the description is short enough to not exceed this height limit, nothing should appear different. 
- If the description exceeds the height threshold, it will fade vertically to white and a button will appear below it, giving the option to "Show more"
- Clicking "Show more" will show the entire description. Button changes to "Show less" and will hide the description again.
- If the user changes the description, it should dynamically update the appearance if the description is made longer or shorter beyond the set height threshold.
- When the description is updated, the default behavior is to have the description box collapse down again.
1. Are …

[ENG-645] Truncate registration description

---

CHANGELOG.md
app/home/route.ts
app/services/analytics.ts
config/environment.d.ts
config/environment.js

We're currently using `isWithdrawn` in preprints analytics and it should be consistent everywhere.  It's dimension 4 on preprints, but dimension 4 on ember-osf-web is currently version.  We should update ember-osf-web to match.
- Add `isWithdrawn` analytic as dimension 4 to the config and update types
`N/A`
`N/A`
`N/A`
https://openscience.atlassian.net/browse/ENG-747

[hotfix][ENG-747] add isWithdrawn dimension to google analytics

---

CHANGELOG.md
app/locales/en/translations.ts
lib/app-components/addon/components/project-contributors/list/component.ts
lib/app-components/addon/components/project-contributors/list/styles.scss
lib/app-components/addon/components/project-contributors/list/template.hbs
lib/app-components/addon/components/project-contributors/template.hbs

As implemented, Collections only allows users to manage the first ten contributors on a node. Users need to be able to manage all contributors.
- Components
- `project-contributors/list` - add ability to load more pages of contributors
None expected.
n/a
Need to make sure, for projects with more than ten contributors, a "Load more contributors" link appears and loads additional pages of contributors.
https://openscience.atlassian.net/browse/ENG-284

[ENG-284] load more collections contributors

---

CHANGELOG.md
lib/app-components/addon/components/project-contributors/component.ts
lib/app-components/addon/components/project-contributors/list/component.ts
lib/app-components/addon/components/project-contributors/list/template.hbs
lib/app-components/addon/components/project-contributors/search/component.ts
lib/app-components/addon/components/project-contributors/template.hbs

The refactoring in #722 introduced an issue where the contributors list does not reload when adding or removing contributors. There should also be loading indicator displayed while contributors are loading.
- Components
- `project-contributors/list`
- add ability to load more pages of contributors
- add loading indicator
None expected.
n/a
Need to make sure contributors management on Collections works as expected.
https://openscience.atlassian.net/browse/ENG-284

[ENG-284] trigger contributors reload on add/remove

---

lib/app-components/addon/components/project-contributors/list/template.hbs

The way I implemented the loading indicator, it hides the existing list of contributors when loading more pages. This is less than ideal.
Move the loading indicator to after the contributor list display instead of conditionally rendering the loading indicator or the list. The works well because the list is initially empty and is simply appended to for "Load more". And reloads clear the list and start over from page 1.
(recommend [hide whitespace changes](https://github.com/CenterForOpenScience/ember-osf-web/pull/728/files?w=1) when viewing the diff)
None expected.
n/a
Should check that the loading indicator works well for initial load, load more, add contributor, and remove contributor.
https://openscience.atlassian.net/browse/ENG-284

[ENG-284] make project contributors loading indicator work better for load more

---

app/locales/en/translations.ts
lib/osf-components/addon/components/editable-field/category-manager/component.ts
lib/osf-components/addon/components/editable-field/description-manager/component.ts
lib/osf-components/addon/components/editable-field/doi-manager/component.ts
lib/osf-components/addon/components/editable-field/institutions-manager/component.ts
lib/osf-components/addon/components/editable-field/publication-doi-manager/component.ts
lib/osf-components/addon/components/editable-field/tags-manager/component.ts
lib/osf-components/addon/components/node-doi-create/template.hbs

The purpose is twofold:
- Allow entering a blank value for "publication DOI" on registrations
- Ensure editable registration fields on the registration overview page have correct error messages and error-handling behavior.
Represent an empty publication DOI as `null` instead of an empty string. (An empty string gets a 400 error from the API.)
For each editable field, handle both success and error consistently. Always display a toast message. If the request fails, the unsaved changes shouldn't remain on the model instance.
n/a
As a registration admin:
- Add a publication DOI (if none already) and save
- Edit the publication DOI again, erase it, and save
- A success message should pop up, and the sidebar should have no publication DOI
As a registration admin, go through each editable field …

[ENG-746] Fix missing/inconsistent translations

---

CHANGELOG.md
app/home/template.hbs
app/modifiers/track-scroll.ts
app/services/analytics.ts
tests/integration/analytics-test.ts

Scroll events are counting as interaction and affecting the bounce rate for Google Analytics. This can be fixed by setting nonInteraction: true when sending the event. Additionally, the inclusion of the version in the label is messing up reporting. It is not necessary to have version in the label because we already have a custom dimension for version. Also, the "Logged-out Homepage" label scope prefix is too long and messes up graphs in Google analytics.
- Services
- `analytics` - allow passing through of `nonIteraction` flag to Google Analytics
- Modifiers
- `trackScroll` - set `nonInteraction` flag when calling `analytics.trackFromElement()`
- Routes
- `home` - remove version and shorten analytics scope
None expected.
n/a
n/a
https://openscience.atlassian.net/browse/ENG-761

[ENG-761] analytics adjustments

---

mirage/factories/registration.ts
tests/engines/registries/acceptance/overview/index-test.ts

Some Percy snapshots for `feature/registries-pre-submission` had some weird/confusing/contradictory states, like showing edit buttons on a withdrawn registration's tombstone page, or while the user is "logged out". This updates some tests -- no effect on app functionality.
- Update the registration factory in mirage to have `currentUserPermissions: null` for withdrawn registrations (same as the actual APIv2)
- Update tests for the registration overview page so the user logged in when looking at a registration with admin permission.
n/a
n/a
no QA required
[EMB-123]: https://openscience.atlassian.net/browse/EMB-123

[no ticket] Update tests and mirage factories to avoid contradictory states

---

CHANGELOG.md
app/adapters/schema-block.ts
app/models/registration-schema.ts
app/models/schema-block.ts
app/serializers/schema-block.ts

To add a model for `schema-blocks`
- Add `schema-block` model
- Update `registration-schema` model to include a `hasMany` relationship with `schema-block`
`N/A`
`N/A`
`N/A`
https://openscience.atlassian.net/browse/ENG-782

[ENG-782] Add schema-block model

---

CHANGELOG.md
app/application/template.hbs
app/modifiers/capture-element.ts
lib/handbook/addon/docs/components/osf-dialog/-components/demo-is-open/template.hbs
lib/handbook/addon/docs/components/osf-dialog/-components/demo-non-modal/template.hbs
lib/handbook/addon/docs/components/osf-dialog/template.md
lib/osf-components/addon/components/osf-dialog/component.ts
lib/osf-components/addon/components/osf-dialog/styles.scss
lib/osf-components/addon/components/osf-dialog/template.hbs
lib/osf-components/addon/components/osf-mode-footer/component.ts
lib/osf-components/addon/components/osf-mode-footer/styles.scss
lib/osf-components/addon/components/osf-mode-footer/template.hbs
lib/osf-components/addon/services/osf-modal-state.ts
tests/integration/components/osf-dialog/component-test.ts
tests/unit/services/osf-modal-state-test.ts

Use the previously-added `osf-dialog` component. Add refinements that came to light while using it.
- Update dev-mode pop-up to use `osf-dialog`
- Add `@isOpen` and `@isModal` params to `osf-dialog`
- Add `capture-element` modifier to clean things up
Navigating the dev-mode tabs makes the dialog change size in a weird way.
The lesson here: Avoid putting complex/re-flowy widgets inside a dialog. If you must, use CSS to control the size.
n/a
n/a
https://openscience.atlassian.net/browse/ENG-807
[EMB-123]: https://openscience.atlassian.net/browse/EMB-123

[ENG-807] Refine & use osf-dialog

---

CHANGELOG.md
app/locales/en/translations.ts
lib/osf-components/addon/components/registries/read-only-contributors-list/component.ts
lib/osf-components/addon/components/registries/read-only-contributors-list/styles.scss
lib/osf-components/addon/components/registries/read-only-contributors-list/template.hbs
lib/osf-components/app/components/registries/read-only-contributors-list/component.js
tests/integration/components/read-only-contributors-list/component-test.ts

To make a component containing a read-only list of contributors for a node and a link to the node's contributors page for editing.  To be used primarily for registries submission workflow.
- Add `read-only-contributors-list` component
- Create new folder workspace in `osf-components` for registries components to be used outside of the registries engine
- Add test
`N/A`
`N/A`
This will just be a list that contains all of the contributors that the node has.  Beneath the list of names there will also be a link that will take the user to the node's contributors page so that they can have the option to edit contributors there.  The component itself will not have any functionality for editing/adding/removing contributors.
https://openscience.atlassian.net/browse/ENG-721

[ENG-721] Read-only contributors list

---

CHANGELOG.md
mirage/views/osf-resource.ts

The `create` action for `osfNestedResource` is not working properly. Namely, it does not connect the nested child resource it creates to the parent resource. This is because the default handler for `post` in mirage doesn't know to connect the resource it creates to the parent. This PR fixes this by implementing a custom handler function for `post` in `osfNestedResource` that creates the child and then connects it to the parent.
- Mirage
- `osfNestedResource` - added custom `post` handler to fix `create` action
None expected.
n/a
No QA needed.

[ENG-670] fix: create for osfNestedResource

---

CHANGELOG.md
mirage/serializers/contributor.ts

The contributors endpoint is nested under the node so we need to serialize the self link this way.
- Mirage
- Serializers
- `contributors` - serialize correct nested self link
None expected.
n/a
NO QA needed.

[ENG-670] mirage: serialize correct self link for contributors

---

CHANGELOG.md
package.json
yarn.lock

Update to latest [ember-angle-bracket-invocation-polyfill](https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill), which gives us angle bracket invocation of built-in components `<LinkTo>`, `<Input>`, and `<Textarea>`. 
- Packages
- update to [ember-angle-bracket-invocation-polyfill@^2.0.2](https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/releases/tag/v2.0.2)
None expected.
n/a
No QA needed.

[ENG-670] chore: update to ember-angle-bracket-invocation-polyfill@^2.0.2

---

CHANGELOG.md
mirage/config.ts
mirage/views/contributor.ts
mirage/views/osf-resource.ts

In Mirage, when a contributor is created, if the contributor is bibliographic, we need to also add that contributor to the node's list of bibliographic contributors.
- Mirage
- `osfNestedResource`
- added `onCreate` hook to perform additional operations after creating a child resource
- Mirage
- `node/contributors` nested resource
- conditionally create bibliographic contributors when creating contributors
None expected.
n/a
No QA needed.

[ENG-670] mirage: create bibliographic contributor on create contributor

---

CHANGELOG.md
lib/app-components/addon/components/project-contributors/list/item/template.hbs
lib/app-components/addon/components/project-contributors/search/result/template.hbs
lib/app-components/addon/components/project-contributors/search/template.hbs
lib/app-components/addon/components/project-contributors/search/unregistered-contributor/template.hbs
lib/app-components/addon/components/project-contributors/template.hbs
lib/app-components/addon/components/submit-section/complete/template.hbs
lib/app-components/addon/components/submit-section/template.hbs
lib/app-components/addon/components/submit-sections/template.hbs
lib/collections/addon/components/collection-item-picker/after-options/template.hbs
lib/collections/addon/components/collections-submission/template.hbs

This is a series of refactors to templates for components used in Collections submission. For each template, template lint issues were fixed and angle bracket invocation was used wherever possible. I also reformatted for readability in a number of places.
Note: this PR depends on #745
- Engines
- `collections`
- fixed template lint and use angle brackets in submission templates
None expected.
n/a
The Collections submission workflow should be thoroughly tested.

[ENG-670] fix lint and refactor templates for collections submission

---

CHANGELOG.md
lib/app-components/addon/components/project-contributors/component.ts
lib/app-components/addon/components/project-contributors/list/item/template.hbs
lib/app-components/addon/components/project-contributors/search/result/template.hbs
lib/app-components/addon/components/project-contributors/search/template.hbs
lib/app-components/addon/components/project-metadata/template.hbs
lib/app-components/addon/components/submit-section/complete/template.hbs
lib/collections/addon/components/collection-submission-confirmation-modal/template.hbs
lib/collections/addon/components/collections-submission/component.ts
lib/collections/addon/components/collections-submission/template.hbs
lib/osf-components/addon/components/contributor-list/contributor/template.hbs
tests/engines/collections/acceptance/submit/submit-test.ts
tests/engines/collections/acceptance/update/update-test.ts
tests/engines/collections/integration/components/collection-submission-confirmation-modal/component-test.ts
tests/index.html

- Ticket: [ENG-670]
This PR adds test selectors and improves the collections submit acceptance test to perform actual assertions (previously just Percy snapshots).
- Components
- `project-contributors`
- added `onAddContributor` hook
- Engines
- `collections`
- Tests
- added/improved test selectors to templates related to submit
- improved submit acceptance tests to perform assertions in addition to taking snapshots
- Tests
- added `ember-basic-dropdown-wormhole` div to test index.html
- Engines
- `collections`
- `submit`
- reload bibliographicContributors when adding a contributor
None expected.
This should be tested as part of the full regression. The only functional change in this PR is to reload bibliographic contributors after adding a new contributor so that the …

[ENG-670] improved collections submit acceptance test

---

CHANGELOG.md
mirage/factories/collected-metadatum.ts
tests/engines/collections/acceptance/update/update-test.ts

- Ticket: [ENG-831]
This PR improves the collections update acceptance test to perform actual assertions (previously just Percy snapshots).
- Engines
- `collections`
- Tests
- improved update acceptance tests to perform assertions in addition to taking snapshots
- Mirage
- Factories
- `collected-metadatum`
- allow manual setting of collection metadata
None expected.
No QA needed specific to this PR.
[ENG-831]: https://openscience.atlassian.net/browse/ENG-831

[ENG-831] improved collections update acceptance test

---

CHANGELOG.md
app/serializers/osf-serializer.ts

- Ticket: n/a
I was trying to use `queryHasMany` to get a list of things with a `related_count`, and discovered that didn't work! The resulting model instances had `relatedCounts: undefined`. This fixes that.
Previously, related counts were gathered in the serializer's `normalizeSingleResponse` method, which is not used by `store.pushPayload`. This means `queryHasMany` results and embeds didn't have their `relatedCount` filled out.
This PR moves the `relatedCount` logic to the serializer's `normalize` method, which is always used for normalizing resources, regardless of where the resource came from.
none?
n/a

[no ticket] fix: populate `relatedCounts` for all

---

app/models/schema-block.ts
app/packages/registration-schema/get-pages.ts
app/packages/registration-schema/get-schema-block-group.ts
app/packages/registration-schema/index.ts
app/packages/registration-schema/schema-block-group.ts
app/packages/registration-schema/schema-block.ts
tests/unit/packages/registration-schema/get-pages-test.ts
tests/unit/packages/registration-schema/get-schema-block-group-test.ts
tsconfig.json

- Ticket: `NA`
Move the Schema-blocks utility to a new home at `app/packages/registration-schema`
Each function that used to be in `util/schema-blocks.ts` is now its own file in `packages/registration-schema` and placeholder files added for `page-manager` and `validations`. We (@futa-ikeda  and @adlius ) could not move the packages directory directly under project root because it would not be built into the bundle resulting in test failure. 
`NA`

[No ticket]Move schema-block utility to app/package/registration-schema

---

CHANGELOG.md
lib/handbook/addon/docs/components/osf-dialog/template.md
lib/osf-components/addon/components/osf-dialog/component.ts
lib/osf-components/addon/components/osf-dialog/styles.scss
lib/osf-components/addon/components/osf-dialog/template.hbs

- Ticket: n/a
Add a `fixedWidth` option to `osf-dialog` to prevent shrinking to fit contents.
- Components
- `osf-dialog`
- add `@fixedWidth` param to prevent shrinking to fit contents
none expected
n/a

[no ticket] add fixedWidth option to osf-dialog

---

CHANGELOG.md
lib/handbook/addon/docs/components/osf-dialog/-components/demo-is-open/template.hbs
lib/osf-components/addon/components/osf-dialog/component.ts
lib/osf-components/addon/components/osf-dialog/footer/styles.scss
lib/osf-components/addon/components/osf-dialog/heading/styles.scss
lib/osf-components/addon/components/osf-dialog/template.hbs
lib/osf-components/addon/services/osf-modal-state.ts
tests/integration/components/osf-dialog/component-test.ts

- Ticket: [ENG-513]
These are the parts of #742 that don't require QA
- Components
- `osf-dialog`
- fixed buggy behavior with `@isOpen` -- make it actually DDAU
- fixed styles so it displays the same both in and out of the handbook
- clean up global state on destroy
None expected.
No QA needed for this PR. Will QA on #742
[ENG-513]: https://openscience.atlassian.net/browse/ENG-513

[ENG-513] osf-dialog fixes

---

CHANGELOG.md
app/home/-components/support-section/support-item/template.hbs
app/meetings/index/-components/meetings-footer/template.hbs
config/optional-features.json
lib/registries/addon/components/registries-advisory-board/template.hbs
lib/registries/addon/components/sharing-icons/popover/template.hbs

- Ticket: n/a
Enable [template-only-glimmer-components](https://github.com/emberjs/rfcs/blob/master/text/0278-template-only-components.md) so that we don't have to create component.ts files just for the purpose of making components tagless.
- Ember Optional Features
- `template-only-glimmer-components`
Any existing template-only components will become tagless, but this *shouldn't* affect anything. 🤞
No QA needed. Percy will catch any issues that could arise.

[no ticket] enable template-only-glimmer-components

---

CHANGELOG.md
lib/osf-components/addon/components/editable-field/category-manager/template.hbs
lib/osf-components/addon/components/editable-field/description-manager/template.hbs
lib/osf-components/addon/components/editable-field/institutions-manager/template.hbs
lib/osf-components/addon/components/editable-field/license-manager/template.hbs
lib/osf-components/addon/components/editable-field/publication-doi-manager/template.hbs
lib/osf-components/addon/components/editable-field/tags-manager/template.hbs
lib/osf-components/addon/components/editable-field/template.hbs

- Ticket: n/a
Expose `isSaving` as an alias for `save.isRunning` in each of the editable field managers for better abstraction. Also pass through `@fixedWith` to add ability to configure the dialog.
- Components
- `editable-field`
- pass `@fixedWidth` through to `OsfDialog`
- use `@manager.isSaving` to disable submit & cancel buttons
- `category-manager`
- expose `isSaving` as alias for `save.isRunning`
- `description-manager`
- expose `isSaving` as alias for `save.isRunning`
- `institutions-manager`
- expose `isSaving` as alias for `save.isRunning`
- `license-manager`
- expose `isSaving` as alias for `save.isRunning`
- `publication-doi-manager`
- expose `isSaving` as alias for `save.isRunning`
- `tags-manager`
- expose `isSaving` as alias for `save.isRunning`
None …

[no ticket] Expose editable field isSaving to disable submit/cancel buttons

---

CHANGELOG.md
lib/osf-components/addon/components/editable-field/subject-field-manager/component.ts
lib/osf-components/addon/components/editable-field/subject-field-manager/template.hbs
lib/osf-components/app/components/editable-field/subject-field-manager/component.js

**Note:** this PR depends on #771 
- Ticket: [ENG-835]
Add a manager component for subjects editable field.
- Components
- `editable-field/subject-field-manager`
Should be none.
n/a
[ENG-835]: https://openscience.atlassian.net/browse/ENG-835

[ENG-835] add subject-field-manager

---

CHANGELOG.md
lib/handbook/addon/docs/components/subject-widget/demo/template.hbs
lib/handbook/addon/docs/components/subject-widget/route.ts
lib/handbook/addon/docs/components/subject-widget/template.md
lib/handbook/addon/docs/template.hbs
lib/handbook/addon/routes.js
mirage/scenarios/default.ts

- Ticket: [ENG-835]
Add `Subjects::Widget` to the handbook component gallery.
- Handbook
- `Subjects::Widget` component to gallery
None.
n/a
[ENG-835]: https://openscience.atlassian.net/browse/ENG-835

[ENG-835] add subjects widget to handbook

---

app/packages/registration-schema/get-schema-block-group.ts
app/packages/registration-schema/index.ts
app/packages/registration-schema/page-response.ts
app/packages/registration-schema/schema-block-group.ts
app/packages/registration-schema/validations.ts
app/validators/validate-response-format.ts
tests/unit/packages/registration-schema/get-schema-block-group-test.ts
tests/unit/packages/registration-schema/validations-test.ts
tests/unit/validators/validate-response-format-test.ts

- Ticket: [ENG-734]
Build a validations helper to build validations for a given schema page
Added a `validations` helper that takes in an array of `SchemaBlock`s and returns a validation object based on the inputs in that array. The validation object will use the `registrationResponseKey` to assign validations to each input.
Added a custom validator to check if `file-input` has the format expected with `id` and `name`.
Added `PageResponse` type. This is the model that the validations are built for.
Added `groupType` property on `SchemaBlockGroup`. This property is the same as `SchemaBlockGroup.inputBlock.blockType`
`N/A`
`N/A`
[ENG-734]: https://openscience.atlassian.net/browse/ENG-734

[ENG-734]Build validations from schemablock groups

---

ember-cli-build.js

- Ticket: n/a
- Mirage is included in all dev builds, even when disabled (this is required for `/tests` to run as expected).
- The `seedrandom` package is required only by our mirage utils, so in `ember-cli-build.js` we include it only when mirage is enabled.
- This causes an error when disabling mirage in dev mode.
Always include `seedrandom` in dev/test builds. Include it in prod builds only when mirage is explicitly enabled (e.g. for deploying to gh-pages)
n/a
n/a

[no ticket] fix: ensure seedrandom is there when needed

---

CHANGELOG.md
lib/handbook/addon/docs/components/osf-dialog/-components/demo-is-open/component.ts
lib/osf-components/addon/components/osf-dialog/styles.scss

- Ticket: n/a
Darken the osf-dialog background overlay
- Components
- `osf-dialog`
- darken background overlay
- Handbook
- `osf-dialog` `demo-is-open` needs component file because it muts `isOpen`
None expected.
Can be tested with the subject picker.

[no ticket] Darken osf-dialog background

---

.editorconfig
.eslintrc.js

- Ticket: n/a
On Windows machines, Git installer's default is to checkout to CRLF line endings and commit LF. This was causing linting errors within the project. These changes just ensure linting matches to the machine it's running on.
Added check for linebreak style in .eslintrc.js and removed forced LF in .editorconfig.

[no ticket] Fix linting errors with CRLF vs LF on Windows machines

---

app/institutions/dashboard/controller.ts
app/institutions/dashboard/route.ts
app/institutions/dashboard/template.hbs
app/models/institution.ts
mirage/factories/institution.ts
mirage/factories/node.ts
mirage/scenarios/default.ts
mirage/utils.ts

- Ticket: [ENG-1059]
- Feature flag: Institutional Dashboard
Add a protected route for the institutional dashboard. This route only allows admins of an institution to view it. Also pulls in institutional user data from the institution model.
Updated institution routes to look for `currentUserIsAdmin` on the institution. Added specific institution to Mirage for testing institutional dashboard with (ID 29). Added placekitten placeholder image for an institution's banner image.
/institutions/29/dashboard is the current route for testing the institutional dashboard.
[ENG-1059]: https://openscience.atlassian.net/browse/ENG-1059

[ENG-1059] Eng 1059/institutional dashboard route

---

CHANGELOG.md
app/institutions/dashboard/-components/panel/component.ts
app/institutions/dashboard/-components/panel/styles.scss
app/institutions/dashboard/-components/panel/template.hbs
app/institutions/dashboard/styles.scss
app/institutions/dashboard/template.hbs
app/models/institution.ts
mirage/factories/institution.ts
tests/integration/routes/institutions/dashboard/-components/panel/component-test.ts

- Ticket: [ENG-1069]
- Feature flag: Institutional Dashboard
To show the number of SSO users connected on the Institutional Users Dashboard.
Added ssoUsersConnected to institution's stat summary. Updated styles for panels on the institutional users dashboard. Added SSO users connected to the page.
[ENG-1069]: https://openscience.atlassian.net/browse/ENG-1069

[ENG-1069] Add SSO Users Connected panel to institutional users dashboard

---

CHANGELOG.md
lib/osf-components/addon/components/registries/partial-registration-modal/component.ts
lib/osf-components/addon/components/registries/partial-registration-modal/template.hbs
tests/integration/components/registries/partial-registration-modal/component-test.ts

- Ticket: https://openscience.atlassian.net/browse/ENG-1131
To add an `onContinue` hook to the `partial-registration-modal`
- Add `continue` action and `onContinue` hook
- Updated tests to check for `continue` call
`N/A`
`N/A`

[ENG-1131] Add onContinue hook to partial-registration-modal

---

CHANGELOG.md
app/packages/registration-schema/index.ts
app/packages/registration-schema/registration-response.ts
lib/handbook/addon/docs/components/schema-block-group-renderer/controller.ts
lib/handbook/addon/docs/components/schema-block-group-renderer/route.ts
lib/handbook/addon/docs/components/schema-block-group-renderer/template.md
lib/osf-components/addon/components/files/manager/component.ts
lib/osf-components/addon/components/files/widget/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/files/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/files/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/mapper/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/files/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/files/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/mapper/template.hbs
lib/osf-components/app/components/registries/review-form-renderer/component.js
lib/osf-components/app/components/registries/schema-block-renderer/editable/files/component.js
lib/osf-components/app/components/registries/schema-block-renderer/read-only/files/component.js
mirage/scenarios/default.ts
mirage/serializers/file.ts
tests/integration/components/registries/schema-block-group-renderer/component-test.ts

- Ticket: https://openscience.atlassian.net/browse/ENG-1091
- To add `files-widget` to the `schema-block-renderer` component
- Add check for `files-input` in read-only and editable mapper files
- Add components for `files` that renders the read-only and editable versions
- Update test to include `files` widget
- Add `SchemaBlockNode` to default scenario that includes both contributors and files
`N/A`
`N/A`

[ENG-1091] Add files widget to schema-block-renderer

---

ember-cli-build.js
lib/osf-components/addon/components/registries/draft-registration-manager/component.ts
lib/osf-components/addon/components/registries/draft-registration-manager/template.hbs
lib/registries/addon/drafts/draft/-components/register/component.ts
lib/registries/addon/drafts/draft/-components/register/template.hbs
lib/registries/addon/drafts/draft/template.hbs
tests/engines/registries/acceptance/draft/draft-test.ts

- Ticket: [ENG-1181](https://openscience.atlassian.net/browse/ENG-1181)
Rework validations and bump autosave debounce to 5s
- Now validate all visited pages on current page load
- Now validate marks all pages as visited upon entering review route and validates all
- Add validation tests
- Bump autosave debounce to 5s

[ENG-1181][ENG-1182] Rework validations, increase autosave debounce 5s

---

lib/osf-components/addon/components/registries/schema-block-renderer/editable/multi-select-input/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/multi-select-input/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/single-select-input/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/single-select-input/template.hbs

Fix how help text is handled for single and multi select
only handle strings for display text and use a mapping object to get help text

[No ticket] Update how the help text is accessed in single/multi select

---

app/packages/registration-schema/registration-response.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/files/component.ts
mirage/factories/utils.ts

Backend expects `file_urls` instead of `file_url`

fix file autosave by changing file_url to file_urls

---

app/locales/en/translations.ts
config/environment.d.ts
config/environment.js

- Ticket: n/a
To add a link to the `Learn more about links` in the embargo modal
- Turn `Learn more about links` into a link
- Add spaces after sentences
`N/A`
`N/A`

[No Ticket] Add link in embargo modal

---

app/locales/en/translations.ts
app/models/file.ts
lib/osf-components/addon/components/files/browse/component.ts
lib/osf-components/addon/components/files/browse/styles.scss
lib/osf-components/addon/components/files/browse/template.hbs
lib/osf-components/addon/components/files/item/component.ts
lib/osf-components/addon/components/files/item/template.hbs
lib/osf-components/addon/components/files/list/template.hbs
lib/osf-components/addon/components/files/manager/component.ts
lib/osf-components/addon/components/files/manager/template.hbs
lib/osf-components/addon/components/files/selected-list/component.ts
lib/osf-components/addon/components/files/selected-list/template.hbs
lib/osf-components/addon/components/files/upload-zone/component.ts
lib/osf-components/addon/components/files/widget/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/files/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/files/template.hbs
tests/integration/components/files-widget/component-test.ts
tests/integration/components/registries/schema-block-group-renderer/component-test.ts

- Ticket: [ENG-1211]
- Show previously selected file as selected upon reloading the draft
- Check uploading multiple versions of the same file in draft — should replace file on draft, don't list both versions
- File widget folders:
- transition slides the wrong way when navigating up/back to non-root folders
- "invalid date"
- Upload to any folder
- Uploading a file refreshes other node files in other files-widgets

[ENG-1211] Files widget improvements

---

app/guid-node/drafts/index/route.ts
app/guid-node/drafts/register/route.ts
app/guid-node/drafts/route.ts
app/router.ts
config/environment.js
lib/osf-components/addon/components/draft-registration-card/component.ts
mirage/serializers/draft-registration.ts

- Ticket: [ENG-1211]
Update the actions for the Edit and Register buttons on draft registration cards so that they transition to routes instead of load URLs.
- add `branchedFrom` and `initiator` resource linkage to draft-registration mirage serializer (to match API)
- add `index` and `register` routes under `guid-node.drafts`
- transition to routes when clicking edit/register buttons in `DraftRegistrationCard`
None expected.

[ENG-1211] Update DraftRegistrationCard buttons to transition to registries/drafts

---

app/authenticators/osf-cookie.ts
lib/osf-components/addon/components/osf-navbar/auth-dropdown/component.ts

- Ticket: [ENG-1212]
The app currently makes a request to the API's `/v2/` on every page transition in an engine, and blocks the transition until it gets back. This seems to be an interaction between engines and the `view_only` query param on the application route (specifically, because it has `refreshModel: true`).
This PR is a quick fix to avoid blocking transitions on a network request -- better solutions would include (1) patching ember-engines to avoid the unnecessary work in model hooks and (2) no longer using ember-engines.
- `osf-cookie` authenticator:
- when auth is successfully verified via the api, stash the user id on the authenticator
- when restoring auth, check whether the last id verified by this authenticator matches the id in localStorage -- if so, no …

[ENG-1212] Avoid unnecessary auth requests

---

app/home/-components/hero-banner/component.ts
app/home/-components/hero-banner/styles.scss
app/home/-components/hero-banner/template.hbs
app/home/-components/integrations-section/component.ts
app/home/controller.ts
app/home/route.ts
app/locales/en/translations.ts
config/environment.d.ts
config/environment.js
package.json
tests/acceptance/logged-out-homepage-test.ts
tests/integration/components/hero-banner/component-test.ts
yarn.lock

- Ticket: https://openscience.atlassian.net/browse/ENG-875
To do round 2 AB testing changes to the logged-out homepage
- Use layout A (Calls to Action stacked)
- Change version A headline to: The place to share your research
- Add version B headline to: There's a better way to manage your research
`N/A`
Logged-out homepage should now only be using version A layout without the only other difference being the headline text between versions A and B.

[Feature][ENG-875] Update logged-out homepage to use version A and alter text

---

app/locales/en/translations.ts
app/models/file-provider.ts
lib/osf-components/addon/components/files/browse/component.ts
lib/osf-components/addon/components/files/browse/template.hbs
lib/osf-components/addon/components/files/item/component.ts
lib/osf-components/addon/components/files/item/styles.scss
lib/osf-components/addon/components/files/item/template.hbs
lib/osf-components/addon/components/files/manager/component.ts
lib/osf-components/addon/components/files/manager/template.hbs
lib/osf-components/addon/components/files/selected-list/component.ts
lib/osf-components/addon/components/files/selected-list/template.hbs
lib/osf-components/addon/components/files/upload-zone/component.ts
lib/osf-components/addon/components/files/upload-zone/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/files/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/files/template.hbs
mirage/factories/file-provider.ts
mirage/factories/node.ts
mirage/scenarios/default.ts
mirage/serializers/file-provider.ts
mirage/views/file.ts
tests/integration/components/files-widget/component-test.ts

- Ticket: https://openscience.atlassian.net/browse/ENG-1211
File widgets improvements
- Utilize ember-data to sync up files across files-widget
- Add `rootFolder` relationship to file-provider model
- Use `rootFolder` on the files-widget manager.
- Update tests to use `rootFolder`
- Update mirage setup for file-provider, submission acceptance tests.
- Update language for text on top of the files-widget.

[ENG-1211] Clean up files-widget

---

app/transforms/registration-response-key.ts
app/transforms/registration-responses.ts
tests/engines/registries/acceptance/draft/draft-test.ts

- Ticket: [ENG-1211]
Questions with a `registration_response_key` that collides with a changeset property will cause erroneous behavior (e.g. the first question on Preregistration Template from AsPredicted.org has key `data`, and cannot be filled out)
We already have transforms to make response keys changeset-friends (replacing `.` by `|`). This extends those transforms to also add a nice, unique prefix.
n/a
This is, fortunately, neither a migration nor a data issue. This should work fine now:

[ENG-1211] sufficiently unique response keys

---

lib/osf-components/addon/components/registries/schema-block-group-renderer/component.ts
lib/osf-components/addon/components/registries/schema-block-group-renderer/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/label/label-content/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/label/label-content/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/label/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/label/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/template.hbs
lib/osf-components/app/components/registries/schema-block-renderer/label/label-content/template.js

- Ticket: https://openscience.atlassian.net/browse/ENG-1211
Any input that has a group of options should be contained in a `<fieldset>` and use a `<legend>`.  This adds those to only `single-select-input` and `multi-select-input` blocks.
- Use `<fieldset>` and `<legend>` on single and multi select blocks and style to match labels
- Create new component under `label` that contains the template and styling for inner label content
`n/a`
`n/a`

[ENG-1211][Feature] Use `fieldset` and `legend` for multi-select and single-select inputs

---

app/locales/en/translations.ts
lib/osf-components/addon/components/files/browse/styles.scss
lib/osf-components/addon/components/files/browse/template.hbs
lib/osf-components/addon/components/files/item/component.ts
lib/osf-components/addon/components/files/item/template.hbs
lib/osf-components/addon/components/files/selected-list/styles.scss
lib/osf-components/addon/components/files/selected-list/template.hbs

- Ticket: [ENG-1211](https://openscience.atlassian.net/browse/ENG-1211)
Make files-widget more aa
Minor: Fix overflow wrap when unselecting a file
- Make file items tab-focusable and respond to [enter] keypress event.
- Add aria-labels to button with no text, just an icon.

[ENG-1211] Make files-widget more aa

---

lib/osf-components/addon/components/registries/finalize-registration-modal/component.ts
lib/osf-components/addon/components/registries/finalize-registration-modal/template.hbs
lib/osf-components/addon/components/registries/partial-registration-modal/template.hbs
lib/registries/addon/drafts/draft/-components/register/component.ts
lib/registries/addon/drafts/draft/-components/register/template.hbs
lib/registries/addon/drafts/draft/route.ts

This PR changes 3 things:
1. Partial registration modal is hidden if the node has no children.
2. Outside click for partial registration modal and finalize registration model does not close the dialog
3. Change 4 years to 1460 days for maximum embargo length to match backend.

Hide partial reg modal if no children; outside click should not close dialog; 4 years to 1460 days.

---

lib/osf-components/addon/components/registries/schema-block-renderer/label/label-content/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/label/label-content/template.hbs

Preserve whitespace for display text formatting. (See Prereg in Social Psych > B. Methods - Essential elements > Design)
- Wrap display text in div and put `white-space: prewrap` on div
- Trim whitespace using hbs `~` helper
`N/A`
`N/A`

[No ticket]Wrap display text in div for whitespace formatting and trim white-space

---

app/locales/en/translations.ts
lib/osf-components/addon/components/files/selected-list/component.ts
lib/osf-components/addon/components/files/selected-list/styles.scss
lib/osf-components/addon/components/files/selected-list/template.hbs
lib/osf-components/addon/components/registries/schema-block-group-renderer/component.ts
lib/osf-components/addon/components/registries/schema-block-group-renderer/styles.scss
lib/osf-components/addon/components/registries/schema-block-group-renderer/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/base/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/editable/files/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/files/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/editable/files/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/label/label-content/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/label/label-content/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/label/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/label/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/page-heading/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/read-only-contributor-list/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/read-only-contributor-list/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/read-only-contributor-list/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/section-heading/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/subsection-heading/styles.scss
lib/registries/addon/drafts/draft/page/styles.scss

- Ticket: []
This removes all border between questions and cleans up whitespace so that it is consistent. It also pulls the instructions for files out of `Files::SelectedList` for better whitespace control (and because these instructions are specific to registries submission).
For whitespace between elements, I've [defined two CSS classes](https://github.com/CenterForOpenScience/ember-osf-web/pull/877/files#diff-afbe43ac228fb8ba6922a0dfad750483) for all schema blocks:
* `Heading` - sets 20px of top margin except for the first child. It also removes any padding. This class is used for headings, labels, and fieldsets.
* `Element` - set a 10px top margin. This is used for all non-label elements.
CSS modules `composes` is used to bring these classes into local classes with …

Remove borders & whitespace cleanup

---

lib/osf-components/addon/components/files/manager/component.ts

- Ticket: []
Fix issue where files-widget breaks when user has linked multiple addons
to their project.
Filter list of storage addons by name.
- Enable multiple storage addons.
- Check and see if files widget can pull node files.

Filter storage providers list by name

---

lib/registries/addon/components/registries-navbar/template.hbs
tests/engines/registries/integration/components/registries-navbar/component-test.ts

- Ticket: []
New version 3.8.1, ember-bootstrap > dropdown.menu  does not seem to support splattributes.
Fix tests.

Remove data-test-* from BsDropdown menu

---

lib/osf-components/addon/components/editable-field/publication-doi-manager/component.ts
lib/osf-components/addon/components/editable-field/publication-doi-manager/template.hbs
lib/osf-components/addon/components/node-publication-doi-editable/template.hbs
tests/engines/registries/acceptance/overview/overview-test.ts

- Ticket: []
Fix editable publication doi tests: use `ember-changeset-validations` instead of `ember-cp-validations`

Fix editable publication doi tests: use ember-changeset-validations

---

tests/engines/registries/integration/components/registries-navbar/component-test.ts
tests/integration/components/osf-navbar/auth-dropdown/component-test.ts

- Ticket: []
Add percy snapshots for `<OsfNavbar/>` and `<RegistriesNavbar/>`.

Add percy snapshots for osf-navbar and registries-navbar

---

lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
lib/osf-components/addon/components/osf-navbar/template.hbs
tests/integration/components/osf-navbar/auth-dropdown/component-test.ts
tests/integration/components/osf-navbar/component-test.ts

More Percy snapshots for `osf-navbar`.
Add and update tests.

Add better percy snapshots for osf-navbar

---

lib/osf-components/addon/components/validated-input/checkboxes/x-checkbox/component.ts

- Fix unchecked checkbox in Personal Access Token test's Percy snapshot
- Make sure the parameters used in checkbox are the types we expect them to be
- handle cases when the relation array is a promise and force it into an array
`n/a`
- Please keep an eye on checkbox behavior (I doubt this should adversely effect existing things, but just in case 👀 )

Make sure checkboxes load as checked for PAT test snapshot

---

app/styles/_components.scss
lib/analytics-page/addon/application/template.hbs
lib/collections/addon/components/discover-page/template.hbs
lib/osf-components/addon/components/delete-node-modal/template.hbs
lib/osf-components/addon/components/file-browser/component.ts
lib/osf-components/addon/components/file-browser/template.hbs
lib/osf-components/addon/components/new-project-navigation-modal/template.hbs
lib/osf-components/addon/components/node-card/styles.scss
lib/osf-components/addon/components/node-card/template.hbs
lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
lib/osf-components/addon/components/osf-navbar/template.hbs
lib/registries/addon/components/registries-header/template.hbs
lib/registries/addon/components/registries-navbar/styles.scss
lib/registries/addon/components/registries-navbar/template.hbs
lib/registries/addon/discover/template.hbs
lib/registries/addon/index/template.hbs
lib/registries/package.json
package.json
tests/integration/components/delete-node-modal/component-test.ts
tests/integration/components/new-project-navigation-modal/component-test.ts
yarn.lock

- Ticket: []
Upgrade ember-bootstrap to 3.0.0, fix styles broken in latest upgrade to 2.8.1.
versions: 1.2.2 -> 2.8.1 -> 3.0.0
Somewhere between 1.2.2 -> 2.8.1, ember-bootstrap started using ember-popper (at least for `BsDropdown`) to absolute position the menu. This change broke styles that were initially lifted
from `osf-style`.
-  Update dropdown styles.
-  Add percy to registries-navbar

Upgrade ember-bootstrap to v3.0.0, fix broken styles

---

app/models/draft-registration.ts

- Ticket: https://openscience.atlassian.net/browse/ENG-1282
To update the `draft-registration` model with new fields and relationships to match metadata field additions on the backend.
- Add fields to the `draft-registration` model
- `N/A`
There shouldn't be any noticeable changes.

[ENG-1282] Update draft-registration model with metadata fields

---

CHANGELOG.md
package.json
yarn.lock

- Ticket: `N/A`
To update `eslint` to the newest version.
- Updated `eslint-config-airbnb-base` from `13.1.0` to `14.0.0`
There shouldn't be any side effects
`N/A` -> An update to `eslint` will not affect anything user-facing. It will only affect tests (failing because of new rules, etc.)

[No Ticket] Update eslint

---

CHANGELOG.md
lib/osf-components/addon/components/debouncer/component.ts
lib/osf-components/addon/components/debouncer/template.hbs
lib/osf-components/app/components/debouncer/component.js
lib/registries/addon/drafts/draft/page/template.hbs
tests/integration/components/debouncer/component-test.ts

- Ticket: [ENG-610]
Add a debounce component that will take care of the save debouncing behavior
- added a component `debouncer` that has functions `doFnDebounce` and `doFnNow`
- use `debouncer` in `draft/page` template
N/A: additive change
- What pages should be tested?
- The draft registration workflow should be tested to see if the save behavior is consistent throughout. Save should wait until about 5 seconds after the latest user input.
- Is cross-browser testing required/recommended?
- no
- What edge cases should QA be aware of?
- If a user makes a change and navigates away from the page before the changes are saved, I'm not too sure what happens...
- What level of risk would you expect these changes to have?
- not very big (localized only to the draft …

[ENG-610]Add debounce component

---

lib/osf-components/addon/components/files/menu/component.ts
lib/osf-components/addon/components/files/menu/template.hbs
lib/osf-components/addon/components/files/upload-zone/component.ts
lib/osf-components/addon/components/files/upload-zone/template.hbs
lib/osf-components/addon/components/responsive-dropdown/component.ts
lib/osf-components/addon/components/responsive-dropdown/template.hbs

- Ticket: []
Follow up bug fix: to [ENG-1292](https://openscience.atlassian.net/browse/ENG-1292).
Prevent outside click from interrupting ongoing upload
- Update `ResponsiveDropdown` to take `onClose` callback.
- Files widget >> upload file button >> select file (preferably a big file)
- Right after selecting file to upload from file browser, click outside the menu continually. The menu should not close.

Prevent outside click from interrupting upload

---

lib/osf-components/addon/components/registries/schema-block-renderer/read-only/response/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/response/template.hbs

- Ticket: [ENG-1316]
Whitespace in user-entered responses should be preserved on the registration draft review page and overview page.
* Add `whitespace: pre-wrap` to response paragraph
* Eat up whitespace surrounding the response
None expected.
Make sure whitespace (e.g. paragraphs) is preserved on the registration draft review page during registration and overview page after registration.
[ENG-1316]: https://openscience.atlassian.net/browse/ENG-1316

[ENG-1316] fix: preserve whitespace formatting in read-only response

---

lib/osf-components/addon/components/registries/draft-registration-manager/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/mapper/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/multi-select/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/multi-select/template.hbs
lib/osf-components/app/components/registries/schema-block-renderer/read-only/multi-select/template.js

- Ticket: [ENG-1333]
On registries draft review page and overview page, display selected multi-select options as an unstyled list.
* add read-only multi-select schema-block-renderer
* use schema-block-renderer/read-only/multi-select
None expected.
This affects the registries draft review page and the registries overview page. When multiple options are selected in a multi-select question (e.g. Design plan -> Blinding on OSF Prereg) instead of being displayed as a comma-separated list the options should be displayed on separate lines separated by whitespace.
[ENG-1333]: https://openscience.atlassian.net/browse/ENG-1333

[ENG-1333] Use list for selects

---

app/transforms/registration-responses.ts
tests/unit/transforms/registration-responses-test.ts

- Ticket: [ENG-1390]
When the API returns `null` for `registration_responses`, the registration-responses transform causes an exception because it passes the value to `mapKeysAndValues`, which expects an object. `registration_responses` being `null` is not an expected state, but there is at least [one registration on staging2](https://api.staging2.osf.io/v2/registrations/b29hf/) for which this is the case.
* add a custom typeguard that tests for an object with string keys.
* if registration_responses fails the typeguard, return an empty object.
* added unit test for registration-responses transform
None expected.
It *should* be impossible, normally, to get a registration into a state where `registration_responses` is `null`, but there is at least one registration in …

[eng-1390] fix: handle case where registration_responses is null

---

app/application/route.ts
app/utils/window-location.ts
lib/osf-components/addon/components/banners/view-only-link/component.ts
tests/acceptance/guid-file/file-detail-test.ts
tests/acceptance/logged-out-homepage-test.ts
tests/acceptance/settings/developer-apps-page-test.ts
tests/acceptance/settings/tokens-page-test.ts
tests/acceptance/view-only-link-test.ts
tests/engines/registries/acceptance/overview/index-test.ts
tests/unit/utils/window-location-test.ts

- Ticket: [None]
- turn `refreshModel` to false
- update tests that will fail after  this change
- turn `refreshModel` to false
- use `currentRouteName` and `currentURL().includes()` instead of `currentURL() equals`
none
These changes shouldn't have an effect on current functionality. They will effect how query params show up on the url bar, but no changes otherwise.

Update tests after turning refreshModel: false

---

app/models/osf-model.ts
lib/collections/addon/components/discover-page/facets/collection-provider/component.ts
package.json
yarn.lock

- Ticket: [ENG-601]
Upgrade to latest stable ember-source, ember-data, and ember-cli.
* chore: upgrade to ember-source@~3.15.0
* fix: schedule collections provider active filter push
* chore: upgrade to ember-data@~3.15.0
* fix: underscore relationship names for lookup in relationshipLinks
* chore: upgrade to ember-cli@~3.15.1
None expected.
In addition to upgrading Ember, this PR makes a small change to how the active provider filter is added on the Collections Discover page. Should test that discover page results are indeed properly filtered by collection.
[ENG-601]: https://openscience.atlassian.net/browse/ENG-601

[ENG-601] Upgrade to Ember 3.15 (Octane)

---

lib/registries/addon/drafts/draft/draft-registration-manager.ts
lib/registries/addon/drafts/draft/metadata/controller.ts
lib/registries/addon/drafts/draft/metadata/route.ts
lib/registries/addon/drafts/draft/metadata/template.hbs
lib/registries/addon/drafts/draft/page/template.hbs

- Ticket: []
- Add changeset for metadata page to support save capability
- Added a new `enum` in metadata route called `MetadataProperties`
- Add new task to create changeset for draftMetadata
- Add new task to save metadata
- Apply save task (`onMetadataInput`) to metadata template
- Update name of `onInput` to `onPageInput`
- There should be none, but let's just double check to see if changes to the draft pages are not effected 😅 
- This will be tested with the draft_metadata release

Add changeset for metadata and save capability

---

mirage/views/user-password.ts
types/ember-cli-mirage/index.d.ts

- Ticket: n/a
Our ember-cli-mirage types redefine the built-in `Record` utility type, which we attempt use elsewhere in the ember-cli-mirage type declaration file (for Response headers). This results in the `Response` constructor expecting args of incorrect type.
* don't clobber the `Record` type
* update `Response` constructor with better types
* update usage of `Response` to no unnecessarily pass `undefined`
None expected.
No QA needed as this does not affect runtime or production code.

fix(types): don't clobber Record in ember-cli-mirage types

---

lib/osf-components/addon/components/editable-field/license-manager/component.ts
lib/osf-components/addon/components/editable-field/license-manager/template.hbs
lib/registries/addon/components/registries-license-picker/template.hbs
tests/engines/registries/acceptance/overview/overview-test.ts

- Ticket: https://openscience.atlassian.net/browse/ENG-1440
The search functionality in the power-select on the registries overview page is currently broken and should be fixed.
- Remove query search function and replace it with native functionality on the power-select
`N/A`
Should only affect components that are using the `registries-license-picker`. As of this PR, this will only be the editable license field, used on the registries overview page. However it will also eventually be used in the metadata license picker, used in registries submission.

[ENG-1440][Bug] Fix search bug in power-select

---

lib/analytics-page/package.json

- Ticket: https://openscience.atlassian.net/browse/ENG-1034
Currently the analytics page is breaking when users click to 'View Links'. This is because it needs `ember-composable-helpers` to be included in order to use the range helper.
- Add `ember-composable-helpers` to the analytics engine
`N/A`
Because this was only adding a dependency to the analytics page, there shouldn't be any outward effects besides getting rid of the current issue. The modal should now display and will not break the page anymore on click.

[Bug] [ENG-1034] Fix Analytics page breaking on 'View Links' button click

---

lib/registries/addon/drafts/draft/-components/top-nav/template.hbs
tests/engines/registries/acceptance/draft/draft-test.ts

- Ticket: []
To add a test for the registries mobile navbar.
- Add acceptance test for the mobile navbar
`N/A`
This is only adding a test and won't have any outward facing changes.

[Improvement] Add test for registries mobile navbar

---

.travis.yml

- Ticket: n/a
Temporarily disable the handbook build since it's failing after the upgrade to Ember 3.15.
* comment out "deploy handbook" stage in .travis.yml
n/a
n/a

Temporarily disable handbook build

---

app/models/draft-registration.ts
app/packages/registration-schema/index.ts
app/packages/registration-schema/validations.ts
lib/registries/addon/components/page-link/component.ts
lib/registries/addon/drafts/draft/draft-registration-manager.ts
lib/registries/addon/drafts/draft/metadata/route.ts
lib/registries/addon/drafts/draft/template.hbs
tests/engines/registries/acceptance/draft/draft-test.ts

- Ticket: [ENG-1420]
- Add validations to the required inputs of the Draft Metadata page
- Add `metadataIsValid` property to `DraftRegistrationModel` class
- Add new function to `app/registration-schema/validation.ts` to build the Metadata validations object
- refactored the existing validation building function for readability
- Moved + renamed `MetadataProperties` to `DraftMetadataProperties` under `draft-registration` model
- Add Subjects to the `DraftMetadataProperties` enum
- *Contributors will not be validated at this stage*
- Update `draft form` test to check metadata validations
- All functionality should be maintained in the draft registration process
This PR is responsible for adding error messages to the draft Metadata page. As functionality on that page is …

[ENG-1420] Add validations to metadata page

---

lib/osf-components/addon/components/editable-field/license-manager/component.ts
lib/osf-components/addon/components/editable-field/license-manager/template.hbs
lib/registries/addon/components/registries-license-picker/template.hbs

- Ticket: [ENG-1451]
Fix overview page editable field weirdness.
Somehow `selectedLicense` is an alias to `node.license`. Remove that alias.
None.
First go to overview page of a registration. Change the license and save. Then change the license again but instead of clicking `Save`, click `Cancel`. The change should not be persisted and the license field shows the correct license.
[ENG-1451]: https://openscience.atlassian.net/browse/ENG-1451

[ENG-1451] Fix editable field.

---

app/adapters/sparse-node.ts
app/dashboard/controller.ts
app/models/sparse-node.ts
app/models/user.ts
app/serializers/sparse-node.ts
app/serializers/user.ts
mirage/config.ts

- Ticket: [ENG-1400]
Change dashboard project list to use sparse node endpoint.
Add `SparseNode` model. Fake the `sparseNodes` relationship on user.
There shouldn't be any.
Make sure the dashboard page project list works exactly the same as before.
[ENG-1400]: https://openscience.atlassian.net/browse/ENG-1400

[ENG-1400] Use sparse node for dashboard project list

---

lib/registries/addon/drafts/draft/-components/top-nav/template.hbs
lib/registries/addon/drafts/draft/review/styles.scss
lib/registries/addon/drafts/draft/styles.scss
tests/engines/registries/acceptance/draft/draft-test.ts

- Ticket: `n/a`
To fix tests on the draft_manager branch. Currently failing because it isn't expecting the new metadata page.
This will also fix the headings for the metadata and review pages on the mobile navbar.
- Update test to anticipate being at the metadata page when first going to the registries' submission page
- Fix the mobile navbar headers
`n/a`
This will affect tests (which shouldn't have any side effects), and the header on the mobile navbar on registries submission. It shouldn't affect anything else.

[No Ticket] [Bug] Update metadata test

---

lib/app-components/addon/components/project-metadata/template.hbs
lib/osf-components/addon/components/license-picker/component.ts
lib/osf-components/addon/components/license-picker/template.hbs

- Ticket: `n/a`
With the draft-metadata license picker changes also came a change to the placeholder from `Required` to `Select license`. This change causes an issue with collections though since it needs the required placeholder there. This will add a new placeholder param that can be passed into the `license-picker` to help it be more dynamic.
- Add `placeholder` param with default value of `Select license`
- Update the collections instance of the `license-picker` to also pass in a value of `Required` to the placeholder
This shouldn't have any side effects.
This will affect the `license-picker` component, which is used in three places: the editable metadata field on the registries overview page, the draft-metadata section in registries submission, and on the …

[No Ticket] [Bug] Update placeholder to accept a param

---

app/guid-file/route.ts
tests/acceptance/guid-user/quickfiles-test.ts

- Ticket: [ENG-1452]
Due to recent upgrades ember-data, the frontend errors when
we lookup file detail using the guid `/v2/files/wsfvj` and return id as the long _id.
If the file record is present in the store with identifier (ember-data) `file:file_long_id` (say you've loaded the list of quickfiles before the detail view),  ember-data IdentifierCache triesto make a new identifier (`file:guid`) but realize that record already exists and fails to merge both identifiers. 
<details>
<summary>console errors</summary>
"Error: Failed to update the 'id' for the RecordIdentifier 'file:wsfvj (@ember-data:lid-file-wsfvj)' to '5df166775ba94a0009c70765', because that id is already in use by 'file:5df166775ba94a0009c70765 (@ember-data:lid-file-5df166775ba94a0009c70765)'
at …

[ENG-1452] Lookup file detail using file long id not guid

---

lib/registries/addon/drafts/draft/-components/top-nav/styles.scss
lib/registries/addon/drafts/draft/-components/top-nav/template.hbs

- Ticket: `n/a`
The metadata button on the mobile navbar on registries submission currently has a border that goes outside of its container.
- Change padding of the metadata button from `16px` to `15px`
`n/a`
This should only affect the metadata button on the mobile navbar on registries submission. It should only remove the overflowing border on the right side of the button. There shouldn't be any other notable effects from this.

[No Ticket] [Bug] Fix metadata button border

---

app/transforms/registration-responses.ts
app/utils/fix-special-char.ts

- Ticket: [ENG-1322]
Fix special character encoding issue in the registration form.
Use `fixSpecialChars` in the `registration-response` transform.
Special characters should not appear in the registration form now.
[ENG-1322]: https://openscience.atlassian.net/browse/ENG-1322

[ENG-1322] Fix special character for registration form

---

app/packages/registration-schema/page-manager.ts
app/serializers/draft-registration.ts
app/validators/validate-response-format.ts
lib/osf-components/addon/components/registries/draft-registration-manager/component.ts
lib/osf-components/addon/components/registries/draft-registration-manager/template.hbs
lib/osf-components/addon/components/registries/review-form-renderer/template.hbs
lib/registries/addon/drafts/draft/page/template.hbs
tests/engines/registries/acceptance/draft/draft-test.ts

- Fix out-of-sync registrationResponses when user switches to review right after modifying
an input field.
- Avoid reloading known deleted files
- Don't save or validate visited page on page load, because there aren't changes and each visited page's changeset is validated when its page manager is instantiated.
- use `registration.registrationResponses` instead of `draftManager.registrationResponses` 
- Avoid reloading known deleted files. They won't come back.
- Add tests; Update tests to use navigation controls instead of reloading the whole app with `visit`; this will help catch more bugs.
- Fix file validations TypeError; [sentry error logs](https://staging-sentry.cos.io/cos/ember-osf-web-27/issues/7864/) We were not normalizing array data (list of draft-registration), so when you …

upgrade all things bugs fixes

---

lib/osf-components/addon/components/citation-viewer/component.ts

- Ticket: [ENG-1288]
Fix special character encoding for `citation-viewer` component.
Use `fixSpecialChars` for the citation endpoint response. It would be nicer if we use ember-data to fetch these citations though...
Citation on registration overview page should render special characters without escaping.
[ENG-1288]: https://openscience.atlassian.net/browse/ENG-1288

[ENG-1288] fix special char encoding for citation widget

---

lib/registries/addon/drafts/draft/navigation-manager.ts
tests/engines/registries/acceptance/draft/draft-test.ts

- Ticket: [ENG-1527]
The right navigation buttons could end up in a state where it would display the `Next ->` button on the review page, or `<- Back` on the metadata page. This PR fixes this issue.
- Add `currentRoute` to the dependent keys of `nextPageParam` and `prevPageParam` in `NavigationManager`
- Added tests to assert which icons should be shown in the LeftNav test of the `draft form` acceptance test
- No side effects should be present
- This PR should fix the aforementioned issue and also tighten up the test coverage in these scenarios. This should fix any mismatch between the actual state of the draft registration and what is shown in the left or right navigation columns
[ENG-1527]: https://openscience.atlassian.net/browse/ENG-1527

[ENG-1527] Fix rightnav issues

---

lib/osf-components/addon/components/form-controls/power-select/template.hbs
lib/registries/addon/components/registries-license-picker/template.hbs
lib/registries/addon/drafts/draft/metadata/styles.scss
lib/registries/addon/drafts/draft/metadata/template.hbs
translations/en-us.yml

- Ticket: https://openscience.atlassian.net/browse/ENG-1523
To add styling to the metadata page on registries submission.
- Add styling
- Update some components to allow `...attributes`
- Add translations for heading and description text
`N/A`
This should only affect styling on the metadata page. Only adds styles to the page and doesn't change anything pre-existing.

[ENG-1523] [Feature] Add metadata styling

---

lib/osf-components/addon/components/status-banner/template.hbs
tests/acceptance/status-banner-test.ts

Render status messages as htmlSafe
- Add `htmlSafe=true` to status message translations.
- Add acceptance test and Percy snapshot.
Please make sure the welcome message has no html markup in it. Other status messages should also show correctly if we do get them on the emberized frontend.

[ENG-1546] Render status messages as htmlSafe

---

lib/registries/addon/components/registries-navbar/styles.scss

Temp fix to unblock release.
In our production build, the `dropdown-menu-right` class does not contain `left:auto` while our non-production build contains `left:auto, right:0`. This is likely a build issue regard how production and non-production build import css assets differently.
Fixed:
Broken:

[ENG-1574] Temp fix for nav dropdown

---

lib/osf-components/addon/components/subjects/manager/component.ts
lib/registries/addon/drafts/draft/-components/metadata-institutions-manager/component.ts

Currently, the autosave timestamp on the right nav does not change after successful update of subjects and institutions. Since that timestamp relies on the `draft-registration` model's `dateTimeUpdated` attribute and the `updateM2MRelationship` method does not reload the model after the update, we will manually trigger a model reload.
Reload the model in subjects manager and institution manager.

[ENG-1572] Reload the model after updating subjects and institutions.

---

lib/osf-components/addon/components/registries/review-metadata-renderer/template.hbs
lib/registries/addon/drafts/draft/-components/tags-manager/component.ts
lib/registries/addon/drafts/draft/-components/tags-manager/template.hbs

Currently, draft metadata page's tags widget would not show updated tags if you go to review page and come back. This PR fix the problem.
Because the tags widget relies on `tagsManager.tags` to render the list of existing tags, changes are made to initialize the `tags` array with existing tags on the model in `didReceiveAttrs()`.
[ENG-1572]: https://openscience.atlassian.net/browse/ENG-1572

[ENG-1572] Fix tags widget not update issue on metadata page

---

tests/integration/components/form-controls/power-select/component-test.ts

No functionality changes. Update tests to ensure that the text is shown on the power-select element.

[No ticket][No QA] Fix power select tests

---

app/utils/capture-exception.ts
lib/osf-components/addon/components/registries/finalize-registration-modal/manager/component.ts

- Ticket: []
there's a mysterious problem on production with submitting registrations, but we don't get the error logged to sentry.
- add a `captureException` util that will log to sentry if the global `Raven` is defined
- log the error to sentry
n/a
n/a

[hotfix] log registration submit errors to sentry

---

app/packages/registration-schema/validations.ts
lib/osf-components/addon/components/subjects/manager/component.ts
lib/osf-components/addon/components/subjects/manager/template.hbs
lib/registries/addon/components/page-link/component.ts
lib/registries/addon/components/registries-license-picker/styles.scss
lib/registries/addon/components/registries-license-picker/template.hbs
lib/registries/addon/drafts/draft/draft-registration-manager.ts
lib/registries/addon/drafts/draft/metadata/template.hbs
lib/registries/addon/drafts/draft/page/controller.ts
tests/engines/registries/acceptance/draft/draft-test.ts

This PR fix three things:
- Metadata page doesn't validate when navigating away
- Subjects field doesn't have validation error message
- Some of the required fields doesn't have a red * next to the label.
- In `updateRoute()` hook of the `drafts/draft/page` controller, we validate `metadataChangeset` so what the validation will run on the metadata page upon navigating away.
- In `page-link` component, make the `pageState` watch for changes in `metadataIsValid` so that it can recompute on validation status change.
- Added `validateSubjects` validator function and use that to build validation object for `metadataChangeset`.
- In `subjects/manager` component, we pass the `metadataChangeset` to it and validate the `subjects` property on save.
- Added …

[ENG-1572] Validate metadataChangeset when navigate away from metadata page.

---

lib/registries/addon/components/registries-license-picker/template.hbs
lib/registries/addon/components/registries-tags-widget/component.ts
lib/registries/addon/components/registries-tags-widget/styles.scss
lib/registries/addon/components/registries-tags-widget/template.hbs
lib/registries/addon/drafts/draft/-components/tags-manager/component.ts
lib/registries/addon/drafts/draft/metadata/styles.scss
lib/registries/addon/drafts/draft/metadata/template.hbs
lib/registries/addon/drafts/draft/template.hbs

- Ticket: https://openscience.atlassian.net/browse/ENG-1572
To update styles on the metadata page.
- Fix searchable subjects styling
- Update tabbable focus to not jump to the hidden 'Next' button
- Update tags to look like subjects
- License field styling
`N/A`
Will affect the style on only the metadata page. Tabbable focus should fix the issue seen on mobile/ipad devices (hitting tab on the last input on the page will focus on the hidden 'Next' button).

[ENG-1572] Update metadata styling

---

lib/osf-components/addon/components/form-controls/power-select/template.hbs
lib/osf-components/addon/components/institution-select-list/template.hbs
lib/osf-components/addon/components/registries/registration-form-navigation-dropdown/template.hbs
lib/osf-components/addon/components/subjects/browse/item/template.hbs
lib/osf-components/addon/components/subjects/display/template.hbs
lib/registries/addon/drafts/draft/metadata/styles.scss
lib/registries/addon/drafts/draft/metadata/template.hbs
translations/en-us.yml

- Ticket: [ENG-1525]
Make our new Metadata content accessible ♿️ 
- Added aria-labels to things that did not previously have them
- Used `<fieldset>` and `<legend>` to group categories with multiple inputs (institutions, subjects)
- There were issues getting the `<TagsInput>` widget to pass the accessibility audit due to the way the `<input>` element was nested in it, and no easy way to put the appropriate `id` onto it, as well as getting an aria-label onto it
- There may be some changes pertaining to components which use the `paginated-list` component as this will create an `<li>` element, but some implementations of this component would nest an additional `<li>` ( `instutional-select-list` in this case). Hopefully this does not result in any styling changes and we …

[ENG-1525]Accessibility changes for Draft Registration Metadata content

---

app/guid-node/drafts/register/route.ts

After refactoring the route, the `register` button on the draft-registration list no longer works because the `guid-node.drafts.register` route redirects us to the wrong route. This PR fixes the problem by changing it to redirect to `registries.drafts.draft.review` route instead of the `page` route.

[ENG-1572] Fix register button on draft-registration list

---

lib/osf-components/addon/components/registries/review-metadata-renderer/label-display/template.hbs
lib/osf-components/addon/components/registries/review-metadata-renderer/styles.scss
lib/osf-components/addon/components/registries/review-metadata-renderer/template.hbs
lib/registries/addon/components/registries-license-picker/template.hbs
translations/en-us.yml

- Add the node license fields to the review page and add validation status to it
- Added flag to hide validation option for fields (needed to combine the nodelicense validations together)
- styling changes for nested properties
- node license required fields to `review-metadata-renderer`
- added anchor id's to the `registries license picker`
`NA`
- this is part of the metadata feature stuff, so if there is any weirdness associated with the license picker and required fields validation, these should be addressing them!
[ENG-1572]: https://openscience.atlassian.net/browse/ENG-1572

[ENG-1572] Add nodelicense fields to the review page

---

app/adapters/registration-provider.ts
config/environment.js
lib/registries/addon/branded/discover/route.ts
lib/registries/addon/branded/discover/template.hbs
lib/registries/addon/branded/route.ts
lib/registries/addon/branded/template.hbs
lib/registries/addon/routes.ts

- Ticket: [ENG-1614]
Add two routes `registries/:provider_id` and `registries/:provider_id/discover`
These routes are placeholders for branded components to be built in
[ENG-1614]: https://openscience.atlassian.net/browse/ENG-1614

[ENG-1614] Add placeholder routes for branded registries

---

app/packages/registration-schema/validations.ts
app/validators/node-license.ts
lib/osf-components/addon/components/license-picker/component.ts
lib/osf-components/addon/components/license-picker/template.hbs
tests/engines/registries/acceptance/draft/draft-test.ts
tests/engines/registries/acceptance/overview/overview-test.ts
translations/en-us.yml

- Ticket: [ENG-1629]
For validation message for subjects, change `field` to `field(s)`
Add validation error message from year.
[ENG-1629]: https://openscience.atlassian.net/browse/ENG-1629

[ENG-1629] Change `field` to `field(s)` and add validation for year.

---

app/guid-node/registrations/controller.ts

Use `reload: true` so that we will always fetch from API the list of active schemas instead of getting that list from the cached store, which may contain multiple versions of the same schema because of existing drafts with old version schemas.

[No ticket] Use reload:true for findAll()

---

app/guid-node/registrations/controller.ts

Uh, well, `reload: true` didn't work. Changed it to `query` and tested locally and confirm that this works.

[No ticket] Fix new registration list

---

config/environment.js

- Ticket: `n/a`
We're currently using `Boolean()` instead of `isTruthy()` for the `ember-cli-mirage` check in the config file. This should be updated to use `isTruthy`.
- Update `Boolean` to be `isTruthy`
`n/a`
This shouldn't need QA and should only affect dev environments using mirage.

[Fix] Update config to use isTruthy

---

lib/osf-components/addon/components/draft-registration-card/component.ts
lib/osf-components/addon/components/draft-registration-card/styles.scss
lib/osf-components/addon/components/draft-registration-card/template.hbs
tests/acceptance/guid-node/registrations-test.ts
tests/integration/components/draft-registration-card/component-test.ts
translations/en-us.yml

- Ticket: [ENG-613](https://openscience.atlassian.net/browse/ENG-613)
To remove the progress bar from the `DraftRegistrationCard` widget.
- Remove the progress bar
- Change 'Register' to 'Review'
- Make the title a link
- Update title to be the draft's title instead of the schema
- Move schema to its own `Form` section
Final component will look like this:
`N/A`
This should only affect the registration card on the `{node}/registrations` page. It should only have visual changes.

[ENG-613] Update component to remove progress-bar

---

app/serializers/registration.ts
lib/osf-components/addon/components/node-card/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/files/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/files/template.hbs
mirage/factories/file.ts
mirage/fixture-data/schema-blocks/open-ended-registration.ts
tests/acceptance/guid-file/file-detail-test.ts
tests/acceptance/guid-user/quickfiles-test.ts
tests/engines/registries/acceptance/overview/overview-test.ts

- Ticket: []
Transitioning from a project's registration list to a registration overview page, the file links do not show.
- Use `Normalize` instead of `NormalizeResponse` to normalize both registration list and detail.
- Add test
- Adds `fileReference` to mirage file model
Please make sure files link are shown on the overview page in both these cases:
- From a project's registration list tab to a particular registration.
- Go directly to a registration overview page.

[ENG-1535] Fix file links issue on overview page

---

app/institutions/dashboard/-components/institutional-users-list/template.hbs
app/institutions/dashboard/styles.scss

- Ticket: [ENG-1611]
- Put user guid in parentheses as requested in the requirements doc
- Update usage of `paginated-list/has-many` to no longer throw error in the console
- SSO-users shows the number of users in an institution. Percy has found that this number can wrap when it is 3-digits or more.
- Users list will now show users' guid in parentheses, instead of being separated with a `-`
- Set `usePlaceholders=false` for `PaginatedList::HasMany` invocation to prevent the console error regarding "`institution.userMetrics` related counts not found"
- Update the CSS for the panel to lower the font size
`NA`
- The requirements ask that the user's guid is shown in parentheses. I've put the guid after the users full name, but the guid will be hidden if the user's name is …

[ENG-1611] Small visual changes to Institutional Dashboard

---

app/institutions/index/template.hbs

- Ticket: [ENG-1799]
- Put the `Read more` link in a new line
- Add a `<br>` between the description and the link
`NA`
- I've put the `Learn more` link to a new line. Please verify there are not any unexpected text-wrapping at reasonable screen-sizes (particularly mobile view)
[ENG-1799]: https://openscience.atlassian.net/browse/ENG-1799

[ENG-1799] Put "Read more" link in a new line

---

app/institutions/dashboard/-components/departments-panel/component.ts
app/institutions/dashboard/-components/departments-panel/template.hbs
app/institutions/dashboard/-components/institutional-users-list/component.ts
app/institutions/dashboard/-components/institutional-users-list/template.hbs
app/institutions/dashboard/controller.ts
app/institutions/dashboard/route.ts
app/institutions/dashboard/styles.scss
app/institutions/dashboard/template.hbs
translations/en-us.yml

- Ticket: [ENG-1611]
- Update mobile view
- Load only 10 depts at a time
- New breakpoint added in CSS to account for mobile view
- Replace use of `loadAll` for departments and just fetch the first 10 depts (these should be the top 10 depts with the most users)
- Update department pie chart to only show the top 10 depts with most users and added an `Other` slice and refactored how that pie chart data is created
`NA`
- Please take a look at the Inst. Dashboard in mobile views and make sure nothing is "gross"
- The departments pie chart should have, at most, 11 slices. The top 10 with most users and "Other". Please verify that those numbers are correct when there are less than 10 depts as well as more than 10 depts
[ENG-1611]: …

[ENG-1611] Department update + mobile view for institutional dashboard

---

app/institutions/dashboard/template.hbs
app/models/institution.ts

- Ticket: [NA]
Remove the CSV export button until it is ready
If there is no banner image, use the Logo image instead
- Added new computed property in institution that will look for the banner image, otherwise use the logo image
- Update the template for institutional dashboard to use new computed property that looks for the banner image
- comment out CSV
- remove deprecated attribute `logoPath`
- Deprecated `logoPath` property was removed, but this is not used anywhere else.
The banner should no longer be broken!

Comment out CSV export and update banner image to fall back to use logo

---

lib/osf-components/addon/components/contributors/card/editable/template.hbs
lib/osf-components/addon/components/contributors/card/readonly/template.hbs

- Ticket: []
Use the user's id instead of the concatenated contributor's id for the link.

[No ticket] Fix contributor links

---

app/metrics-adapters/keen.ts
lib/collections/addon/components/discover-page/component.ts

- Ticket: [ENG-2010]
Send public pageview logs to two keen collections: `pageviews` and `pageviews-$foo`, where `$foo` is the first letter of the project guid.  After a month we can switch the analytics page to query the partitioned collection, which should be significantly faster.
* Log the public pageview events into collection buckets partitioned
by the first letter of the project guid.  After one month, we will
switch the analytics page to pull from the partitioned buckets.
Since each bucket will have approximately 1/31 (there are 31
possible letters or numbers that can appear in a guid) of the
events in the common collection, it should make the analytics page
more responsive.
None expected.
No QA needed, will be dev-tested.
[ENG-2010]: …

[hotfix][ENG-2010] send keen public pageviews into partitioned collections

---

lib/app-components/addon/components/branded-navbar/template.hbs
lib/collections/addon/components/collection-search-result/node/template.hbs
lib/collections/addon/components/discover-page/component.ts
lib/collections/addon/components/discover-page/facets/checklist/component.ts

- Ticket: [ENG-1135](https://openscience.atlassian.net/browse/ENG-1135)
A quick PR to add the provider theme id to the analytics on the collection's discover page.
Updates the analytics for:
- search bar
- `Add to collection` button on the branded navbar
- filter facets (adding and removing)
- search result link (to view project)
`N/A`
You should be able to see the provider's id at the beginning of the label now and should look something like the following:
- Search bar: `category: button, action: click, label: studyswap Discover - Search, extra: t`
- Navbar `Add to Collection` button: `category: link, action: click, label: studyswap Navbar - Add to Collection, extra: undefined`
- Add facet: `category: filter, action: add, label: studyswap Discover - Filter Type …

[ENG-1135] Update collections analytics to include provider

---

lib/osf-components/addon/components/contributors/card/readonly/template.hbs
mirage/factories/contributor.ts
tests/integration/components/contributors/component-test.ts

Update read-only contributor cards to show unregistered contributors as plain text, as opposed to a link to their profile page
- Added condition to check if a contributor is registered or not
- Added test to verify if unregistered contributor is rendered as plain text and not a link
- Should be none
- this should address the bug found for read-only contributor management

Update contributor card to handle unregistered users

---

app/guid-node/registrations/controller.ts
lib/osf-components/addon/components/osf-layout/template.hbs
lib/registries/addon/drafts/draft/-components/register/component.ts
lib/registries/addon/drafts/draft/-components/top-nav/template.hbs
lib/registries/addon/drafts/draft/template.hbs

- Ticket: []
- Fix broken layout on draft-registration detail page
- Prevent brand flickering between default brand and provider.brand on following transitions:
- project registrations/drafts to draft-registration detail
- draft-registration to registration
- Embed `provider` on project registrations (drafts request)
- Add provider to (frontend) created registration
- Move layout.top out of `backgroundClass` div

[No ticket] Additional dev for branded registries

---

tests/integration/components/password-strength-bar/component-test.ts

- Ticket: []
Fix probabilistic failures on travis for password-strength component tests.
- Move failing assertion past the settled() call.
N/A

[ENG-2095] Fix password-strength component tests

---

app/models/registration-provider.ts
lib/registries/addon/branded/discover/controller.ts
lib/registries/addon/discover/controller.ts
mirage/factories/draft-registration.ts
mirage/factories/external-provider.ts
mirage/factories/registration-provider.ts
mirage/factories/registration.ts
mirage/fixtures/registration-providers.ts
mirage/models/external-provider.ts
mirage/scenarios/default.ts
mirage/views/share-search.ts
tests/engines/registries/acceptance/branded/discover-test.ts
tests/engines/registries/acceptance/discover-page-test.ts
tests/engines/registries/integration/discover/discover-test.ts

Update the shareSourceKey property on registration providers to be shareSource to match what is implemented in the backend
Same as above
NA
This should fix the broken discover page!

[ENG-2095]Replace shareSourceKey with shareSource

---

lib/osf-components/addon/components/button/styles.scss
lib/osf-components/addon/components/editable-field/template.hbs

- Ticket: https://openscience.atlassian.net/browse/ENG-2095
To remove the hover background on fakelink buttons.
Add `background: none` to the fakelink hover css
`N/A`
This should fix the issue of background colors being shown on hover over link buttons.

[ENG-2095] Remove hover background on button link class

---

app/styles/_global.scss

Make subjects placeholder text blurred when searching
- Re-added the blur property to `[inert]` in our global css
- previously removed the inert blur as we thought it was redundant when updating styles for modal dialogs, so other parts that had the blur behavior removed should be fixed as well
- Searching for subjects in the draft registration should be blurred again!

[ENG-2095]Reapply inert blur to global style

---

lib/app-components/addon/helpers/get-model.ts
lib/app-components/app/helpers/get-model.js
lib/osf-components/addon/modifiers/with-branding.ts
lib/registries/addon/branded/new/template.hbs
lib/registries/addon/components/registries-navbar/template.hbs
lib/registries/addon/discover/template.hbs
lib/registries/addon/drafts/draft/controller.ts
lib/registries/addon/drafts/draft/draft-registration-manager.ts
lib/registries/addon/drafts/draft/route.ts
lib/registries/addon/drafts/draft/template.hbs
lib/registries/addon/overview/template.hbs
tests/engines/app-components/integration/helpers/get-model-test.ts

- Ticket: []
Link registries navbar provider logo to (branded) discover route.
- Link to `branded.discover` if provider else `registries.discover`
- Pass down provider to navbar component in `draft`, `overview` routes.
- Refactor draftRegistrationManager class to add provider property.

[ENG-2095] Link provider logo to (branded) discover route

---

lib/osf-components/addon/components/container/styles.scss

- Ticket: https://openscience.atlassian.net/browse/ENG-2095
To fix the issue of the navbar being below other items on the page.
- Remove z-index from gutters and main container class
This will effect items using the `<Container>` element, namely the gutters and the navbar.
Should affect the z-index on the navbar and the gutters.

[ENG-2095] Remove conflicting z-index

---

lib/registries/addon/branded/new/styles.scss
lib/registries/addon/branded/new/template.hbs
lib/registries/addon/drafts/draft/metadata/styles.scss

Update style for dropdowns to better render multi-line items
- change style for ember dropdown to use `padding` instead of `line-height` to render multi-line items differently
BEFORE:
AFTER:
- Dropdowns in the draft metadata page will look differently too, since the dropdown on the `/registries/<provider_id>/new` page uses the same style used in the `draft metadata` workflow
- when the selected item in a dropdown wraps to the next line, the spacing between these lines should be much smaller now

[ENG-2095] Update dropdown styles for multi-line items

---

lib/registries/addon/branded/new/controller.ts
tests/engines/registries/acceptance/branded/new-test.ts

Only show the projects that a user can create a registration for in the branded submission page
- add filter to show only projects that user has admin privileges on
NA
- On `registries/<provider_id>/new` the dropdown to select the project to register should now only show projects that the current user is an admin on

[ENG-2095]Update project loading filter

---

lib/osf-components/addon/components/contributor-list/unregistered-contributor/template.hbs

- Allow users to interact with the Claim unregistered Contributor modal dialog in Safari
- Removed `renderInPlace={{true}}` for the dialog
- The dialog will not longer be branded :(
- The dialog should be usable in Safari, but we had to compromise so it will no longer be branded

[ENG-2095] Fix claim contributor modal for Safari

---

app/models/registration-provider.ts
lib/registries/addon/branded/discover/route.ts
lib/registries/addon/branded/index/route.ts
mirage/factories/registration-provider.ts
tests/engines/registries/acceptance/branded/discover-test.ts

branded index `(/registries/<providerId>/)` is a blank page
- Redirect branded index `(/registries/<providerId>/)` to discover `(/registries/<providerId>/discover)`
- Redirect `/registries/osf/discover` to /registries/discover/
- Special case for `provider.brandedDiscoveryPage`
- Update tests

[ENG-2095] Redirect branded index to discover

---

lib/app-components/addon/components/branded-navbar/component.ts
lib/app-components/addon/components/branded-navbar/template.hbs
lib/osf-components/addon/components/osf-navbar/auth-dropdown/component.ts
lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
lib/registries/addon/components/registries-navbar/component.ts
lib/registries/addon/components/registries-navbar/template.hbs
lib/registries/addon/components/registries-wrapper/template.hbs

- Ticket: https://openscience.atlassian.net/browse/ENG-2050
To add the `campaign` queryParam to the signup button on registries and collections.
- Add `campaign` queryParam to the registries and branded osf navbar
This should only affect the queryparam passed through the navbar when clicking the signup button.
`TODO`

[ENG-2050] Add campaign queryParam for collections and registries

---

lib/registries/addon/components/registries-registration-type-facet/component.ts
lib/registries/addon/discover/controller.ts
mirage/factories/draft-registration.ts
mirage/factories/registration.ts
mirage/fixtures/registration-providers.ts
tests/engines/registries/integration/discover/discover-test.ts
tests/engines/registries/unit/services/share-search-test.ts

- Allow users to filter by registration form type on the registries discover page when `OSF Registries` is the only provider selected
- Update some of the logic that uses hardcoded `OSF` to `OSF Registries` to match what is implemented (Eventually this filter method will be available for other providers, but now is not the time)
`NA`
- The registration form filter should show up when a user filters by OSF Registries (and _only_ OSF Registries)
- When a user selects a form type to filter by, that form type should be in the URL as a query parameter as well
- When a user deselects OSF Registries as a provider filter, or adds another provider in the provider filter, the form filter should go away
[ENG-2095]: …

[ENG-2095] Registries discover page form type facet

---

lib/registries/addon/branded/discover/route.ts

- Ticket: []
Currently, when going to a discover page of a provider whose `brandedDiscoveryPage` is `false`, the app doesn't transition to `page-not-found` route correctly. This PR fixes the problem. 
Use `window.location.pathname` and remove starting slash because `transitionTo` doesn't like it.
None.

[No ticket] Fix not found transition error.

---

lib/registries/addon/discover/controller.ts
lib/registries/addon/index/controller.ts
tests/engines/registries/integration/discover/discover-test.ts

- Ticket: []
Currently, sorting by date doesn't work for registries discover page because the `date_updated` field is null in share. 
Change `date_updated` to `date`
None

[No ticket] Fix sorting

---

lib/registries/addon/branded/new/template.hbs
lib/registries/addon/discover/template.hbs
lib/registries/addon/drafts/template.hbs
lib/registries/addon/forms/template.hbs
lib/registries/addon/overview/template.hbs
lib/registries/addon/page-not-found/template.hbs

- Ticket: https://openscience.atlassian.net/browse/ENG-2158
To switch the order of the information in page tabs to have the provider first before additional info (Search, registration title, etc)
- Add `prepend=false` to the `{{title}}` helper on registries pages
This should affect and update all registries pages.
This should change the order of the information in the page tab for both branded and non-branded pages. The brand name should always come first on all registries tabs.

[ENG-2158] Update page title to have osf brand display first

---

lib/registries/addon/components/registries-search-result/component.ts
lib/registries/addon/components/registries-search-result/styles.scss
lib/registries/addon/components/registries-search-result/template.hbs

- Ticket: [ENG-2152]
- Remove dropdown on registries discover search results
- Remove dropdown icon on search result card
- Truncate registration description to one line with ellipsis
**Before (Closed):**
**Before (Expanded):**
**Before (Closed, mobile):**
**Before (Expanded, mobile):**
**After:**
**After (mobile):**
We lose the functionality to view tags and the full description of a registration
Tags should no longer be visible on the registries search results on the registries discover page, and registrations with long descriptions should be truncated in this view as well.
[ENG-2152]: https://openscience.atlassian.net/browse/ENG-2152

[ENG-2152] Remove tags toggle

---

app/styles/_components.scss

- Ticket: https://openscience.atlassian.net/browse/ENG-2169
The `Sign Up` and `Sign In` buttons on the collections navbar are different sizes. We should fix that.
- Update the styles to use the new navbar button styles so match the navbar on the rest of the site.
Before:
After:
This will change the buttons only on the navbar. It shouldn't affect any other part of the navbar or the pages it's on.
This will mainly affect the collections navbar, but the default style was updated to be the style used on the newer osf-navbar. This could potentially affect the navbars used on Collections and emberized OSF pages.

[ENG-2169] Remove old style for navbar buttons

---

lib/registries/addon/components/registries-search-result/styles.scss

- Ticket: [ENG-2155]
Reduce font size for the Registration Search Results cards to accommodate longer registration titles and make the `Withdrawn` tag smaller
- Reduce font size on the `registries-search-result` component titles
- Increase font weight to default for registries
- Increase line-height for titles that wrap into multiple lines
Before:
Before (mobile):
After:
After (mobile):
`NA`
- the font size and line-spacing have been adjusted, so hopefully it is easier to read and the `Withdrawn` tag is less chunky
[ENG-2155]: https://openscience.atlassian.net/browse/ENG-2155

[ENG-2155] Reduce font-size for Registry Discover search results

---

lib/registries/addon/components/registries-navbar/component.ts
lib/registries/addon/components/registries-navbar/styles.scss
lib/registries/addon/components/registries-navbar/template.hbs
tests/engines/registries/integration/components/registries-navbar/component-test.ts

- Ticket: https://openscience.atlassian.net/browse/ENG-2192
To add the brand name to the navbar.
- Add brand name to navbar as a link that will take the user to the same page as the logo
- Add conditional to remove brand name on mobile screens
- Add styling
This should only add a name to the navbar in the case that it's a branded provider.
This should only affect the navbar for branded providers. The name is a link that will take the user to the same page the logo does. On mobile screen sizes, the branded name should disappear.

[ENG-2192] Add registry brand name to navbar

---

app/metrics-adapters/keen.ts
lib/analytics-page/addon/components/analytics-charts/component.ts
lib/analytics-page/addon/components/analytics-charts/x-chart-wrapper/component.ts

- Ticket: [ENG-2147](https://openscience.atlassian.net/browse/ENG-2147)
Now that we've gathered a month worth's of data in the partitioned collection, switch the analytics page over to using them and stop logging to the common collection.
* Pull from collections partitioned by the first character of the project guid instead of the monolithic collection.  This will reduce scanning costs.
* Update the analytics chart specs to make the `keenQueryOptions` key a function.  Previously this had been static data, once all projects used the same collection.  It is now a function whose only argument is the node.  The function can parameterize the collection name based off the properties of the node.
* Stop logging to the monolithic collection.  Now that the previous month's data …

[hotfix][ENG-2147] pull keen analytics from partitioned collections

---

app/adapters/moderator.ts
app/adapters/provider.ts
app/models/moderator.ts
app/models/provider.ts
app/serializers/moderator.ts
mirage/scenarios/default.ts

- Ticket: https://openscience.atlassian.net/browse/ENG-2211
To add a moderator model in prep for registries moderation.
- Add `moderator` model
- Add `moderator` serializer
`N/A`
Until this is used on the front end, there shouldn't be any noticeable changes.

[ENG-2211] Add model for moderator

---

app/styles/_accessibility.scss
lib/osf-components/addon/components/button/styles.scss

- Ticket: [ENG-2151]
- Remove color change on disabled buttons
- Update global `_accessibility.scss` so hover does not change color (note: .disabled is used for `<a role='button'>`)
- Update Button component style to not change color on hover if the button is disabled.
Some of the disabled buttons in the the app may look different
- Branded buttons should not change colors if they are not disabled (ie: `/registries/<provider_id>/new`, the `start registraiton draft` button should no longer change colors if the project is not selected)
[ENG-2151]: https://openscience.atlassian.net/browse/ENG-2151

[ENG-2151] Remove color change for disabled buttons

---

app/models/contributor.ts
lib/registries/addon/components/registries-recent-list/template.hbs
mirage/factories/contributor.ts
tests/engines/registries/acceptance/index/index-test.ts

- Ticket: [ENG-2156]
Fix missing contributor names
- Contributor `fullName` is a write-only field
- Use `contributor.users.fullName`
- Update tests
N/A
[ENG-2156]: https://openscience.atlassian.net/browse/ENG-2156

[ENG-2156] Fix missing contributor names

---

app/styles/_components.scss
lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs

- Ticket: https://openscience.atlassian.net/browse/ENG-2169
Fix the slight difference in height between buttons on the collections navbar.
- Add `display: flex` on the wrapping div to ensure that both buttons end up being the same height.
`N/A`
This should fix the slight height difference between buttons. Both buttons should now be 32px in height.

Update navbar styling to have buttons as same height

---

lib/registries/addon/overview/-components/overview-topbar/component.ts
lib/registries/addon/overview/-components/overview-topbar/template.hbs
translations/en-us.yml

- Ticket: https://openscience.atlassian.net/browse/ENG-2182
To add a `Make decision` button to the `overview-topbar` component if the user is a moderator.
Note: This adds a button for registration actions, but it doesn't include the dropdown (to be done in a separate ticket).
- Add state to the `overview-topbar` component to check if the user is a moderator
- Add button to the `overview-topbar`
`N/A`
This should only add the 'Make decision' button if the user is a moderator. Otherwise the topbar should show up like normal.

[ENG-2182] Add moderator action navbar

---

lib/registries/addon/branded/moderation/submissions/controller.ts
lib/registries/addon/components/make-decision-dropdown/component.ts
lib/registries/addon/components/make-decision-dropdown/template.hbs
translations/en-us.yml

- Ticket: [ENG-2368]
Follow up on demo requests.
- Added `filterState` query param to the moderation submissions route.
- After rejecting submission, transition to the submissions route with `?filterState=rejected`
- Force withdraw comment should have label `Justification for Withdrawal`
- Comment should have placeholder `Remarks to registration admin`.
[ENG-2368]: https://openscience.atlassian.net/browse/ENG-2368

[ENG-2368] Demo followup

---

lib/osf-components/addon/components/moderators/add-modal/styles.scss

- Ticket: [NA]
- Address unintended CSS changes caught by percy
- Atone for my CSS sins
- Wrap all `:global()` CSS rules in a local-class
- there should be none _this time_
NA

Fix CSS issues caused by bad use of :global

---

lib/osf-components/addon/components/moderators/add-modal/component.ts
lib/osf-components/addon/components/moderators/add-modal/template.hbs
tests/integration/components/moderators/component-test.ts

- Ticket: https://openscience.atlassian.net/browse/ENG-2368
To add a default permission to the 'Add moderator' modal.
- Set default permission to 'moderator' in the form changesets
`N/A`
`N/A`

Add default permission to add moderator modal

---

lib/osf-components/addon/components/subscriptions/list/styles.scss
lib/osf-components/addon/components/subscriptions/list/template.hbs
lib/osf-components/addon/components/subscriptions/manager/component.ts
lib/osf-components/addon/components/subscriptions/manager/template.hbs
lib/registries/addon/branded/moderation/notifications/controller.ts
lib/registries/addon/branded/moderation/notifications/template.hbs

- Ticket: [ENG-2367]
Add notification subscription ids and loading state content placeholders
- Build subscription ids based on the provider model.id
- Add content placeholders for consistency with other moderation routes and style them.
[ENG-2367]: https://openscience.atlassian.net/browse/ENG-2367

[ENG-2367] Add notification subscription ids

---

app/models/provider.ts
app/models/registration-provider.ts
lib/registries/addon/components/registries-navbar/styles.scss
lib/registries/addon/components/registries-navbar/template.hbs
translations/en-us.yml

- Ticket: [ENG-2412]
Add "My Reviewing" button to the `registries-navbar` component. Make it show conditionally depending on whether the user has permission to review submissions.
Added enum `ReviewPermissions`. Added `permissions` field to registration-provider model. Add a computed to the same model to show whether the user can use the review app.
[ENG-2412]: https://openscience.atlassian.net/browse/ENG-2412

[ENG-2412] Add "My Reviewing" button to registries-navbar

---

lib/registries/addon/branded/moderation/route.ts
mirage/factories/registration-provider.ts
tests/engines/registries/acceptance/branded/moderation/moderators-test.ts
tests/engines/registries/acceptance/branded/moderation/submissions-test.ts

- Ticket: [ENG-2413]
Check if user has permission to access the provider's registration route
- add a condition to check if the user has `view_submissions` permission for a given provider
- the old way of doing things just checked if the user was a moderator on _any_ provider, so a moderator for provider A could still go to provider B's moderation route (although they wouldn't get to see any of the submissions or moderators as the backend would return 403Forbidden for those requests)
`NA`
- Please verify that a moderator/admin for can only access the moderation app for providers that they are admins in.
- going to https://staging2.osf.io/registries/<not_a_moderator>/moderation should take them to page not found. same behavior for all routes within the moderation route …

[ENG-2413] Check provider permissions

---

lib/registries/addon/components/make-decision-dropdown/component.ts
lib/registries/addon/components/make-decision-dropdown/template.hbs
translations/en-us.yml

- Ticket: [ENG-2414]
Fix make-decision-dropdown component comment label and placeholder
- Fix computed property by removing `@computed` decorator usage
- Make computed property return an object with label and placeholder as keys for more readability.
- Add placeholder language to translations file 
N/A
N/A. Will be tested along with the release/20.22.0
[ENG-2414]: https://openscience.atlassian.net/browse/ENG-2414

[ENG-2414] Fix make-decision-dropdown comment label, placeholder

---

app/settings/account/-components/connected-identities/template.hbs

- Ticket: []
- Update the delete button on the connected identities component
- Use the `noBackground` property on the `delete-button` component since the styling for this button looks a little strange when it has the standard `<Button @type='delete'>` styling
`NA`
`NA`

[No ticket] Update Connected Identities component

---

lib/osf-components/addon/components/delete-button/component.ts
lib/osf-components/addon/components/moderators/manager/component.ts
lib/osf-components/addon/components/moderators/manager/template.hbs
lib/osf-components/addon/components/moderators/row/template.hbs
translations/en-us.yml

- Ticket: [ENG-2404]
Fix moderator delete toast
- Wrap the remove in an action that's passed in to `<DeleteButton/>` instead of passing a task
N/A Tested in release 20.12.0
[ENG-2404]: https://openscience.atlassian.net/browse/ENG-2404

[ENG-2404] Fix moderator delete toast

---

lib/osf-components/addon/components/moderators/manager/component.ts
translations/en-us.yml

- Ticket: []
Error toast messages don't show when deleting a moderator
- Wrap try catch, toast api error message, with frontend translated string as title.
- Reload the moderator list even after a delete error, so the UI gets the removed moderator back.

Fix toast on moderator delete error

---

tests/engines/registries/acceptance/branded/moderation/notifications-test.ts
tests/integration/components/subscriptions/component-test.ts

- Ticket: [ENG-2391]
- Make better tests for notifications/subscriptions of moderation app
- add acceptance test for notifications
- update component test for subscriptions
`NA`
[ENG-2391]: https://openscience.atlassian.net/browse/ENG-2391

[ENG-2391] Revamp notifications tests

---

lib/registries/addon/components/registration-list/manager/component.ts

- Ticket: https://openscience.atlassian.net/browse/ENG-2454
To update the default sort parameter for the `registration-list` to be newest to oldest.
- Update the `date_registered` parameter to be `-date_registered`
`N/A`
This should make the sort on all states be newest first.

[ENG-2454] Update date-registered sort on registration-list

---

app/models/registration.ts
lib/osf-components/addon/components/registries/review-actions-list/component.ts
lib/registries/addon/components/make-decision-dropdown/component.ts
lib/registries/addon/components/make-decision-dropdown/template.hbs
mirage/config.ts
tests/engines/registries/acceptance/overview/moderator-mode-test.ts
tests/engines/registries/integration/components/make-decision-dropdown/component-test.ts
translations/en-us.yml

- Ticket: [ENG-2391]
Add `make-decision-dropdown` component tests
- Add tests
- Added `hasModeratorActions` to fix an edge-case where comment box and submit button show
despite no action trigger. The edge case occurs when `reviewsState` is `initial` and current user is a moderator and contributor on the registration.
For documentation purposes, I also added `withdrawn`, `rejected` even though this dropdown is currently not shown
in those `reviewsState`s
[ENG-2391]: https://openscience.atlassian.net/browse/ENG-2391

[ENG-2391] Add make-decision-dropdown component tests

---

lib/registries/addon/components/registries-license-picker/styles.scss
lib/registries/addon/components/registries-license-picker/template.hbs
translations/en-us.yml

- Ticket: https://openscience.atlassian.net/browse/ENG-2409
To add help text to the license metadata section when submitting a new registration.
- Add translation for help text with link
- Add styling
`N/A`
This should only add help text to the license picker section of the submission form.

[ENG-2409] Add license help text and link

---

lib/osf-components/addon/components/registries/registration-list/card/template.hbs
lib/osf-components/addon/components/registries/registration-list/manager/component.ts
lib/osf-components/app/components/registries/registration-list/list/component.js
tests/integration/components/registries/registration-list/card/component-test.ts

- Ticket: https://openscience.atlassian.net/browse/ENG-2391
To add tests for the `registration-list/card` component
- Move file
- Add tests

[ENG-2391] Add registration-list/card tests

---

lib/registries/addon/components/registries-header/styles.scss
lib/registries/addon/components/registries-header/template.hbs
translations/en-us.yml

- Ticket: https://openscience.atlassian.net/browse/ENG-2246
Make the search icon clickable for registries discovery without changing the layout.
1. Make the search icon a button
2. Adjust the styling for hover and to make it stay in the same spot
3. Make the search button accessible
4. Add data-test selectors
None
This is a fairly innocuous change. The search button needs to function, and the ability to press return to search should be preserved. Text should overflow in a decent manner.

[ENG-2246] Make registries search button clickable

---

lib/registries/addon/overview/styles.scss
lib/registries/addon/overview/template.hbs
translations/en-us.yml

- Ticket: [ENG-2320](https://openscience.atlassian.net/browse/ENG-2320)
Update the archiving tombstone page to give better warnings to users about what will cause problems with the archiving process, as requested by Product.
1. Add text to support email
2. Add a call to action to notice the support
Shouldn't be
Make sure these changes show up where they're supposed to and nowhere else.

[ENG-2320] Update support language for archiving registrations

---

lib/registries/addon/overview/template.hbs
tests/engines/registries/acceptance/overview/overview-test.ts

- Ticket: [ENG-2299](https://openscience.atlassian.net/browse/ENG-2299)
Ensure that the branded provider is used in the registration overview page title rather than always using OSF Registries.
1. Override the page title from the overview page
2. Add a test assertion
No
Just make sure that this works with both branded providers and OSF Registries. This will not have an effect outside of the overview page.

[ENG-2299] Use branded provider name for page title on registration overview

---

lib/osf-components/addon/components/editable-field/category-manager/component.ts
lib/osf-components/addon/components/editable-field/description-manager/component.ts
lib/osf-components/addon/components/editable-field/doi-manager/component.ts
lib/osf-components/addon/components/editable-field/institutions-manager/component.ts
lib/osf-components/addon/components/editable-field/publication-doi-manager/component.ts
lib/osf-components/addon/components/editable-field/tags-manager/component.ts
mirage/scenarios/default.ts
tests/engines/registries/acceptance/overview/overview-test.ts

- Ticket: [ENG-1694](https://openscience.atlassian.net/browse/ENG-1694)
Allow R+W users to be able to edit metadata on registrations.
1. Add a mirage scenario for current user to be write contributor to a registration
2. Update managers' components to use `userHasWritePermission` instead of `userHasAdminPermission` for:
- Description
- Category
- Registration DOI (can create one)
- Publication DOI
- ~~Subjects~~ This is not supported by the back-end
- Affiliation (add or remove their own affiliation)
- Tags
3. Update tests
No
This shoooould only affect the registration overview page.

[ENG-1694] Allow write users to edit registration metadata

---

app/models/user.ts
lib/osf-components/addon/components/contributors/card/readonly/component.ts
lib/osf-components/addon/components/contributors/card/readonly/styles.scss
lib/osf-components/addon/components/contributors/card/readonly/template.hbs
lib/osf-components/addon/components/contributors/card/styles.scss
mirage/factories/node.ts
mirage/factories/user.ts
translations/en-us.yml

- Ticket: [ENG-1899]
Add education and employment dropdown to readonly contributor cards.
Modified the readonly contributor card component to show education and employment dropdown
None.
[ENG-1899]: https://openscience.atlassian.net/browse/ENG-1899

[ENG-1899] Add education and employment dropdown

---

app/models/user-email.ts
app/settings/account/-components/connected-emails/component.ts
app/settings/account/-components/connected-emails/template.hbs
app/settings/account/-components/default-region/component.ts
app/settings/account/-components/default-region/template.hbs
app/settings/account/-components/security/component.ts
app/settings/account/-components/security/template.hbs
tests/acceptance/settings/account/security-test.ts
tests/acceptance/settings/settings-test.ts
translations/en-us.yml

- Ticket: [ENG-2496]
- Replace validated-model-form with form-controls
- Replaced validated model form in Settings::Account::-Components::ConnectedEmails
- Replaced validated model form in Settings::Account::-Components::DefaultRegion
- Replaced validated model form in Settings::Account::-Components::Security
NA
- The connected emails panel (adding a new email for the user), the default storage location panel, and security settings panel on osf.io/settings/account _should_ function the same, but a quick spot check is always appreciated! 
[ENG-1528]: https://openscience.atlassian.net/browse/ENG-1528
[ENG-2496]: https://openscience.atlassian.net/browse/ENG-2496

[ENG-2496] Replace validated models in settings.account route

---

app/models/developer-app.ts
app/settings/developer-apps/-components/app-form/component.ts
app/settings/developer-apps/-components/app-form/template.hbs
app/settings/developer-apps/create/controller.ts
app/settings/developer-apps/create/route.ts
app/settings/developer-apps/create/template.hbs
app/settings/developer-apps/edit/controller.ts
app/settings/developer-apps/edit/template.hbs

- Ticket: [ENG-2497]
- Phase out validated-model-forms as a way of validating forms and instead using form-controls and changesets for the settings.applications route
- Create a new component that is shared between the developer-apps/create and developer-apps/edit pages
- Removing validated-model-forms from these forms and replacing them with form-controls
- I think there is a small side-effect with how validation errors go away. When a user hits the `create`/`save` button and tries to submit an invalid form (e.g. they try to create/edit an app with an invalid callbackUrl), validation errors will show. When they go to edit the callbackUrl by typing anything into that text field, the validation error goes away, whereas before it would stay until the user clicks the …

[ENG-2497] Remove validated-model-forms from developer-apps pages

---

lib/osf-components/addon/components/editable-field/doi-manager/component.ts
tests/engines/registries/acceptance/overview/overview-test.ts

- Ticket: [ENG-2538](https://openscience.atlassian.net/browse/ENG-2538)
Revert back part of https://github.com/CenterForOpenScience/ember-osf-web/pull/1123 because the back-end doesn't support it. Also, in the very near future, all Registrations will be given a DOI from us, so this feature will no longer need to be.
1. Make Registration DOI admin-only
2. Update tests
No
This is a pretty straightforward change, and should only restore previous functionality.

[ENG-2538] Make registration doi controls admin-only

---

Dockerfile
README.md

- Ticket: []
Fix broken staging deploy builds
What: It turns out our ember-osf-web docker container was still configured to run on top of a node8 base (starting image)
despite us having migrate to Node 10. This was not breaking anything till we installed `ember-exam` which has
`fs-extra @9.0` as a dependency.`fs-extra @9.0` requires Node 10.
Fix: @mattclark added a [new node10 ember-base](https://github.com/CenterForOpenScience/docker-library/blob/master/ember-base-10/Dockerfile). Here, I am simply pointing to the new image. We are contemplating using
volta in our docker setup in the near future that way we obviate the need to sync the versions.
- Point to the new ember-base quay image
- Bonus: remove handbook deploy/travis config

[No ticket] Use node10 ember-base

---

app/models/draft-registration.ts
mirage/factories/draft-registration.ts

- Ticket: [ENG-2573](https://openscience.atlassian.net/browse/ENG-2573)
Add the hasProject boolean to draft-registrations. This matches up with the Platform PR https://github.com/CenterForOpenScience/osf.io/pull/9607
1. Add the attribute to the DraftRegistration model
2. Add the attribute to the mirage factory
No, all additive. I made the mirage factory default work with all of the existing draft registrations in the default scenario and tests, so going forward with no project we can override as necessary.
Nothing testable yet.

[ENG-2573] Add hasProject boolean to draft-registrations

---

app/adapters/draft-registration.ts
app/models/node.ts
lib/registries/addon/branded/new/controller.ts
lib/registries/addon/branded/new/styles.scss
lib/registries/addon/branded/new/template.hbs
lib/registries/addon/drafts/draft/draft-registration-manager.ts
lib/registries/addon/drafts/draft/template.hbs
mirage/config.ts
mirage/serializers/draft-registration.ts
tests/engines/registries/acceptance/branded/new-test.ts
translations/en-us.yml

- Ticket: https://openscience.atlassian.net/browse/ENG-2276
To update the `Add New` page to allow users the chance to start a no-project draft registration.
- Update the `Add New` page to include a radio button to select `yes` or `no` to using a registration
- Add translations
- Update mirage to allow draft-registrations to be created with a project
- Update the draft template/controller to include a conditional for the project link
This touched some styling on the `Add New` page and updated some draft-registration things in mirage.
This affects two pages. It will add a new option to the `Add New` page and it should also remove the project link on the draft page in the case that the draft-registration doesn't have a project it's related to. The `Create Draft` button …

[ENG-2276] Update add-new page to allow no project registration

---

app/models/file.ts
lib/osf-components/addon/components/delete-button/component.ts
lib/osf-components/addon/components/files/item/styles.scss
lib/osf-components/addon/components/files/item/template.hbs
lib/osf-components/addon/components/files/manager/component.ts
lib/osf-components/addon/components/files/manager/template.hbs
lib/osf-components/addon/components/files/widget/template.hbs
lib/osf-components/addon/components/registries/page-renderer/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/files/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/files/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/mapper/template.hbs
lib/registries/addon/drafts/draft/page/template.hbs
mirage/views/wb.ts
tests/engines/registries/acceptance/draft/draft-test.ts
translations/en-us.yml

- Ticket: [ENG-2278]
Add file/folder delete to the files widget
~Waiting on product for language updates.~
- Update `<DeleteButton />` to not propagate click by default.
- Add file/folder delete button to `<Files::Item />`
- Add a file/folder delete task to `<Files::Manager />`
- Update `<Files::Manager >` to use `onDeleteFile` and allow consumers of the file widget to dictate what happens
upon successful delete in this case `<Registries/SchemaBlockRenderer::Editable />`
- Add `onDeleteFile` action to `<Registries/SchemaBlockRenderer::Editable::Files />` 
- Add acceptance tests
Regression test for files widget on draft registrations.
[ENG-2278]: https://openscience.atlassian.net/browse/ENG-2278

[ENG-2278] Add file/folder delete to <Files::widget>

---

lib/registries/addon/branded/new/template.hbs

- Ticket: [ENG-2648](https://openscience.atlassian.net/browse/ENG-2648)
Make data analytics name for creating a new draft registration dependent on isBasedOnProject. I left the original response as was, and just added "no-project" to the no-project case, so all of the historical clicks of the button would match with the future clicks of the button meaning that it was based on a project.
1. Add an if to the data-analytics-name element
No
Just check the first `collect` network request in each case to make sure if it says "no-project" or not.

[ENG-2648] Make data analytics name dependent on isBasedOnProject

---

lib/registries/addon/drafts/draft/-components/register/component.ts
translations/en-us.yml

Omit `registered_from` in the registration create `POST` request for no-project registration.
- Only include `registered_from` if `draftRegistration.hasProject` is `true`
- Add toast and sentry-capture exception
- Tested as part of the no-project registration release

[ENG-2641] Don't include registered_from on no-project registration create

---

lib/osf-components/addon/components/contributors/card/readonly/styles.scss
mirage/scenarios/default.ts

- Ticket: [ENG-2641](https://openscience.atlassian.net/browse/ENG-2641)
Make:
Be more like:
1. Change `max-width` on read-only contributor card to be `width`
2. Update an existing mirage scenario to make it easy to test things like this
Nope, should be very isolated
This is a low-risk change. Will just affect the CSS on that one component.

[ENG-2641] 21.1.0/read card read only width

---

lib/registries/addon/branded/new/styles.scss
lib/registries/addon/branded/new/template.hbs

- Remove behavior on Add New page where clicking outside of the Yes/No radio buttons would change the Step 1 radio button to `Yes` (see attached video)
- A little bit of accessibility cleanup
- Removed some errant `<label>` tags, added unique IDs to input elements
https://user-images.githubusercontent.com/51409893/110848791-7a0a8f00-827c-11eb-9717-c915d8771301.mov
- NA

[ENG-2641] Fix radio button behavior on Add New page and some accessibility updates

---

lib/osf-components/addon/components/contributors/add-unregistered-modal/template.hbs

- Change wording for unregistered user permissions to match contributor list
- see above
- NA
- This is only a wording change on the modal to add unregistered contributors. The new wording should be 'Read', 'Read + Write', and 'Administrator'

[ENG-2641][Demo feedback] Change permission wording in unregistered contributor modal

---

lib/registries/addon/components/registries-navbar/component.ts
lib/registries/addon/components/registries-navbar/template.hbs
lib/registries/config/environment.d.ts
lib/registries/config/environment.js

- Ticket: [ENG-2673]
- Allow users to create a draft registration to OSF Registries by using the Add New button
- Show Add New button when looking at OSF Registries
- NA
- Add New button will be visible on `osf.io/registries/discover` route. This button will take users to `osf.io/registries/osf/new` and users should be able to submit to OSF registries from there
[ENG-2673]: https://openscience.atlassian.net/browse/ENG-2673

[ENG-2673] Show Add New for button for OSFRegistries

---

lib/osf-components/addon/components/contributors/card/editable/styles.scss
lib/osf-components/addon/components/contributors/card/styles.scss
lib/osf-components/addon/components/contributors/user-search/card/styles.scss

Set a width for the permission dropdown so that it is consistent across browsers.

[ENG-2641] Permission dropdown width fix

---

lib/osf-components/addon/components/contributors/card/editable/template.hbs
lib/osf-components/addon/components/contributors/user-search/card/template.hbs

- Remove the search box from the contributor permissions dropdown
- set the `searchEnabled` argument to the power select component invoked to be false
Before:
After:
- Users now won't be able to search the permissions in the contributor widget, but there's only 3 options, so I don't think it was helping really...
- When adding/modifying contributor permissions, the dropdown to select the permission should no longer have the search box. 

[ENG-2641] Remove contributor permissions search

---

lib/registries/addon/branded/new/template.hbs

- Add analytics to the Add New page's project-based/no-project registration radio buttons
- Add analytics called `Toggle to project based registration` or `Toggle to no project registration` based on which radio button is selected
NA
- Analytics events should be firing when users toggle between project-based and no-project registrations on the Add New page. The Network tab in the developer tools should show an event going to `https://www.google-analytics.com/j/collect` when toggling between these buttons

[ENG-2641] Add analytics to Add New page radio buttons

---

app/validators/validate-response-format.ts

- Ticket: []
Execute file validation requests sequentially instead of concurrently.
Instead of `allSettled` the promises, we await each promise sequentially with a for loop.
Note: Assuming that prod has the same throttle of file ops as specified in `local-dist.py`, which is 3/sec for `files-burst`, executing requests sequentially should not break this throttle limit, as each request to staging2 API for file validation takes about 500 ms. However we need to deploy this to staging2 just to make sure. Testing this locally doesn't really help because local test servers are rrrrrreeeeaaaalllllly slow and the problem couldn't be replicated.
File validations on drafts are slower, but better than not validated at all.

[LukewarmFix] Bypass file validation throttle

---

app/validators/validate-response-format.ts

- Don't let the file validation status hang in limbo if one of the files fail validation
- wrap the file-loading logic in a try-catch so file validation doesn't break if one of them is an error

[ENG-2641] File validation error handling

---

app/guid-node/registrations/controller.ts
lib/registries/addon/components/registries-registration-type-facet/component.ts
lib/registries/addon/discover/controller.ts

- Ticket: [ENG-2636](https://openscience.atlassian.net/browse/ENG-2636)
Use the page[size] query parameter to get all of the registration schemas for faceting on the registries discover page.
1. Change instances of `findAll` where we want to use `page[size]` to `query`
2. Add `page[size]` query parameter to the registration-type-facet for the registries discover page.
3. Add `page[size]` query parameter to the guid-nodes/registration page
None anticipated
- There should be more than 10 registration types on the registration discovery page 'registration types' facet when limiting the provider to OSF Registries (if there are more than 10 registration types in that environment)
- There should be more than 10 registration providers in the 'provider' facet on the registries …

[ENG-2636] Get all registration schemas on discover page

---

app/models/registration-provider.ts
lib/registries/addon/components/registries-header/styles.scss
lib/registries/addon/components/registries-header/template.hbs
lib/registries/addon/discover/styles.scss
lib/registries/addon/discover/template.hbs
mirage/factories/registration-provider.ts
tests/engines/registries/acceptance/branded/discover-test.ts
translations/en-us.yml

- Ticket: [ENG-2604](https://openscience.atlassian.net/browse/ENG-2604)
- Ticket: [ENG-2273](https://openscience.atlassian.net/browse/ENG-2273)
Show the description from the registration provider on the discover page, including html. Also, while we're here, remove the 'Powered by SHARE' logo.
1. Make an HTML Safe computed on the provider model for the description
2. Change the mirage factory for registration provider to provide better data for this case
3. [Remove the 'Powered by SHARE' logo](https://openscience.atlassian.net/browse/ENG-2273)
4. Show the registry provider description on the discover page
Should be pretty localized.
The registry discover pages should be tested. It will need the provider's description to be set in the admin app. HTML should work fine in this widget.

[ENG-2604][ENG-2273] Show registration provider description

---

app/styles/_variables.scss
lib/registries/addon/components/registries-header/styles.scss

- Ticket: [ENG-2751](https://openscience.atlassian.net/browse/ENG-2751)
Give product the ability to do limited changes of the color of the Provider Description text and links. One would use it by wrapping the description in a span with the appropriate classes. For example, `<span class="ColorBlack LinkColorPurple">This is the provider description <a href="https://osf.io/">with a link</a>.</span>`. I added the following CSS classes for use by Product:
For text: 
- ColorBlack
- ColorPureBlack
- ColorBlue
- ColorPureBlue
- ColorGrey
- ColorRed
- ColorGreen
- ColorYellow
- ColorTurquoise
- ColorPurple
For links:
- LinkColorBlack
- LinkColorBlue
- LinkColorPureBlue
- LinkColorGrey
- LinkColorRed
- LinkColorGreen
- LinkColorYellow
- LinkColorTurquoise
- LinkColorPurple …

[ENG-2751] Allow provider descriptions to have color options

---

lib/osf-components/addon/components/gutters/styles.scss

- Ticket: [No ticket]
Fix tablet view of the metadata panel for registration overview page
- remove unneeded style
Before:
After:
- There should be none... I think this style was added in by mistake to begin with
- for tablets (or for mobile if the screen is landscape), there should no longer be the weird background-less view for the metadata panel

[No ticket]Fix metadata panel for registry overview page for tablet view

---

lib/app-components/addon/components/project-contributors/search/template.hbs
lib/collections/addon/components/collections-submission/template.hbs
lib/collections/addon/components/discover-page/template.hbs
lib/osf-components/addon/components/file-browser/template.hbs
lib/osf-components/addon/components/files/list/template.hbs
lib/osf-components/addon/components/files/menu/template.hbs
lib/osf-components/addon/components/node-doi-create/template.hbs
lib/osf-components/addon/components/registries/registration-list/card/template.hbs
lib/registries/addon/components/registries-states/template.hbs

Fix all the cases of the size parameter being mis-used in the new Font Awesome icons.
All places in the code where `size='[0-9]'` or `size={{[0-9]}}`
1. Project contributors search spinner (do we still even use a spinner?)
2. Collections submission spinner (apparently)
3. Collections discover page spinner (seriously?)
4. Quickfiles no-file state upload icon
5. Files list upload icon
6. Files menu plus icon
7. Node-doi create info icon (I think this isn't used anymore, or won't be soon)
8. Registration card state icons
This should be limited to just the places above.

Fix FaIcon size parameters

---

lib/registries/addon/components/registries-navbar/styles.scss
lib/registries/addon/components/registries-navbar/template.hbs
tests/engines/registries/integration/components/registries-navbar/component-test.ts

- Ticket: [No ticket]
- Hide `OSFRegistry` text in the registries navbar to prevent undesired text-wrapping
- Add a new class to the text in the navbar to hide the title for tablets
Old:
New:
- None
- Please verify that logged out users don't get the text-wrapping shown above for tablet view

[No ticket] Hide OSFRegistry in navbar for tablet

---

lib/osf-components/addon/components/registries/my-registrations-list/registrations/component.ts
lib/osf-components/addon/components/registries/my-registrations-list/registrations/template.hbs
lib/osf-components/app/components/registries/my-registrations-list/registrations/component.js
mirage/views/utils/-private.ts
mirage/views/utils/index.ts
tests/integration/components/registries/my-registrations-list/component-test.ts

- Ticket: [No ticket]
- Filter out component registrations on my-registrations page (e.g. Project A has Component B. I create a registration for Project A and select Component B to be registered as well in the `Almost Done...` modal)
- Note: this will not filter out registrations of components by themselves (e.g. I create a registration for Component B only)
- Add filter to the paginated list component invocation
- Updated how mirage handles some filtering for `null` 
- Tests
- If there are other places where we are filtering for null, these may behave differently (only in mirage)?
- For MyRegistrations page, only registrations of top-level projects should show up (ie: when submitting the draft and a component gets registered with it, that component that was registered …

[No ticket] Only show top-level registrations on my-registrations

---

lib/osf-components/addon/components/draft-registration-card/styles.scss
lib/osf-components/addon/components/draft-registration-card/template.hbs

- Ticket: [No ticket]
- Remove visual bug caused by excess whitespace when hovering the `Review` button of the Draft Registration Card
- Rearranged `Button` and `OsfLink` component for Review button to prevent the visual bug when hovering Review button
- I tried using some whitespace trimming techniques (a lot of them listed in [this ember discussion thread](https://discuss.emberjs.com/t/removing-whitespace-with-angle-bracket-syntax/17094/7)) but to no avail, so I decided to just change how the button is invoked in the template
Old:
New:
- No side effects
- Hovering on the `Review` Button on a draft card should no longer have that weird line poking out behind it
- This bug only showed up on the `Review` button when the `Edit` button is visible

[No ticket]Rearrange draft-registration-card to prevent visual bug on hover

---

lib/osf-components/addon/components/draft-registration-card/styles.scss

- Ticket: []
- Correct a style that was supposed to be fixed by earlier PR
- Hovering on the `Review` button will create a small visual bug on Draft Registration cards
- Specify that the `text-underline: none` should apply to `<a>` to override style given by OsfLink
- Added a linting exception to this rule as we are trying to override default OsfLink behavior here
- None

[No ticket] Update styling for draft card button hover

---

lib/osf-components/addon/components/draft-registration-card/styles.scss
lib/osf-components/addon/components/draft-registration-card/template.hbs

- Ticket: []
- Fix slightly misaligned buttons on Draft Registration Card in Safari
- Realign button using `vertical-align: bottom`
Before:
After:
- This was only happening for Safari

[No ticket] Align draft buttons for Safari

---

lib/registries/addon/components/registries-navbar/component.ts

- Ticket: []
- Remove provider names for tablet on branded providers
- add condition to check if tablet view for showing provider names
Before:
After:
- none

[No ticket] Remove registration names for tablet

---

app/guid-node/registrations/controller.ts
mirage/factories/registration-provider.ts
mirage/fixtures/registration-schemas.ts
mirage/scenarios/registrations.ts
tests/acceptance/guid-node/registrations-test.ts
tests/acceptance/resolve-guid-test.ts

- Ticket: [ENG-2713](https://openscience.atlassian.net/browse/ENG-2713)
On the guid-node/registrations page, stop using the top-level schemas endpoint and instead use the default provider's schema relationship.
1. Grab the default provider and that provider's schemas for the guid-node/registrations page's list of schemas
2. Fix tests
3. Add a 'withAllSchemas' trait to the registrationProvider factory
4. Add a couple more test schemas to the total number of schemas so we have more than 10
5. Make a couple of small mirage scenario changes to support the change and make testing easier
Shouldn't be.
This is the older workflow's (i.e. with project, through the project page) create registration list of schemas. It should work the same as it did before, I'm just grabbing the …

[ENG-2713] Use provider's schemas relationship to get registration schemas

---

package.json
yarn.lock

- Ticket: [ENG-2039]
- remove uses of deprecated features in Ember, specifically the `Copyable` mixin and `copy` method found in ember object's internals (more info here: https://deprecations.emberjs.com/v3.x/#toc_ember-runtime-deprecate-copy-copyable)
- Updated our fork of ember-metrics as this was pinned to an old version that was using these deprecated features
- Unfortunately we will still need to use this fork of ember-metrics as we are anonymizing captured metrics, and [ember-metrics does not currently support explicitly setting fields](https://github.com/adopted-ember-addons/ember-metrics/pull/202).
- Big thank you to @aaxelb for all the help and updating the fork. Further information on anonymized GA events here: …

[ENG-2039] Remove uses of deprecated Copyable mixin and copy method

---

app/models/review-action.ts
tests/integration/components/registries/review-actions-list/review-action/component-test.ts

- Ticket: [ENG-2791] 
- Make sure special characters `< > &` display properly for review actions, instead of `&lt; &gt; &amp;`
- Updated review action model to account for these special characters
- Update test
Before:
After:
- None
- If a moderator leaves a comment containing these special characters, the review history shown in the Moderation app should show the appropriate characters. 
[ENG-2791]: https://openscience.atlassian.net/browse/ENG-2791

[ENG-2791] Fix string for moderator comments

---

lib/app-components/addon/helpers/fix-string.ts
lib/app-components/app/helpers/fix-string.js
lib/osf-components/addon/components/provider-metadata-display/template.hbs
tests/engines/app-components/integration/helpers/fix-string-test.ts
tests/engines/registries/acceptance/overview/overview-test.ts

- Ticket: [ENG-2771](https://openscience.atlassian.net/browse/ENG-2771)
Ensure that special characters like `<`, `>`, and `&` do not render as their encoded version in the display of the Registries custom metadata field. Note that this does not affect the edit field, because the text in the <Input> helper couldn't be overridden without breaking it.
* Add helper to fix strings in the templates
* Apply helper to registries custom metadata display
* Adjust tests
This is very isolated, so there should be no side effects.
This affects the registries overview page, when there is custom metadata that has `&amp;`, `&lt;`, or `&gt;` coming from the OSF, which happens if you try to save `&`, `<`, or `>` to the field.

[ENG-2771] Unencode special characters in Registries Custom Metadata

---

lib/registries/addon/my-registrations/styles.scss
lib/registries/addon/my-registrations/template.hbs
translations/en-us.yml

- Ticket: [ENG-2789]
- Let users know that registrations and drafts are sorted by date modified
- Add a div with explanation to my-registrations page template
- Should be none.
- There should be a little bit of text on the my registrations page that says how drafts and registrations are submitted. The text is the same for both tabs
[ENG-2789]: https://openscience.atlassian.net/browse/ENG-2789

[ENG-2789] Add description to how drafts and registrations are sorted

---

app/models/registration.ts
lib/registries/addon/components/make-decision-dropdown/component.ts
lib/registries/addon/components/registries-states/component.ts
lib/registries/addon/overview/-components/overview-topbar/template.hbs
mirage/serializers/application.ts
mirage/serializers/registration.ts
mirage/views/registration.ts
tests/engines/registries/acceptance/overview/topbar-test.ts

- Ticket: [ENG-2881]
- Fix a bug where anonymous view-only links (AVOLs) will not load properly
- Hide the registration state when registrations are viewed anonymously
- Added test
- Note: Registration state is not visible on the grey bar below the registration title
- none
- This change should only happen when looking at a registration through an anonymous VOL. Any other view should be unchanged
[ENG-2881]: https://openscience.atlassian.net/browse/ENG-2881

[HOTFIX][ENG-2881] Hide registration state for anonymous VOLs

---

lib/registries/addon/my-registrations/template.hbs

- Ticket: []
Fix my registration page infinite reload.
It seems that my registration page is reloading infinitely because the app cannot find `{{title}}`. Change to `{{page-title}}`.
None

[ENG-2898] Fix my registrations page infinite reload.

---

lib/osf-components/addon/components/files/menu/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/files/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/files/template.hbs
lib/osf-components/addon/components/validation-errors/component.ts
lib/osf-components/addon/components/validation-errors/template.hbs

- Fix broken upload file button
- Fix indefinite validation status loading indicator
- For upload files button
**Fix**: pass `rootEventType='mousedown'` argument to `<BasicDropdown::Content>` component.
**Issue**: with [ember-basic-dropdown v2](https://github.com/cibernox/ember-basic-dropdown/blob/master/CHANGELOG.md#200-alphax), the `rootEventType` default changed to `click` previously `mousedown`.
The `rootEventType` parameter determines what type of event ('click' | 'mousedown') outside the dropdown should result
in closing an open dropdown. With v2, if a user clicks outside the dropdown, the dropdown should close. It turns out, this interferes with how the `Dropzone` upload button works because the `upload` button is rendered in the dropdown. …

[ENG-2898] Fix files widget uploads and validation

---

lib/registries/addon/drafts/draft/styles.scss
lib/registries/addon/drafts/draft/template.hbs

Modify the top position of the sticky edit warning div so that it doesn't get clipped on the Review page.

[ENG-2898] Fix warning sticky top

---

lib/osf-components/addon/components/registries/schema-block-renderer/helper-text-icon/template.hbs

- Fix broken help text icons in the draft-registration workflow
- Moved `BsPopover` outside of `FaIcon` invocation
- Attached `@triggerElement` to the help icon so popover will trigger on hover and focus of help icon
- NA
- The `?` icons in the Draft Registration submission process will now properly show help text when you hover or focus into it (whether by tabbing into it, or clicking on it). OSF Preregistration has a lot of these help-texts (especially Sampling Plan page), so that is a good schema to check. Other schemas may not have these help-texts

[ENG-2898] Draft registration Help icon hover

---

lib/registries/addon/components/registries-search-result/styles.scss

Fix registries discover page contributor list appearance on firefox.
Remove excess space in content of the `::after` pseudo element.

[ENG-2898] Fix firefox contributor list

---

lib/registries/addon/drafts/draft/-components/right-nav/styles.scss
lib/registries/addon/drafts/draft/draft-registration-manager.ts
lib/registries/addon/drafts/draft/styles.scss

When autosave fails on the draft-registration metadata, the notice in the right sidebar is not showing up.
- Update `DraftRegistrationManager.lastSaveFailed` computed property to update on status of `onMetadataInput` task.
- Make notice red (actually have rules in the notice existing local class)
N/A
- On a draft-registration metadata page, currently, one way to cause an auto-save error is by deleting the autofilled `year`
on a license with required fields (for example `No License`, `MIT License`); you should see an error toast then in the right sidebar; a notice similar to the one below should show.

[ENG-2898] Fix notice for metadata failed autosave

---

lib/registries/addon/components/registries-license-picker/template.hbs

Fix missing save/cancel buttons on the registration's license/node-license editable field.
Currently, only licenses with `requiredFields` can be saved.
- Make it so control buttons show regardless of whether or not the selected license has required fields. 
You should be able to edit and save a registration's license (with or w/o required fields) or cancel the edit.
Try 'MIT License' or 'No License' (have requiredFields) to make sure you still see the editable field control buttons.
Try a difference license and make sure the control buttons are visible and usable.

[ENG-2898] Fix missing save/cancel buttons

---

lib/osf-components/addon/components/registries/my-registrations-list/drafts/template.hbs
lib/osf-components/addon/components/registries/my-registrations-list/registrations/template.hbs
lib/registries/addon/my-registrations/styles.scss
lib/registries/addon/my-registrations/template.hbs
tests/engines/registries/acceptance/my-registrations-page-test.ts
tests/integration/components/registries/my-registrations-list/component-test.ts

- Ticket: [ENG-2919]
- Add data-test selectors to the my-registrations page to help with Selenium testing
- Add integration test to the my-registrations page while we're here
- Changed invocation of BsTab to allow us to set data-test selectors on the BsNav.items
- Add data-test selectors to the tabs, the buttons within the tabs, and to the tab panes
- Update some CSS to match the existing style
- Update analytics scope to a more appropriate name
- Update data-test selectors on the `Create New Registration` button to be unique for easier selecting in Selenium testing
- Added integration test to My-Registrations page
- None
- The My-Registrations page should now be contained under `data-analytics-scope='My Registrations page'`
- Clicking …

[ENG-2919] Add data-test selectors to my-registrations page

---

app/packages/registration-schema/validations.ts
lib/osf-components/addon/components/validated-input/base-component.ts
lib/registries/addon/drafts/draft/-components/managers/license-picker-manager/component.ts
lib/registries/addon/drafts/draft/draft-registration-manager.ts
mirage/factories/registration-provider.ts
tests/acceptance/settings/profile/names-test.ts
tests/engines/registries/acceptance/draft/draft-test.ts
tests/engines/registries/acceptance/overview/overview-test.ts

- Ticket: [ENG-2940]
- update the way node licenses are validated to prevent validation errors from occurring when they should not
- Removed validating year for node license as this was causing odd behavior in the validation (ie: no errors would appear when node license did not have year and/or copyright holder)
- Used the `@dependentKeyCompat` decorator to circumvent troublesome tracking behavior for changeset's error object
- Created a new task that will update the metadata changeset without having to wait for the debounce to circumvent potential state where nodeLicense getting fetched from backing draftRegistration could cause issues
- Decreased debounce time from 5 to 3 seconds
- Reinstated some tests
- We will no longer validate if the year format is valid. This …

[ENG-2940][Hotfix] Update node license validations

---

app/transforms/node-license.ts

- Ticket: []
- the node license would be serialized when updating any field on the metadata page. This PR will make it so it is only sent when the node-license fields have been changed
- Update a condition to check if the node license value is an empty object (previous condition was checking truthiness on an empty object)
- update the return object to be undefined when the node license is an empty
- None that we know of...
- This is to help alleviate some of the node license issues that have been occurring on the draft registration's metadata page
- The most important thing to test is that all combinations of modifying the node license work properly, especially clearing out fields.

Return undefined for empty node license

---

lib/osf-components/addon/components/osf-layout/registries-side-nav/x-link/styles.scss

- Ticket: [ENG-2983](https://openscience.atlassian.net/browse/ENG-2983)
Stop violating WCAG 2 AA contrast rules on the registries sidebar
Before:
After:
1. Change hover color to darker color
This should be isolated to the sidenav in registries.
This is just a css change, and an isolated one at that, so shouldn't require much QA.

[ENG-2983] Registries sidebar link hover background

---

app/services/current-user.ts
lib/app-components/addon/components/branded-navbar/template.hbs
lib/osf-components/addon/components/osf-navbar/auth-dropdown/component.ts
lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
lib/registries/addon/components/registries-navbar/template.hbs
tests/engines/registries/integration/components/registries-navbar/component-test.ts

- Ticket: [ENG-2943]
- Make users actually log out when using the logout button
- Separate invalidating session and redirect logic from the `CurrentUser.logout` function
- none
- Users should now actually be logged out when clicking the logout button. This effect should have been happening on any emberized page when a user logs out. Unsure why it was happening primarily when logging out of the Registries app though 🤔 
[ENG-2943]: https://openscience.atlassian.net/browse/ENG-2943

[ENG-2943] Separate session invalidate and redirect from logout

---

lib/osf-components/addon/components/registries/overview-form-renderer/component.ts
lib/osf-components/addon/components/registries/overview-form-renderer/template.hbs
lib/registries/addon/overview/controller.ts
lib/registries/addon/overview/index/template.hbs

- Ticket: [NA]
- update overview-form-renderer to handle responses off of a registration or off of a revision
- add logic to overview-form-renderer to get responses from different objects
- add query params to registration overview route
- NA
- if the `revisionId` query param doesn't point a valid revision, it will just use the latest responses without giving any indication that loading the revision failed.

Update overview-form-renderer to handle registration or revision

---

lib/osf-components/addon/components/registries/overview-form-renderer/component.ts
lib/osf-components/addon/components/registries/overview-form-renderer/template.hbs
lib/osf-components/addon/components/registries/version-metadata/styles.scss
lib/osf-components/addon/components/registries/version-metadata/template.hbs
lib/osf-components/app/components/registries/version-metadata/template.js
tests/engines/registries/acceptance/overview/revision-test.ts
tests/integration/components/registries/version-metadata/component-test.ts
translations/en-us.yml

- Ticket: [ENG-3034]
- Add a component to show that a user is viewing a revision to a registration
- Added said component
- Added tests
Overview page when there is a `revisionId` query param:
- NA
- This component should only show up when viewing a specific revision
[ENG-3034]: https://openscience.atlassian.net/browse/ENG-3034

[ENG-3034] Add version-metadata component and tests

---

.github/PULL_REQUEST_TEMPLATE.md

- Ticket: None
- Add a `Screenshot` section to the PR template cause I keep forgetting to do that
- Update PR template
- None
- Just updating the template for these PRs

[No ticket] Add screenshot section to PR template

---

translations/en-us.yml

-   Ticket: [ENG-2982]
We had a translation string that should have been 'citation' but was 'citiation'. This corrects that typo.
1. Fix translation string
[ENG-2982]: https://openscience.atlassian.net/browse/ENG-2982

[ENG-2982] Correct typo in citation

---

lib/collections/addon/components/discover-page/styles.scss

-   Ticket: [ENG-2936](https://openscience.atlassian.net/browse/ENG-2936)
Enable colors on the collection provider description.
1. Add the color classes into the provider description local-class.
This is all very isolated.
Same testing notes as for https://github.com/CenterForOpenScience/ember-osf-web/pull/1181 though wrapping in a span acted weird for me, so you might need to use a p tag instead of a span.

[ENG-2936]Add colors to collection provider description

---

lib/osf-components/addon/components/banners/view-only-link/component.ts

-   Ticket: [ENG-1578](https://openscience.atlassian.net/browse/ENG-1578)
The existing functionality of 1578 is only half-fixed. It's removing the VOL from the URL, but leaving it on the currentUser service, so the VOL banner still shows on the dashboard, and transitioning to any other route will put the VOL back on the url. This fixes it so that the VOL is cleared from the currentUser as well.
1. Clear the VOL from the currentUser service.
Nope.
This should just be the same test plan you used before for 1578.

[ENG-1578] Remove the VOL from the currentUser when stopping view only
