CenterForOpenScience/ember-osf-web

- app/models/node.ts
- app/models/registration.ts
- lib/registries/addon/drafts/draft/-components/register/template.hbs
- lib/registries/addon/drafts/draft/review/template.hbs
- lib/registries/addon/drafts/draft/styles.scss
- lib/registries/addon/edit-revision/-components/right-nav/template.hbs
- lib/registries/addon/edit-revision/-components/submit-and-decide/component.ts
- lib/registries/addon/edit-revision/-components/submit-and-decide/styles.scss
- lib/registries/addon/edit-revision/-components/submit-and-decide/template.hbs
- lib/registries/addon/edit-revision/-components/top-nav/styles.scss
- lib/registries/addon/edit-revision/-components/top-nav/template.hbs
- lib/registries/addon/edit-revision/nav-manager.ts
- lib/registries/addon/edit-revision/review/template.hbs
- lib/registries/addon/edit-revision/revision-manager.ts
- lib/registries/addon/edit-revision/route.ts
- tests/engines/registries/acceptance/draft/draft-test.ts
- tests/engines/registries/acceptance/edit-revision/revision-test.ts
- tests/engines/registries/acceptance/overview/revision-test.ts
- tests/helpers/index.ts
- translations/en-us.yml
-   Ticket: [ENG-3031]
- Update `edit-revision` to handle user's permissions appropriately
- Add logic to allow admins to submit update, continue edits
- Add logic to allow write users to edit responses, but not submit update
- Add logic to keep read-only users to the review page
- Add logic to disallow edits when the update is submitted and is pending admin approval or moderator approval
- Add logic to reroute users to the overview page if the update is already accepted by moderators
- Tests
[ENG-3031]: https://openscience.atlassian.net/browse/ENG-3031
> [ENG-3031] Revisions permissions

- lib/registries/addon/branded/moderation/-components/upload-csv/template.hbs
- lib/registries/addon/branded/moderation/settings/controller.ts
- lib/registries/addon/branded/moderation/settings/template.hbs
- tests/engines/registries/acceptance/branded/moderation/settings-test.ts
> Add acceptance tests

- lib/osf-components/addon/components/registries/update-dropdown/component.ts
- lib/osf-components/addon/components/registries/update-dropdown/template.hbs
- lib/osf-components/addon/components/registries/update-dropdown/update-label/component.ts
- lib/registries/addon/components/make-decision-dropdown/styles.scss
- lib/registries/addon/components/registries-states/component.ts
- lib/registries/addon/edit-revision/template.hbs
- mirage/views/review-action.ts
- tests/engines/registries/acceptance/edit-revision/revision-test.ts
- tests/engines/registries/acceptance/overview/moderator-mode-test.ts
- tests/engines/registries/acceptance/overview/topbar-test.ts
- translations/en-us.yml
-   Ticket: []
- Add a link back to the registration for edit-revision routes
- Show appropriate versions in moderator mode
- Update wording of the registration state shown on the overview page
- Wording changes for registries state
- Add link back to registration in edit-revision route
- Update conditionals for showing revisions and buttons to continue edit in update-dropdown component
> Minor updates for versioning

- lib/registries/addon/components/registries-registration-type-facet/component.ts
-   Ticket: n/a
When doing a search from the registries landing page, we would get an error on the discover page that we couldn't load the registration types. This happened because provider was becoming undefined after the await L45 in the diff for this PR was executed.
1. Wait for attrs to load before running task (h/t @aaxelb)
This should be pretty isolated
Original error was when performing a search from the registries landing page, the error above would show on the discover page. This should no longer happen.
> [No ticket] Cache providerIsDefault to avoid problem where this.provider is undefined

- app/meetings/detail/-components/meeting-submissions-list/template.hbs
-   Ticket: [https://openscience.atlassian.net/browse/ENG-3214]
Add an aria label to the search box on the meetings detail page. Apparently last time I got the meeting list page, but not the detail page's search box.
1. Add aria label
No
Just needs a11y testing.
> [ENG-3214] Add aria label to search box on meetings detail page

- lib/collections/addon/components/collection-search-result/node/template.hbs
-   Ticket: [ENG-3235](https://openscience.atlassian.net/browse/ENG-3235)
The description text on the collections discover page was not passing accessibility standards of contrast. This fixes that.
1. Un-mute the text
None
Just needs to run through accessibility testing.
> [ENG-3235] Un-mute the collections discover description text for accessibility

- lib/osf-components/addon/components/draft-registration-card/styles.scss
- lib/osf-components/addon/components/draft-registration-card/template.hbs
- lib/osf-components/addon/components/node-card/styles.scss
- lib/osf-components/addon/components/node-card/template.hbs
-   Ticket: [ENG-3243]
- Simplify the HTML that is rendered for draft-registration card and node-cards to prevent weird artifacts when hovering, and also better tab-navigation UX
- Un-nested some html that was causing issues when hovering these buttons/links, as well as causing tab-focus on these buttons/links to be caught twice
- style these links to look like `<Button>`s
Node Cards:
- This should no longer have a little line poking out of the right-side of the button when hovering the View button
- Before
- ![image](https://user-images.githubusercontent.com/51409893/142290578-cfab385d-1913-4832-b8f3-255a1677bb34.png)
- After
- ![image](https://user-images.githubusercontent.com/51409893/142289942-fce4606e-5b5d-45d8-be2f-95f93cfd2491.png)
Draft Registration Cards:
- …
> [ENG-3243] Refactor node and draft reg cards for better CSS

- app/models/registration.ts
- app/packages/registration-schema/validations.ts
- lib/registries/addon/drafts/draft/-components/right-nav/styles.scss
- lib/registries/addon/drafts/draft/-components/right-nav/template.hbs
- lib/registries/addon/drafts/draft/draft-registration-manager.ts
- lib/registries/addon/edit-revision/-components/right-nav/styles.scss
- lib/registries/addon/edit-revision/-components/right-nav/template.hbs
- lib/registries/addon/edit-revision/controller.ts
- lib/registries/addon/edit-revision/justification/styles.scss
- lib/registries/addon/edit-revision/justification/template.hbs
- lib/registries/addon/edit-revision/revision-manager.ts
- lib/registries/addon/edit-revision/route.ts
- lib/registries/addon/edit-revision/template.hbs
- mirage/config.ts
- tests/engines/registries/acceptance/draft/draft-test.ts
- tests/engines/registries/acceptance/edit-revision/revision-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3243]
- Move the Delete Revision button in the edit revision workflow
- Remove Updated responses list from the Justification page of the edit-revision workflow
- Add Delete Draft button to the draft registration workflow
- Draft Registration workflow:
- ![image](https://user-images.githubusercontent.com/51409893/142509754-0a096e3d-7e98-4079-be45-56d0ac49af09.png)
- Revision workflow:
- ![image](https://user-images.githubusercontent.com/51409893/142509828-8f2287d8-97c8-4e8b-984b-142b44b04f63.png)
- None
- We will no longer validate whether or not responses have been updated on the FE. When submitting an update, the backend should validate that, and if there are no updated responses, the revision shouldn't be able to be submitted
[ENG-3243]: …
> [ENG-3243] Delete button for Revisions and Draft Reg

- translations/en-us.yml
-   Ticket: [None]
- prevent text  overlap on collections discover page for desktop (993px-1200px)
- Remove "Collection" at the end of the title on navbar
- I didn't refactor the translation key usage as to leave it refactorable in case future changes are requested. Also it's a little bit more work for this hotfix...
- before:
- ![image](https://user-images.githubusercontent.com/51409893/142915466-ffe9b69a-7382-43d1-8b01-f8723870ebc8.png)
- After:
- ![image](https://user-images.githubusercontent.com/51409893/142920645-7baf7e4c-c293-4ad8-8852-9b87ea80bd1e.png)
- forbidden and page not found error pages will no longer contain the trailing "Collection" as well
This should only effect window sizes between 993px and 1200px.
There is still some overlap that happens for …
> [No ticket][Hotfix] Update collection header width for desktop

- app/styles/_variables.scss
- lib/osf-components/addon/components/delete-button/template.hbs
- lib/osf-components/addon/components/node-card/template.hbs
- lib/osf-components/addon/components/registries/update-dropdown/component.ts
- lib/osf-components/addon/components/registries/update-dropdown/list-item/template.hbs
- lib/osf-components/addon/components/registries/update-dropdown/template.hbs
- tests/integration/components/delete-button/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3243] [ENG-3417]
- Address various bugs found in Revisions workflow
- Darken color contrast for create buttons (3.41 -> 5.33 : 1, passes AA)
- Small wording changes
- Auto-close the dropdown when selecting a revision on the overview page
- Add data-test selectors to delete button modal for automated testing
- All create buttons will have better color contrast!
[ENG-3243]: https://openscience.atlassian.net/browse/ENG-3243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-3417]: https://openscience.atlassian.net/browse/ENG-3417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3243][ENG-3417] Revisions bugfixes

- app/styles/_variables.scss
- lib/osf-components/addon/components/button/styles.scss
- lib/registries/addon/edit-revision/-components/submit-and-decide/component.ts
- tests/engines/registries/acceptance/edit-revision/revision-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3243]
- Redo accessiblity fix for color contrast that was darkening <BsButtons> unexpectedly
- wording change
- Undo change in _variables.scss that was changing `<BsButton @type='success'>`
- wording change for revisions being submitted for admin review
[ENG-3243]: https://openscience.atlassian.net/browse/ENG-3243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Additional tweaks for Revision workflow

- lib/osf-components/addon/components/node-card/component.ts
- lib/osf-components/addon/components/registries/overview-form-renderer/component.ts
- lib/osf-components/addon/components/registries/overview-form-renderer/template.hbs
- lib/osf-components/addon/components/registries/registration-list/manager/component.ts
- lib/registries/addon/overview/-components/diff-manager/component.ts
- mirage/factories/registration.ts
- mirage/serializers/registration.ts
- mirage/views/registration.ts
- tests/integration/components/node-card/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3423]
- Clean up some weirdness around registrations with one approved schemaResponse (the original) and another in-progress
- Hide `Update` button on node-cards on my-registrations page for non-admin contributors
- Hide first time submissions from "pending updates" tab of Registries Moderation app
- Update the diffManager to only get the responses from the latest approved revision when no revisionId is specified
- Update the condition to show the version metadata box, so the box no longer shows up when there is only one approved response and one response in progress (2 or more responses need to be public before the version metadata box appears)
- Change condition for node-card to show update button
- Add filter[reviews_state]=embargo,accepted` when …
> [ENG-3423] Version metadata updates

- lib/registries/addon/components/registries-search-result/styles.scss
- lib/registries/addon/discover/template.hbs
- mirage/scenarios/registrations.ts
-   Ticket: [ENG-3406](https://openscience.atlassian.net/browse/ENG-3406)
Fix the contrast issues on the registries discover page
1. Fix the mirage scenario for the withdrawn registration to show it as being withdrawn on the search page
2. Darken the 'Withdrawn' tag
3. Un-mute the 'no results found' text (and also the 'cannot load results' text, while I was in there)
No
Just needs accessibility testing
> [ENG-3406] Fix contrast issues on registries discover page

- app/guid-node/template.hbs
-   Ticket: [ENG-3410](https://openscience.atlassian.net/browse/ENG-3410)
Add a 'main' landmark to the project.registrations page
1. Add the main landmark
No, unless there's somehow already a main landmark in there under some circumstances.
My A11y tool did not pick up on the lack of a main landmark. Also, I couldn't find one even if there were a registration card on the page. So I don't think I broke anything with this, but I can't verify for sure. As near as I can tell, there's only one main landmark, so it shooould be fine.
> [ENG-3410] Add main landmark to project.registrations page

- lib/osf-components/addon/components/subjects/display/styles.scss
- lib/osf-components/addon/components/subjects/display/template.hbs
-   Tickets: 
[ENG-3414](https://openscience.atlassian.net/browse/ENG-3414)
[ENG-3415](https://openscience.atlassian.net/browse/ENG-3415)
Fix accessibility problems with draft registration metadata page's subjects placeholder.
1. Increase contrast
2. Use `li` inside of the `ul`
No
Should just need accessibility testing
> [ENG-3414][ENG-3415] Fix a11y with draft registration metadata subjects placeholder

- lib/app-components/addon/components/branded-navbar/styles.scss
-   Ticket: [ENG-3241](https://openscience.atlassian.net/browse/ENG-3241)
The collection provider branded css uses `!important` tags to override styles, which is causing some trouble. In the case of a logged-out user, the sign-up button text is overridden. In the case of a logged in user, the secondary nav in the navbar is overridden, which in the case of jbp collection, causes it to look like:
This is the set of changes necessary to allow the jbp.css provider css to be changed in order to override the menu links but not the secondary nav nor the sign-in button. It will have no visible effect before the provider css is changed.
I had to do things that our stylelint doesn't like, so I've disabled linting for my new rules. It's better than using the `!important` tag in …
> [ENG-3241] Prepare for jbp collection provider style changes

- lib/registries/addon/components/registries-services-list/styles.scss
- lib/registries/addon/components/registries-services-list/template.hbs
-   Ticket: [ENG-3357](https://openscience.atlassian.net/browse/ENG-3357)
The external services links on the registries landing page were too dark compared to their background in the hover state. This lightens up the hover state and increases the contrast.
1. Add hover state css.
2. Fix the link for "open source code" to go to ember-osf-web instead of ember-osf-registries.
This is isolated to those links and the hover state.
Just verify that I made the hover state light enough to be properly visible.
> [ENG-3357] Make hover state lighter and more contrasty

- lib/registries/addon/drafts/draft/route.ts
- translations/en-us.yml
-   Ticket: [ENG-2471]
- Reroute users out of the draft registration edit route to the overview page if a draft has already been submitted
- Add reroute logic and toast message for users accessing a draft that's already submitted
- I looked at changing some of the logic in the osf.io repo, specifically https://github.com/CenterForOpenScience/osf.io/blob/develop/api/nodes/views.py#L225-L226
- I tried changing this to be something like: `self.headers['location'] = 'localhost:5000/' + draft.registered_node._id` but that didn't seem to work as expected, so I've kept it as is
NA
None
- This should only impact drafts that have already been submitted when going to osf.io/registries/drafts/<draft_that_is_already_submitted>
[ENG-2471]: …
> [ENG-2471] Reroute users out of draft route when already submitted

- lib/osf-components/addon/components/registries/overview-form-renderer/template.hbs
- lib/osf-components/addon/components/registries/version-metadata/template.hbs
- mirage/factories/registration.ts
- tests/engines/registries/acceptance/overview/revision-test.ts
- tests/integration/components/registries/update-dropdown/component-test.ts
- tests/integration/components/registries/version-metadata/component-test.ts
-   Ticket: [ENG-3486]
- Show correct date for when a registration was originally submitted when viewing the original version of a registration
- Pass in `@registration` into the <Registries::VersionMetadata> component and use the registration's dateRegistered property to show when the registration was submitted instead of the SchemaResponse's dateModified
- Tests
- When viewing the original version of a registration with multiple revisions, these dates should match
- None
- There was a mismatch of dates discovered in registrations that were submitted before Registration Updating was released (Dec. 01, 2021). If there is a registration that was submitted before Dec. 01, 2021 that has an update, the dates shown in the righthand metadata bar and the Version metadata …
> [ENG-3486] Fix language for overview revision metadata

- app/styles/_components.scss
-   Ticket: [ENG-3241](https://openscience.atlassian.net/browse/ENG-3241)
Apply the white color to the sign up button text so that, when the jbp css is modified, the button will have white text.
1. Apply white color to text of button
Before:
After:
No, this should be isolated.
Test on https://staging.osf.io/collections/test/discover - it should work with no other changes.
> [ENG-3241] JBP Collection CSS part 2

- app/guid-file/controller.ts
- app/guid-file/route.ts
- app/services/meta-tags.ts
- mirage/scenarios/registrations.ts
- tests/acceptance/resolve-guid-test.ts
- tests/unit/guid-file/controller-test.ts
-   Ticket: n/a
Add the route for guid-files so we can do programatic things on the guid-file page.
1. Add route
2. Add minimal controller
3. Add tests
4. Add mirage for a guid-addressable file
5. Fix meta-tags service to use the correct current URL
No, new code.
This is not testable in isolation. Testable stories coming soon.
> [No ticket] Add guid-file route

- app/packages/files/file.ts
- lib/osf-components/addon/components/file-browser/styles.scss
- lib/osf-components/addon/components/file-browser/template.hbs
- tests/engines/registries/acceptance/overview/files-test.ts
-   Ticket: [ENG-3527](https://openscience.atlassian.net/browse/ENG-3527)
Enable the "Download all files" link.
1. Add folder download links to `File.links`
2. Change Download all files from button to link and adjust styling
3. Add href to the Download all files link
4. Test
This gives all folders download links, which will be different links than what Mirage provides, since the OSF API doesn't provide download-as-zip links for folders, while Mirage does.
Make sure it downloads the right things, mostly.
> [ENG-3527] Download provider/current-folder as zip

- app/packages/files/file.ts
- lib/osf-components/addon/components/file-browser/component.ts
- lib/osf-components/addon/components/file-browser/template.hbs
- lib/osf-components/addon/components/storage-provider-manager/osf-storage-manager/component.ts
- mirage/views/file.ts
-   Ticket: [ENG-3523](https://openscience.atlassian.net/browse/ENG-3523)
Enable filtering for Files page. Note that this does not yet include tests, because I'm waiting on a change to mirage that @futa-ikeda is working on that will affect how tests are setup.
1. Change filter query parameter to filter on filename
2. Have input box perform filter update
3. Add debouncing to filtering
4. Clear out the current results if currentPage=1
5. Fix file view in mirage so that it filters
No
Filtering should work on file name after this.
> [ENG-3523] Filespage/filter file list

- lib/registries/addon/components/registries-metadata/template.hbs
- translations/en-us.yml
-   Ticket: [ENG-3559]
- Update the language for the `registered from` relationship of a registration, since this wording doesn't make much sense now that users can create a registration without a prior project
- Update translation file
- None
- This impacts only the Registration Overview page (osf.io/<registration_guid>), on the right metadata column. It will no longer say `Registered from` but instead say `Associated project`
[ENG-3559]: https://openscience.atlassian.net/browse/ENG-3559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3559] Update wording for a registration's registered_from

- app/models/file-provider.ts
- app/models/file.ts
- lib/registries/addon/overview/controller.ts
- lib/registries/addon/overview/route.ts
- lib/registries/addon/overview/styles.scss
- lib/registries/addon/overview/template.hbs
- mirage/factories/file-provider.ts
- mirage/factories/registration.ts
- mirage/scenarios/registrations.ts
- mirage/serializers/registration.ts
- tests/engines/registries/acceptance/overview/files-test.ts
- tests/engines/registries/acceptance/overview/index-test.ts
- translations/en-us.yml
-   Ticket: []
- Show file-providers for registries
- Add element to show a registration's files provider on the registration overview page when you are on the registration's files route
- Change `inverse` for the `target` relationship of the file/file-provider models as this was incorrectly adding files to the `registration.files` relationship
> Add providers list to the leftnav when on registries file route

- app/models/base-file-item.ts
- app/models/file-provider.ts
- app/packages/files/osf-storage-provider-file.ts
- app/packages/files/provider-file.ts
- lib/osf-components/addon/components/storage-provider-manager/osf-storage-manager/component.ts
- lib/registries/addon/overview/route.ts
- mirage/factories/file-provider.ts
- mirage/serializers/file-provider.ts
- tests/engines/registries/acceptance/overview/files-test.ts
-   Ticket: [ENG-3585](https://openscience.atlassian.net/browse/ENG-3585)
Root folders are incomplete and buggy in the OSF API. For OSF Storage, they provide a url that is incompatible with waterbutler. For other storage providers, it's not implemented. So, instead of using the root folder, this PR uses the storage provider's files relationship, which provides the same info in a way that's complete and functional across providers. This should also allow the download provider as zip functionality to work.
1. Add mirage for provider files relationship
2. Add provider files relationship to model
3. Create provider-file and osfstorage-provider-file
4. Make osfstorage manager use the osfstorage-provider-file when appropriate
5. Fix download as zip test
6. Don't embed …
> [ENG-3585] Filespage/fix download provider

- lib/osf-components/addon/components/storage-provider-manager/provider-mapper/template.hbs
- lib/osf-components/app/components/storage-provider-manager/provider-mapper/template.js
- lib/registries/addon/overview/controller.ts
- lib/registries/addon/overview/files/index/route.ts
- lib/registries/addon/overview/files/provider/route.ts
- lib/registries/addon/overview/files/provider/template.hbs
- lib/registries/addon/overview/files/template.hbs
- lib/registries/addon/routes.ts
- tests/engines/registries/acceptance/overview/files-test.ts
- tests/engines/registries/acceptance/overview/index-test.ts
-   Ticket: [ENG-3590]
- Move the Registration's file list view into a provider specific route
- Create a new route: `registries.overview.files.provider`
- Reroute users to default storage provider (OsfStorage) when users enter the overview.files route
- Expand existing logic for files pages to account for new nested route
- Create new component: `StorageProviderManager::ProviderMapper`
- Use this new component to grab the appropriate storage manager in the overview.files.provider route
- Show provider name at the top of the files-list
- provider name shown a the top of the file list
- None, whatsoever. This is totally harmless with no side effects
[ENG-3590]: https://openscience.atlassian.net/browse/ENG-3590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
> [ENG-3590] Move registration files-list route

- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/styles.scss
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
- lib/osf-components/addon/components/file-browser/styles.scss
- lib/osf-components/addon/components/file-browser/template.hbs
- lib/osf-components/addon/components/infinite-list/template.hbs
- translations/en-us.yml
-   Ticket: []
Make files list view more better
- Change date format.
- Align the folder icons more better
- Add text for when the folder is empty
- Use named yields to make `InfiniteList` component more better.
> Make file list page more better

- lib/osf-components/addon/components/file-browser/breadcrumbs/crumb/template.hbs
- lib/osf-components/addon/components/file-browser/breadcrumbs/styles.scss
- lib/osf-components/addon/components/file-browser/breadcrumbs/template.hbs
- lib/osf-components/addon/components/file-browser/template.hbs
- lib/osf-components/addon/components/storage-provider-manager/osf-storage-manager/template.hbs
- lib/osf-components/app/components/file-browser/breadcrumbs/crumb/template.js
- lib/osf-components/app/components/file-browser/breadcrumbs/template.js
- lib/registries/addon/overview/files/provider/template.hbs
- tests/integration/components/file-browser/breadcrumbs/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3609](https://openscience.atlassian.net/browse/ENG-3609)
Add breadcrumbs to the file browser.
1. Add browser component
2. Export folder lineage from manager
2. Add tests
Long folder structures will push the screen down.
This should make a segment for each folder that you travel into, including osfstorage, divided by `>`.
> [ENG-3609] Filespage/breadcrumbs

- app/guid-file/route.ts
- app/guid-file/template.hbs
- tests/acceptance/guid-file/registration-file-detail-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3531](https://openscience.atlassian.net/browse/ENG-3531)
-   Feature flag:`ember_file_registration_detail_page`
Add the file renderer to the file detail page
1. Add file renderer
2. Use file's name above renderer
3. Add tests 
4. Remove unused translation strings
No.
I wasn't able to fully test this locally because MFR doesn't like working locally without jumping through a lot of hoops. So when we see it on staging, there may need to be adjustments. The general CSS work I think will also affect the presentation.
> [ENG-3531] Add file renderer to file detail page

- app/guid-file/route.ts
- app/guid-file/styles.scss
- app/guid-file/template.hbs
- tests/acceptance/guid-file/registration-file-detail-test.ts
-   Ticket: [ENG-3629](https://openscience.atlassian.net/browse/ENG-3629)
-   Feature flag: `ember_file_registration_detail_page`
Link the file back to the target node or registration (in this case, registration). 
1. Embed the target in the model request
2. Change button to link
3. Use target info for link
4. Remove h3 for not being semantically correct  
The layout is a bit messed up, but I wanted to make minimal changes to layout since there will be some larger-page changes coming soon.
> [ENG-3629] Link back to target registration/node

- app/models/file.ts
- lib/osf-components/addon/components/button/styles.scss
- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-embed-menu/component.ts
- lib/osf-components/addon/components/file-embed-menu/styles.scss
- lib/osf-components/addon/components/file-embed-menu/template.hbs
- lib/osf-components/addon/components/sharing-icons/dropdown/styles.scss
- lib/osf-components/app/components/file-embed-menu/component.js
- lib/osf-components/app/components/file-embed-menu/template.js
- tests/integration/components/file-embed-menu/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3536](https://openscience.atlassian.net/browse/ENG-3536)
-   Feature flag: `ember_file_registration_detail_page`
Allow users to embed files into their own web pages
1. Create `file-embed-menu` component
2. Add `file-embed-menu` component to `file-actions-menu`
3. Add translation strings
4. Test
5. Add render link to file links
This will also put the embed on the file list screen.
This does not fix the accessibility problem with the menu's no-nested-interactive problem, nor any styling issues that may be happening in mobile.
> [ENG-3536] Add file-embed-menu to file-actions-menu

- lib/osf-components/addon/components/file-version/template.hbs
- mirage/config.ts
- tests/acceptance/guid-file/registration-file-detail-test.ts
- tests/integration/components/file-version/component-test.ts
-   Ticket: [ENG-3652]
- Add tests for file-version component
- Add acceptance tests for file detail page
- component tests and data-test selectors for the file-version component
- add acceptance test for file-detail page
- View revisions
- Mobile view
- Add mirage endpoint for waterbutler revisions
- NA
- NA
- NA
[ENG-3652]: https://openscience.atlassian.net/browse/ENG-3652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3652] Add tests for file revisions

- app/guid-file/template.hbs
- app/models/abstract-node.ts
- app/models/node.ts
- app/packages/files/file.ts
-   Ticket: [ENG-3534]
-   Feature flag: `ember_file_registration_detail_page`
Add the tags widget to the file detail page. 
1. Add tags widget
No, this is isolated.
You will need the current version of `johnetordoff/sunset-quickfiles` in order to test this, as it contains, among other things, the code to make tags writeable.
[ENG-3534]: https://openscience.atlassian.net/browse/ENG-3534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3534] Add tags widget

- lib/osf-components/addon/components/button/styles.scss
- lib/osf-components/addon/components/file-actions-menu/styles.scss
- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
- lib/osf-components/addon/components/file-browser/template.hbs
- lib/osf-components/addon/components/registries/update-dropdown/styles.scss
- lib/osf-components/addon/components/responsive-dropdown/styles.scss
- lib/osf-components/addon/components/responsive-dropdown/template.hbs
- lib/osf-components/addon/components/side-nav/x-link/styles.scss
- lib/registries/addon/components/registries-states/styles.scss
- translations/en-us.yml
- Fix accessibility issues on registries file list page
- Remove uses of nested interaction elements
- Add styling for `<ResponsiveDropdown>` to make it look like a `<Button>`
- Remove some uses of `outline: none/0` to let keyboard users know where they are on the page
- Add aria-label to Filter textbox
NA
None
- These changes should fix the existing A11y issues on this page
> [ENG-3649] Fileslist a11y fixes

- translations/en-us.yml
Ticket: https://openscience.atlassian.net/browse/ENG-3649
Feature flag: n/a
The purpose of this change is to provide a translation string for the mfr iframe on the File Renderer component.
-The en-us.yml translation file was updated to include file_detail.mfr_iframe_title : 'File Detail View: '
-A paragraph tag including the title was added to the iframe element
Screenshots will need to be updated with Docker enabled.
When missing, the error message produced would throw off the UI. It is suggested that there be a font property added to the error message that renders it smaller and the same size as the current/ no larger than the parent element.
-Does the string render properly?
-Is proper styling added to the string?
> [ENG-3649] Fix bugs: add mfr iframe translation

- lib/osf-components/addon/components/file-browser/breadcrumbs/styles.scss
-   Ticket: https://openscience.atlassian.net/browse/ENG-3649
The purpose of this change was to decrease the font weight present on the file list view and it increase its font size.
I have updated the font weight to be 500 from 700 and increased the font-size from large to x-large in the File Browser's breadcrumb scss file here: lib/osf-components/addon/components/file-browser/breadcrumbs/styles.scss
Figure 1: File List view prior to font-weight change
Figure 2: File List view after font-weight change
This will change how the font for the breadcrumb will display. UA testing should ensure this looks right.
-Does the breadcrumb title display? Is it aesthetically pleasing with the rest of the page?
> [ENG-3649] Fix bugs: decrease breadcrumb font weight

- lib/osf-components/addon/components/file-browser/styles.scss
-   Ticket: []
- Align 'Download this folder button' to center
- Ditto
> Align download button to center

- lib/osf-components/addon/components/sharing-icons/component.ts
- lib/osf-components/addon/components/sharing-icons/dropdown/template.hbs
- lib/osf-components/addon/components/sharing-icons/template.hbs
- tests/engines/registries/acceptance/overview/topbar-test.ts
- translations/en-us.yml
Remove LinkedIn from the sharing icons. The functionality is rarely used and has been broken for an indeterminate amount of time. There is a ticket to add it back if we decide to do that.
1. Remove LinkedIn from Sharing Icons
2. Remove LinkedIn test case
3. Remove from translations file
Should be pretty isolated.
You'll know it works if you can't find LinkedIn to share with any more.
> [ENG-3649] Remove LinkedIn from sharing icons

- app/packages/files/file.ts
- app/packages/files/provider-file.ts
Fix Download As Zip links for when people are using View Only Links.
1. Don't just append `?zip=` to the URL. Actually properly manipulate the query parameters.
This is isolated to uses of the DAZ link functionality
Should work properly now in the case of View Only Links.
> [ENG-3649] Fix DAZ for VOLs

- config/environment.js
- lib/osf-components/addon/components/osf-navbar/x-links/component.ts
- lib/registries/config/environment.js
-   Ticket: [ENG-3657]
- Update navbar links to go to the new helpscout guides
- Update general OSF navbar to go to helpscout
- Update registries navbar to go to helpscout
NA
- We will no longer be taking users to the support route (osf.io/support) via the navbar links
This is to just change the link in the navbar. Other links going to the old help guides can stay for now, and will be revisited in the future
[ENG-3657]: https://openscience.atlassian.net/browse/ENG-3657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3657] Link users to new helpscout guides

- app/packages/files/file.ts
The versions list wasn't working properly when viewed in a VOL. This changes the way query parameters were appended to the upload link so that it would handle when there was already a query parameter in the URL.
1. Append query parameter properly
No, this is isolated to the versions pane
It should work with and without VOLs now.
> [ENG-3649] Fix versions feature in VOL

- app/guid-file/-components/file-detail-layout/styles.scss
- app/guid-file/styles.scss
-   Ticket: []
- Fix issue where tags widget width would increase as more tags are added
- use flex-basis instead of min-width for right panel container div
- make revisions tab and tags tab have same amount of padding/margin
> Update styling for file-detail right panel

- app/packages/files/file.ts
- app/packages/files/provider-file.ts
The versions list wasn't working properly when viewed in a VOL. This changes the way query parameters were appended to the upload link so that it would handle when there was already a query parameter in the URL. Also, I accidentally merged the last version of this before it was done, so there's a new PR here.
1. Append query parameter properly
2. Simplify  query param setting in other locations
No, this is isolated to the versions pane
It should work with and without VOLs now.
> [ENG-3649] Better revisions query parameters (take 2)

- lib/osf-components/addon/components/file-version/template.hbs
- tests/acceptance/guid-file/registration-file-detail-test.ts
- tests/integration/components/file-version/component-test.ts
-   Ticket: []
- Hide revision creator name due to AVOL issues
- Remove User section from revision item
This is what got removed
> Hide user name from revisions (needed for AVOLs)

- lib/osf-components/addon/components/file-actions-menu/styles.scss
- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/styles.scss
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
- lib/osf-components/addon/components/file-browser/styles.scss
- lib/osf-components/addon/components/file-browser/template.hbs
- lib/osf-components/addon/components/file-embed-menu/styles.scss
- lib/osf-components/addon/components/file-embed-menu/template.hbs
- lib/osf-components/addon/components/sharing-icons/dropdown/template.hbs
- lib/registries/addon/components/hero-overlay/styles.scss
-   Ticket: []
- Make files page related dropdowns tab-navigable
- Use `renderInPlace` option for dropdowns in file page
- Add style change needed to prevent text wrap
- restrict some loose CSS rules to not apply to newly nested dropdown content
- No visible changes
- Haven't updated the social media sharing icons yet as applying the same fix as I have done for the other dropdowns makes it so the "Share this registration" button does not show dropdown properly
- EDIT: There was a `overflow: hidden` on the `HeroOverlay` component that was hiding the dropdown content. I've removed that rule, and it shows the dropdown. I've checked other places where this HeroOverlay component is used (branded registries moderation, add new registration, registries discover page, draft …
> Tab-navigable dropdown

- lib/osf-components/addon/components/file-browser/styles.scss
- lib/osf-components/addon/components/file-browser/template.hbs
-   Ticket: []
- Moible: Fix small visual error when selecting "Last modified" option in file sort dropdown
- Remove padding that is unneeded due to flex-box styling for that dropdown
Fixes the caret overlapping the very right side of the button seen here
- Seen in narrow phones (screenshot from Samsung Galaxy S8+, also seen in Galaxy S21)
> Mobile: remove excess padding for file sort dropdown

- app/guid-file/route.ts
- app/packages/files/file.ts
- app/packages/files/osf-storage-file.ts
- app/packages/files/osf-storage-provider-file.ts
- app/packages/files/provider-file.ts
- lib/osf-components/addon/components/storage-provider-manager/osf-storage-manager/component.ts
-   Ticket: []
Fix reivisions list for files whose revisions list view requires permissions.
Add `currentUser` as a class attribute.
Note: can't inject `currentUser` service directly because this is a native JS class.
> Add currentUser service when initializing File instances

- app/guid-file/route.ts
If a file belongs to a withdrawn registration, this will take direct access of that file to the registration's tombstone page rather than showing the file.
1. Route withdrawn file request to registration tombstone page.
Shouldn't be. 
Should just need quick testing with regular and withdrawn registration files.
> [ENG-3649] Route withdrawn file to registration overview page for tombstone

- lib/registries/addon/drafts/draft/draft-registration-manager.ts
- lib/registries/addon/drafts/draft/route.ts
- lib/registries/addon/edit-revision/revision-manager.ts
- lib/registries/addon/edit-revision/route.ts
-   Ticket: [ENG-3700] 
- Keep URL user tried to go to when rerouting them to page-not-found
- Change reroute behavior in draft registration and edit revision pages
- This changes what is shown in the URL bar when a user goes to an invalid draft registration (osf.io/registries/drafts/invalid/) or an invalid revision (osf.io/registries/revisions/invalid). Before, this would take users to a URL like `osf.io/a`. Now users should see the full URL they tried to go to
[ENG-3700]: https://openscience.atlassian.net/browse/ENG-3700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3700] Keep currentURL readable when rerouting to page-not-found

- lib/osf-components/addon/components/side-nav/component.ts
- lib/registries/addon/overview/styles.scss
- lib/registries/addon/overview/template.hbs
-   Ticket: [ENG-3689] [ENG-3682]
- Make the globe for file-provider's storage location bigger for mobile users
- Disallow collapse for sidenav on registries overview page
- Increase size of globe icon in left-nav shown when in registration overview's file route
- Disallow collapse for sidenav (done in a way that if we need to revert this, it's not that bad)
- Overview sidenav is no longer collapsible, but draft registration and registration revision routes still have collapsible sidenav
The globe icon should be easier to tap on mobile.
The registration overview sidenav should no longer be collapsible (was only collapsible on desktop)
[ENG-3689]: https://openscience.atlassian.net/browse/ENG-3689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
> [ENG-3689][ENG-3688] Make file provider globe icon larger

- lib/osf-components/addon/components/dropzone-widget/component.ts
- lib/osf-components/addon/components/files/manager/component.ts
- translations/en-us.yml
-   Ticket: [ENG-3682]
- Fix broken translation string when user successfully uploads a file to the draft registration
- Remove Dropzone file-previews that are not working correctly
- Add translation for file-upload success toast
- Do not use Dropzone's preview feature
Removed issues seen in the JIRA ticket
None
- This is for the draft registrations workflow. Dragging/dropping a file onto the widget should no longer show the little file preview with the ✅  and ❌  icons, and the toast message should say something meaningful
[ENG-3682]: https://openscience.atlassian.net/browse/ENG-3682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3682] File uploader issue for draft registrations

- lib/osf-components/addon/components/file-renderer/component.ts
- tests/integration/components/file-renderer/component-test.ts
-   Ticket: [ENG-3690]
- Fix broken file-renderer when viewing a file through an anonymized view-only-link
- Use actual queryparam manipulation in JS instead of treating them like glorified strings
- prevents views like this:
- None
should prevent `UNAUTHORIZED` message in MFR iframe in URLs like: https://staging2.osf.io/sx8g4?view_only=b1a940b7abd84d9f892275437b65e730
[ENG-3690]: https://openscience.atlassian.net/browse/ENG-3690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3690] Set file-renderer url params properly

- lib/osf-components/addon/components/osf-layout/registries-side-nav/component.ts
-   Ticket: [ENG-3688]
- Remove collapse leftnav button from the draft registration and update registration pages to make them more consistent with overview page
- Temporarily change `isCollapseAllowed` to always return false
- If removing permanently, we should remove `shouldCollapse`, `isCollapsed`, `isCollapseAllowed` and other properties pertaining to collapsibility
- Draft registration page
- Registration update page
[ENG-3688]: https://openscience.atlassian.net/browse/ENG-3688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3688] Remove leftnav collapse button from registration draft and update pages

- lib/registries/addon/drafts/draft/route.ts
-   Ticket: []
- take read-only users to registration overview page if the draft registration is already submitted
- prevent reroute to review page from happening if the draft is already submitted
- NA
- NA
- This should only impact read-only users on a submitted registration. Read-only users will still be routed to the review page if the draft is still in progress
> [ENG-3741] Fix draft reg reroute logic for read-only users 

- app/guid-file/-components/file-detail-layout/styles.scss
- app/guid-file/styles.scss
-   Ticket: https://openscience.atlassian.net/browse/ENG-3649 , https://openscience.atlassian.net/browse/ENG-3736
The purpose of this ticket is to fix the display of project link and file names which overflow to the next line.
The properties for ellipse text-overflow behavior were added to the CSS file. Additional properties that were added include its white-space set to not wrap, making the element display as an inline block, left aligning the text, and setting a width to ensure the ellipse displays regardless to communicate to the user that there is more text present in the project name.
There is a concern that the side divs open oddly on the right when viewport width is added. The solution is not ideal, and should be seen as more of a hotfix until a more complete …
> [ENG-3736] Fix bugs: project link overflow text

- app/guid-node/files/provider/route.ts
- app/guid-node/files/provider/template.hbs
- ember-cli-build.js
- lib/osf-components/addon/components/file-browser/component.ts
- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/styles.scss
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
- lib/osf-components/addon/components/file-browser/template.hbs
- lib/osf-components/addon/components/storage-provider-manager/osf-storage-manager/component.ts
- lib/osf-components/addon/components/storage-provider-manager/osf-storage-manager/template.hbs
- mirage/factories/node.ts
- tests/acceptance/guid-node/files-test.ts
- tests/integration/components/file-browser/component-test.ts
- tests/integration/components/file-browser/file-item/component-test.ts
- tests/integration/components/file-browser/folder-item/component-test.ts
- translations/en-us.yml
-   Ticket: []
- Allow users to select files in list view
- Add leftnav content to guid-node/file route
- Add label and hidden checkbox to file-browser/file-item and file-broswer/folder-item 
- Add logic to file-browser to handle selected files
- Add logic to osf-storage-manager to handle selected files
- Add leftnav content to guid-node/file template
- Functionality and styling are still a little rough
> File list select

- app/guid-node/files/provider/route.ts
- app/guid-node/files/provider/styles.scss
- app/guid-node/files/provider/template.hbs
- lib/registries/addon/overview/template.hbs
-   Ticket: [ENG-3761]
Add the provider links to the leftnav and style the outer portions of the page
1. Add hero banner
2. Add provider links to leftnav
3. Fix broken translation
Nah
It should only show providers that are linked to the current project, and you should be able to navigate to each of the providers.
[ENG-3761]: https://openscience.atlassian.net/browse/ENG-3761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3761] LeftNav links and page styling

- lib/osf-components/addon/components/file-browser/add-new/template.hbs
- lib/osf-components/addon/components/file-browser/help-modal/template.hbs
- translations/en-us.yml
- Better accessibility for files page stuff
- Add tab index to modal body to allow scrolling with keyboard
- Add aria-label to files widget omni-button
NA
- These fixes should be covered by automated testing:
- Green omni button to add folder and files should have aria-label
- Files widget help modal should be scrollable
> [No ticket] Files page a11y fixes

- app/models/file.ts
- app/packages/files/file.ts
- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
-   Ticket: [ENG-3728]
When a new version of a file is put up, people who haven't seen it yet should show it as unviewed, which in this case means a bolder font-weight in the file list.
1. Update model
2. Update file object
3. Add style if the version hasn't been viewed 
This shouldn't interact with anything
Viewing a file to clear the flag means rendering it in MFR, so visiting the file detail page should clear it. This is osfstorage-only functionality, so other providers should never show bolded files in the file list, as far as I understand it. If the user isn't logged in or isn't a contributor to the project, it should similarly show as non-bolded. 
[ENG-3728]: https://openscience.atlassian.net/browse/ENG-3728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
> [ENG-3728] Show unviewed files as unviewed

- app/packages/files/file.ts
- lib/osf-components/addon/components/file-browser/template.hbs
- translations/en-us.yml
Fix sorting by date modified
1. Use date_modified instead of modified for sorting to match the recently fixed backend.
Will also affect the registries files page
Sorting should work properly now.
> [No ticket] Fix sorting by date

- app/guid-node/files/provider/route.ts
- app/guid-node/files/provider/template.hbs
- tests/acceptance/guid-node/files-test.ts
Adjust which leftnav links are seen with different permission levels and AVOL/VOLs.
1. Hide Addons for read-only users
2. Hide everything but Overview, Files, Wiki, and Registrations from VOL
3. Hide Registrations for AVOL users
Write permissions:
Read permissions:
Non-anonymous VOL:
AVOL:
Wiki disabled:
No
Just verify that the current states are as expected.
> [ENG-3811] Leftnav links with differing permissions

- lib/osf-components/addon/components/move-file-modal/component.ts
- lib/osf-components/addon/components/move-file-modal/list-item/component.ts
- lib/osf-components/addon/components/move-file-modal/list-item/template.hbs
-   Ticket: [ENG-3806]
- Address bugs found for move files/folders capabilities
- Load all file-providers when fetching a node's file providers
- Show provider icons properly
- Issue where only 10 providers load as seen here fixed and should now show icons
[ENG-3806]: https://openscience.atlassian.net/browse/ENG-3806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3806] Move files bugs

- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
Allow selenium tests (and ours) to access the move, copy, and delete buttons more easily
1. Add data test selectors to file and folder action menus
None anticipated
This should give you the ability to use those buttons easily in your tests.
> [ENG-3811] Add data-test selectors for copy/move/delete buttons

- app/guid-file/template.hbs
- app/guid-node/files/provider/styles.scss
- app/guid-node/files/provider/template.hbs
- lib/osf-components/addon/components/file-actions-menu/delete-modal/template.hbs
- lib/osf-components/addon/components/file-renderer/component.ts
Fix a few bugs on the files page
1. Don't reload files page when clicking files link in sidebar
2. Put padding around whole filebrowser
3. Try to make the pulser work on MFR when changing versions on the file detail page - note that this is hard to test locally because MFR doesn't work, but the theory seems sound.
4. Disable delete button when delete task is running
5. Hide horizontal rules in ordered list from aria
> [ENG-3811] Misc files page bugs 1

- app/packages/files/file.ts
- lib/osf-components/addon/components/move-file-modal/component.ts
- lib/osf-components/addon/components/move-file-modal/template.hbs
- translations/en-us.yml
-   Ticket: [ENG-3806]
- Limit simultaneous move/copy tasks to 3 at a time to avoid issues with requests getting throttled
- Add `enqueue` and `maxConcurrency: 3` to copy and move tasks
- Add new message for files waiting to be moved/copied
- Actually cancel move/copy tasks that haven't started when the user closes the modal
- The limit of 3 simultaneous requests was chosen arbitrarily. This may slow down providers that are able to handle more than 3 requests at a time, so it may be worthwhile to adjust the limit higher/lower depending on the provider the users are trying to copy/move to or copy/move from.
- We could add a property like `maxConcurrentTasks` to the `provider-file` base class and overwrite it with a smaller/larger number for specific providers and …
> [ENG-3806] Multi file move bugs

- lib/osf-components/addon/components/move-file-modal/list-item/styles.scss
- lib/osf-components/addon/components/move-file-modal/list-item/template.hbs
- Wrap text for file providers in move/copy file modal
- Fix left-align issue for valid vs invalid move/copy destinations
- Add class to move-file-modal's list-items
- text wraps for invalid destinations
- old:
- new:
- NA
- Text for invalid move/copy destinations now wrap
- Text/icons for valid/invalid move destinations now have the same amount of left-padding
> [ENG-3811] Text styling for move/copy modal destinations

- app/models/file.ts
- Prevent 410 errors when moving files out of OsfStorage
- Stop doing a `file.reload` after a file has moved. Not sure why this was there in the first place, but maybe it was needed for some Quickfiles stuff?
- NA
- hopefully none
- Moving files out of OsfStorage should no longer cause errors
> [ENG-3811] Prevent 410 errors when moving files out of OsfStorage

- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
- lib/osf-components/addon/components/storage-provider-manager/storage-manager/component.ts
- Allow users to shift-click files/folders and select a range in firefox
- Move the click event handler from the `<input>` to the `<label>` element
- preventDefault for the click event if the event is started from the label to prevent the `selectFile` action from firing twice (once from the label, another from the input)
- Some interesting discussion about this bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=559506 and some indication that this behavior may be by-design (to allow users to select text in a `<label>` element)
- NA
- Not really a side-effect, but for whatever reason, Firefox doesn't believe that the shiftKey is pressed when you "click" a checkbox using the spacebar, so other browsers will allow users to select a range of …
> [ENG-3811] Firefox multi file select

- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- translations/en-us.yml
Fix accessibility problems related to unseen file versions
1. Make the bold text bolder
2. Have the aria label change based on whether you've seen the version or not
No, this is pretty isolated.
> [ENG-3811] Fix a11y problems with unseen file versions

- app/models/file.ts
- app/packages/files/file.ts
- lib/osf-components/addon/components/move-file-modal/component.ts
- lib/osf-components/addon/components/move-file-modal/template.hbs
- translations/en-us.yml
- Show better message when file moves are queued
- cram the xhr status onto the file model's `move` and `copy` methods (Shoutout to @adlius )
- check status on move-file-modal template and show more informative message
> [ENG-3811] Queue move

- app/guid-node/files/provider/template.hbs
- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/storage-provider-manager/storage-manager/template.hbs
Prevent copy from being an option if using a view-only link.
1. Pass around isViewOnly
2. Disable selections for view_only links
3. Hide copy button for view_only links
Prooobably not
> [ENG-3811] Don't show copy button or allow selections if view only

- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
Prevent the copy button from showing up on the folder menu when in a View Only Link
1. Hide the button conditionally
> [ENG-3811] Don't allow copying of folders in VOL

- lib/osf-components/addon/components/file-browser/file-rename-modal/styles.scss
-   Ticket: https://openscience.atlassian.net/browse/ENG-3811
-   Feature flag: feature/file-rename-vw
These changes update the width of the modal to accommodate fifty percent of the viewport width.
1. lib/osf-components/addon/components/file-browser/file-rename-modal/styles.scss
-Styling was added to the styles.scss file for the FileRenameModal component
This change should have no formal side effects. It will however change the UI (view) to make the modal display wider.
-Does the modal still render properly?
-Do all translation strings also still render?
-How does the modal look in mobile. Ironically, this is similar to the original display in desktop. Do you think it should be wider in mobile or does the styling work here as well?
> [ENG-3811] Miscellaneous Bugs

- lib/osf-components/addon/components/file-browser/file-rename-modal/component.ts
- Don't replace files/folders when there is a name conflict
- instead appends (1), (2), etc depending on number of duplicate file/folder names discovered (similar to macOS's handling of dupe file names)
- set `conflict` param to empty string to override default `replace` behavior
- Result of trying to name two folders `aaa`
- Result of trying to name a second file `test.txt` and another file renamed to `test(2).txt`
- None
- we should now no longer be replacing files when there is a name conflict
> [ENG-3811] Prevent replace on rename conflict

- app/packages/files/file.ts
- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/styles.scss
-   Ticket: [ENG-3849]
Show the file sizes on the files page list view
1. Make the flexbox into pretty columns
2. Add the file sizes to the list view
Shouldn't be.
[ENG-3849]: https://openscience.atlassian.net/browse/ENG-3849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3849] Add file sizes to list view

- app/packages/files/osf-storage-file.ts
When the backend is fixed for the storage limit calculation problem, this will still be needed to ensure that the call completes before the calculation is made.
1. Await the call to storage
2. DRY up the code
> [ENG-3811] Fix storage limit async call and DRY

- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/folder-item/styles.scss
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
- tests/integration/components/file-browser/component-test.ts
When I added the file sizes, I made the flex box act columnar. This had the side-effect of extending the divs/buttons that had a z-index of 9, making the click target for a selection much smaller than it had been. This reduces the surface area of the z-indexed items to just be the clickable targets and prevents the button from extending the width of the column in the case of folders.
1. Juggle around z-index
2. Restrict size of button to not be the width of the column
Should just make things easier to select. Smaller item names will have smaller click targets.
If you were selecting rows the same way our unit tests were, you may need to update Selenium to use a new, better test selector. Instead of doing …
> [ENG-3811] Make it easier to select rows

- app/packages/files/osf-storage-file.ts
- app/packages/files/osf-storage-provider-file.ts
- lib/osf-components/addon/components/file-browser/template.hbs
- mirage/scenarios/dashboard.ts
- tests/acceptance/guid-node/files-test.ts
Make storage usage actually work in the places it needs to. The basic problem was that, while getters get magic from ember to wait for async calls as part of .get(), they don't get access to that if the gets are in another async function. So I moved the getters for the storage limit into the getters for the properties that need that info.
1. Remove async helper function
2. Update `userCanMoveToHere`
3. Fix incorrect property on multi-select move button
4. Add 'withStorage' trait where needed
You have to use the 'withStorage' trait if you want a mirage node that can use its files page. ~~Also, this will generate a 404 in the console of a registration's file list page because there's no storage endpoint. This should be easily fixed when I have a …
> [ENG-3811] Fix storage limit code

- lib/osf-components/addon/components/move-file-modal/current-node-item/styles.scss
- lib/osf-components/addon/components/move-file-modal/current-node-item/template.hbs
- Prevent current destination node name from getting cut off in move/copy file modal in mobile
- Wrap. That. Text
Prevents following:
Looks like:
> [ENG-3811] Wrap current destination node in move-file-modal

- lib/osf-components/addon/components/file-browser/help-modal/styles.scss
- lib/osf-components/addon/components/file-browser/help-modal/template.hbs
- translations/en-us.yml
- add some text to warn users about special characters in the file browser's help modal
- Update translation for Upload and Rename section of help modal
> [ENG-3811] Warning for special chars in help modal

- lib/osf-components/addon/components/file-browser/add-new/template.hbs
-   Ticket: [ENG-3811] 
- Adjust where the "Add new file" dropdown content shows up to prevent it from going off screen
- Switch counterintuitive argument
Prevents:
Now renders to the left:
> [ENG-3811] Show add new dropdown on the other right side (the left side)

- lib/osf-components/addon/components/move-file-modal/list-item/component.ts
- lib/osf-components/addon/components/move-file-modal/list-item/template.hbs
- lib/osf-components/addon/components/move-file-modal/template.hbs
- translations/en-us.yml
- Don't allow users to move/copy folders into themselves
- Properly check if an item in the move-modal destination list is one of the files being moved
- Add new translation string
- Remove unused class and properties
Write/Admin users:
Read users:
- Users should no longer be able to copy/move folders into themselves and should be shown appropriate descriptive text as to why certain destination options are disabled
> [Hotfix(?)][ENG-3811] Prevent recursive move/copy

- lib/osf-components/addon/components/file-browser/file-rename-modal/component.ts
We had a ts error on build that wasn't caught by eslint. Apparently we were too clever with an if statement, and had to be more explicit.
```
lib/osf-components/addon/components/file-browser/file-rename-modal/component.ts:31:46 - error TS2532: Object is possibly 'undefined'.
31         return (Boolean(this.newFileName) && this.newFileName.trim() !== this.originalFileName &&
~~~~~~~~~~~~~~~~
lib/osf-components/addon/components/file-browser/file-rename-modal/component.ts:32:13 - error TS2532: Object is possibly 'undefined'.
32             this.newFileName.trim() !== '');
~~~~~~~~~~~~~~~~
```
1. Wrap return in an if statement to check for the existence of newFileName
No, this is isolated.
This should change nothing about the functionality of the rename modal. It should still not allow you to …
> [No ticket] Fix ts error for potentially undefined newFileName

- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/folder-item/styles.scss
-   Ticket: [ENG-3881]
- Show long files names a bit more appropriately
- change file-list height to accommodate long file names
- change file/folder-action menu placement to be in the center
Before:
After:
After(Mobile):
- A single entry could get potentially very long if the file/folder name is really long, but I think hiding the name would be a worse UX
[ENG-3881]: https://openscience.atlassian.net/browse/ENG-3881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3881] Style long file names better

- lib/osf-components/addon/components/file-browser/add-new/template.hbs
- lib/osf-components/addon/components/file-browser/component.ts
- lib/osf-components/addon/components/file-browser/delete-file-modal/template.hbs
- lib/osf-components/addon/components/file-browser/template.hbs
- mirage/factories/file.ts
- tests/acceptance/guid-node/files-test.ts
- tests/engines/registries/acceptance/overview/files-test.ts
- tests/integration/components/file-browser/component-test.ts
-   Ticket: [ENG-3880]
- Add/edit test for files page functionality
- Add data-test selectors
- Edit Registration Files test
- Edit FileBrowser component test
- Edit Node Files test
- NA
- I can sleep better at night knowing we have test coverage for some of this
-  I've added data-test selectors for the bulk file actions: `data-test-bulk-copy-trigger`, `data-test-bulk-move-trigger`, and `data-test-bulk-delete-trigger`
- I've added a data-test selector for the green "Add new" omni button: `data-test-add-new-trigger`
[ENG-3880]: https://openscience.atlassian.net/browse/ENG-3880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3880] Add file tests

- app/models/file.ts
- lib/osf-components/addon/components/file-browser/add-new/create-folder-modal/component.ts
- lib/osf-components/addon/components/file-browser/add-new/create-folder-modal/styles.scss
- lib/osf-components/addon/components/file-browser/add-new/create-folder-modal/template.hbs
- lib/osf-components/addon/components/file-browser/add-new/template.hbs
- lib/osf-components/addon/components/file-browser/file-rename-modal/component.ts
- lib/osf-components/addon/components/file-browser/file-rename-modal/styles.scss
- lib/osf-components/addon/components/file-browser/file-rename-modal/template.hbs
- mirage/serializers/file-provider.ts
- mirage/serializers/file.ts
- mirage/views/file.ts
- tests/integration/components/file-browser/component-test.ts
- tests/integration/components/file-browser/file-rename-modal/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3882]
- Disallow special characters in new folders and file/folder rename modals
- Add logic to check against forbidden special chars for file rename and new folder modal
- Add error messages to those modals
- Rename
- Desktop:
- ![image](https://user-images.githubusercontent.com/51409893/177358365-54ada530-4d00-44eb-8b47-7f578ad6aed6.png)
- Mobile:
- ![image](https://user-images.githubusercontent.com/51409893/177358305-a41026cb-d236-49c8-9ce9-d2d03e796795.png)
- New folder
- Desktop
- ![image](https://user-images.githubusercontent.com/51409893/177358510-9f2cc4e9-e59f-4a27-aad8-19f984019a2a.png)
- Mobile
- ![image](https://user-images.githubusercontent.com/51409893/177358569-7413731d-ccc0-4ff5-a013-0a981b1efb3e.png)
- Renaming existing files/folders …
> [ENG-3882] Prevent special chars and show error messages

- app/guid-node/files/provider/controller.ts
- app/guid-node/files/provider/route.ts
- app/guid-node/files/provider/template.hbs
- app/models/node.ts
- tests/acceptance/guid-node/files-test.ts
-   Ticket: [ENG-3886]
- Hide `Contributors` and `Settings` link for non-contributors
- Add condition to show/hide Contributors and Settings links
- Remove logic around Analytics link (doesn't match legacy page)
- AVOL:
- <img width="269" alt="image" src="https://user-images.githubusercontent.com/51409893/178378152-89b5fae0-eaab-4728-a12e-38ee6e7b3bcd.png">
- <img width="195" alt="image" src="https://user-images.githubusercontent.com/51409893/178378182-04af66f8-b63d-4572-8033-1bd7aed76bf9.png">
- VOL:
- <img width="347" alt="image" src="https://user-images.githubusercontent.com/51409893/178378095-825250d7-696b-4de2-a095-fb2c6c5358c9.png">
- <img width="190" alt="image" src="https://user-images.githubusercontent.com/51409893/178378128-5a0946d5-42b3-4198-91f8-8f745780f3 …
> [ENG-3886] Hide node-files page links based on permission

- app/guid-file/template.hbs
- app/packages/files/dataverse-file.ts
- app/packages/files/file.ts
- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- tests/integration/components/file-browser/file-item/component-test.ts
- tests/unit/packages/files/dataverse-file-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3879]
- Show which files are draft vs published for dataverse
- Add `providerSpecificData` object to File abstract class
- Add `titleSuffix` to this object
- Add suffix for file list view and file detail view
- Add test for checked out, unviewed, and dataverse files
- list view
- file detail view
- None
- We show both versions as separate files in the file list view, so I've added some text to distinguish which one is the published version
[ENG-3879]: https://openscience.atlassian.net/browse/ENG-3879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3879] Show dataverse specific info

- lib/registries/addon/components/hero-overlay/styles.scss
Reverts CenterForOpenScience/ember-osf-web#1568
Relevant flowdock conversation here: https://www.flowdock.com/app/cos/embosf/threads/L1C4u55cVmIEYH_TBhClo33qRfo
Key takeaway: removing the opacity from the overlay hid the banner image below it. Extra work would have been needed to balance out background image, brand color, registration title, etc
> Revert "[ENG-3748] Remove opacity filter from branded providers"

- lib/osf-components/addon/components/file-browser/add-new/create-folder-modal/template.hbs
- lib/osf-components/addon/components/file-browser/file-rename-modal/component.ts
- lib/osf-components/addon/components/file-browser/file-rename-modal/template.hbs
- tests/integration/components/file-browser/component-test.ts
- tests/integration/components/file-browser/file-rename-modal/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3917]
- Fix bugs with rename file and create folder modals when users hit "Enter" key to submit
- Add missing translation key
- Only submit name change/new folder when users hit "Enter" for these modals
- Add missing translation key
- NA
- NA
- Rename modal with no text/whitespace only has been fixed as well
[ENG-3917]: https://openscience.atlassian.net/browse/ENG-3917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3917] Create folder/rename file bugs

- translations/en-us.yml
When first creating a Resource, the back end send us a resource with a type of Undefined. The user has to choose a non-undefined type. There was no translation string for this case, so this PR adds that translation string.
1. Add translation string
Buggy state:
Mockups:
> Add translation string for case of undefined resource type

- lib/osf-components/addon/components/resources-list/edit-resource/component.ts
- lib/osf-components/addon/components/resources-list/edit-resource/styles.scss
- lib/osf-components/addon/components/resources-list/edit-resource/template.hbs
-   Ticket: [Notion](https://www.notion.so/cos/Add-edit-dialog-needs-a-width-c851803fa9f146bea3282f5c86b39b46)
Added a width to the edit dialog box
1. Add local class
2. Add width to style of local-class
3. Add mobile checking and styling
Before:
After:
Nope
> Add width to edit dialog

- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
- lib/osf-components/addon/components/osf-dialog/styles.scss
- lib/osf-components/addon/components/resources-list/edit-resource/template.hbs
-   Ticket: [ENG-3943]
- Revert z-index of dialog backgrounds to prevent bad behaviors associated with dropdowns in modal windows
- We bumped the z-index up due to some issues with mobile view for Files Page Phase II in this PR here: https://github.com/CenterForOpenScience/ember-osf-web/pull/1529 to address the problem found here: https://www.notion.so/cos/Files-Page-Phase-II-Bugs-Found-2daf0384e75f43c18bef48c60e4b58be#02af2801c0f243b99b4c8be9ab0aef28
- Prevent issue where opening the "Resource Type" dropdown using the 🔽 down caret would immediately close the dropdown options
- Revert z-index for dialog background to 900
- Close dropdown when selecting a file/folder action to prevent them from showing up simultaneously and obscuring each other
Prevents dropdown …
> [ENG-3943] Revert dialog z-index and change file-action behavior

- lib/osf-components/addon/components/resources-list/edit-resource/component.ts
-   Ticket: [Notion ticket](https://www.notion.so/cos/Duplicate-Resource-gives-a-vague-error-44852f675d9a415caf50244ff51b6513)
When the API returns an error from finalizing the resource, we should show that error, so people know what went wrong.
1. Show error message on finalize
> Show API error on finalize

- tests/integration/components/resources-list/delete-resource/component-test.ts
I think the DeleteButton PR was not up to date with feature/output-reporting before merge, which caused one of the tests to break. Jenkins caught it. This fixes the test.
1. Fix broken test
> Fix broken deletebutton test

- lib/osf-components/addon/components/resources-list/edit-resource/component.ts
- lib/osf-components/addon/components/resources-list/edit-resource/template.hbs
- lib/osf-components/addon/components/resources-list/resource-card/template.hbs
- lib/osf-components/addon/components/resources-list/template.hbs
- tests/integration/components/resources-list/edit-resource/component-test.ts
- translations/en-us.yml
-   Ticket: []
- Address issues found with Add/Edit Resource modal
- unfinalized resources weren't being deleted properly
- User changes were persisting in an unintuitive way when editing an existing resource 
- Remove "Preview" functionality when editing existing resource
- Delete unfinalized resource when adding a new resource
- Change modal header if adding or editing resource
- Update tests
- Editing existing resource now shows "Save" instead of "Preview" (Adding new one is unchanged). Modal header is also changed to "Edit resource"
- Users won't be able to preview the changes made to an existing resource, but they can just edit it again :/
> Add resource bugfixes

- lib/registries/addon/components/registries-search-result/template.hbs
- lib/registries/addon/services/share-search.ts
- tests/engines/registries/unit/services/share-search-test.ts
rename `open_badges` to `related_resource_types`, aligning with:
https://github.com/CenterForOpenScience/SHARE/pull/793
https://github.com/CenterForOpenScience/osf.io/pull/10004
-   Ticket: [ENG-3905]
[ENG-3905]: https://openscience.atlassian.net/browse/ENG-3905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3905] rename open_badges to related_resource_types

- mirage/views/share-search.ts
-   Ticket: n/a
When https://github.com/CenterForOpenScience/ember-osf-web/pull/1603 was merged, it didn't quite have everything it needed, and while things work great on staging, they didn't work in mirage. This corrects that.
1. Update mirage view for SHARE search results
Nope.
No QA necessary for this one; it's entirely developer-facing.
> Fix SHARE search results in mirage view

- lib/osf-components/addon/components/form-controls/power-select/template.hbs
-   Ticket: []
- Remove unnecessary aria-label
- Remove redundant aria-label
- This aria-label was actually bad if we had placeholder text for when a selection's value was 'undefined'. The screenreader would say "Undefined" instead of the placeholder text
- NA
- I don't think there should be  any. If there are other cases of placeholder text used when a dropdown's value is undefined, this should fix that as well.
> Remove overzealous aria-label

- app/models/registration.ts
- lib/osf-components/addon/components/node-card/template.hbs
- lib/registries/addon/overview/template.hbs
- tests/engines/registries/acceptance/overview/index-test.ts
- tests/integration/components/node-card/component-test.ts
-   Ticket: [[Notion card]](https://www.notion.so/cos/Remove-Front-end-option-to-add-Resource-for-certain-registration-states-9780597577c7436e91b83b345aff6841)
- Prevent users from adding resources when not appropriate
- Prevent showing resource badges if users cannot add resources
- Update Overview leftnav to hide resources if the registration is not accepted by admins or moderators
- Update node-card to hide resource badges if registration is not accepted by admins or moderators
- Update tests
- Node cards
None
- If an admin/write user manually enters the overview/resources page manually, it will still look like they can add a resource, but the resource they add there won't persist and behave strangely
> Hide resource badges for certain registration states

- lib/osf-components/addon/components/resources-list/styles.scss
- lib/osf-components/addon/components/resources-list/template.hbs
-   Ticket: [Notion ticket](https://www.notion.so/cos/Add-White-Space-c07d80684c634b619167679de22e84d5)
- Add margin to add resource heading
- Add 10px margin-bottom to the section explaining how to add new resource
- Rename class to not be misleading
- Before
- After
> Add margin-bottom to resource heading

- lib/registries/addon/components/registries-search-result/template.hbs
- lib/registries/addon/services/share-search.ts
- mirage/views/share-search.ts
- tests/engines/registries/unit/services/share-search-test.ts
-   Ticket: [Notion bug](https://www.notion.so/cos/Link-to-resources-from-SHARE-is-using-the-wrong-ID-741b68ff3a1c4ce5891cd8fbc24ee750)
Links to the resource page were broken because the ID I was using from SHARE to point to a guid-based route was not a GUID. This takes advantage of a new field returned from SHARE that gives us the guid, in the case of OSF-based results. **Note:** ~~We want to avoid merging this until we do a reindex of SHARE, because if not, registrations that have resources but have not been updated since this morning will break the search page.~~ I think SHARE is reindexed on staging2 by now.
1. Add new property to SHARE results 
2. Have main link to registration overview page in SHARE results link using the new property in case of OSF-based registrations
3. Have …
> Allow search results from OSF to use routed links

- lib/osf-components/addon/components/node-card/styles.scss
-   Ticket: [notion card](https://www.notion.so/cos/Registration-badges-go-off-the-card-in-mobile-view-1a85009ebe1b4fde9e2d0747a8ef2e99)
- Fix some mobile view issues with node cards
- Remove padding for mobile view node-card badges list
prevents this issue
> Remove badges list padding for mobile view

- lib/osf-components/addon/components/resources-list/edit-resource/component.ts
- mirage/views/resource.ts
- translations/en-us.yml
-   Ticket: [notion ticket](https://www.notion.so/cos/Misleading-error-message-when-updating-a-resource-e01b8a4f655e40c796116fb2587e614f)
- Give better error messaging for DOIs conflicts
- Check error source  on error and change error message accordingly
> Resource error handling

- lib/registries/addon/overview/controller.ts
-   Ticket: [Notion](https://www.notion.so/cos/Badge-and-Labels-are-Oddly-Aligned-b6c1ffe18826470da119945092177d12)
Make the node cards on the components tab of the registries overview look better by removing the right panel and giving the cards more room to breathe.
1. Remove metadata panel on registries components page.
No, this is isolated.
> Remove metadata panel on registries components page

- lib/osf-components/addon/components/resources-list/styles.scss
- lib/osf-components/addon/components/resources-list/template.hbs
- tests/integration/components/resources-list/component-test.ts
- translations/en-us.yml
-   Ticket: []
- Add link to help guides for resources
- Add new link in the top of resources page
- Add new translation
- TODO: add this link to the leftnav when it is ready
- The helpdocs don't have a section for resources yet, but should before this feature is released
> Add link to help docs

- lib/osf-components/addon/components/resources-list/edit-resource/template.hbs
-   Ticket: [Notion card](https://www.notion.so/cos/Disable-add-edit-buttons-when-saving-e8a2ace5fdaa4cc6b650e80e9dc4fe7f)
- Disable Preview and Save buttons while those tasks are running
- Show loading indicator while those tasks are running
- Basically exactly what was mentioned above
> Disable buttons while tasks are running

- lib/osf-components/addon/components/resources-list/resource-card/template.hbs
- tests/integration/components/resources-list/resource-card/component-test.ts
-   Ticket: [Notion](https://www.notion.so/cos/Links-to-doi-org-when-viewing-on-an-AVOL-5af01ba377344b368903114ef89eae02)
For some reason, the anonymized view link wasn't causing us to hide the PID link (I suspect because the meta tag is part of the list and not the individual items of the list, but I didn't look that closely into it). This changes the test to something more direct, so that if the pid value is missing, it won't try to render the link.
1. Use pid value for checking whether to render PID link
2. Update test
> Fix AVOL view

- lib/osf-components/addon/components/resources-list/edit-resource/styles.scss
- lib/osf-components/addon/components/resources-list/edit-resource/template.hbs
- lib/osf-components/addon/components/resources-list/resource-card/styles.scss
- lib/osf-components/addon/components/resources-list/resource-card/template.hbs
- lib/osf-components/addon/components/resources-list/styles.scss
- lib/osf-components/addon/components/resources-list/template.hbs
-   Ticket: []
- Fix tab order in editable resource card
- Remove `<li>` from ResourceCard component, so we don't have a `<li>` that's not wrapped in a `<ul>`
- Wrap edit and delete button in a div, change their order
- Move `<li>` wrapper from ResourceCard component to ResourcesList
- No visible changes
- none
- Tab order should be "as expected" now, and shouldn't have an a11y issue in the Add Resource modal
> A11y fixes

- lib/osf-components/addon/components/resources-list/resource-card/styles.scss
- lib/osf-components/addon/components/resources-list/resource-card/template.hbs
-   Ticket: [Notion card](https://www.notion.so/cos/Resource-Card-Move-Edit-and-Delete-resource-buttons-to-same-line-as-resource-type-2a60928d5aa040b6a92520a872ccf678)
- Prevent unexpected whitespace of resource cards in mobile view
- Move edit/delete buttons in resource card to same line as resource type
Before:
After:
> Move edit/delete buttons in resource card

- lib/osf-components/addon/components/open-resource/styles.scss
-   Ticket: [Notion](https://www.notion.so/cos/Adjust-font-weight-of-left-nav-resources-text-to-match-the-node-card-resources-list-645d7c3035e44e58bd4c0089af21a381)
Make the font weight of the leftnav resource icons match the font weight of the other resource icons.
1. Remove font-weight line from css
New leftnav:
Existing My Registrations page:
> Match font weight on resource icons

- lib/osf-components/addon/components/resources-list/template.hbs
-   Ticket: [notion card](https://www.notion.so/cos/Help-link-open-help-doc-in-new-tab-d303461852f6479e97b6b82d73aca5c6)
- Open registration resources help link in a new tab
> Open resource help link in new tab

- lib/osf-components/addon/components/new-feature-popover/component.ts
- lib/osf-components/addon/components/new-feature-popover/template.hbs
- lib/osf-components/addon/modifiers/on-click-outside.ts
- lib/osf-components/app/modifiers/on-click-outside.js
-   Ticket: []
Clicking outside the feature popover footer section should close the popover.
Added a `on-click-ouside` modifier to handle click outside behavior.
> Click outside feature popover closes the popover

- lib/osf-components/addon/components/resources-list/edit-resource/styles.scss
- lib/osf-components/addon/components/resources-list/edit-resource/template.hbs
-   Ticket: [Notion card](https://www.notion.so/cos/Add-whitespace-between-Resource-type-and-description-in-Add-Edit-resource-modal-3b5c5ad4640e436fa1478c3dae9ecf4a)
- Add some whitespace above the "Description" in the add/edit resource modal
- Add class to modal description
- before screenshot in the notion card
- After
> Add whitespace above description

- lib/osf-components/addon/components/resources-list/resource-card/template.hbs
- lib/registries/addon/overview/template.hbs
-   Tickets: 
- [Notion ticket 1](https://www.notion.so/cos/Open-Check-DOI-for-accuracy-in-a-new-tab-8a682761e99a48f090704472360294a7)
- [Notion ticket 2](https://www.notion.so/cos/Have-in-leftnav-go-to-help-guides-in-a-new-tab-fd5aee5565ef400ebfe41556c6f881f7)
Open some links in a new tab. *Note*: Links to help docs are still temporary and need replacing before deploying.
1. Add link to help docs to the leftnav question mark icon
2. Make link to DOI in the add modal's preview open the doi in a new tab
> Open links in a new tab

- lib/osf-components/addon/components/validated-input/text/styles.scss
- lib/osf-components/addon/components/validated-input/text/template.hbs
-   Ticket: [Notion card](https://www.notion.so/cos/Add-Edit-resource-on-small-screens-b4ce82cc55914699966f7ee89b61aa21)
- Prevent text-wrap of "doi.org" prefix
- Change styling of uneditable prefix to make it more clear that it is not an editable part of the text-input
- CSS changes
- Prior on Galaxy S8+:
- After on Galaxy S8+:
- After desktop:
- ~~The right border is not fully visible on small screens...~~
> Prevent doi prefix text-wrap. Change prefix background color

- lib/registries/addon/overview/controller.ts
- lib/registries/addon/overview/template.hbs
-   Ticket: [Notion](https://www.notion.so/cos/Hide-New-feature-popover-on-mobile-7443be0a51bb4fe2b7870bc9e5499589)
Hide the New Feature Popover when in tablet or mobile view, since that's when the leftnav will be potentially hidden, so the popover would otherwise point at nothing.
I tried to do this using the popover's `shouldShow` getter, but it resulted in erratic behavior. Basically, it would work if you started in mobile view, but if you went from desktop to mobile view, it would still show the popover. Also, I didn't want to put the logic on the popover itself since, in this particular instance, we're hiding it for both tablet and mobile view, not just mobile view, and that won't always necessarily be true for the popover.
One oddity with this implementation is that if you close the …
> Don't show popover when not showing leftnav

- lib/registries/addon/overview/template.hbs
-   Ticket: [Notion](https://www.notion.so/cos/Replace-help-guide-link-with-real-link-in-leftnav-a8c9ed25146548e99ac48b0ff6d7fd57)
We just got the link for the leftnav help, so this replaces the old, placeholder link with the new one. Note: the link will not be live yet, it's in preview-only for now.
1. Use new link
> Use correct link for leftnav help

- lib/osf-components/addon/components/resources-list/template.hbs
-   Ticket: [Notion card](https://www.notion.so/cos/Hide-Add-resource-button-for-pending-registrations-fb4c68591c814f439098a076949ff62c)
- Hide the Add Resource button if the registration is not in a state that can accept resources, as the modal behaves a bit erratically when the registration is in that state (ie: can't select a resource type)
- Update condition to show add button
Registration pending moderation when a user manually goes to the resources page:
None
Users _shouldn't_ be going to the resources page (resource link hidden in the leftnav) when a registration is pending admin/moderator approval, but some people (like me) might manually go to the resources page and get confused when they see that big green button
> [No ticket] Hide add-resource button if resources are not visible

- lib/osf-components/addon/components/resources-list/edit-resource/component.ts
- translations/en-us.yml
-   Ticket: []
- Give indication that the DOI validation fails
- Add toast behavior if the error returned from API is not a 400
> Add error toast if DOI validation fails

- lib/registries/addon/discover/controller.ts
-   Ticket: [ENG-2293]
Don't try to filter on subjects. It's not fully implemented, so it causes a particular bug when the query parameter is in the url. This is a minimal-change fix to this to keep the search page from being stuck on zero search results, rather than finishing out the feature or deleting it entirely.
1. Remove the subjects filter from the list of filters. (h/t @futa-ikeda)
Before:
After:
Won't be able to filter on subjects, but we couldn't before, so… no?
[ENG-2293]: https://openscience.atlassian.net/browse/ENG-2293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-2293] Don't try to filter on subjects

- lib/osf-components/addon/components/node-doi/template.hbs
-   Ticket: [ENG-1119]
Instead of showing just the DOI for registration DOIs, show the full URL. Note: There's an alternative approach to this where we have the [backend return to us the full URI](https://github.com/CenterForOpenScience/osf.io/pull/9825). Once that's in, if we want we can alter the computed property that this uses to just grab the value of the full URI instead, so this is a good intermediate step to the backend changing.
1. Use the doi url property instead of the doi property
No, this is isolated
[ENG-1119]: https://openscience.atlassian.net/browse/ENG-1119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-1119] Show full doi url for registration doi

- app/transforms/node-license.ts
-   Ticket: [ENG-2792]
- Fix special characters (`&`, `>` and `<`) in node-license copyright holder field
- Wrap copyright holder in `fixSpecialChars` in the `node-license` transform
- After loading a draft registration that had a special character in the copyright holder field:
- None
- The copyright holder in the API will still have special characters encoded as `&amp;`, `&gt;`, and `&lt;`. 
[ENG-2792]: https://openscience.atlassian.net/browse/ENG-2792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-2792] Fix special chars in node license copyright holder

- lib/registries/addon/components/hero-overlay/styles.scss
-   Ticket: [ENG-3748]
- Remove some of the complexities around how we use brand colors and images in the registries header
- Remove the logic pertaining to how we show brand color/images on the registries header, so the only thing shown in the header will just be the brand's hero image 
- Accessibility/color contrast on branded registry pages is gonna be a little whacky until we change the brand assets to a more appropriate color
- A lot of the external registries will look funny until their brand assets are updated, so I imagine most registries won't look good until those images are updated
- Before (Solid brand primary color background with 40% opacity and greyscaled image on top) :
- After (Just the image, no greyscale or opacity) :
- Community-operated …
> [ENG-3748] Simplify branded reg pages to just use brand background img

- lib/analytics-page/addon/application/styles.scss
The modal for the links on the project analytics page doesn't scroll. Instead, it just runs off the screen if there's too much content, and that content will never be seen. This makes it so that the dialog box behaves properly with the scrolling and the not overfilling the screen.
1. Add max-height to the modal
2. Set overflow to scroll
If there were any other `bs-modal-simple`s on the page, they would also be upgraded. But there aren't, so this is isolated.
> Make dialog box scroll on overflow

- app/guid-file/styles.scss
-   Ticket: [ENG-4033]
Fixed the text from being cut off. It was a side-effect of the "overflow: hidden" attribute
Add a height: 40px attribute to the class
Make sure the text is no cropped.
[ENG-4033]: https://openscience.atlassian.net/browse/ENG-4033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4033] Bottom of hanging letters cut off on file detail page

- lib/registries/addon/overview/-components/overview-header/template.hbs
-   Ticket: [ENG-4014]
The fontawesome upgrade requires no positional arguments for FaIcon. I thought I had caught all of them, but at least one set got past me.
1. Fix icons for registries leftnav show/hide in mobile view
No, this is isolated
[ENG-4014]: https://openscience.atlassian.net/browse/ENG-4014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4014] Fix icons for registries leftnav show/hide in mobile view

- lib/osf-components/addon/components/contributors/card/editable/template.hbs
- lib/osf-components/addon/modifiers/before-unload.ts
- lib/osf-components/app/modifiers/before-unload.js
- lib/registries/addon/drafts/draft/-components/right-nav/template.hbs
- lib/registries/addon/drafts/draft/controller.ts
- lib/registries/addon/drafts/draft/draft-registration-manager.ts
- lib/registries/addon/drafts/draft/route.ts
- lib/registries/addon/drafts/draft/template.hbs
- lib/registries/addon/edit-revision/-components/right-nav/template.hbs
- lib/registries/addon/edit-revision/controller.ts
- lib/registries/addon/edit-revision/revision-manager.ts
- lib/registries/addon/edit-revision/route.ts
- lib/registries/addon/edit-revision/template.hbs
- tests/engines/registries/acceptance/draft/draft-test.ts
- tests/engines/registries/acceptance/edit-revision/revision-test.ts
- tests/integration/modifiers/before-unload-test.ts
- translations/en-us.yml
-   Ticket: [ENG-1641]
- Let users know they have unsaved changes before they exit the draft registration workflow
- Let users know when an autosave is in progress
- Change some of the links on the Draft Registration Metadata page to open in a new tab to prevent users from navigating away
- Add a new `{{before-unload}}` modifier
- Add logic to show popup if the draft has pending changes
- One to handle `onBeforeUnload` (closing or refreshing the browser window)
- One to handle route transitions (clicking the "Add new"/"My Registrations" buttons or navigating away within the app)
- Add same logic for edit-revision workflow
- Update rightnav template to show when an autosave is in progress
- Edit revision workflow. When navigating away within 3 seconds of updating the …
> [ENG-1641] Draft registration save before exit

- lib/analytics-page/addon/application/styles.scss
- lib/analytics-page/addon/application/template.hbs
Fixed the CSS for cutting off a button on the mobile view on the Project Analytics Page > Linked Projects
-   Ticket: [ENG-4051]
-   Feature flag: No
Fixed the CSS for cutting off a button on the mobile view on the Project Analytics Page > Linked Projects
Updated the analytics-page/andon/application/template.hbs to be the same dom structure and css.
Updated the analytics-page/andon/application/styles.scss to have a @media screen and (max-device-height: 500px) attribute to change the max-height, padding and margin-bottom.
Non-mobile view
Mobile View
041537.png)
A rouge phone with a super small screen?
The test requires to Projects with a file being shared between the two project.
On the `shared with` project do the following steps
1. Click on the project
2. Click on Analytics
3. Click on …
> [Eng-4051] Fixed the CSS for cutting off a button on the mobile view

- config/deprecation-workflow.js
- package.json
- tests/unit/instance-initializers/prerender-test.ts
- yarn.lock
-   Ticket: [ENG-4004]
Stop tripping the warning for ember.globals-resolver deprecation.
1. Stop using ember-cli-shims, which we don't _seem_ to need anymore.
2. Update the prerender instance initializer test to prevent a future problem when upgrading to 4.0 that wasn't caught by the deprecation.
ember-cli-shims has been removed and re-added before, and I'm not sure why it was re-added. But everything builds, and tests run, so as long as selenium and percy does fine, we're probably okay.
I don't have anything specific to look out for with this PR.
[ENG-4004]: https://openscience.atlassian.net/browse/ENG-4004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4004] Unsilence ember.globals-resolver deprecation

- app/instance-initializers/router.ts
- app/router.ts
- config/deprecation-workflow.js
- handbook-docs/troubleshooting/template.md
- tests/acceptance/resolve-guid-test.ts
- tests/engines/registries/integration/components/page-link/component-test.ts
- tests/engines/registries/integration/components/side-nav/component-test.ts
- tests/integration/components/ancestry-display/component-test.ts
- tests/integration/components/contributors/component-test.ts
- tests/integration/components/draft-registration-card/component-test.ts
- tests/integration/components/moderators/component-test.ts
- tests/integration/components/node-card/component-test.ts
- tests/integration/components/node-description/component-test.ts
- tests/integration/components/node-navbar/component-test.ts
- tests/integration/components/node-navbar/link/component-test.ts
- tests/integration/components/open-badges-list/component-test.ts
- tests/integration/components/osf-navbar/auth-dropdown/component-test.ts
- tests/integration/components/osf-navbar/component-test.ts
- tests/integration/components/registries-side-nav/component-test.ts
- tests/integration/components/registries/my-registrations-list/component-test.ts
- tests/integration/components/registries/registration-list/card/component-test.ts
- tests/integration/components/registries/registration-list/component-test.ts
- tests/integration/routes/institutions/dashboard/-components/institutional-users-list/component-test.ts
- tests/integration/routes/meetings/index/-components/meetings-list/component-test.ts
- tests/unit/instance-initializers/router-test.ts
- tests/unit/metric-adapters/keen-test.ts
-   Ticket: [ENG-4010]
- Address deprecation of router events found here: https://deprecations.emberjs.com/v3.x/#toc_deprecate-router-events
- Remove usage of `willTransition` and `didTransition` in the app router
- Remove usage of private router API from app router
- Move logic that was handled in aforementioned `willTransition`, `didTransition` and other private router API calls into a new app-instance initializer `router` (The name is sort of awful, so any alternative name suggestions would be much appreciated 😬 )
- Fetch server-side rendered page if a given waffle flag is not enabled
- Scroll to top on page change, except in cases of query-param only route changes
- NA
- None I think
- This PR impacts how our app handles route changes (including query param only …
> [ENG-4010] Address deprecated router event

- app/dashboard/controller.ts
- app/dashboard/styles.scss
- app/dashboard/template.hbs
- app/home/-components/support-section/styles.scss
- app/home/-components/support-section/template.hbs
- lib/osf-components/addon/components/osf-link/component.ts
- tests/integration/components/osf-link/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3995]
Add a video to the dashboard logged out page about how to use the OSF
Add the same video and a link to the "Getting Started" guide on the logged in dashboard page without a collection.
Updated to .hbs files
(s)
Falling asleep watching a one hour video without chapters.
See if the video loads and button works on the /dashboard and the video plays on the home page when not logged in.
[ENG-3995]: https://openscience.atlassian.net/browse/ENG-3995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3995] Embed OSF 101 video onto logged out homepage and no-content dashboard - Part 2

- app/models/custom-file-metadata-record.ts
- app/models/custom-item-metadata-record.ts
- app/models/custom-metadata.ts
- app/models/guid.ts
- tests/unit/models/custom-file-metadata-record-test.ts
- tests/unit/models/custom-item-metadata-record-test.ts
-   Ticket: [ENG-4156]
Add some models for the guid-metadata project.
1. Modify guid model to have a link to new metadata models
2. Add custom-file-metadata-record model
3. Add custom-item-metadata-record model
4. Add tests
No, this is additive.
Nothing for QA yet
[ENG-4156]: https://openscience.atlassian.net/browse/ENG-4156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4156] Add models for metadata

- app/adapters/moderator.ts
- lib/osf-components/addon/components/moderators/manager/component.ts
- lib/osf-components/addon/components/registries/overview-form-renderer/component.ts
- lib/registries/addon/overview/-components/overview-header/component.ts
- Fetch moderators for collections or registrations depending on the context
- Add an adapterOption to specify what type of provider the user is a moderator for
- NA
- NA
> [No ticket] Fetch moderators

- lib/osf-components/addon/components/collection-submission-card/styles.scss
- Prevent long titles from pushing the make-decision-dropdown outside of the collection-submission-card
- Add ellipsis text-truncation to title
- Before
Mobile:
Desktop:
- After
Mobile:
Desktop:
> [ENG-4196] Fix long titles in collection-submission-card

- lib/collections/addon/components/collection-item-picker/component.ts
- lib/collections/addon/components/collections-submission/component.ts
-   Ticket: [ENG-4224]
- Avoid API requests to `/v2/collections/ru4bv/collection_submissions/` with `filter[reviews_state]=a,b` as the API doesn't support this yet
- Split up requests to `/v2/collections/ru4bv/collection_submissions/` to limit `filter[reviews_state]` to just one review state at a time
- NA
- potentially slower to find nodes on the submit page, and slower to move to the next section after selecting node
[ENG-4224]: https://openscience.atlassian.net/browse/ENG-4224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Split reviews state requests into two

- lib/collections/addon/components/collections-submission/component.ts
-   Ticket: [ENG-4224]
- Align resubmit workflow with API
- POST a new collection-submission-action to resubmit on resubmit
- NA
[ENG-4224]: https://openscience.atlassian.net/browse/ENG-4224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4224] Resubmit actions

- lib/collections/addon/provider/moderation/moderators/controller.ts
- lib/collections/addon/provider/moderation/moderators/template.hbs
- lib/osf-components/addon/components/moderators/manager/component.ts
- lib/registries/addon/branded/moderation/moderators/controller.ts
- lib/registries/addon/branded/moderation/moderators/template.hbs
- Redirect users out of moderation app after they remove themselves as a moderator
- Add an optional `@afterSelfRemoval` argument to `Moderators::Manager` component to be called if you remove yourself as a moderator
NA
NA
- This is implemented for both collections and registries moderators
> Redirect out of moderation app after removing self as moderator

- app/models/provider.ts
- lib/collections/addon/provider/moderation/moderators/controller.ts
- lib/collections/addon/provider/moderation/moderators/template.hbs
- lib/osf-components/addon/components/moderators/manager/component.ts
- lib/registries/addon/branded/moderation/moderators/controller.ts
- lib/registries/addon/branded/moderation/moderators/template.hbs
- Hide "Moderation" button in navbar if you removed yourself as a moderator
- Reload provider after removing yourself as a moderator
- Make `currentUserCanReview` a computed property
NA
> [ENG-4196] Reload provider permissions after self-remove

- lib/collections/addon/provider/moderation/all/controller.ts
- lib/collections/addon/provider/moderation/all/styles.scss
- lib/collections/addon/provider/moderation/all/template.hbs
- lib/osf-components/addon/components/form-controls/power-select/template.hbs
- lib/osf-components/addon/components/form-controls/template.hbs
- lib/osf-components/addon/components/make-decision-dropdown/styles.scss
- lib/osf-components/addon/components/make-decision-dropdown/template.hbs
- lib/osf-components/addon/components/moderators/add-modal/styles.scss
- lib/osf-components/addon/components/moderators/add-modal/template.hbs
- translations/en-us.yml
- A11y fixes
- Use darker color for links and interactable elements
- Un-nest make-decision-dropdown's toggle button
- Add text-content to "Search user" dropdown when adding moderators by name
- Add moderator modal with accessible text for dropdown, and darker blue for "Search user by name" and "Invite user by email" panels
- All submissions state names are slightly darker
- Neigh, said the horse
- This should fix the same A11y issues on the registries moderation workflows for the "Make decision" dropdown, as well as the "Add moderator" modals
> [ENG-4196] A11y fixes for collection moderation

- lib/collections/addon/components/collections-submission/component.ts
- lib/collections/addon/components/collections-submission/template.hbs
- Hide option to `Remove` a submission in `osf.io/collections/providerId/submissionId/edit` if the submission is not accepted
- Only show "Remove" button if the submission is accepted
- This button should only be visible on a route like https://staging2.osf.io/collections/postmod/nhrqd/edit if the submission is public
- Currently we don't support users removing a submission if it is still pending. That workflow is something we will need to visit in a future improvement
> [ENG-4196] Hide remove button unless submission is accepted

- lib/app-components/addon/components/branded-navbar/styles.scss
- Lower the navbar's z-index to be below modals
- Override the `z-index: 1030` of BsNav class `.navbar-fixed-top` to be below `.ember-basic-dropdown-content` class's `z-index: 1000`
- Prevents:
- New:
> [ENG-4196] Lower navbar z-index below modals

- app/models/custom-metadata.ts
- lib/osf-components/addon/components/node-metadata-form/template.hbs
- lib/osf-components/addon/components/node-metadata-manager/component.ts
- tests/acceptance/guid-node/metadata-test.ts
- tests/engines/registries/acceptance/overview/metadata-test.ts
-   Ticket: [ENG-4223]
Test the NodeMetadataForm component and its corresponding manager component.
1. Add guid-node tests for everything
2. Add registries-overview tests for mainly making sure the subjects picker shows up
3. Disable save buttons when changeset isn't dirty
4. Limit display of long descriptions
5. Move contributors list up
6. Add more data-test selectors
7. Hide things in AVOLs
Tests take about six seconds longer to run.
[ENG-4223]: https://openscience.atlassian.net/browse/ENG-4223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4223] Test node-metadata-form

- app/router.ts
- tests/acceptance/resolve-guid-test.ts
-   Ticket: N/A
Design changes caused us to no longer need the metadata route under guid-file, so this pulls that out.
1. Remove route
2. Remove template
3. Fix tests
No
> Guid metadata/remove file metadata route

- lib/osf-components/addon/components/node-metadata-form/template.hbs
-   Ticket :n/a
Allow the subjects widget to save, rather than just sitting there looking pretty.
1. Enable autosave on subjects widget.
> Let subjects widget save

- app/guid-file/-components/file-detail-layout/styles.scss
- app/guid-file/-components/file-detail-layout/template.hbs
- app/guid-file/styles.scss
- app/guid-file/template.hbs
-   Ticket: https://openscience.atlassian.net/browse/ENG-4186
-   Feature flag: feature/file-metadata-detail-styling
The purpose of these changes is to update the styling of the files detail metadata section for the File Metadata project.
Changes include updating the form label <div> elements to the appropriate heading tag, updating the font weight and size, adding flex, and adding appropriate spacing between elements.
These changes affect the layout and sizing of the expandable panel on the right of the File Detail page. Alterations may result in text overflow, incorrect spacing for different size texts, and button formatting. Testing should include browser compatibility as well as mobile formatting.
-Are the elements appropriately spaced?
-Are duplicate elements present?
-Do all buttons …
> [ENG-4186] Add styling to file detail page view section

- lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
-   Ticket: [ENG-4266]
- Address a11y issue in navbar's auth dropdown
- Move `role='menuitem'` to direct descendant of `role='menu'`
- Use vanilla `<li>` instead of `<DropdownMenu.item>` as `<ddm.item>` doesn't has splattributes
- check the `role`s of the `<ul>` and `<li>`s
[ENG-4266]: https://openscience.atlassian.net/browse/ENG-4266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4266] Add menuitem role to dropdown direct descendants

- app/guid-file/template.hbs
- app/guid-node/styles.scss
- lib/osf-components/addon/components/file-metadata-manager/component.ts
- lib/osf-components/addon/components/file-metadata-manager/template.hbs
- lib/osf-components/addon/components/node-metadata-form/template.hbs
- lib/osf-components/addon/components/node-metadata-manager/component.ts
- mirage/scenarios/dashboard.ts
- tests/acceptance/guid-node/metadata-test.ts
Fix and improve a few small things.
1. Add search to power select for languages on files and nodes
2. Show the language name on the files node metadata section
3. Remove duplicate 'display' property on CSS for node hero
4. Properly detect if a node is a component or not
5. Hide appropriate info on file display for AVOLs
6. Add a component to the default mirage scenario for the dashboard
The node title is centered in the hero now like it is on registries rather than being pulled to the left.
Language selection should be easier now. If you're on a file that's on a component of a project, it should say that the node's metadata is "Component metadata" rather than "Project metadata" or "Registration metadata".
> Guid metadata/misc updates

- app/guid-file/template.hbs
Certain fields of the metadata shouldn't be accessible while viewing with an AVOL. Rather than complicating server-side logic, let's hide the download button if viewing through an AVOL.
1. Hide download button for AVOLs
> Guid-Metadata / Hide download button in AVOL

- lib/osf-components/addon/components/node-metadata-form/styles.scss
On staging, not local (or maybe on Safari, not Chrome), the metadata container was being constrained to be smaller than it needed to be. This corrects that problem.
1. Remove what seemed to be an unnecessary display directive
Before:
After:
> Guid-Metadata / Unconstrain metadata container

- lib/osf-components/addon/components/file-metadata-manager/component.ts
Make AVOLs behave on file detail page
1. Use `apiMeta.anonymous`, which should exist, instead of `apiMeta.isAnonymous`, which doesn't
> Guid-Metadata / Use proper property for anonymous views

- app/guid-file/template.hbs
- lib/osf-components/addon/components/file-metadata-manager/component.ts
- lib/osf-components/addon/components/file-metadata-manager/template.hbs
In anticipation of the backend having download capabilities for metadata, add the download link to the download button on the files page.
1. Create a link builder
2. Add link getter to manager
3. Add link to download button
Make sure this works properly with non-anonymous VOLs on a private project.
> Guid-Metadata / Add metadata download link to file detail page

- app/guid-file/styles.scss
- app/guid-file/template.hbs
- lib/osf-components/addon/components/file-metadata-manager/component.ts
- lib/osf-components/addon/components/node-metadata-form/template.hbs
- mirage/scenarios/dashboard.ts
- translations/en-us.yml
Fix some a11y problems and some potential a11y problems. Note: There was a weird merge conflict, so hopefully I put everything back right? The diff isn't looking exactly right though, so I'm a bit concerned.
1. Move contributors outside of data-list and make the h3 heading match the dt styling
2. Put placeholders on the power selects (note: this will only affect the resource type widget until we upgrade ember power select)
3. Hide fields in a data list unless they will be filled out with information to prevent having a dt without a dd
4. Add in mirage contributors to the file5 node for better testing
No metadata, write access:
No metadata, no write access:
Some metadata:
New contributors placement:
I didn't do anything to explicitly fix the contributor contrast, but I wasn't getting the …
> Guid metadata/file a11y fixes 1

- lib/osf-components/addon/components/funding-metadata/template.hbs
- lib/osf-components/addon/components/node-metadata-form/styles.scss
- lib/osf-components/addon/components/node-metadata-form/template.hbs
- translations/en-us.yml
Fix a number of small issues including accessibility problems.
1. Rename funding widget's buttons to be a bit clearer
2. Ensure funding widget header remains when editing funding info
3. Add placeholder onto resource type power select
4. Fix accessibility on funding display to not have a dt without a dd
5. Add more space between funding widget and subjects widget
As with files, the two search power select widgets will still fail accessibility and will be hopefully fixed shortly after release.
> Guid metadata/node a11y fixes

- lib/osf-components/addon/components/funding-metadata/component.ts
Registration approval stopped working because of the problem described by [this sentry error](https://staging-sentry.cos.io/cos/osf-back-end-77/issues/15597/).
> 'Crossref Funder URI' is not one of ['ISNI', 'GRID', 'Crossref Funder ID', 'ROR', 'Other'] Failed validating 'enum' in schema['properties']['fundingReferences']['items']['properties']['funderIdentifierType']: {'enum': ['ISNI', 'GRID', 'Crossref Funder ID', 'ROR', 'Other'], 'type': 'string'} On instance['fundingReferences'][0]['funderIdentifierType']: 'Crossref Funder URI'
1. Change `Crossref Funder URI` to `Crossref Funder ID`
> Guid metadata / Fix registration approval

- app/guid-file/styles.scss
- app/guid-file/template.hbs
- app/guid-node/styles.scss
- app/guid-node/template.hbs
- lib/osf-components/addon/components/file-metadata-manager/component.ts
- lib/osf-components/addon/components/node-metadata-form/template.hbs
- lib/osf-components/addon/components/node-metadata-manager/component.ts
- lib/osf-components/addon/components/node-metadata-manager/template.hbs
- mirage/scenarios/dashboard.ts
- translations/en-us.yml
A smorgasbord of fixes for guid-metadata.
1. Put some space between contributors and the footer on the guid-file page
2. Add expandable previews to descriptions on guid-file page
3. Fix institutions on guid-file page
4. Make mobile nav toggle left aligned rather than center aligned
5. Add license and institutions to node metadata component
6. Give file5 in mirage some institutions
> guid metadata / Fix a bunch of things found during QA

- app/guid-file/template.hbs
-   Ticket: [ENG-4311]
There was a bug preventing metadata from displaying for files on providers that have neither tags nor revisions. This fixes that.
1. Move the metadata outside of the if statement
[ENG-4311]: https://openscience.atlassian.net/browse/ENG-4311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4311] Hotfix: Display metadata even if no tags or revisions

- lib/collections/addon/provider/moderation/all/styles.scss
- lib/collections/addon/provider/moderation/all/template.hbs
-   Ticket: [ENG-4318]
- Address a visual bug in mobile view for collection moderation's submission view
- Move sorting dropdown to next line for mobile view
- Before:
- After:
- None
- The dropdown should only be moved for mobile view and should no longer be obscured as it was before
[ENG-4318]: https://openscience.atlassian.net/browse/ENG-4318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4318] Move sorting dropdown on mobile

- app/guid-file/styles.scss
- app/guid-file/template.hbs
- config/environment.d.ts
- config/environment.js
- lib/osf-components/addon/components/funding-metadata/template.hbs
- lib/osf-components/addon/components/node-metadata-form/styles.scss
- lib/osf-components/addon/components/node-metadata-form/template.hbs
- lib/registries/addon/overview/controller.ts
- lib/registries/addon/overview/template.hbs
- mirage/factories/draft-node.ts
- mirage/factories/node.ts
- mirage/factories/registration.ts
- package.json
- translations/en-us.yml
- yarn.lock
Tickets:
- [ENG-4307]
- [ENG-4309]
There were three power select widgets that didn't have placeholders, because their selections were objects rather than a simple type, so it couldn't tell when the object was empty. 
Also, this moves the new feature popover to the metadata tab.
1. Upgrade ember-power-select to 4.1.7
2. Add manual placeholders to power select widgets
3. Stop using random numbers for count of files created by mirage, because that caused different nodes to have different file guids associated with them every time you reloaded the page, so it was impossible to consistently know what permissions any given file was going to have or even if a given file guid was going to exist or not.
4. Generalize the new feature popover and move it to the metadata tab
Shouldn't be. I didn't do …
> [ENG-4307][ENG-4309] Add placeholders to power selects

- app/guid-file/styles.scss
- app/guid-file/template.hbs
- app/router.ts
- lib/osf-components/addon/components/node-metadata-form/styles.scss
- lib/osf-components/addon/components/node-metadata-form/template.hbs
- lib/osf-components/addon/components/registries/version-metadata/styles.scss
- tests/acceptance/resolve-guid-test.ts
-   Ticket: https://openscience.atlassian.net/browse/ENG-4312
The purpose of these changes is to fix any remaining visual changes affected by the Files Metadata project following post-release.
Issue 1: File Name is cut off for lower case (descending) letters. Add a `padding-bottom: 5px;` to the h3 that holds the title to fix. 
-> Padding has been added to the h3 title.
Issue 2: Fade clip for very long text area descriptions. Take off the 5px margin to the div that holds the description to fix (or possibly change the 5px margin added to all divs into padding instead)
-> Margin has been set to 0 for the div nested in the edit metadata description text area.
Issue 3. Resource Dropdowns overflow in mobile view
-> Issues were not reproducible when testing on Edge and …
> [ENG-4312] Visual fixes for Guid Metadata

- app/models/user-registration.ts
- config/deprecation-workflow.js
-   Ticket: [ENG-4009]
- Remove [deprecated volatile computed properties](https://deprecations.emberjs.com/v3.x/#toc_computed-property-volatile) 
- Change how we fetch the `existingEmails` and `invalidEmails` when validating a new user registration
- when visiting `osf.io/register` and trying to sign up with an email already in use by another user
- There should be no side-effects
- Please verify that the register page works properly and users get a meaningful message when they try to sign up using an email that is already in use by another account, and also when they try to use an email domain that is forbidden (`danger@forbiddendomain.com`)
[ENG-4009]: https://openscience.atlassian.net/browse/ENG-4009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> [ENG-4009] Remove use of volatile computed property

- app/guid-file/template.hbs
- tests/acceptance/guid-file/registration-file-detail-test.ts
-   Ticket: https://openscience.atlassian.net/browse/ENG-4187
-   Branch: feature/file-metadata-mirage-tests
The purpose of these changes is to add tests to ember-osf-web for the File Metadata project.
Tests were added to the registration-file-detail-test.ts file to verify the functionality of metadata label and div elements, the edit metadata form and its save and cancel buttons, and the mobile default view for the application.
There should be no unintended side effects.
-This PR references the following PRs that were revised: https://github.com/CenterForOpenScience/ember-osf-web/pull/1756 && https://github.com/CenterForOpenScience/ember-osf-web/pull/1793. Any changes reflected here should also include changes referenced in them.
-Are all added components and functionalities properly …
> [ENG-4187] Test file detail view section - Updated

- config/environment.js
Make metrics track GA events again. I removed the keen metrics adapter from the codebase, but it's still being called by the configuration, which is probably the thing breaking the metrics service right now.
1. Removed unused and now missing keen adapter from configuration
> Remove keen config from metrics

- lib/osf-components/addon/components/funding-metadata/styles.scss
- lib/osf-components/addon/components/funding-metadata/template.hbs
- lib/osf-components/addon/components/node-metadata-form/styles.scss
- lib/osf-components/addon/components/node-metadata-form/template.hbs
There were a couple of places that needed more padding for the basket/tin release
1. Add padding to the bottom of the funder widget
2. Add padding to the bottom of the institutions select list
> Add some padding

- app/guid-file/template.hbs
- lib/osf-components/addon/components/file-metadata-manager/component.ts
- tests/acceptance/guid-file/registration-file-detail-test.ts
-   Ticket: https://openscience.atlassian.net/browse/ENG-4333
-   Branch: feature/test-file-detail-view-only
The purpose of these changes is to test the edit functionality of the file detail page.
-A test has been added to verify that changing the values and saving will result in appropriate changes in the view-only section for the file title, description, resource type, and resource language.
-A test has been added to verify that changing those fields and canceling the edit will result in the values not changing in the view-only section.
-A test has been added to verify that trying to save, getting an error, and canceling the save causes the values not to change for the view-only section.
- A test has been added to verify that, if you don’t have permission to edit, the edit capability is …
> [ENG-4333] Test file detail editing

- app/dashboard/template.hbs
- app/home/-components/support-section/template.hbs
-   Ticket: [ENG-4361]
- Update links to OSF 101 video
- Changed existing links to OSF 101 videos
for logged out homepage, this video should be the new one:
NA
Please verify that the users are taken to the new video when they are not logged in on the homepage, or when they are logged in but have no projects. [New video here](https://www.youtube.com/watch?v=X07mBq2tnMg)
[ENG-4361]: https://openscience.atlassian.net/browse/ENG-4361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4361] Update youtube link for OSF 101 video

- lib/collections/addon/components/discover-page/component.ts
- lib/collections/addon/components/discover-page/template.hbs
-   Ticket: []
- Fix scroll-to-top behavior when changing pages on collection discover page
- Moved `.results-top` to a different element as navbar's positioning covers up the first search result's title
- Use vanilla js `Element.scrollIntoView` instead of jquery
NA
None
Page should scroll to the top of the first search result when changing pages on pages like https://staging2.osf.io/collections/colmod/discover?page=2
> Fix page-change scroll behavior

- lib/registries/addon/components/registries-metadata/template.hbs
- lib/registries/addon/components/registries-states/component.ts
- lib/registries/addon/overview/-components/overview-topbar/template.hbs
- tests/engines/registries/acceptance/overview/topbar-test.ts
- translations/en-us.yml
-   Ticket: [ENG-4195]
- Add logic around showing/hiding more fields based on this [Platform PR](https://github.com/CenterForOpenScience/osf.io/pull/10343) 
- Add conditional logic to show/hide associated project in AVOL
- Show the registries state dropdown even in AVOL, as without it, the updates dropdown floats in an odd location
- Overview topbar before:
- Overview topbar after:
[ENG-4195]: https://openscience.atlassian.net/browse/ENG-4195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4195] Hide additional fields and show state for AVOL registrations

- Dockerfile
Fix CI/CD pipelines
- Created `ember-base-14` image, available in quay: https://quay.io/repository/centerforopenscience/ember-base-14
- Tested resulting EOW image via `docker run --rm --env 'CI=true' ember-osf-web yarn test:ember` with these changes in a cloud shell
Ember tests only go so far, **should be verified on staging before production deploy**
> [Hotfix] Update dockerfile to use node 14

- package.json
- yarn.lock
-   Ticket: n/a
Ember engines 0.9.0 broke rebuilds, and isn't necessary for deprecation fixes since the testing api was in 0.8.3.
1. Downgrade ember-engines to 0.8.3
> Make rebuilds work again

- config/optional-features.json
- tests/engines/registries/acceptance/draft/draft-test.ts
- tests/engines/registries/acceptance/edit-revision/revision-test.ts
- tests/engines/registries/acceptance/overview/moderator-mode-test.ts
- tests/engines/registries/acceptance/overview/overview-test.ts
- tests/integration/components/contributors/component-test.ts
- tests/integration/components/draft-registration-card/component-test.ts
- tests/integration/components/review-actions-list/review-action/component-collection-test.ts
- tests/integration/components/review-actions-list/review-action/component-registration-test.ts
- yarn.lock
-   Ticket: [ENG-4427]
Turn jQuery integration off. This causes some subtle timing issues with rendering which are fixable with timeouts.
1. Disable jQuery integration
2. Sprinkle timeouts throughout the tests where necessary to get them to pass again.
Tests will take a bit longer to run.
No real QA needed for this. Hopefully it won't break selenium with the new timing issues.
[ENG-4427]: https://openscience.atlassian.net/browse/ENG-4427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4427] Fix timing issues due to no jQuery integration

- app/adapters/osf-adapter.ts
Requests made through ember-data directly were not being authenticated after switching off jQuery Integration. This fixes that.
1. Make fetch requests authenticated
This should make it possible to view draft registrations again, and probably fix some other things as well.
> Make fetch requests authenticated

- config/deprecation-workflow.js
- lib/osf-components/addon/components/carousel/component.ts
- lib/osf-components/addon/components/carousel/x-item/component.ts
- lib/osf-components/addon/components/validated-input/base-component.ts
- tests/helpers/require-auth.ts
- tests/integration/components/contributor-list/component-test.ts
- tests/integration/components/contributor-list/unregistered-user/component-test.ts
- tests/integration/components/contributors/component-test.ts
- tests/integration/components/files-widget/component-test.ts
- tests/integration/components/moderators/component-test.ts
- tests/integration/components/move-file-modal/component-test.ts
- tests/integration/components/registries/my-registrations-list/component-test.ts
- tests/integration/components/tos-consent-banner/component-test.ts
- tests/integration/services/current-user-test.ts
- tests/unit/packages/files/dataverse-file-test.ts
-   Ticket: [ENG-4021]
Un-silence the deprecation for computed property overrides and fix the problems.
1. Un-silence the deprecation
2. Update validated input to accept isActive as a parameter and computer the active state property properly rather than overriding the computed property
3. Fix the logged-out home page carousel
4. Update the current-user stub to accept a testUser rather than overriding the user computed property
5. Fix usage of current-user in tests to use the new testUser property
The main thing I would be concerned about is if I broke some indications that fields are required, but I think I fixed that in a pretty safe way.
[ENG-4021]: https://openscience.atlassian.net/browse/ENG-4021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
> [ENG-4021] Deprecation/computed property override

- lib/analytics-page/addon/application/controller.ts
- lib/analytics-page/addon/application/styles.scss
- lib/analytics-page/addon/application/template.hbs
- lib/analytics-page/addon/components/analytics-charts/component.ts
- lib/analytics-page/addon/components/analytics-charts/styles.scss
- lib/analytics-page/addon/components/analytics-charts/template.hbs
-   Ticket: [ENG-4406]
To remove the bootstrap css classes
Removed the bootstrap css and translated them to native css
**Before Desktop**
**Before Mobile**
**After Desktop**
**AFter Mobile**
Non
Check the images
[ENG-4406]: https://openscience.atlassian.net/browse/ENG-4406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4406] Removed bootstrap from the analytics pages

- lib/registries/addon/overview/children/template.hbs
- lib/registries/addon/overview/links/template.hbs
- tests/engines/registries/acceptance/overview/components-page-test.ts
- tests/engines/registries/acceptance/overview/links-page-test.ts
- tests/integration/components/license-text/licence-text-test.ts
- tests/integration/components/registries/new-update-modal/component-test.ts
-   Ticket: [ENG-4492]
- Add data-test selectors to registration components and links pages for Selenium test
- Add data-test selectors to the "No components" and "No linked registrations/nodes" messages
- Add acceptance tests for these pages
- NA
- None
- The data-test selector for the "No components" message is `data-test-no-components`
- The data-test selector for the "No linked nodes" message is `data-test-no-linked-nodes `
- The data-test selector for the "No linked registrations" message is `data-test-no-linked-registrations `
- Functionality should not be impacted at all
[ENG-4492]: https://openscience.atlassian.net/browse/ENG-4492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4492] Add data-test selectors to registration components and links page

- lib/registries/addon/overview/children/template.hbs
- lib/registries/addon/overview/links/template.hbs
- tests/engines/registries/acceptance/overview/components-page-test.ts
- tests/engines/registries/acceptance/overview/links-page-test.ts
-   Ticket: [ENG-4492]
- Add data-test selectors for selenium tests in a better place
- Add data test selectors to the heading element for components and links page
- NA
- None
- The data test selectors for the `<h3>`s are `data-test-components-page-heading` and `data-test-links-page-heading`
[ENG-4492]: https://openscience.atlassian.net/browse/ENG-4492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4492] Data test selectors for Selenium tests

- lib/analytics-page/addon/application/template.hbs
- lib/app-components/addon/components/branded-navbar/component.ts
- lib/app-components/addon/components/branded-navbar/styles.scss
- lib/app-components/addon/components/branded-navbar/template.hbs
- lib/app-components/addon/components/project-contributors/list/item/template.hbs
- lib/app-components/addon/components/project-contributors/search/result/template.hbs
- lib/app-components/addon/components/project-contributors/search/template.hbs
- lib/app-components/addon/components/project-contributors/search/unregistered-contributor/template.hbs
- lib/app-components/addon/components/search-paginator/template.hbs
- lib/app-components/addon/components/submit-section-buttons/template.hbs
- lib/collections/addon/components/collection-search-result/template.hbs
- lib/collections/addon/components/collections-submission/template.hbs
- lib/collections/addon/components/discover-page/active-filters/filter/template.hbs
- lib/collections/addon/components/discover-page/active-filters/template.hbs
- lib/collections/addon/components/discover-page/template.hbs
- lib/osf-components/addon/components/carousel/template.hbs
- lib/osf-components/addon/components/license-picker/template.hbs
- lib/osf-components/addon/components/sharing-icons/popover/template.hbs
- lib/registries/addon/branded/moderation/pending/template.hbs
- lib/registries/addon/branded/moderation/submitted/template.hbs
- lib/registries/addon/components/registries-discover-results-header/template.hbs
-   Ticket: [ENG-4502]
Get rid of boring HTML buttons and replace them with exciting ember-osf-web Buttons. Except for:
1. In component tests
2. In the Button component itself, naturally
3. In the BsAlert component, because that's going to be completely redone soon anyways, so no sense replacing that out just yet.
1. Replace buttons with Buttons
2. Do a bit more work with the button from the collections branded navbar
There will be some minor visual differences because we're now using a standardized component with standardized styling.
[ENG-4502]: https://openscience.atlassian.net/browse/ENG-4502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4502] Replace buttons with Buttons

- lib/analytics-page/addon/application/styles.scss
- lib/analytics-page/addon/application/template.hbs
- lib/collections/addon/components/discover-page/styles.scss
- lib/collections/addon/components/discover-page/template.hbs
- lib/osf-components/addon/components/node-card/styles.scss
- lib/osf-components/addon/components/node-card/template.hbs
- lib/osf-components/addon/components/osf-navbar/auth-dropdown/styles.scss
- lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
- lib/osf-components/addon/components/osf-navbar/styles.scss
- lib/osf-components/addon/components/osf-navbar/template.hbs
- lib/registries/addon/components/registries-navbar/styles.scss
- lib/registries/addon/components/registries-navbar/template.hbs
-   Ticket: [ENG-4419]
Remove usage of BsDropdown from the ember-osf-web codebase.
Remove BsDropdown from:
1. Analytics page
2. Node card
3. Collections Discover page
4. OSF Navbar and OSF Navbar Auth Dropdown
5. Registries Navbar
Analytics page:
Node Card:
Collections Discovery page:
OSF Navbar:
Registries Navbar:
The look may be a bit different in places
Just make sure the menus still work and don't look weird. For navbars, be sure to check the logged-out state as well.
[ENG-4419]: https://openscience.atlassian.net/browse/ENG-4419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4419] No BsDropdown

- app/settings/controller.ts
- app/settings/styles.scss
- app/settings/template.hbs
- lib/analytics-page/addon/application/template.hbs
Not having the active highlight in Firefox for the settings page was a problem that needed fixing. This fixes it.
1. Fix active page highlight on settings page navigation
2. Add page identity test selector for Analytics Page to make QA's life better
> [No ticket] Xenon/Fix active page highlight in Firefox

- lib/analytics-page/package.json
Make the linked nodes list show private projects
1. Add ember-tooltips to the analytics engine.
> [No ticket] Xenon / Add ember tooltips to analytics engine

- lib/collections/addon/components/collections-submission/styles.scss
Make the collections "Reason to remove from collection" text area wider
1. Make CSS Selector less specific
> [No ticket] Xenon - Make reason to remove text area wider

- app/adapters/index-card-search.ts
- app/adapters/index-card.ts
- app/adapters/index-property-search.ts
- app/adapters/index-value-search.ts
- app/helpers/get-localized-property.ts
- app/models/index-card-search.ts
- app/models/index-card.ts
- app/models/index-property-search.ts
- app/models/index-value-search.ts
- app/models/search-result.ts
- app/search/-components/filter-facet/component.ts
- app/search/-components/filter-facet/template.hbs
- app/search/controller.ts
- app/search/styles.scss
- app/search/template.hbs
- app/serializers/index-card-search.ts
- app/serializers/index-card.ts
- app/serializers/index-property-search.ts
- app/serializers/index-value-search.ts
- mirage/config.ts
- mirage/views/search.ts
- tests/acceptance/search/search-filters-test.ts
- tests/acceptance/search/search-query-params-test.ts
- translations/en-us.yml
-   Ticket: [ENG-4469]
- Add object type filter and sort dropdown to search page
- Add tabs to filter by object type (All, Projects, Registrations, Preprints, Files, Users)
- Add dropdown to sort results by Relevance, Date modified/created ascending and descending
- Change model names to reflect more library-analogy based names
- Change how metadata properties are fetched from SHARE models
- Desktop
- Mobile
- NA
[ENG-4469]: https://openscience.atlassian.net/browse/ENG-4469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4469] Add object filter and sort dropdown to search

- lib/osf-components/addon/components/osf-navbar/styles.scss
- lib/osf-components/addon/components/osf-navbar/template.hbs
- tests/acceptance/settings/tokens-page-test.ts
-   Ticket: [ENG-4548]
Changing the off navbar's auth dropdown from a bootstrap dropdown to a responsive dropdown caused it to lose the ability to be an li, and instead it became a div. This broke the accessibility, because it was inside the ul where divs are forbidden. This fixes the accessibility problems.
1. Move the auth dropdown outside of the unordered list
2. Fix the styling
Just need to verify the accessibility and make sure I didn't break anything in the process.
[ENG-4548]: https://openscience.atlassian.net/browse/ENG-4548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4548] A11y fix for OSF Navbar

- tests/acceptance/settings/tokens-page-test.ts
Jenkins keeps failing on one test due to not waiting long enough. This increases the timeout so hopefully Jenkins will start deploying our branches.
1. Increase timeout
> Increase timeout for Jenkins

- app/institutions/dashboard/-components/institutional-users-list/component.ts
- lib/collections/addon/provider/moderation/styles.scss
- lib/osf-components/addon/components/draft-registration-card/styles.scss
- lib/osf-components/addon/components/subscriptions/list-row/styles.scss
- lib/osf-components/addon/components/subscriptions/list-row/template.hbs
- lib/registries/addon/branded/moderation/styles.scss
Ensure that the menu for moderation is correct in mobile
Updated the menus to have a fixed height
Hopefully none
Automated tests, looks at the screenshot or browse to it.
> [ENG-4551] Fixed the registries and collection moderation menus on mobile

- app/institutions/dashboard/-components/institutional-users-list/component.ts
- app/styles/_components.scss
- lib/osf-components/addon/components/banners/view-only-link/styles.scss
- lib/osf-components/addon/components/banners/view-only-link/template.hbs
- lib/osf-components/addon/components/maintenance-banner/template.hbs
- lib/osf-components/addon/components/sort-button/styles.scss
- lib/osf-components/addon/components/subscriptions/list-row/styles.scss
- lib/osf-components/addon/components/subscriptions/list-row/template.hbs
- lib/registries/addon/components/registries-header/styles.scss
- lib/registries/addon/overview/-components/overview-topbar/template.hbs
- package.json
- yarn.lock
Bug fixes for Cesium. Ignore the last two commits if you go commit-by-commit, they were a mistake and the last one reverts out the second-to-last.
1. No flex on headers provider-description div - This one I found, not QA. It was causing the registries header to separate out anchor tags from the main paragraph and put them in their own little flex space.
2. Choose Bette focus color for sort buttons
3. On collections navbar, don't make background white
4. Ensure power select doesn't get too small
5. Make maintenance banner dismissible
6. Pad the warning text on the VOL banner
7. Make sharing tooltip look good
8. Move ember tooltips to dev dependencies - Not a bug, but a mistake I made earlier that needed fixing
9. Work with newer versions of …
> [ENG-4551] Cesium/fourth batch of bug fixes

- app/settings/tokens/-components/create-form/component.ts
- app/settings/tokens/-components/edit-form/component.ts
Don't allow attempt to create or update a token without scopes and a name
1. Add scopes validator to create token form
2. Add name and scopes validator to edit token form and validate that form
> [ENG-4551] Ensure tokens always require name and scopes

- app/models/preprint-provider.ts
- app/preprints/discover/controller.ts
- app/preprints/discover/route.ts
- app/preprints/discover/template.hbs
- app/preprints/template.hbs
- app/search/controller.ts
- app/search/template.hbs
- lib/app-components/addon/components/branded-navbar/component.ts
- lib/app-components/addon/components/branded-navbar/template.hbs
- lib/osf-components/addon/components/osf-layout/template.hbs
- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
- mirage/scenarios/default.ts
- mirage/scenarios/preprints.ts
- mirage/serializers/preprint-provider.ts
- package.json
- tests/acceptance/preprints/discover-test.ts
- translations/en-us.yml
-   Ticket: [ENG-4574]
- Rewrite the preprints discover page to use the new search-page component
- Add `app/preprints/template.hbs` to house general preprints templating (import CSS using `<ThemStyles>` and `<BrandedNavbar>`
- Update `<BrandedNavbar>` to support preprints in ember-osf-web
- Update preprints discover route and controller to support search-page
- Update search-page component 
- support default query options to send to SHARE
- Add result count
Preprint branded discover page
Desktop
Mobile
- Should be none...
- This touches the `<BrandedNavbar>` component that is used in collections. I checked to make sure these didn't break, but a double-check if the buttons for collections navbars are showing up as expected would be much appreciated ("Moderation", "My …
> [ENG-4574] Preprint discover rewrite

- app/guid-node/registrations/styles.scss
- app/guid-node/registrations/template.hbs
- lib/osf-components/addon/components/node-card/styles.scss
- lib/osf-components/addon/components/node-card/template.hbs
- lib/registries/addon/components/registries-recent-list/component.ts
- lib/registries/addon/components/registries-recent-list/styles.scss
- lib/registries/addon/components/registries-recent-list/template.hbs
Fix hopefully the last of the css problems with cesium.
1. Fix text color on node card update button
2. Reduce margin on registries recent list in mobile view to fit the 'See more' link
3. Add margin to the node registration lists for their empty states
> [ENG-4551] Cesium/css fixes

- app/models/preprint-provider.ts
- app/preprints/controller.ts
- app/preprints/discover/template.hbs
- app/preprints/route.ts
- app/preprints/template.hbs
- lib/app-components/addon/components/branded-navbar/component.ts
- lib/osf-components/addon/components/search-page/template.hbs
- mirage/scenarios/preprints.ts
- tests/acceptance/preprints/discover-test.ts
- tests/unit/models/preprint-provider-test.ts
- translations/en-us.yml
-   Ticket: [ENG-4574]
- Add appropriate page title to discover page
- Add appropriate analytics scope to discover page
- Make provider description now show html entities
- Use `{{html-safe}}` when showing provider description
- Add `providerTitle` in preprint-provider model
- Most branded providers should show their name with their preprint word (e.g. AfricaRxiv Preprints, MarXiv Papers), except Thesis Commons
- If it's OSF, we just show "OSF Preprints"
- Add page-title and analytics scope using the new `providerTitle`
- Before
- After
- None
- On production, all preprint providers have their preprint word included in the navbar and page-title (visible in the browser tab), except Thesis Commons
[ENG-4574]: https://openscience.atlassian.net/browse/ENG-4574?atlOrigin=e …
> [ENG-4574] Preprint discover fixes

- app/utils/capture-exception.ts
See if a weird bug gets fixed on staging2 by removing a slightly risky re-throw of error messages.
1. Don't re-throw error message
Will have anti-side-effects.
> [No ticket] Don't re-throw error in getApiErrorMessage

- lib/registries/addon/overview/route.ts
Help to be able to debug situations where the registries overview page goes to the not-found page inappropriately.
1. Send the error to sentry after transitioning to page not found.
Shouldn't be any
> [No ticket] Throw an error when registries overview page errors

- lib/osf-components/addon/components/osf-layout/component.ts
- lib/osf-components/addon/components/osf-layout/template.hbs
- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/filter-facet/template.hbs
- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
- tests/acceptance/search/search-help-test.ts
- translations/en-us.yml
-   Ticket: [ENG-4535]
- Add search help feature
- Basically a re-implementation of https://github.com/CenterForOpenScience/ember-osf-web/pull/1891 and https://github.com/CenterForOpenScience/ember-osf-web/pull/1877
- Notable difference is moving the Popovers to the end of the file to avoid merge conflicts
- Added EmberPopovers to the search-page component
- Added getters to search-page component to fetch EmberPopover targets dynamically
- Translations
- Tests
- General search page, desktop
- Preprints mobile
[ENG-4535]: https://openscience.atlassian.net/browse/ENG-4535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4535] Search help feature

- config/environment.js
-   Ticket: [ENG-4598]
Try to get Google Tag Manager working in ember-osf-web
1. Added GoogleTagManager config to ember-metrics
[ENG-4598]: https://openscience.atlassian.net/browse/ENG-4598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4598] Add GTM to metrics adapters

- app/index.html
- config/environment.d.ts
- config/environment.js
- ember-cli-build.js
-   Ticket: [ENG-4598]
To allow rest of GTM to be configurably added to page body.
1. Add config variable for GTM script so devops can add the script as needed with the proper config per env
2. Add build process to make it available for index.html
3. Add section to index.html
4. Types
Here's the stub script in where it's supposed to be:
[ENG-4598]: https://openscience.atlassian.net/browse/ENG-4598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4598] Enable rest of GTM to be inserted into page

- app/serializers/osf-serializer.ts
When upgrading to ember 3.28, we lost the ability to distinguish between dirty relationships and clean ones when PATCHing a record, so we would send all the relationships. This was a problem because many of the clean relationships in the serializer had null information, which broke the API, because it doesn't like PATCHed relationships with null information. This fixes that by removing any relationship that is just null info in the serializer. We will still sometimes PATCH relationships we don't need to, but the info should be the same and thus not cause problems for the API. 
1. Scan for null relationships in osf-serializer and remove them from the request payload.
Hypothetically, we might have a relationship at some point that we try to PATCH where the user doesn't have proper …
> Barium / Remove most non-dirty relationships

- config/environment.d.ts
- config/environment.js
- ember-cli-build.js
-   Ticket: [ENG-4598]
You can't just pull something into the index.html from runtime, it has to happen build time. So we'll try doing this the way raven works instead.
1. Initialize GTM in a way that works runtime.
2. Add environment variable for the gtm id
3. Types
[ENG-4598]: https://openscience.atlassian.net/browse/ENG-4598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4598] Try initializing GTM in a way that works runtime

- app/preprints/template.hbs
- lib/app-components/addon/components/branded-navbar/component.ts
- lib/app-components/addon/components/branded-navbar/styles.scss
- lib/app-components/addon/components/branded-navbar/template.hbs
- mirage/fixtures/preprint-providers.ts
- mirage/scenarios/preprints.ts
-   Ticket: []
- Remove possible failure point by not using preprintProvider.asset
- Add special casing to address nutrixiv's navbar color https://osf.io/preprints/nutrixiv/
- Remove use of ThemeStyles from preprint (this set the navbar logo to use the preprintProvider.asset. square_color_transparent, when we want to just use the brand. topnavLogoImage going forward)
- Add special case for nutrixiv to use a white background similar to biohackrxiv
Thank you to Doug for pointing these out!
> Preprints branding update

- app/serializers/osf-serializer.ts
- types/@ember-data/record-data/-private.d.ts
- types/@ember-data/store.d.ts
Properly remove clean relationships from a PATCH request.
1. Get the graph
2. Scan the graph for changes in each relationship in the serializer
3. Remove the relationship from the serializer if there are no changes
4. Types
If I did this wrong, it would break lots of stuff, but that would break tests, so I don't think I did.
Should get caught by unit tests and selenium combo.
> [No ticket] Remove clean relationships from PATCH request

- app/adapters/index-card-search.ts
- app/models/index-card-search.ts
- app/search/controller.ts
- app/search/template.hbs
- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
- translations/en-us.yml
> Add pagination

- app/models/search-result.ts
- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-result-card/template.hbs
- translations/en-us.yml
> User orcid

- app/models/related-property-path.ts
- lib/osf-components/addon/components/search-page/filter-facet/template.hbs
-   Ticket: []
- Fix a bug where properties with no filterable values were showing up in the filter list
- Check for length of property.cardSearchResultCount
- This should prevent properties from showing up that have no values when you expand them
> Hide empty properties better

- app/models/search-result.ts
- lib/osf-components/addon/components/search-result-card/file-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/preprint-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/project-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/registration-secondary-metadata/template.hbs
-   Ticket: []
- Add missing metadata fields in the expanded view of search-result-cards
- [Notion card](https://www.notion.so/cos/Registration-Search-Result-Card-Missing-Expanded-Card-Data-5283ba6b5be342ac894bfa3cf370e60b)
- should be outlined in commit messages
> Add more secondary metadata to search-result-card

- app/dashboard/template.hbs
- app/home/-components/hero-banner/component.ts
- app/search/controller.ts
- app/search/template.hbs
- lib/osf-components/addon/components/editable-field/tags-manager/component.ts
- lib/osf-components/addon/components/tags-widget/component.ts
- lib/registries/addon/drafts/draft/-components/tags-manager/component.ts
- translations/en-us.yml
-   Ticket: []
- Address links to search page scattered around OSF
- [Notion card on QA bug board](https://www.notion.so/cos/Access-to-Search-Page-from-other-OSF-Ember-Pages-5cc8763d68ec49e4838e45139495ecc7)
- Update "New and noteworthy" link to search
- Update logged out page searchbox enter behavior
- Update link in "Welcome to OSF" banner link
- Update destination when clicking on a tag
- Change query-param to `q` to address any other possible links to search page
> Existing search page links

- app/models/index-card-search.ts
- lib/osf-components/addon/components/search-page/component.ts
-   Ticket: []
- Show search result counts properly
- [notion card](https://www.notion.so/cos/No-Visible-Count-of-Total-Search-Results-Either-Before-or-After-Applying-Filters-cc26a6201696481b9e17ed64f9166581)
- Add handling for over 10k search results
- Update logic for showing result count
> Properly show result count; handle 10k+ results

- app/app.ts
- lib/registries/addon/components/registries-recent-list/template.hbs
- lib/registries/addon/engine.js
-   Ticket: []
- [Notion card](https://www.notion.so/cos/Access-to-Search-Page-from-other-OSF-Ember-Pages-5cc8763d68ec49e4838e45139495ecc7)
- Address another link to old registries discover page
- Define external route
- Link to it
> Update browse registrations link

- lib/osf-components/addon/components/search-page/component.ts
-   Ticket: []
- Don't overwrite filter values when selecting multiple filters from a given property
- [Notion card](https://www.notion.so/cos/Selecting-multiple-values-in-a-facet-type-will-only-apply-the-last-value-b3d243c5e27e47119cefb1c7931bb252)
- Use arrays for active filters of a given property (h/t @aaxelb for pointing me to this solution!)
- Filters added from the left-panel will have a redundant `[]` in the request payload, but the API should ignore those
> Allow multiple values for a filterable property

- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
- tests/acceptance/search/search-help-test.ts
- translations/en-us.yml
-   Ticket: []
- Update targets for help popover on mobile
- [notion card](https://www.notion.so/cos/Update-help-text-change-help-guide-target-for-mobile-0f03074ca2a44702983293898b30193f)
- Mobile help popover targets the side-panel toggle button
- Update search input placeholder
- Add link to help guide in help tour
- Add styling cause the link doesn't show up too well with default styling
> Help popover targets for mobile; Search textbox placeholder

- lib/osf-components/addon/components/search-page/filter-facet/component.ts
-   Ticket: []
- [Notion card](https://www.notion.so/cos/Supplements-facet-9cc6da32f3c04a2cafc5ddd171dacda3)
- Add boolean fields
- Remove the "No xyz" option from boolean filters
- Change Project's `supplements` property to a boolean field
- Change preprints `isSupplementedBy` to a boolean fields
- Remove the "No" option from boolean fields (e.g. "No Analytic Code")
- Preprints:
- Registrations
- Projects
> Boolean search fields

- lib/osf-components/addon/components/osf-dialog/heading/styles.scss
- lib/osf-components/addon/components/search-page/filter-facet/styles.scss
- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
- lib/osf-components/addon/components/search-result-card/styles.scss
- lib/osf-components/addon/components/search-result-card/template.hbs
- translations/en-us.yml
-   Ticket: https://openscience.atlassian.net/browse/ENG-4486
-   Git branch: feature/styling-search-cards
The purpose of these changes is to make the search page easy to scan and aesthetically pleasing as well as functional in both desktop and mobile views.
Styling was added to the main search route to include the heading wrapper, topbar, facet filters, and cards on desktop and mobile. Changes also included institutions' assets styling on desktop and mobile. Individual changes include:
- Background image with default background OSF blue was added to the heading wrapper 
- Flex was added to the header and cards for formatting and responsiveness 
- Cards were formatted, adding semantic tag elements and local class selectors where appropriate
- Padding and margin were augmented to match …
> [ENG-4486]  Styling new search page + facet filters and cards

- lib/osf-components/addon/components/search-page/template.hbs
- tests/acceptance/search/search-help-test.ts
- translations/en-us.yml
-   Ticket: []
- Update help text
> Update help text

- lib/osf-components/addon/components/search-result-card/styles.scss
- lib/osf-components/addon/components/search-result-card/template.hbs
-   Ticket: [Notion card](https://www.notion.so/cos/Mobile-Withdraw-label-for-registration-and-preprints-text-wrap-8e047d77a0e44af9b2e52ecc15dc998f?pvs=4)
Address the following visual bug
- Desktop:
- mobile:
> Mobile: Fix squished withdraw label

- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
-   Ticket (Notion): https://www.notion.so/cos/Sort-dropdown-will-not-toggle-open-6f234edd07fc4de7a8f588f237a7e91f?pvs=4
-   Branch name: feature/search-improvements-b-and-i-part-1
The purpose of these changes was to resolve the bug fixes for sort dropdown and the help guide. Further bug fixes will be resolved in any subsequent PRs. 
-Flexbox was removed from the sort dropdown
-Padding and margin was added/removed to the help tutorial buttons and description
-Local class selector name was updated to match other help guides
-Selector name was updated to reflect the skip button local class name
> [BUG] Fix sort dropdown, help tutorial

- lib/osf-components/addon/components/search-result-card/file-secondary-metadata/styles.scss
- lib/osf-components/addon/components/search-result-card/file-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/preprint-secondary-metadata/styles.scss
- lib/osf-components/addon/components/search-result-card/preprint-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/project-secondary-metadata/styles.scss
- lib/osf-components/addon/components/search-result-card/project-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/registration-secondary-metadata/styles.scss
- lib/osf-components/addon/components/search-result-card/registration-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/template.hbs
-   Ticket: []
- Add back the isContainedBy field that tells which node a file belongs to
- Preserve the whitespace for descriptions on the expanded view
- Add back `isContainedBy` field that was removed in an [earlier PR](https://github.com/CenterForOpenScience/ember-osf-web/pull/1940)
- Preserve whitespace for description field (Didn't apply to all `<dd>` as this caused some of the fields to have a lot of unexpected whitespace)
- Preserved whitespace for description
- Added back the `From:` field for files (highlighted in the screenshot for visibility)
> Search card fixes

- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/template.hbs
-   Ticket: [Notion card](https://www.notion.so/cos/Scroll-to-top-of-page-when-changing-pages-f1c70059d51d4b4693ada9a2934fb021?pvs=4)
- Scroll to top between page changes
- Add scroll to `switchPage` task (scroll target is a little higher than the first card, since the navbar can cover up the first result)
> Scroll to top on page change

- lib/osf-components/addon/components/search-page/styles.scss
-   Ticket: []
- Don't target `body` in css file
- rewrite rule targeting `body` to target the  local-class used in `<OsfLayout>`'s backgroundClass
> Stop targeting body in css

- lib/osf-components/addon/components/search-result-card/file-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/preprint-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/project-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/registration-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/template.hbs
- translations/en-us.yml
-   Ticket: [Notion card](https://www.notion.so/cos/Contributors-list-ends-with-and-if-there-are-more-than-5-contributors-4778f2a50e9344499e39e9072a70f1a0)
- Fix inline list with 5+ items
- Handle cases of lists with `remainingCount`
- Prevents this bug
- Now looks like
> Fix long list items for search cards

- lib/registries/addon/components/registries-search-result/template.hbs
-   Ticket: [Notion card](https://www.notion.so/cos/Resource-Badges-on-Branded-Registry-Discover-Pages-Should-be-Vertical-62ec199fda5f43fb84b3d2709408c0bf)
- Use vertical align for registration badges on branded discover pages
- Fixes this issue on branded discover page
> Use vertical layout for registries search result cards

- app/styles/_variables.scss
- lib/osf-components/addon/components/open-badges-list/styles.scss
- lib/osf-components/addon/components/search-result-card/styles.scss
- lib/osf-components/addon/components/search-result-card/template.hbs
Tickets (Notion): 
-https://www.notion.so/cos/Styling-Expanded-Card-Elements-Could-Use-More-Padding-Between-Them-5271761d87b240a7a9af2092a912371b?pvs=4, 
-https://www.notion.so/cos/What-happened-to-the-Fold-Line-Separator-Between-Top-of-Card-and-Expanded-Card-9e9e10bc80a14d78a4e62f350346ced3?pvs=4
-https://www.notion.so/cos/Reduce-margin-at-bottom-of-resources-1ae018883f314d25a53ac54bc981da09?pvs=4
-https://www.notion.so/cos/Result-card-titles-need-to-be-bold-ef738a46d57e44f69e1d3d56b22b5f8e?pvs=4
GitHub branch: feature/search-improvements-b-and-i-part-2
The purpose of these changes was to address the styling in the secondary metadata container.
- top border was added to the secondary metadata container
- local class selector was added to the secondary metadata container 
- excessive …
> [BUG] Fix expanded card elements, result card title, fold line separator

- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
- lib/osf-components/addon/components/search-result-card/styles.scss
- lib/osf-components/addon/components/search-result-card/template.hbs
- translations/en-us.yml
Tickets (Notion): 
-https://www.notion.so/cos/Pagination-buttons-added-styling-0ef0c6bfca96423e9b323fd7b9031172?pvs=4
-https://www.notion.so/cos/Selenium-Request-to-add-data-test-attributes-to-Search-Page-Elements-969958ae9c1e431a98125584bd8c6028?pvs=4
GitHub branch: feature/search-improvements-b-and-i-part-3
The purpose of these changes was to fix the active and hover states of the search top bar, the excessive top margin in the left panel header, increase pagination button padding, and to provide QA with data test selectors for the result card container and its individual title link.
- Top margin of the left panel header was reduced to balance it with the corresponding facet filter border
- Width of list elements of the topbar was evenly divided across topbar width
- Padding was added …
> [BUG] Fix search topbar active and hover state, pagination buttons, panel header

- lib/osf-components/addon/components/search-page/styles.scss
> Revert some of the topbar padding and width changes

- app/institutions/discover/controller.ts
- app/preprints/discover/controller.ts
- app/search/controller.ts
- lib/osf-components/addon/components/search-page/component.ts
-   Ticket: [ENG-4649]
- Reset the page when entering new text into the search box
- Remove the query-param for `page`
- Reset page query param on debounceSearch task
- Remove the query-param for `page` from general search page and branded pages
- Look ma, no query-params
- The page query param should ~reset when you are on the second page and enter new text into the search-box. The "Prev" button should go away in this case as well~ be gone entirely
[ENG-4649]: https://openscience.atlassian.net/browse/ENG-4649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Hotfix][ENG-4649] Reset page QP on new search text

- app/register/controller.ts
- app/register/route.ts
- lib/osf-components/addon/components/search-page/component.ts
- lib/registries/addon/branded/discover/controller.ts
- package.json
- yarn.lock
- Remove ember-parachute
- Remove page query param from branded discover page
- update package.json and yarn
- update branded discover controller and `OnSearchParams` type to exclude `page`
> Remove ember-parachute; Remove page QP

- translations/en-us.yml
- Use less confusing wording in object type dropdown
- Wording change
- Avoid potentially confusing wording on mobile
> [No ticket] Reword object filter dropdown label

- lib/osf-components/addon/components/copy-button/template.hbs
Try to fix a selenium test that was broken when we re-wrote the clipboard button.
1. Add data selector
Here's the problem I'm trying to fix:
Shouldn't be.
Selenium tests should pass.
> [No ticket] Fix selenium test for clipboard button

- package.json
- yarn.lock
-   Ticket: [ENG-4022]
There are two major parts to fixing the try-invoke deprecation. The first is updating ember-composable-helpers, and the second is removing ember parachute. This handles the first. The second will be part of Search Phase 2 once the branded registries discovery page, which is the page that uses ember-parachute, is removed.
1. Update ember-composable-helpers
This should be fairly straightforward.
[ENG-4022]: https://openscience.atlassian.net/browse/ENG-4022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4022] Deprecation/try-invoke part 1

- app/meetings/detail/-components/meeting-submissions-list/template.hbs
- app/meetings/index/-components/meetings-list/template.hbs
A recent deprecation fix caused [meetings searches to break](https://www.notion.so/cos/Meetings-filtering-is-broken-26e361c983224e1a817be0a29404270f?pvs=4). This should fix that.
1. Add `target` string to `on` actions
> Fix broken meetings searches

- app/institutions/discover/controller.ts
- lib/registries/addon/branded/discover/controller.ts
-   Ticket: []
- Fix issue where FE is querying SHARE incorrectly on branded discover pages
- Use `affiliation` query-param for institution discover
- Fix link to provider IRI for registrations
> Fix branded page query-params

- app/institutions/discover/controller.ts
- app/institutions/discover/template.hbs
- app/preprints/discover/controller.ts
- app/preprints/discover/template.hbs
- app/search/controller.ts
- app/search/template.hbs
- lib/osf-components/addon/components/search-page/component.ts
- lib/registries/addon/branded/discover/controller.ts
- lib/registries/addon/branded/discover/template.hbs
> [ENG-4660] activeFilters query param

- app/models/related-property-path.ts
- lib/osf-components/addon/components/search-page/boolean-filters/component.ts
- lib/osf-components/addon/components/search-page/boolean-filters/styles.scss
- lib/osf-components/addon/components/search-page/boolean-filters/template.hbs
- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/filter-facet/component.ts
- lib/osf-components/addon/components/search-page/template.hbs
- lib/osf-components/app/components/search-page/boolean-filters/component.js
- lib/osf-components/app/components/search-page/boolean-filters/template.js
- mirage/views/search.ts
- translations/en-us.yml
-   Ticket: [ENG-4656]
- Special-case boolean type filters
- Add new `suggestedFilterOperator` property to RelatedPropertyPath model
- Split out iri-centric filters and boolean filters when conducting a search
- Add new `<SearchPage::BooleanFilters>` component to display boolean filters
- Remove existing boolean-filter special-casing from SearchPage and SearchPage::FilterFacet components
- Projects:
- Registrations:
- Preprints:
[ENG-4656]: https://openscience.atlassian.net/browse/ENG-4656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4656] Special-case is-present type filters

- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
-   Ticket: []
- Show the banner image for branded discover pages
- Allow html entities from institution description
- Add z-index to default banner
- wrap institution description in `{{html-safe}}`
Before for preprint/registration discover:
After for preprint/registration discover:
Prevents this bug in institutions discover:
> Show provider hero-banner on search page

- app/institutions/discover/controller.ts
- app/models/institution.ts
- app/models/related-property-path.ts
- lib/osf-components/addon/components/search-page/boolean-filters/template.hbs
- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/filter-facet/component.ts
- lib/osf-components/addon/components/search-page/filter-facet/template.hbs
- mirage/factories/institution.ts
- mirage/views/search.ts
-   Ticket: []
- Actual fetch stuff in the institution discover page
- Only fetch stuff from the specific environment the search is happening in by using `accessService` query-param
- This addresses the issue of seeing multiple instances of `OSF Registries` or `Open-ended Registration` registration templates on staging
- Add `rorIri` and `iri` attributes to Institution model (ultimately these comes from the `ror_uri ` and `identifier_domain` respectively in the admin app and is being added in a [BE PR](https://github.com/CenterForOpenScience/osf.io/pull/10452))
- fetch by either ROR, URI, or URL from OSFv2 URL (the URLs that are [relevant to SHARE for understanding institution affiliation](https://github.com/CenterForOpenScience/osf.io/blob/a3e0a0b9ddda5dd75fc8248d58f …
> Update institution discover default query options

- app/models/related-property-path.ts
- lib/osf-components/addon/components/search-page/component.ts
-   Ticket: [Notion card](https://www.notion.so/cos/Date-created-facet-missing-in-all-searches-cd8a168282d8419e94118dfd76162f3c)
- Bring back date Created filter on search page
- Make the condition for getting non-boolean type filters less restrictive
> Bring back Date Created filter

- app/packages/registration-schema/validations.ts
- lib/registries/addon/drafts/draft/draft-registration-manager.ts
- tests/engines/registries/acceptance/draft/draft-test.ts
-   Ticket: [ENG-4293]
Fix node license validation
- Modify `validateNodeLicense` validator to make use of `newValue` parameter instead of relying on `changes`, which is not a reliable way of getting the newest value of the changeset.
- Add tests
[ENG-4293]: https://openscience.atlassian.net/browse/ENG-4293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4293] Fix node license validation

- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
-   Ticket: [[Notion Card]](https://www.notion.so/cos/Sort-options-missing-on-branded-registries-search-pages-9b2fd17692eb49e6ae00f1a510687167)
- Bring back sort dropdown for preprints and registries discover
- Move sort-dropdown outside of conditional
- Styling
- General search
- Preprints discover
- Registries discover
> Return sort dropdown for registries and preprints discover

- lib/osf-components/addon/components/search-page/styles.scss
-   Ticket: [[Notion Card 1]](https://www.notion.so/cos/Darpaasist-registry-header-text-not-displaying-properly-df1fc7d9b7974989a60fce0715147298?pvs=4) [[Notion Card 2]](https://www.notion.so/cos/Help-modal-on-branded-registries-appears-to-have-no-text-as-opposed-to-too-dark-Doug-s-tix-above--5f32ad262ad64682b775bafb3ef7673b?pvs=4) [[Notion Card 3]](https://www.notion.so/cos/Search-Help-Feature-Appears-Empty-on-Branded-Registry-Discover-Pages-Because-the-Color-of-the-Text-i-0db1ca6d1c374d5a8f6c0925d03ae679?pvs=4)
- Fix DAPRA ASIST description text styling
- Fix text-color issue in help popovers
- Fix issue with help popovers showing up under search-result cards
- For DARPA ASIST description: Update selector in `. heading-wrapper-mobile` class to not select extraneous …
> Address branded registries style issues

- lib/osf-components/addon/components/sign-up-form/template.hbs
Placeholder text went away on the sign-up page. This restores the placeholders.
1. Send the placeholders to the component properly.
Before:
After:
> Restore placeholder text on sign-up page

- app/preprints/discover/route.ts
- app/router.ts
-   Ticket: []
- Reroute users going to `preprints/discover` and `preprints/osf/discover` to general search page
- Add route to router to handle `preprints/discover`
- Add logic to handle these cases
- NA
> Reroute users to general discover page for preprints/discover and preprints/osf/discover

- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
-   Ticket: []
- Make institution logo show up
- Update institutions header background color
- Update institution logo image `src`
- Add `institutions-overlay` style to add plain grey background to header
- Institutions discover page header (Desktop): Before
- Institutions discover page header (Desktop): After
- Institutions discover page header (Mobile): After
> Institutions header

- lib/registries/addon/branded/discover/route.ts
- lib/registries/addon/branded/route.ts
-   Ticket: [[Notion Card]](https://www.notion.so/cos/Going-to-an-invalid-registry-s-discover-page-leads-to-a-blank-page-eb4488f6e231499a8ffdbbc659657ac8?pvs=4)
- Show page-not-found if you go to an invalid registry's discover page (e.g. https://osf.io/registries/foo/discover )
- add `try catch` block to branded route
- `await` the registration-provider
> Reroute for registry not found

- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
-   Ticket: [NotionCard](https://www.notion.so/cos/Search-Help-Feature-Appears-Empty-on-Branded-Registry-Discover-Pages-Because-the-Color-of-the-Text-i-0db1ca6d1c374d5a8f6c0925d03ae679?pvs=4)
- Increase color contrast of help link in search page help tour
- Use different color for links in help tour 
- color contrast is now 4.32 (#15A5EB vs. #263947, which should pass for WCAG AA for large text (14px and bold, or 18pt or larger)
Before:
After:
> Increase color contrast of link in help tour

- app/institutions/discover/controller.ts
- app/models/institution.ts
- lib/osf-components/addon/components/search-page/component.ts
-   Ticket: []
- Use new `iris` field on institution model to get all institution identifiers
- Remove "All" as an option for institution discover page
- Update default query-params based on object type filter in place
- Move `onSearch` hook to happen before query to SHARE
> Institutions updates

- app/adapters/share-adapter.ts
- lib/osf-components/addon/components/search-page/component.ts
-   Ticket: []
- Add `accessService` query-param to SHARE requests to filter out items from other staging environments
- Basically undoing this PR: https://github.com/CenterForOpenScience/ember-osf-web/pull/1997
> Add back accessService to SHARE request

- lib/osf-components/addon/components/search-page/styles.scss
-   Ticket: [Notion Card](https://www.notion.so/cos/Accessibility-Issue-Color-Contrast-on-Institution-Discover-Page-08359c9b31344379be0ad6efad2e711a?pvs=4)
- Address a11y issue
- Increase institution description links to color contrast 4.98:1 (#2D6A9F vs #ECF0F1)
> Darken institution description links

- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/styles.scss
- translations/en-us.yml
-   Ticket: Notion cards in description
- Grammar for result counts ([Notion Card](https://www.notion.so/cos/Grammatical-error-for-1-result-c2e8237c06ef47b58c7d6053a58cbb5c?pvs=4))
- Show search results for mobile in preprint/registry discover page ([Notion Card](https://www.notion.so/cos/Registries-Bug-of-search-results-hidden-in-mobile-view-04a7ad9ffa9144c390082be7b40c6343?pvs=4))
- Add grammar rules for translation string for results count
- Update logic for 
- Look at this grammar!
- Results counts now shown in mobile for registry overview page
> Result counts

- app/institutions/discover/template.hbs
- app/models/preprint-provider.ts
- app/settings/account/-components/opt-out/component.ts
- lib/app-components/addon/components/branded-navbar/component.ts
- lib/osf-components/addon/components/search-page/component.ts
- lib/registries/addon/branded/discover/controller.ts
- lib/registries/addon/branded/index/route.ts
- mirage/serializers/preprint-provider.ts
-   Ticket: 
- Add better page title to instittuion discover page ([Notion Card](https://www.notion.so/cos/No-useful-title-on-institution-search-page-3aca15cc449b4bb990f9a06ac630bcd2?pvs=4))
- Fix `Affiliation` facet for instition discover page ([Notion Card](https://www.notion.so/cos/Institution-facet-on-institution-page-not-faceting-properly-e80c3d801313410492b21a6198ab8c4f?pvs=4))
- Add `{{page-title}}` to institution discover page
- Don't naively overwrite existing filters with default query-params
- Update `config` imports
> Search bug fixes

- lib/app-components/addon/components/branded-navbar/styles.scss
-   Ticket: []
- Fix branded navbar for biohackr and nutrixiv
- Add specificity to rules in `.white-background-branded-navbar` class (used for biohackr and nutrixiv)
- behold the white "Sign up" button
> Add specificity to supposedly important rules

- app/preprints/discover/route.ts
-   Ticket: [ENG-4818]
- Use provider's favicon when looking at branded preprint discover page
- Add afterModel hook to preprint-discover route to add favicon (same logic as lib/registries/addon/branded/route.ts)
- Can move this afterModel hook  to parent route once preprints landing page rewrite
- favicon associated with a preprint-provider in admin app and used in the browser tab below
- Please make sure the preprint provider is using a given favicon in the admin app by going to `admin.staging.osf.io/provider_asset_files/<asset_id>/`
[ENG-4818]: https://openscience.atlassian.net/browse/ENG-4818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4818] Use provider favicon for preprint discover page

- lib/app-components/addon/components/branded-navbar/styles.scss
- lib/osf-components/addon/components/osf-dialog/styles.scss
- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/filter-facet/component.ts
- lib/osf-components/addon/components/search-page/filter-facet/template.hbs
- lib/osf-components/addon/components/search-page/filter-facet/value-option/component.ts
- lib/osf-components/addon/components/search-page/filter-facet/value-option/styles.scss
- lib/osf-components/addon/components/search-page/filter-facet/value-option/template.hbs
- lib/osf-components/app/components/search-page/filter-facet/value-option/component.js
- lib/osf-components/app/components/search-page/filter-facet/value-option/template.js
-   Ticket: [ENG-4814]
allow searching by creator
- add `creator.name` to the properties used for free-text search (depends on https://github.com/CenterForOpenScience/SHARE/pull/812 )
- skip showing creators without a text query
- when searching within a filter facet, display affiliations
- fix a z-index bug so dropdown content is visible atop the dialog box
https://github.com/CenterForOpenScience/ember-osf-web/assets/6776190/0bddf490-488e-4d1f-bae0-19e88b2fd264
user with affiliation:
z-index bug (before fix):
https://github.com/CenterForOpenScience/ember-osf-web/assets/6776190/1588b69e-991d-4907-9321-735800cc6854
[ENG-4814]: https://openscience.atlassian.net/browse/ENG-4814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4814] creator search

- app/settings/tokens/-components/edit-form/component.ts
- app/settings/tokens/-components/edit-form/template.hbs
- app/settings/tokens/edit/controller.ts
- app/settings/tokens/edit/template.hbs
-   Ticket: https://openscience.atlassian.net/browse/ENG-2224
-   GitHub branch: access-token-edit-scopes
The purpose of these changes is to have the edit token page and its scopes properly displayed following new access token creation.
- The access token value is now cleared when the 'Edit scopes' button is pressed following token creation
Figure 1: Initial access token scope selection
Figure 2: Display of a new access token if the token value is present
Figure 3: Scopes properly display when clicking the 'Edit scopes' button
Figure 4: Saving the changes results in the token's scopes being updated
Figure 5: Clicking on the access token within the list view properly displays updated scopes
Figure 6: Deletion of token following clicking the 'Edit token' button
There should be no side …
> [ENG-2224] Access Token Edit Scopes

- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/filter-facet/component.ts
-   Ticket: []
correct creator-facet behavior when already searching by creator name in free-text search
send same `cardSearchText` param for index-value-search as already used for index-card-search
on the search page:
1. search by a creator name in the main search box (note the creator in search results)
2. click on the "Creator" facet and search by the same creator name
3. should be able to select and filter by the creator in question
> fix: consistent cardSearchText for value-search

- lib/osf-components/addon/components/search-page/template.hbs
- lib/osf-components/addon/components/search-result-card/component.ts
- translations/en-us.yml
-   Ticket: [ENG-4838]
- Don't show "PREPRINT" on search result card for branded preprint provider discover page
- Pass provider to search-result card
- Check result type and provider's `preprintWord`
- Update `Preprint Provider` word to just `Provider`
- For preprint provider's discover page:
[ENG-4838]: https://openscience.atlassian.net/browse/ENG-4838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4838] Update search-result card to show preprint word

- app/models/search-result.ts
-   Ticket: [ENG-4760]
- Show ORCID ids on search result cards regardless of protocol
- Look for `orcid.org` in the identifiers array instead of `http://orcid.org`, as some results were using the `https` protocol in the identifier
[ENG-4760]: https://openscience.atlassian.net/browse/ENG-4760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Broaden how we find orcid ids

- app/guid-node/addons/addon/account/route.ts
- app/guid-node/addons/addon/account/template.hbs
- app/guid-node/addons/addon/configure/route.ts
- app/guid-node/addons/addon/configure/template.hbs
- app/guid-node/addons/addon/confirm/route.ts
- app/guid-node/addons/addon/confirm/template.hbs
- app/guid-node/addons/addon/route.ts
- app/guid-node/addons/addon/template.hbs
- app/guid-node/addons/addon/terms/route.ts
- app/guid-node/addons/addon/terms/template.hbs
- app/guid-node/addons/route.ts
- app/guid-node/addons/template.hbs
- app/router.ts
- tests/unit/guid-node/addons/addon/account/route-test.ts
- tests/unit/guid-node/addons/addon/configure/route-test.ts
- tests/unit/guid-node/addons/addon/confirm/route-test.ts
- tests/unit/guid-node/addons/addon/route-test.ts
- tests/unit/guid-node/addons/addon/terms/route-test.ts
- tests/unit/guid-node/addons/route-test.ts
-   Ticket: [ENG-4683]
- Add routes and placeholder templates for new addon service routes
- Update app/router.ts
- Add route and template file for new routes
- Add unit tests for new routes
- NA
- None
- Nothing testable yet. Routes may change later
[ENG-4863]: https://openscience.atlassian.net/browse/ENG-4863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-4683]: https://openscience.atlassian.net/browse/ENG-4683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4683] Add addon service routes

- app/guid-file/route.ts
- app/guid-file/template.hbs
- app/guid-node/files/provider/route.ts
- app/models/node.ts
- app/packages/files/file.ts
- lib/osf-components/addon/components/file-actions-menu/component.ts
- lib/osf-components/addon/components/file-actions-menu/submit-to-boa-modal/component.ts
- lib/osf-components/addon/components/file-actions-menu/submit-to-boa-modal/template.hbs
- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- lib/osf-components/app/components/file-actions-menu/submit-to-boa-modal/component.js
- lib/osf-components/app/components/file-actions-menu/submit-to-boa-modal/template.js
- mirage/config.ts
- mirage/factories/node.ts
- mirage/scenarios/dashboard.ts
- mirage/views/addons.ts
- translations/en-us.yml
To be filled out.
-   Ticket: https://openscience.atlassian.net/browse/ENG-4671
Add "Submit to Boa" action to file pages for .boa files
> [ENG-4671] Implement submit-to-boa flow for file list and file detail page

- app/adapters/addon.ts
- app/adapters/external-account.ts
- app/adapters/node-addon.ts
- app/adapters/user-addon.ts
- app/models/addon.ts
- app/models/external-accounts.ts
- app/models/node-addon.ts
- app/models/user-addon.ts
- app/serializers/addon.ts
- app/serializers/external-account.ts
- app/serializers/node-addon.ts
- app/serializers/user-addon.ts
-   Ticket: [ENG-4687]
Add models, adapters, and serializers for various v2 endpoints we'll need for addons. Note that some of this does not reflect the BE as it exists today, but is a bit aspirational. That being said, it does not include all the changes we ultimately want, just the ones that are necessary to make this function in a sane manner.
1. Add addon, external-account, node-addon, and user-addon models, adapters, and serializers
[ENG-4687]: https://openscience.atlassian.net/browse/ENG-4687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [ENG-4687] Add v2 models, adapters, and serializers

- lib/osf-components/addon/components/file-actions-menu/component.ts
- lib/osf-components/addon/components/file-actions-menu/template.hbs
-   Ticket: [Notion Card 1](https://www.notion.so/cos/Files-Detail-Page-There-s-to-cancel-the-kebob-menu-fa7d22471f164d979adf13f2de686748?pvs=4) [Notion Card 2]
(https://www.notion.so/cos/Submit-to-Boa-not-present-on-file-detail-page-4366c4f5864147c8bd7d6338b9e003d3?pvs=4)
- Show "Submit to Boa" for file detail page properly
- Avoid issue with mobile view where modal wasn't closable due to the error that was caused by this bug
- Avoid using `parentFolder.userCanUploadToHere` as this was causing issues due to some unresolved promises (`target` specifically)
- `showSubmitToBoa` will now basically do the same check as `userCanUploadToHere` sans `this.isFolder` condition
> Address bugs in file-detail page

- app/guid-file/route.ts
- app/guid-file/template.hbs
- app/guid-node/files/provider/route.ts
- app/models/node.ts
- app/packages/files/file.ts
- lib/osf-components/addon/components/file-actions-menu/component.ts
- lib/osf-components/addon/components/file-actions-menu/submit-to-boa-modal/component.ts
- lib/osf-components/addon/components/file-actions-menu/submit-to-boa-modal/template.hbs
- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- lib/osf-components/app/components/file-actions-menu/submit-to-boa-modal/component.js
- lib/osf-components/app/components/file-actions-menu/submit-to-boa-modal/template.js
- mirage/config.ts
- mirage/factories/node.ts
- mirage/scenarios/dashboard.ts
- mirage/views/addons.ts
- translations/en-us.yml
-   Ticket: [ENG-4642](https://openscience.atlassian.net/browse/ENG-4642)
Implement submit-to-boa in file list page and in file details page.
Work done by @felliott and @futa-ikeda 👍 👍 and reviewed by @brianjgeiger 👍 
* https://github.com/CenterForOpenScience/ember-osf-web/pull/2034
* https://github.com/CenterForOpenScience/ember-osf-web/pull/2047
* https://github.com/CenterForOpenScience/ember-osf-web/pull/2049
N/A
N/A
See [QA Test Plan for Boa](https://docs.google.com/document/d/1XuiSKV2JPpPdXt8aqFXOfBvMXSIA2qz8a1Bxevqh6-M/edit)
* OSF part: https://github.com/CenterForOpenScience/osf.io/pull/10469
* Release note: https://www.notion.so/cos/Boa-Add-on-Release-372fe3b1b5dd42849f6c1c06536c3768
[ENG-4642]: https://openscience.atlassian.net/browse/ENG-4642?atlOrigin=eyJpI …
> [ENG-4642] Boa Add-on Project PR - Ember Part

- app/config/environment.d.ts
- config/environment.js
- ember-cli-build.js
- lib/osf-components/addon/components/cedar-metadata-editor/component.ts
- lib/osf-components/addon/components/cedar-metadata-editor/template.hbs
- lib/osf-components/app/components/cedar-metadata-editor/component.js
- lib/osf-components/app/components/cedar-metadata-editor/template.js
- package.json
- yarn.lock
> [ENG-4908] Prototype CEE

- app/models/external-accounts.ts
- app/models/node-addon.ts
- app/models/node.ts
- app/models/user-addon.ts
- app/models/user.ts
- mirage/config.ts
- mirage/factories/external-account.ts
- mirage/factories/node-addon.ts
- mirage/factories/user-addon.ts
- mirage/fixtures/addons.ts
- mirage/scenarios/dashboard.ts
- mirage/scenarios/default.ts
- mirage/serializers/addon.ts
- mirage/serializers/external-account.ts
- mirage/serializers/node-addon.ts
- mirage/serializers/node.ts
- mirage/serializers/user-addon.ts
- mirage/serializers/user.ts
- mirage/views/external-account.ts
- mirage/views/node-addon.ts
-   Ticket: [ENG-4681]
Make the v2 endpoints work with mirage. This includes a lot of normalization of the API but not the extra features such as extended attributes for providers nor getting the folder lists.
1. Add mirage
2. Adjust models
[ENG-4681]: https://openscience.atlassian.net/browse/ENG-4681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4681] Add mirage for v2 api

- app/preprints/-components/branded-footer/styles.scss
- app/preprints/-components/preprint-author-assertions/component.ts
- app/preprints/-components/preprint-author-assertions/styles.scss
- app/preprints/-components/preprint-author-assertions/template.hbs
- app/preprints/-components/preprint-status-banner/component.ts
- app/preprints/-components/preprint-status-banner/styles.scss
- app/preprints/-components/preprint-status-banner/template.hbs
- mirage/fixtures/preprint-providers.ts
https://www.notion.so/cos/0de7c99478234fd7be57029dd96aa2d3?v=a4e6d7c70c004d27a0955aa2742775a4&p=c7b78078a9454234b8fcf168e4448b12&pm=c
-   Ticket: []
The preprint footer links for branded providers was too biased.
removed the css flex and changed it to be text-align: center
N/A
N/A
This bug should be working now.
https://www.notion.so/cos/0de7c99478234fd7be57029dd96aa2d3?v=a4e6d7c70c004d27a0955aa2742775a4&p=c7b78078a9454234b8fcf168e4448b12&pm=c
https://www.notion.so/cos/0de7c99478234fd7be57029dd96aa2d3?v=a4e6d7c70c004d27a0955aa2742775a4&p=6d048fec2c554fb2beae2d838bc63c77&pm=c
> Fixed the branded footer link for preprints

- app/models/provider.ts
- app/preprints/detail/template.hbs
- lib/osf-components/addon/components/citation-viewer/component.ts
- lib/osf-components/addon/components/citation-viewer/template.hbs
- mirage/config.ts
- mirage/scenarios/default.ts
- mirage/scenarios/preprints.ts
- mirage/serializers/preprint-provider.ts
- mirage/views/citation.ts
-   Ticket: [ENG-4567][[Notion Card]](https://www.notion.so/cos/Preprint-Detail-regression-Provider-s-default-citation-styles-are-not-supported-7c70a556020f4591b42bfd1440e93d1b?pvs=4)
- Allow provider to override default citation styles
- Mirage updates
- Update `<CitationStyles>` component to accept optional `@provider` argument and check if given provider has `citationStyles` defined
- Provider with default citation styles set
- Provider without default citation styles
- Default citation styles can be set in the admin app for a given preprint-provider
[ENG-4567]: https://openscience.atlassian.net/browse/ENG-4567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow provider-specfic default citation styles

- lib/app-components/addon/components/branded-navbar/styles.scss
- lib/app-components/addon/components/branded-navbar/template.hbs
-   Ticket: [[Notion Card]](https://www.notion.so/cos/iOSSafari-Labels-not-visible-in-hamburger-menu-icon-7d6e3cffa74247cd8746908dae090c06?pvs=4)
- Fix visibility issue of links for mobile branded navbar
- CSS updates to make the branded-navbar slightly less gross
- Remove `light-text` class, and just make white text the default
- Simplify `.white-background` by just using `.dark-text` to indicate which text-color to use
- Before photos in the notion card
- Biohackrxiv (special-cased to use white background and black text on desktop)
- Agrixiv (uses black text on desktop)
- Other provider with white text
> Fix branded navbar colors for mobile

- app/preprints/index/template.hbs
- mirage/scenarios/preprints.ts
Found during regression on live servers
-   Ticket: []
The "see example" button was attempting to go to a /content/<guid> route that was not ported from OSP.
Removed the "content" prefix
N/A
As long as the "example" is set admin, it will go to that preprint example. if the example is not set then it will go to the default OSF example.
Fill in the admin and click the button.
> See example hot fix

- app/models/identifier.ts
- app/models/preprint.ts
- mirage/config.ts
- mirage/factories/identifier.ts
- mirage/scenarios/preprints.ts
- mirage/serializers/preprint.ts
-   Ticket: []
- Fix plaudit widget
- Add `identifier` relationship to preprint pmodel
> [HOTFIX] Fix plaudit widget

- app/adapters/external-account.ts
- app/adapters/node-addon.ts
- app/adapters/user-addon.ts
- app/models/addon.ts
- app/packages/addons-service/legacy-provider.ts
- app/packages/addons-service/provider.ts
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/app/components/addons-service/manager/component.js
-   Ticket: [ENG-4685]
Start the development of the management component. This includes the mixing and sorting of the various provider types, creating abstracted providers for each api, and filling out some of the v2 api functionality.
1. Create management component
2. Create Provider and LegacyProvider
3. Add parent relationships to some models
4. Modify the addon model for the new way of serializing the addon category
Nah. It's not really hooked to anything yet.
Not QA-able yet.
[ENG-4685]: https://openscience.atlassian.net/browse/ENG-4685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [ENG-4685] Implement basic management component and providers

- app/institutions/discover/template.hbs
- Allow `q` query-param in URL to set the search textbox value
- Update query-param in component invocation that was missed in [previous PR](https://github.com/CenterForOpenScience/ember-osf-web/pull/2085)
- Institution discover page with the `q` query-param
- Enter an institution's discover page with the `q` query-param set to something (`https://staging3.osf.io/institutions/uva?q=some text here`), and the search text-box should be pre-populated
> Update qp name in search-page component invocation

- app/models/preprint.ts
- app/preprints/detail/route.ts
- mirage/factories/preprint.ts
- mirage/scenarios/preprints.ts
- mirage/serializers/preprint.ts
-   Ticket: [ENG-5055]
The withdrawn preprints are serving up a 404 error
I didn't know that a widthdrawn preprint didn't have a document. So when the route was fetching data is was attempting to update an attribute on an undefined object throwing an error and being redirected to the 404 page.
I added a conditional statement.
NA
None
All withdrawn preprints should now be visible.
[ENG-5055]: https://openscience.atlassian.net/browse/ENG-5055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5055] Fixed an issue that withdrawn preprints get a 404

- app/models/node-addon.ts
- tests/unit/models/node-addon-test.ts
-   Ticket: [ENG-5032]
- Add properties to v2 `node-addon` model to match what is found on the new addons service's `configured-storage-addon` model properties
- Added the following properties to the node-addon model
- `externalUserId`
- `externalUserDisplayName`
- `rootFolder`
- Add test
- NA
[ENG-5032]: https://openscience.atlassian.net/browse/ENG-5032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5032] Add proxy-properties to node-addon model

- lib/osf-components/addon/components/license-picker/component.ts
- lib/osf-components/addon/components/license-picker/template.hbs
- lib/registries/addon/components/registries-license-picker/component.ts
- lib/registries/addon/components/registries-license-picker/template.hbs
- translations/en-us.yml
-   Ticket: [ENG-5049]
- Fix broken links to license help guides
- Update license help guide link on draft registration metadata page
- Remove unneeded "License FAQ" link (previous link was broken anyway)
- Update "License FAQ" link on collection submission page
- On draft registration metadata page
- On collection submissions's "Project metadata" panel
[ENG-5049]: https://openscience.atlassian.net/browse/ENG-5049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5049] Update links to license help guide

- app/config/environment.d.ts
- app/router.ts
- app/settings/template.hbs
- config/environment.js
- mirage/factories/root.ts
-   Ticket: [ENG-5164]
Add a user settings addon page and start the waffling process.
1. Add gravy_waffle flag
2. Add route to settings.addons
3. Add template to settings.addons
4. Adjust menu item for settings.addons to conditionally route to new page if the flag is set
Should be side-effect free
This should only route to the new page on environments where the waffle flag above is set.
[ENG-5164]: https://openscience.atlassian.net/browse/ENG-5164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5164] Addons - User settings page

- app/preprints/index/template.hbs
- translations/en-us.yml
-   Ticket: [ENG-5225]
- Update "Submit a preprint" button label on the preprint landing page to use the provider's preprintWord
- Update translation string to use passed in `documentType`
- Remove unused translation string
- The green button here should have the appropriate preprint-word
- None
- This button only shows up if the preprint provider is currently accepting submissions. Please check the `allow_submissions` flag in the admin app for preprint-providers
- Please verify that the different preprint words used in production ("preprint", "paper", "thesis", and "work") all show up.
[ENG-5225]: https://openscience.atlassian.net/browse/ENG-5225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5225] Update submit button label

- app/guid-file/-components/file-detail-layout/styles.scss
- app/guid-file/-components/file-detail-layout/template.hbs
- app/guid-file/-components/file-header/styles.scss
- app/guid-file/index/styles.scss
- lib/osf-components/addon/components/cedar-metadata-renderer/component.ts
- lib/osf-components/addon/components/cedar-metadata-renderer/styles.scss
- lib/osf-components/addon/components/cedar-metadata-renderer/template.hbs
- lib/osf-components/addon/components/metadata/metadata-tabs/component.ts
- lib/osf-components/addon/components/tos-consent-banner/styles.scss
- mirage/scenarios/dashboard.ts
- mirage/scenarios/registrations.lite.ts
- mirage/serializers/cedar-metadata-record.ts
- translations/en-us.yml
-   Ticket: [https://www.notion.so/cos/Changing-tabs-does-not-change-the-URL-4edd6f28eb6746c888e0eb31dc50da4e]
When clicking on the tabs, the uri was not changing. Also add a share button
Added some code to replace the browser history when the tab was clicked.
Also added a "share" icon to copy the current uri to the clipboard on projects and registrations.
I will add it to files, once I figure out the routing.
Numerous when messing around with the browser history
Click on the tabs and the uri should change.
> Added a share icon and fixed the routing to reflect the current tab

- lib/osf-components/addon/components/addon-card/component.ts
- lib/osf-components/addon/components/addon-card/template.hbs
- tests/integration/components/addon-card/component-test.ts
-   Ticket: [ENG-5157]
Make the disable addon workflow work.
1. Performed the task
[ENG-5157]: https://openscience.atlassian.net/browse/ENG-5157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5157] Make disableAddon disable the addon

- app/guid-node/addons/index/styles.scss
- app/guid-node/addons/index/template.hbs
- app/packages/addons-service/provider.ts
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/manager/template.hbs
- mirage/config.ts
- mirage/serializers/configured-storage-addon.ts
- mirage/views/addons.ts
- translations/en-us.yml
-   Ticket: [ENG-5149]
- Allow users to select an existing account to enable for a project
- Update AccountSelect view of addons page to support selection of existing account
- Update Confirm view of addons page to support confirming selected account
- Add `createConfiguredStorageAddon` on the Provider class when a user configures a storage-addon to a node
- Choosing an account
- Confirming the chosen account
[ENG-5149]: https://openscience.atlassian.net/browse/ENG-5149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5149] Choose account workflow for addons

- app/guid-node/metadata/add/route.ts
- app/guid-node/metadata/detail/route.ts
- lib/osf-components/addon/components/metadata/metadata-tab-view/styles.scss
- lib/osf-components/addon/components/metadata/metadata-tab-view/template.hbs
- lib/osf-components/addon/components/metadata/metadata-tabs/component.ts
- lib/osf-components/addon/components/metadata/metadata-tabs/styles.scss
- lib/osf-components/addon/components/metadata/metadata-tabs/template.hbs
- lib/registries/addon/overview/metadata/add/route.ts
- lib/registries/addon/overview/metadata/detail/route.ts
-   Ticket: [N/A]
Speed up loading of the metadata detail and add pages
Added the `embed` attribute for the cedar record template. This downloads the template and then stores it in the cache.
Now that I think about it, this is a good change and a red herring. I have set-up the mirage scenario to add 2 to 10 cedars with the same template which is impossible in production. So locally, the page speed was a lot longer than likely possible in production. 
At the end of the day, this change will still be beneficial overall.
N/A
Page loading speed up
No difference
> Enabled the embedding of templates on cedar records

- app/settings/addons/controller.ts
- app/settings/addons/route.ts
- app/settings/addons/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/template.hbs
- lib/osf-components/app/components/addons-service/user-addons-manager/component.js
- lib/osf-components/app/components/addons-service/user-addons-manager/template.js
-   Ticket: [ENG-5165]
- Add manager componenet for user-addons
- Add user-addon-manager component
- WIP view of User > Settings > Addons page
[ENG-5165]: https://openscience.atlassian.net/browse/ENG-5165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5165] Add user-addons-manager component

- app/preprints/detail/route.ts
- mirage/factories/preprint.ts
- mirage/scenarios/preprints.ts
-   Ticket: []
- Make sure preprint detail page head tags show correct date, and not show that all preprints were published today
- Use `Preprint.datePublished` instead of non-existent `Preprint.dateRegistered`
- Before
- After
> Make preprint head tags show correct created/published dates

- lib/osf-components/addon/components/metadata/metadata-tabs/styles.scss
- Update styling to prevent all content in metadata panel to have the cursor set to be a pointer
- Update CSS to restrict cursor styling to appropriate element
- Prevent issue where highlighted area will always have the cursor show up as a pointer regardless of hover-target (this is on file and node metadata pages)
- Should fix issue where the mouse cursor is pointer in the metadata panel of files and nodes
> [No ticket] Update styling

- app/settings/addons/styles.scss
- app/settings/addons/template.hbs
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/template.hbs
- mirage/config.ts
- translations/en-us.yml
-   Ticket: [ENG-5166]
- Show list of enabled addons in the user settings page
- Add section to user settings page
- Update user-addons-manager
- Mirage and translation updates
- User settings > Addons page
[ENG-5166]: https://openscience.atlassian.net/browse/ENG-5166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5166] Show user enabled addons

- app/guid-node/addons/index/template.hbs
- app/packages/addons-service/provider.ts
- app/settings/addons/styles.scss
- app/settings/addons/template.hbs
- lib/osf-components/addon/components/addon-card/component.ts
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/template.hbs
- tests/integration/components/addon-card/component-test.ts
- tests/unit/packages/addons-service/provider-test.ts
-   Ticket: [ENG-5165]
- Allow users to filter addons on user settings page
- Add filter logic to user addons manager
- Update user settings addon page template
- Update user-addon-manager component to support different addon types
- Update addon manager component to support different addon types
- Update Provider class to support differnt addon types
- User settings, addons page
[ENG-5165]: https://openscience.atlassian.net/browse/ENG-5165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5165] Filter user addons

- app/models/authorized-citation-account.ts
- app/models/authorized-computing-account.ts
- app/models/authorized-storage-account.ts
- lib/osf-components/addon/components/addons-service/manager/component.ts
-   Ticket: [ENG-5151]
- Support different credential types for addons
- Add `credentials` attr to all authorizied-account types
- Clear credentials after making the account or cancelling account setup
NA
NA
[ENG-5151]: https://openscience.atlassian.net/browse/ENG-5151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5151] Addon credentials

- lib/osf-components/addon/components/addons-service/account-setup-manager/styles.scss
- lib/osf-components/addon/components/addons-service/account-setup-manager/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/manager/template.hbs
- mirage/config.ts
- mirage/views/addons.ts
-   Ticket: [ENG-5155]
- Show validation messages and errors in addon auth flow
- Update mirage view to pretend to validate auth credentials
- Show toast with backend error message
- Add validation message if account connect task fails
[ENG-5155]: https://openscience.atlassian.net/browse/ENG-5155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5155] Pretend check addon auth credentials in mirage

- app/guid-node/addons/index/template.hbs
- app/models/authorized-citation-account.ts
- app/models/authorized-computing-account.ts
- app/models/authorized-storage-account.ts
- app/models/external-storage-service.ts
- app/packages/addons-service/provider.ts
- lib/osf-components/addon/components/addons-service/account-setup-manager/component.ts
- lib/osf-components/addon/components/addons-service/account-setup-manager/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/manager/template.hbs
- mirage/views/addons.ts
- translations/en-us.yml
-   Ticket: [ENG-5159]
- Support OAuth workflow on Node Addons page
- Add `authUrl` and `isAuthorized` attributes to AuthorizedStorageAccount models and its friends
- Update account-setup-manager component to handle OAuth workflow
- Update addons-service/manager component to handle OAuth workflow
- Update Node Addons page to handle OAuth workflow
- Add mirage views
- Fix some bad patterns I introduced into Provider class
- This doesn't translate to screenshots very well. Probably best to check it out locally and go through it
[ENG-5159]: https://openscience.atlassian.net/browse/ENG-5159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5159] Oauth

- app/preprints/index/template.hbs
-   Ticket: [ENG-5482](https://openscience.atlassian.net/browse/ENG-5482)
Fix Redirect Issue for "See all subjects available" Link on Branded Preprint Landing Page
Adjusted the OsfLink component within the preprint landing page template to dynamically construct the redirect URL based on the preprint provider's id. 
[ENG-5482]: https://openscience.atlassian.net/browse/ENG-5482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ENG-5482 Fix Redirect Issue for "See all subjects available" Link on Branded Preprint Landing Page

- app/guid-node/controller.ts
- app/guid-node/files/provider/route.ts
- app/guid-node/files/provider/template.hbs
- app/guid-node/template.hbs
- app/models/configured-storage-addon.ts
- app/packages/files/service-file.ts
- app/packages/files/service-provider-file.ts
- lib/osf-components/addon/components/file-browser/breadcrumbs/crumb/component.ts
- lib/osf-components/addon/components/file-browser/breadcrumbs/crumb/template.hbs
- lib/osf-components/addon/components/file-browser/breadcrumbs/template.hbs
- lib/osf-components/addon/components/file-provider-menu/component.ts
- lib/osf-components/addon/components/file-provider-menu/template.hbs
- lib/osf-components/addon/components/move-file-modal/component.ts
- lib/osf-components/addon/components/move-file-modal/list-item/template.hbs
- lib/osf-components/addon/components/storage-provider-manager/storage-manager/component.ts
- mirage/scenarios/dashboard.ts
- tests/engines/registries/acceptance/overview/files-test.ts
- translations/en-us.yml
-   Ticket: [ENG-5174]
-   Feature flag:`gravy_waffle`
Allow the files page to work with the addons service.
1. Add service-file and service-provider-file classes to take advantage of having configuredStorageAddons
2. Use service-file and service-provider-file classes when `gravy_waffle` flag is active and not using `osfstorage` as a provider.
3. Update mirage
4. Add ConnectedCapabilities and ConnectedOperationNames enums and use them
5. Fix breadcrumbs
6. Fix move/copy dialog
7. Fix left sidebar menu
8. Fix tests
The worst is that I might have broken functionality for non-gravy-waffled environments, but I thiiiink it's okay? 
Make sure this doesn't break environments that are not running the feature flag.
[ENG-5174]: https://openscience.atlassian.net/browse/ENG-5174?atlOrigin=eyJpIjoiNWRk …
> [ENG-5174] Service files

- app/models/external-citation-service.ts
- app/models/external-computing-service.ts
- app/models/external-storage-service.ts
- app/packages/addons-service/provider.ts
- app/settings/addons/styles.scss
- app/settings/addons/template.hbs
- lib/osf-components/addon/components/addon-card/component.ts
- lib/osf-components/addon/components/addons-service/account-setup-manager/template.hbs
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/template.hbs
- mirage/fixtures/external-citation-service.ts
- mirage/fixtures/external-computing-service.ts
- mirage/fixtures/external-storage-services.ts
- tests/integration/components/addon-card/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-5168]
- Allow users to add new addon accounts in their user settings page
- Make node argument optional for Provider class
- Update user-addons-manager to handle auth workflows
- Update external-service models
- Update user-settings addon page to allow for auth workflows
- Desktop (adding new Amazon S3 account)
- Mobile (adding new Dataverse account)
- Hopefully none and the auth workflow for project addons works great still
[ENG-5168]: https://openscience.atlassian.net/browse/ENG-5168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5168] User addon credentials

- app/services/theme.ts
- lib/app-components/addon/components/branded-navbar/component.ts
- lib/app-components/addon/components/branded-navbar/template.hbs
- lib/osf-components/addon/components/osf-navbar/preprint-links/template.hbs
-   Ticket: [ENG-5298](https://openscience.atlassian.net/browse/ENG-5298) and [ENG-5317](https://openscience.atlassian.net/browse/ENG-5317)
Update "Add/Submit a preprint" button for OSF and branded providers
This PR replaces https://github.com/CenterForOpenScience/ember-osf-web/pull/2186 and https://github.com/CenterForOpenScience/ember-osf-web/pull/2187
* "Add a preprint/thesis/paper" in both branded and OSF nav-bar now use in-app transition
* "Add a preprint" in OSF nav-bar goes to the new preprints select provider page
* "Add a preprint/thesis/paper" in branded nav-bar goes directly to the branded submit page
* "Submit a preprint/thesis/paper" in both branded and OSF nav-bar goes directly to respective submit page
* Added `data-test` and/or `data-analytics` …
> [ENG-5298] [ENG-5317] Update "Add/Submit a preprint" button for OSF and branded providers

- app/preprints/detail/template.hbs
-   Ticket: [ENG-5316](https://openscience.atlassian.net/browse/ENG-5316)
Update "edit preprint" link
* Replace `href` with in-app transition
* This PR has two assumptions:
*  First, the new route for edit a preprint is `preprints.edit` (to-be implemented)
*  Seconde, the new route needs two models, one is provider and the other is the preprint (since the to-be-implemented URL is `/preprints/<provider_id>/<preprint_id>/edit`) 
See **Purpose**
N/A
N/A
N/A
[ENG-5316]: https://openscience.atlassian.net/browse/ENG-5316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5316] Update "edit preprint" link

- lib/osf-components/addon/components/registries/schema-block-renderer/helper-text-icon/template.hbs
-   Ticket: [ENG-3769](https://openscience.atlassian.net/browse/ENG-3769)
Fix a11y of an SVG icon on draft registration pages
- Changed @ariaHidden to ensures the SVG icon is not hidden.
- Added aria-label.
[ENG-3769]: https://openscience.atlassian.net/browse/ENG-3769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ENG-3769: Fix a11y issue on draft registration pages

- app/models/authorized-citation-account.ts
- app/models/authorized-computing-account.ts
- app/models/authorized-storage-account.ts
- app/packages/addons-service/provider.ts
- app/settings/addons/controller.ts
- app/settings/addons/styles.scss
- app/settings/addons/template.hbs
- ember-cli-build.js
- lib/osf-components/addon/components/addons-service/account-setup-manager/template.hbs
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/template.hbs
- lib/osf-components/addon/components/delete-button/component.ts
- lib/osf-components/addon/components/delete-button/template.hbs
- mirage/scenarios/dashboard.ts
- translations/en-us.yml
-   Ticket: [ENG-5455]
- Add tabs on user settings addon page
- Add tabs to User Settings Addons page
- Hide whitespace is advised on the templates
- Update user-settings-manager to support these tabs, and update method names to make a bit more sense
- Update delete-button component to be able to render a new size
- 
- All Addons tab
- All Addons tab (mobile)
- Terms  page with new "Cancel" button
- Authorized Accounts tab
- Authorized Accounts tab (mobile)
[ENG-5455]: https://openscience.atlassian.net/browse/ENG-5455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5455] User settings tab

- app/packages/addons-service/provider.ts
- lib/osf-components/addon/components/addons-service/manager/component.ts
- tests/unit/packages/addons-service/provider-test.ts
-   Ticket: [ENG-5539]
Start to build the infrastructure for having multiple configured addons per external service.
1. Have tasks get multiple addons
2. Add placeholder in state machine for the configuration list
This is not really tested and shouldn't do a lot just yet. Will need work for [ENG-5454] to make it do stuff.
[ENG-5539]: https://openscience.atlassian.net/browse/ENG-5539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-5454]: https://openscience.atlassian.net/browse/ENG-5454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5539] Multiple configured addons per addon

- app/models/configured-citation-addon.ts
- app/models/configured-computing-addon.ts
- app/models/configured-storage-addon.ts
- app/packages/addons-service/provider.ts
- app/packages/files/service-file.ts
- app/packages/files/service-provider-file.ts
- lib/osf-components/addon/components/addons-service/manager/component.ts
- mirage/config.ts
- mirage/scenarios/dashboard.ts
- mirage/views/addons.ts
-   Ticket: [ENG-5454]
Do better at getting the configured addons
1. Fix typo for ConnectedOp~a~erationNames
2. Get all configured addons at once for a node
3. Mirage up some endpoints and views
4. Fix configuration
5. Move manager constructor tasks to an initialize function so they can be done synchronously
This passed the addons-services tests locally, and it runs, so it probably doesn't have a lot of side effects.
[ENG-5454]: https://openscience.atlassian.net/browse/ENG-5454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5454] Addons/Multiple Configured Addons part 2 / 3

- app/models/preprint-provider.ts
- app/preprints/index/route.ts
- app/preprints/index/template.hbs
- mirage/fixtures/preprint-providers.ts
- tests/acceptance/preprints/index-test.ts
-   Ticket: [[ENG-4839]](https://openscience.atlassian.net/browse/ENG-4839)
Implement Visibility Control for Preprint Providers on Discover Page
- Added a new attribute to track whether a preprint provider should be advertised on the discover page.
- Integrated the advertiseOnDiscoverPage attribute in the condition to render preprint provider logos.
[ENG-4839]: https://openscience.atlassian.net/browse/ENG-4839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ENG-4839 Implement Visibility Control for Preprint Providers on Discover Page

- app/guid-node/addons/index/styles.scss
- app/guid-node/addons/index/template.hbs
- app/packages/addons-service/provider.ts
- lib/osf-components/addon/components/addon-card/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/manager/template.hbs
- tests/integration/components/addon-card/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-5454]
Allow multiple addons to be configurable. This updates the template and supporting ts files.
1. Add configurationList page mode to the template
2. Update some text to match mockups
3. Style
4. Add function to remove a configured addon
[ENG-5454]: https://openscience.atlassian.net/browse/ENG-5454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5454] Addons/multiple configured addons part 3

- app/models/node.ts
- lib/osf-components/addon/components/node-metadata-form/template.hbs
- lib/osf-components/addon/components/subjects/browse/browse-manager/component.ts
- lib/osf-components/addon/components/subjects/manager/component.ts
- lib/osf-components/addon/components/subjects/manager/template.hbs
- mirage/config.ts
- mirage/models/subject.ts
- mirage/serializers/node.ts
- mirage/views/provider-subjects.ts
- mirage/views/subjects-acceptable.ts
- tests/acceptance/guid-node/metadata-test.ts
-   Ticket: [[ENG-4354](https://openscience.atlassian.net/browse/ENG-4354)]
To integrate an editable subjects widget into the project metadata editor
- Added subjectsAcceptable property to the Node model for project-specific subjects.
- Updated SubjectManagerComponent to handle nodes without providers.
- Modified BrowseManagerComponent to load subjectsAcceptable if the provider is not present.
- Integrated the subjects widget into the node metadata form template for projects.
[ENG-4354]: https://openscience.atlassian.net/browse/ENG-4354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Editable Subjects Widget to Project Metadata Editor

- app/search/controller.ts
- lib/registries/addon/branded/discover/template.hbs
- mirage/views/search.ts
-   Ticket: https://openscience.atlassian.net/browse/ENG-5228
Fix search text not populating as query parameter and correct filter-value preview counts.
- Renamed cardSearchText to q and @query to @cardSearchText in the search page controller and templates.
- Adjusted filter-value preview counts to reflect the current search context's result count.
> Fix Search Text and Filter-Value Issues on OSF Search Page

- app/guid-node/addons/index/template.hbs
- lib/osf-components/addon/components/addons-service/addon-account-setup/template.hbs
-   Ticket: [ENG-5161]
- Ensure new interactable elements have analytics associated with them
- Add analytics names and scopes to new addon pages (best to hide whitespace changes)
- NA
[ENG-5161]: https://openscience.atlassian.net/browse/ENG-5161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5161] Analytics

- app/preprints/-components/submit/metadata/template.hbs
- lib/osf-components/addon/components/contributors/widget/template.hbs
- lib/osf-components/addon/components/form-controls/radio-button-group/radio-button/template.hbs
-   Ticket: [N/A]
There was a double header found on the percy snapshots
Removed the header from the widget template.hbs file and added it to the submit/metadata/template.hbs file
Should not be any
You should never even know this happened.
> Fixed a double header on the registries contributors

- app/guid-node/addons/index/template.hbs
- lib/osf-components/addon/components/addons-service/addon-account-setup/component.ts
- lib/osf-components/addon/components/addons-service/addon-account-setup/template.hbs
- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
- tests/acceptance/guid-node/addons-test.ts
- tests/acceptance/guid-node/metadata-test.ts
-   Ticket: [ENG-5158]
- Add acceptance tests for node addons workflows
- Add tests
- Add data-test selectors
- Some minor bugfixes discovered along the way
- Discovered an issue where adding a configured account doesn't show up on the addons page. Will address this in a later PR
- NA
[ENG-5158]: https://openscience.atlassian.net/browse/ENG-5158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5158] Add node addons acceptance tests

- app/preprints/-components/submit/file/upload-file/component.ts
- Address bug found in this slack thread: https://centerforopenscience.slack.com/archives/C065UH8B5KP/p1721139827554269
- Issue when uploading a new version of a file with the same name in the edit workflow
- Detect if a new file version has a different name and only do a `File.rename` if the name has changed
> [No ticket] Preprint file upload bug

- app/packages/addons-service/provider.ts
-   Ticket: [ENG-5950]
- Address a bug where adding a new configured account for a provider with no configured account does not update the Addon-card to indicate it has a configured account
- After creating a configured addon, add this new configuredAddon to the list of Provider's `configuredAddons` list
- Remove unused `listOfFolders` method
- Rewrite how `Provider.configuredAddons` gets set to make it less weird and confusing
- On the node addons page, the addon cards should be change from `Connect` to `Configure` when you add a new configured account to a provider that previously had no configured account
- NA
- Adding/removing a configured addon for a given provider should update the language on the addon-card in the screenshot above
[ENG-5950]: …
> [ENG-5950]Configured addon bugs

- app/guid-node/addons/index/template.hbs
- app/models/authorized-account.ts
- app/models/authorized-storage-account.ts
- app/models/external-service.ts
- app/models/external-storage-service.ts
- app/packages/addons-service/provider.ts
- app/settings/addons/template.hbs
- lib/osf-components/addon/components/addons-service/addon-account-setup/component.ts
- lib/osf-components/addon/components/addons-service/addon-account-setup/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/manager/template.hbs
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/template.hbs
- mirage/views/addons.ts
- tests/acceptance/guid-node/addons-test.ts
- tests/acceptance/settings/addons-test.ts
-   Ticket: [ENG-5951]
- Address some bugs in the authorized-account creation process
- Need to remove `AuthorizedAccount.credentials.url` and `AuthorizedAccount.credentials.repo` out and use `AuthorizedAccount.apiBaseUrl` instead
- Should be able to rename accounts when reconnecting
- Move `apiBaseUrl` to `AuthorizedAccount` superclass
- Move `configurableApiRoot` to `ExternalService` superclass
- Move some logic that was for account creation out of the manager component and into the addon-account-setup component
- Moved `displayName`, `credentialsObject` and `connectAccountError`, and other methods
- Change method args for account creation
- Allow users to change name on account reconnect
- Update Dataverse repo options to include "https://"
- Remove …
> [ENG-5951] Authorized account bugs

- app/models/node.ts
-   Ticket: [ENG-5974]
- Make files page a bit more robust with waffle flag `gravy_waffle`
- Add try-catch around getting node addons, so page load doesn't break
- NA
- Ideally the files page won't break as things change with how we get addons
[ENG-5974]: https://openscience.atlassian.net/browse/ENG-5974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5974] Add try-catch when getting addons

- app/models/abstract-node.ts
- app/models/preprint.ts
- app/models/registration.ts
- app/models/review-action.ts
- app/preprints/-components/submit/preprint-state-machine/component.ts
- tests/unit/models/review-action-test.ts
-   Ticket: [https://openscience.atlassian.net/browse/ENG-5994]
Fix Preprint Resubmission Workflow to Ensure Proper Moderation Handling
- Added a hasMany relationship to review-action with the inverse set to target.
- Changed the belongsTo relationship from registration to abstract-node with the inverse set to reviewActions.
- Removed the conditional check for isEditFlow to ensure the review action is correctly triggered during both initial submission and edits.
> [ENG-5994] Fix Preprint Resubmission Workflow to Ensure Proper Moderation Handling

- mirage/config.ts
- mirage/views/user.ts
-   Ticket: [[ENG-6015]](https://openscience.atlassian.net/browse/ENG-6015)
Added a new endpoint to Mirage to handle requests for fetching a list of preprints associated with a specific user.
- Added `userPreprintList` function to `mirage/views/user.ts` to fetch and filter preprints associated with a user's contributors.
- Configured the new `/users/:id/preprints` endpoint in `mirage/config.ts` to use the `userPreprintList` function for retrieving preprint data.
[ENG-6015]: https://openscience.atlassian.net/browse/ENG-6015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6015] Add User Preprint List Endpoint to Mirage Server

- app/institutions/dashboard/-components/institutional-dashboard-wrapper/styles.scss
- app/institutions/dashboard/-components/institutional-dashboard-wrapper/template.hbs
- lib/osf-components/addon/components/osf-link/component.ts
- lib/osf-components/addon/components/osf-link/styles.scss
- lib/osf-components/addon/components/osf-link/template.hbs
- translations/en-us.yml
-   Ticket: []
- Address some CR comments from prior PR https://github.com/CenterForOpenScience/ember-osf-web/pull/2296
- Add a new arg `@fakeButton` to `OsfLink` to easily make a link look like a button (which maybe isn't a pattern we want to encourage, but at least now it's DRY when we do it 😬 )
- Update wording for hover text for reports
- Have link open in a new window
> Link to reports updates

- app/adapters/share-adapter.ts
- app/models/index-card.ts
- mirage/config.ts
- mirage/utils.ts
- mirage/views/search.ts
-   Ticket: [ENG-6181]
- Update mirage view for trove index-card-search to return some more realistic results
- Replace placekittens with placecats
- Remove hard-coded return object in mirage/views/search.ts
- add a new factory-type object that creates resourceMetadata for index-cards of a given type
- search page with richer metadata fields!
Projects:
Registrations:
Preprints:
Files:
Users:
- None, really. The search page and search-result-card component should be a bit better testable now, but I don't know if I want to blow up the scope of this ticket just yet...
- This is to update the info returned in mirage (our fake backend), so this should have no testable bit from QA team
[ENG-6181]: https://openscience.atlassian.net/browse/ENG-6181?atlOrigin=eyJpIjoiNWRkNTljN …
> [ENG-6181] Update search mirage view

- app/institutions/dashboard/-components/institutional-users-list/component.ts
- app/institutions/dashboard/-components/institutional-users-list/styles.scss
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
- app/styles/_variables.scss
- lib/osf-components/addon/components/sort-arrow/component.ts
- translations/en-us.yml
-   Ticket: [https://openscience.atlassian.net/browse/ENG-6117]
Add the ability to filter users by Orcid status, ensure filter works with sorting.
- adds slider inputs to user institutional dashboard tab
- adds component code to make Orcid filters work
- adds template code for layout.
> [ENG-6117] Add Filter for Orcid on Instutional Dashboard

- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
- tests/acceptance/guid-node/addons-test.ts
- tests/integration/components/addons-service/configured-addon-edit/component-test.ts
-   Ticket: []
- Loosen criteria for save button being disabled when creating and configuring a configured addon
- Allow any non-empty name for display name
- Previous logic included a condition that the save button would be disabled if the display name had not been changed
- Allow rootFolder to be empty
- Only time the save button will be disabled is if the display name field is empty
> Loosen criteria for disabling save button for configured addons

- lib/osf-components/addon/components/osf-navbar/preprint-links/template.hbs
-   Ticket:[ [ENG-6011]](https://openscience.atlassian.net/browse/ENG-6011)
Link 'My Preprints' on navbar to new page
Change the link of the My Preprints button on the preprints navbar to link to the new My Preprints page.
[ENG-6011]: https://openscience.atlassian.net/browse/ENG-6011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6011] Link My Preprints on nav bar to new page

- app/institutions/dashboard/-components/institutional-dashboard-wrapper/styles.scss
- app/institutions/dashboard/-components/institutional-dashboard-wrapper/template.hbs
- app/institutions/dashboard/-components/object-list/component.ts
- app/institutions/dashboard/-components/object-list/styles.scss
- app/institutions/dashboard/-components/object-list/template.hbs
- app/institutions/dashboard/projects/controller.ts
- app/institutions/dashboard/projects/template.hbs
- lib/osf-components/addon/components/index-card-searcher/component.ts
- lib/osf-components/addon/components/osf-layout/component.ts
- lib/osf-components/addon/components/osf-layout/main-column/template.hbs
- lib/osf-components/addon/components/osf-layout/template.hbs
- mirage/views/search.ts
- translations/en-us.yml
-   Ticket: [ENG-6183]
- Add filtering capability to Institutional Dashboard's Project page
- Update mirage's index-value-search view to handle filterable values
- Add filtering logic to the page and show active filters on right-sidebar
- Update OsfLayout to be able to manually set the left and right sidebar behavior regardless of device size
- Add total results count to object-list component
- desktop
- mobile
[ENG-6183]: https://openscience.atlassian.net/browse/ENG-6183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6183] Project list filtering

- app/institutions/dashboard/-components/object-list/component.ts
- app/institutions/dashboard/-components/object-list/styles.scss
- app/institutions/dashboard/-components/object-list/template.hbs
- app/institutions/dashboard/projects/controller.ts
- lib/osf-components/addon/components/sort-arrow/component.ts
- translations/en-us.yml
-   Ticket: [ENG-6184]
- Allow sorting for project table
- Add new optional `sortKey` to project column object
- Show sort arrow if the sortKey is present on the column
- Styling updates
- Add pagination links to object list
- Desktop
- Mobile
[ENG-6184]: https://openscience.atlassian.net/browse/ENG-6184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6184] Allow sorting for project list

- lib/registries/addon/components/registries-metadata/component.ts
- lib/registries/addon/components/registries-metadata/template.hbs
- tests/engines/registries/acceptance/overview/overview-test.ts
-   Ticket: [https://openscience.atlassian.net/browse/ENG-5879]
Hide Categories Section on Registrations
- Modified the registries-metadata component template to hide the categories field.
- Set a hideCategories flag in the component to control the visibility of the categories section.
> [ENG-5879] Hide Categories Section on Registrations

- app/institutions/dashboard/-components/total-count-kpi-wrapper/component-test.ts
- app/institutions/dashboard/-components/total-count-kpi-wrapper/component.ts
- app/models/institution-summary-metric.ts
-   Ticket: []
Fix little typo in dashboard summary that was preventing the preprint count from showing.
- two small refactors from `prepirntCount` to `publishedPreprintCount`
> fix preprint typo for institutional dashboard

- app/models/institution-user.ts
- Update institution-user date fields to be strings to avoid a bug where month data would be shown incorrectly
- Don't use `date` transform for InstitutionUser model's `monthLastLogin`, `monthLastActive`, and `accountCreationDate`
- Use of this transform was causing problems with the display of these fields as the API would return `account_creation_date: "2024-10"`, but the `date` [transform would convert](https://github.com/emberjs/data/blob/v3.28.8/packages/serializer/addon/-private/transforms/date.js#L40) that to `9/2024` depending on timezone
(e.g. `new Date('2024-10') // Mon Sep 30 2024 20:00:00 GMT-0400 (Eastern Daylight Time) {}`)
- Prevents this issue (Note the date in the API response and the date displayed in the table):
- Great …
> Update month data fields to be strings

- app/institutions/dashboard/-components/institutional-users-list/component.ts
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
-   Ticket: https://openscience.atlassian.net/browse/ENG-6370
Make the total user count update as the number of users is filtered by orcid or department.
- pass the totalCount attribute from the paginated list to the component 
- display that new attribute in the template
- remove old totalUsers code.
> [ENG-6370] Update total user for dashboard label

- app/models/addon-operation-invocation.ts
- app/models/configured-storage-addon.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/template.hbs
- lib/osf-components/addon/components/addons-service/file-manager/component.ts
- mirage/views/addons.ts
- tests/acceptance/guid-node/addons-test.ts
- translations/en-us.yml
-   Ticket: [ENG-6346]
- Address a bug where the root folder picker doesn't show the correct folder content when widget loads (shows root folder's parent, not root folder's contents). See video in ticket for better description
- Update types
- Set currentFolder to be the explicit Id of the starting folder
- Always show Home option in breadcrumbs
- Prevents this bug where "All Files" is apparently the current folder content that you are viewing, and while also only showing the "All Files item"
- Should look like this if "All Files" is the selected root folder upon loading this page:
- Should look like this if no root folder is selected
[ENG-6346]: https://openscience.atlassian.net/browse/ENG-6346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
> [ENG-6346] Update logic to set initial folder id in file manager

- lib/osf-components/addon/components/node-card/template.hbs
- lib/registries/addon/drafts/draft/metadata/controller.ts
- lib/registries/addon/drafts/draft/metadata/template.hbs
- tests/engines/registries/acceptance/branded/new-test.ts
- tests/engines/registries/acceptance/draft/draft-test.ts
-   Ticket: [https://openscience.atlassian.net/browse/ENG-5879]
Hide Categories Section for Draft Registrations
- Added hideCategories Flag
- Added Conditional Category Display for draft registrations
> [ENG-5879] Hide Categories Section for Draft Registrations

- app/institutions/dashboard/-components/chart-kpi-wrapper/chart-kpi/component.ts
- app/institutions/dashboard/-components/chart-kpi-wrapper/chart-kpi/styles.scss
- app/institutions/dashboard/-components/chart-kpi-wrapper/chart-kpi/template.hbs
- app/institutions/dashboard/-components/chart-kpi-wrapper/component-test.ts
- app/institutions/dashboard/-components/chart-kpi-wrapper/component.ts
- mirage/factories/institution-summary-metric.ts
- translations/en-us.yml
- types/ember-cli-chart.d.ts
-   Ticket: [ENG-6368]
- Hook up graphs for licenses, addon usage and storage locations to actual data
- Add loading/error state to chart component
- Add task to fetch data from SHARE to chart-wrapper component
- Finished graphs:
- Loading/error states:
[ENG-6368]: https://openscience.atlassian.net/browse/ENG-6368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6368] Share summary graphs

- app/institutions/dashboard/registrations/controller.ts
- app/institutions/dashboard/registrations/route.ts
- app/institutions/dashboard/registrations/template.hbs
- mirage/views/search.ts
- tests/acceptance/institutions/dashboard-test.ts
- translations/en-us.yml
-   Ticket: [ENG-6270] [ENG-6273] [ENG-6274]
- Add table to registration tab
- Adds sort, filter, and customize functionality as well
- invoke `ObjectList` component in institutional dashboard registrations tab
- Add controller to institutional dashboard registrations route to define which columns to show
[ENG-6270]: https://openscience.atlassian.net/browse/ENG-6270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-6274]: https://openscience.atlassian.net/browse/ENG-6274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-6273]: https://openscience.atlassian.net/browse/ENG-6273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6270][ENG-6273][ENG-6274] Add registration table

- app/institutions/dashboard/-components/institutional-users-list/styles.scss
-   Ticket: [https://openscience.atlassian.net/browse/ENG-6401]
Stop narrow screens for scroll squishing the total user count numbers
- simple css change
> [ENG-6401] Fix mobile users count dashboard

- app/guid-node/addons/index/template.hbs
- app/models/addon-operation-invocation.ts
- app/models/configured-addon.ts
- app/models/configured-citation-addon.ts
- app/models/configured-storage-addon.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/template.hbs
- lib/osf-components/addon/components/addons-service/file-manager/component.ts
- lib/osf-components/addon/components/addons-service/manager/component.ts
- mirage/scenarios/dashboard.ts
- mirage/serializers/configured-citation-addon.ts
- mirage/serializers/configured-computing-addon.ts
- mirage/views/addons.ts
- tests/integration/components/addons-service/configured-addon-edit/component-test.ts
-   Ticket: [ENG-6428]
- Allow root-folder to be chosen for configured-citation-addons
- Move tasks for creating `addon-operation-invocations` to the `configured-addons` superclass
- Update imports and such
For setting up Mendeley for example:
[ENG-6428]: https://openscience.atlassian.net/browse/ENG-6428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6428] Allow citation addons to pick root folder

- lib/osf-components/addon/components/addons-service/addon-account-setup/component.ts
- lib/osf-components/addon/components/addons-service/addon-account-setup/template.hbs
- translations/en-us.yml
-   Ticket: [ENG-6320]
- Show a link to open the OAuth window in case the new window gets blocked
- Add a new link when the page is pending OAuth
- Add some language letting folks know that there hould be an OAuth window opening
[ENG-6320]: https://openscience.atlassian.net/browse/ENG-6320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6320] Show link to start oauth

- app/packages/addons-service/provider.ts
- Prevent GV from responding with a 400 error when POSTing a new `configured-citation-addon`
- Include `rootFolder: ''` when creating a new `configured-citation-addon` and `configured-computing-addon`
- Prevents this error
> [No ticket] Prevent 400 when POSTing configured-citation-addon

- app/institutions/dashboard/preprints/controller.ts
- app/institutions/dashboard/preprints/route.ts
- app/institutions/dashboard/preprints/template.hbs
- tests/acceptance/institutions/dashboard-test.ts
-   Ticket: [ENG-6276] [ENG-6277] [ENG-6278]
- Add table for preprints in institutional dashboard
- Add `object-list` component to institutional dashboard preprint tab
- Add controller to determine which columns to show
- Update tests
[ENG-6276]: https://openscience.atlassian.net/browse/ENG-6276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-6277]: https://openscience.atlassian.net/browse/ENG-6277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-6278]: https://openscience.atlassian.net/browse/ENG-6278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6276][ENG-6277][ENG-6278] Add Preprints table

- lib/osf-components/addon/components/addons-service/addon-account-setup/component.ts
- lib/osf-components/addon/components/addons-service/addon-account-setup/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- translations/en-us.yml
-   Ticket: [ENG-6345]
- Add logic to prevent moving forward in account creation if OAuth flow fails
- check `credentialsAvailable` flag in oauthRefocus callback and proceed or don't based on this flag
- Add some message to show that OAuth failed
[ENG-6345]: https://openscience.atlassian.net/browse/ENG-6345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6345] Failed OAuth workflow

- app/models/configured-addon.ts
- app/serializers/configured-addon.ts
- app/serializers/configured-citation-addon.ts
- app/serializers/configured-computing-addon.ts
- app/serializers/configured-storage-addon.ts
- Prevent 400 errors when PATCHing configured addons 
- Remove the `authorizedResourceUri` attr in PATCH requests to configured-xyz-addons if `authorizedResourceUri` is `null`
- NA
> [No ticket] Prevent 400 errors when PATCHing configured addons

- app/institutions/dashboard/route.ts
- Fix when users are rerouted from the dashboard to the `not-found` page for whatever reason
- use `window.location.pathname` for `not-found` param as `this.router.get('currentURL')` would often times be `undefined` leading to an error and a blank screen
> [No ticket] Fix reroute to not-found

- app/models/addon-operation-invocation.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/template.hbs
- mirage/views/addons.ts
-   Ticket: [ENG-6436]
- Add logic to prevent users from selecting or navigating into an inappropriate item when selecting a root folder
- Add `canBeRoot` and `mayContainRootCandidates` flags to addon-operation-invocation item-results
- Use these flags to control whether a user can navigate into that item (`mayContainRootCandidates`), or select an item as a root folder (`canBeRoot`)
- Relevant GV PR https://github.com/CenterForOpenScience/gravyvalet/pull/139
- An example of items that can be roots or may contain roots for illustrative purposes. In practice, folders should be selectable as root folders and navigable to find root folder candidates
- FOLDER1: `canBeRoot: true` and `mayContainRootCandidates: true`
- FOLDER2: `canBeRoot: false` and …
> [ENG-6436] Add new canBeRoot and mayContainRootCandidates flags

- app/institutions/dashboard/-components/object-list/contributors-field/component.ts
- app/institutions/dashboard/-components/object-list/contributors-field/template.hbs
- app/institutions/dashboard/-components/object-list/doi-field/template.hbs
- app/institutions/dashboard/preprints/controller.ts
- app/institutions/dashboard/projects/controller.ts
- app/institutions/dashboard/registrations/controller.ts
- app/models/search-result.ts
- app/packages/osfmap/jsonld.ts
- mirage/views/search.ts
- translations/en-us.yml
-   Ticket: [ENG-6419]
- Make sure institution dashboard pages talking to SHARE don't break
- Update project page controller's getters to account for missing values
- Add new package `osfmap/jsonld.ts` with utilities to make getting stuff from SHARE easier and more readable
[ENG-6419]: https://openscience.atlassian.net/browse/ENG-6419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6419] Share integration

- app/institutions/dashboard/-components/object-list/component.ts
- app/institutions/dashboard/-components/object-list/template.hbs
- Fix index-value-search query-params from institutional dashboard page
- Add new `valueSearchQueryOptions` to use for index-value-search
- Prevents this issue:
- And should now look like:
> [No ticket] Fix institutional dashboard index-value-search

- app/guid-node/addons/index/template.hbs
- lib/osf-components/addon/components/addons-service/addon-account-setup/component.ts
- lib/osf-components/addon/components/addons-service/addon-account-setup/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- translations/en-us.yml
-   Ticket: [ENG-6345]
- Prevent users from creating a new unauthorized account and then selecting it later as an "Existing account"
- Send users to the "Connect acccount" page if a user selects an unauthorized account
- Fix issues `addon-account-setup` component's reconnect workflow
- Follow-up to this prior PR https://github.com/CenterForOpenScience/ember-osf-web/pull/2372
- Delete newly created account if the auth workflow hasn't succeeded and the user cancels out of the account creation process
- Will not delete account if it is a "Reconnect"/Reauthorize workflow (checks if `account` is passed into `addon-account-setup` component
- Miscellaneous whitespace changes
[ENG-6345]: https://openscience.atlassian.net/browse/ENG-6345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
> [ENG-6345] Prevent users from using unauthorized accounts to make a configured-addon

- app/institutions/dashboard/-components/chart-kpi-wrapper/component-test.ts
- app/institutions/dashboard/-components/total-count-kpi-wrapper/component-test.ts
- app/institutions/dashboard/-components/total-count-kpi-wrapper/component.ts
- translations/en-us.yml
- Update and clarify language on summary page
- Update Registration count to account for embargoed registrations
- Update label
- Update labels for Licenses, Add-ons, Storage Region graphs
- Registrations count before:
- Registrations count after:
- Licenses, Add-ons, Storage Regions before:
- Licenses, Add-ons, Storage Regions after:
> [No ticket] Update language and counts on summary page

- app/institutions/dashboard/-components/object-list/component.ts
- Fix bug where removed filters were "remembered"
- Change how we use the `args.defaultQueryOptions` param when building request query options
-  Previous method of initializing `options` was allowing us to directly add entries to `defaultQueryOptions` in line 53 (now line 55) when doing `acc.cardSearchFilter[filter.propertyPathKey] = ...`
- New way of initializing `options` should no longer allow us to add new entries to `defaultQueryOptions`
- Shallow copies are a doozy
- Before the fix: `args.defaultQueryOptions` object before and after this showing the newly added `rights` entry
- After the fix: `args..defaultQueryOptions` object remains the same
> [No ticket] Actually remove filters when removing them in the UI

- app/institutions/dashboard/-components/institutional-dashboard-wrapper/styles.scss
- Properly hide right panel on desktop view
- Update CSS to hide right-panel in desktop view
- Currently it is off screen, but there is a horizontal scroll option that allows you to see the right-panel by scrolling over
- Remove unneeded CSS
- Before:
- Closed (note the scrollbar at the bottom):
- Right panel is "Closed", but you can just scroll over to see it
- After:
- Closed:
- Opened:
> [No ticket ]Right panel hidden

- lib/osf-components/addon/components/addons-service/terms-of-service/component.ts
-   Ticket: [ENG-6525]
- Fix Terms widget to show partial feature support
- Fix typo in logic to detect partial feature detection
- Before: 
- After:
[ENG-6525]: https://openscience.atlassian.net/browse/ENG-6525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6525] Fix partial feature support detection

- app/institutions/dashboard/-components/object-list/component.ts
- Fix bug when applying multiple filter types of a given category
- Update how filters are appended
- Issue was stemming from how existing filters were used leading to queries that looked like
- Should now look like
> Fix issue when applying multiple filters of a kind

- app/institutions/dashboard/-components/institutional-dashboard-wrapper/template.hbs
- app/institutions/dashboard/-components/institutional-users-list/styles.scss
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
- app/institutions/dashboard/-components/object-list/component-test.ts
- app/institutions/dashboard/-components/object-list/styles.scss
- app/institutions/dashboard/-components/object-list/template.hbs
- tests/acceptance/institutions/dashboard-test.ts
- translations/en-us.yml
⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️  Currently only FE, BE is not done yet, still waitng on links.
- https://openscience.atlassian.net/browse/ENG-6280
- https://openscience.atlassian.net/browse/ENG-6281
Move the archive link button to the other button group over the table and add buttons that allow a variety of file types.
- changes to institution user template
- changes to  institution user styles
- changes to object-list template
- changes to object-list styles.
> [ENG-6280][ENG-6281] Add download dashboard buttons move archive link

- app/institutions/dashboard/-components/object-list/component.ts
- app/institutions/dashboard/preprints/controller.ts
- app/institutions/dashboard/projects/controller.ts
- app/institutions/dashboard/registrations/controller.ts
- Fix an issue where the value-searches for a given filterable property were not being queried with any applied filters
- Fix an issue where adding more affiliation filters was breaking
- Pass all applied filters to value-searches
- Update `cardSearchFilter[affiliation]` query-param to be an array, instead of a string
- `defaultQueryParams.cardSearchFilter.affiliation` not being an array lead to this misformatted request param (array.concat vs. string.concat)
> Fix value-search bugs

- app/institutions/dashboard/-components/object-list/contributors-field/template.hbs
- app/institutions/dashboard/-components/object-list/doi-field/template.hbs
- app/institutions/dashboard/preprints/controller.ts
- app/institutions/dashboard/projects/controller.ts
- app/institutions/dashboard/registrations/controller.ts
- translations/en-us.yml
- Update placeholder text when there is no data for a given column
- Use a simple `-` to denote missing values
- Add placeholder text if no contributors are no longer affiliated for a project/registration/preprint
- Example of columns with missing values
- When no affiliated contributors are found (in case a user is no longer is affiliated with an institution)
> Update no data placeholder text

- app/institutions/dashboard/-components/object-list/component.ts
- app/institutions/dashboard/-components/object-list/template.hbs
- app/institutions/dashboard/projects/controller.ts
- app/institutions/dashboard/registrations/controller.ts
-   Ticket: []
- Allow users to sort by total storage on project and registration tabs
- Add new optional `sortParam` to sortable integer columns
> Sort by byte count

- app/institutions/dashboard/-components/object-list/component.ts
- lib/osf-components/addon/components/index-card-searcher/component.ts
-   Ticket: []
- Fix issues with pagination
- Prevent the "First" button from showing up when we are already on the first page
- Reset page param when we change sort or add/remove filters
> Pagination machination

- app/institutions/dashboard/-components/institutional-dashboard-wrapper/styles.scss
- app/institutions/dashboard/-components/institutional-dashboard-wrapper/template.hbs
-   Ticket: []
- See title
- Add `max-width` and `max-height` to institution banner image
- Prevents anything silly like this:
- and now looks like
> Limit institution banner image size

- lib/osf-components/addon/components/paginated-list/layout/styles.scss
-   Ticket: []
- Add text-centering class back to paginator controls (Thanks percy!)
- Resurrect removed class
- Example before:
- Example after:
> Bring back a local-class that got removed

- app/institutions/dashboard/-components/institutional-dashboard-wrapper/styles.scss
- app/institutions/dashboard/-components/institutional-users-list/styles.scss
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
-   Ticket: [ENG-6401]
- Avoid issue with weird text-wrap of tabs in mobile
- Avoid issue with weird text-wrap of total users in mobile
- Update CSS
- Group buttons into divs of user-list topbar (best to view changes with whitespace off)
- Desktop before
- Desktop after (should be no changes)
- Mobile before
- Mobile after
[ENG-6401]: https://openscience.atlassian.net/browse/ENG-6401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6401] Mobile styling

- app/institutions/dashboard/-components/object-list/template.hbs
- lib/osf-components/addon/components/index-card-searcher/component.ts
- lib/osf-components/addon/components/index-card-searcher/template.hbs
-   Ticket: [ENG-6585]
- Combine boolean filters into one group to match filtering behavior of search page
- Create a new boolean-filter group on institutional dashboard filter list
- Before (bug where some filter value names may be blank):
- After:
[ENG-6585]: https://openscience.atlassian.net/browse/ENG-6585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6585] Move boolean filters into group

- app/institutions/dashboard/preprints/controller.ts
- app/institutions/dashboard/projects/controller.ts
- app/institutions/dashboard/registrations/controller.ts
-   Ticket: [ENG-6590]
- Allow users to sort projects and registrations by view count
- Allow users to sort preprints by view and download counts
- Add sort params to projects, registrations and preprint page controllers
- Before:
- After:
[ENG-6590]: https://openscience.atlassian.net/browse/ENG-6590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6590] Allow users to sort by view and download count

- app/institutions/dashboard/-components/object-list/component.ts
-   Ticket: []
- Fix how boolean filters are implemented
- Update logic to fix boolean filters
- Before:
- After:
> Implement boolean filters correctly

- app/institutions/dashboard/-components/institutional-users-list/component.ts
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
- tests/integration/routes/institutions/dashboard/-components/institutional-users-list/component-test.ts
- translations/en-us.yml
-   Ticket: []
- Show ORCID info in user list table
- Add new column type in user list
> Show orcid in user list table

- app/institutions/dashboard/-components/institutional-users-list/component.ts
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
- app/institutions/dashboard/-components/object-list/template.hbs
- lib/osf-components/addon/components/adjustable-paginator/template.hbs
- translations/en-us.yml
-   Ticket: [ENG-6599] [ENG-6598]
- Address a11y issues
- Add `title` to "Items per page" dropdown
- Add `aria-label` to link to prior report (it seems that the `aria-describedby` added by  `EmberTooltip` does not suffice :/ )
- Add `aria-label` to download button
- NA
[ENG-6599]: https://openscience.atlassian.net/browse/ENG-6599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-6598]: https://openscience.atlassian.net/browse/ENG-6598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6599][ENG-6598] A11y

- app/institutions/dashboard/-components/total-count-kpi-wrapper/total-count-kpi/template.hbs
-   Ticket: []
- Remove hover tooltip from summary page KPIs as requested by product
- Remove `EmberTooltip` from summary KPIs
- Prevents this visual issue
> Remove tooltip from summary kpi

- app/institutions/dashboard/-components/institutional-users-list/styles.scss
- lib/osf-components/addon/components/adjustable-paginator/template.hbs
-   Ticket: [ENG-6567] [ENG-6598]
- Fix dropdown placement for mobile view
- Fix a11y best practice issue where dropdown isn't properly labeled
- Remove unneeded CSS property
- Use an explicit `<label>` element for "Items per page" dropdown
- Before:
- After:
[ENG-6567]: https://openscience.atlassian.net/browse/ENG-6567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-6598]: https://openscience.atlassian.net/browse/ENG-6598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6567][ENG-6598] Fix dropdown placement for mobile

- app/packages/osfmap/jsonld.ts
-   Ticket: []
- Rewrite `hasOsfmapValue` based on comment
- use `Array.some()` instead of manually looping through the array
> Rewrite hasOsfmapValue based on earlier suggestion

- app/institutions/dashboard/-components/chart-kpi-wrapper/chart-kpi/component-test.ts
- app/institutions/dashboard/-components/chart-kpi-wrapper/component.ts
-   Ticket: []
- Clean up leftover commented out import and test
- Address comments from earlier feature-branch PR https://github.com/CenterForOpenScience/ember-osf-web/pull/2395
- NA
> Cleanup commented out import and test

- app/guid-node/addons/index/template.hbs
- app/models/addon-operation-invocation.ts
- app/models/authorized-account.ts
- app/models/configured-addon.ts
- app/packages/files/service-file.ts
- app/packages/files/service-provider-file.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/template.hbs
- lib/osf-components/addon/components/addons-service/file-manager/component.ts
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/manager/template.hbs
- mirage/views/addons.ts
- tests/integration/components/addons-service/configured-addon-edit/component-test.ts
-   Ticket: [ENG-6538]
- Disallow users from saving if there is no root folder selected
- Disable "Save" button if no root folder is selected
- Update default behavior to prevent a `configure-addon` from being created until after all the configuring has finished
- Update tests
- Save button disabled when no root folder selected:
- Save button enabled with root folder selected:
- users will no longer have a configured-addon until after they hit "Save" on the "Configure <provider-name>" screen, which I would argue is a good thing
[ENG-6538]: https://openscience.atlassian.net/browse/ENG-6538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6538] Require root folder to be selected when configuring addon

- app/institutions/dashboard/-components/institutional-users-list/component.ts
- app/institutions/dashboard/-components/institutional-users-list/styles.scss
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
- tests/integration/routes/institutions/dashboard/-components/institutional-users-list/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-6559] [ENG-6617]
- Integrate download functionality for users tab (Projects, Registrations, and Preprints will be in a subsequent PR)
- Add functionality to the download buttons on the FE
- Turn the buttons into links
[ENG-6559]: https://openscience.atlassian.net/browse/ENG-6559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-6617]: https://openscience.atlassian.net/browse/ENG-6617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6617][ENG-6559] Integrate user download functionality

- app/institutions/dashboard/-components/institutional-users-list/component.ts
-   Ticket: []
- Add relevant user search query-params to the download links (follow up to this prior PR https://github.com/CenterForOpenScience/ember-osf-web/pull/2413)
- Add the `queryUsers` object entries to the downloadUrl
- Behold, query-params in the anchor tag's href
> Add remaining user search query-params to download

- app/institutions/dashboard/-components/object-list/component-test.ts
- app/institutions/dashboard/-components/object-list/component.ts
- app/institutions/dashboard/-components/object-list/styles.scss
- app/institutions/dashboard/-components/object-list/template.hbs
- app/models/index-card-search.ts
- app/serializers/index-card-search.ts
- lib/osf-components/addon/components/index-card-searcher/component.ts
- lib/osf-components/addon/components/index-card-searcher/template.hbs
- mirage/views/search.ts
-   Ticket: [ENG-6559]
- Allow users to download projects/registrations/preprints info in institutional dashboard
- Add functionality to download from SHARE using the `acceptMediatype` and `withFileName` query-params
- For this filter set (where license is a boolean filter)...
... the CSV download link would look like 
```
https://staging-share.osf.io/trove/index-card-search
?acceptMediatype=text/csv
&withFileName=projects-search-results
&cardSearchFilter[affiliation]=http://ror.org/has-users
&cardSearchFilter[resourceType]=Project
&cardSearchFilter[rights][is-present]=true
&cardSearchFilter[funder]=http://dx.doi.org/10.10000/505000005050,https://doi.org/10.10000/100000001
&page[cursor]=&page[size]=10000&sort=-dateModified
```
[ENG-6559]: …
> [ENG-6559] Download feature for SHARE data

- app/institutions/dashboard/index/styles.scss
- app/institutions/dashboard/index/template.hbs
- app/institutions/dashboard/route.ts
- app/institutions/dashboard/users/styles.scss
- app/institutions/dashboard/users/template.hbs
- app/models/institution-summary-metric.ts
- app/models/institution-user.ts
- mirage/factories/institution-summary-metric.ts
- mirage/factories/institution-user.ts
- tests/acceptance/institutions/dashboard-test.ts
- translations/en-us.yml
-   Ticket: [ENG-6625]
- Add report date to Institutional Dashboard Summary and Users tab
- Add new `reportYearmonth` attribute to `institution-summary-metric` and `insitution-user` models
- This attribute is a `string` to prevent an issue with the `@attr('date')` transform that would shift the month by one depending on your timezone
- Show this new attribute on the summary and users tab
- Desktop
- Mobile
[ENG-6625]: https://openscience.atlassian.net/browse/ENG-6625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6625] Add report date to Institutional Dashboard Summary and Users tab

- app/models/preprint.ts
- app/preprints/detail/route.ts
- app/serializers/preprint.ts
- mirage/config.ts
- mirage/factories/preprint.ts
- mirage/scenarios/preprints.ts
- mirage/serializers/preprint.ts
- mirage/views/preprint.ts
- types/osf-api.d.ts
-   Ticket: [ENG-6447]
- Update the Preprint model to add new version-specific fields
- Add new `preprintVersion` and `isLatestVersion` attrs to Preprint
- Add new `versions` relationship to Preprint
- This won't be returned from the API, but the preprint response should have a `preprint_version` URL that can be used to get versions, hence the chicanery with the preprint-serializer
- Add new mirage view to handle fetching versions
- Add new trait to preprint factory to quickly create versions for a given preprint
- This is the mirage request/response made when accessing the detail page of a preprint with versions
[ENG-6447]: https://openscience.atlassian.net/browse/ENG-6447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6447] Update preprint model for versioning

- app/preprints/-components/preprint-doi/component-test.ts
- app/preprints/-components/preprint-doi/component.ts
- app/preprints/-components/preprint-doi/styles.scss
- app/preprints/-components/preprint-doi/template.hbs
- app/preprints/detail/template.hbs
- mirage/factories/preprint.ts
- mirage/views/preprint.ts
- translations/en-us.yml
-   Ticket: [ENG-6448]
- Update preprint-doi component to handle versions
- Update Preprints::PreprintDoi component 
- Takes an array of versions, rather than a single preprint
- Add dropdown to select a specific version
- Tests
- Example of a preprint with a fully minted DOI (from tests, so that's why the background is weird):
- Example of a preprint that has a DOI, but it is pending:
- Example of preprint with no DOI due to it pending moderation (from tests, so that's why the background is weird)
[ENG-6448]: https://openscience.atlassian.net/browse/ENG-6448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6448] Update preprint-doi component to handle versions

- app/preprints/-components/preprint-provider-selection/template.hbs
- app/preprints/-components/submit/preprint-state-machine/component.ts
- app/preprints/-components/submit/preprint-state-machine/status-flow/status-flow-display/template.hbs
- app/preprints/-components/submit/preprint-state-machine/template.hbs
- tests/acceptance/preprints/edit-test.ts
- tests/acceptance/preprints/submit-test.ts
-   Ticket: [ENG-6434]
- Add logic to show/hide the file upload step on the preprint submission/edit workflow
- Add a new flag `displayFileUploadStep` that controls whether or not the file upload step is shown
- Should be shown for initial preprint submission
- Should be shown for rejected preprint re-submission
- Create new preprint workflow showing the file upload step
- Edit and resubmit workflow showing the file upload step
- Editing an existing preprint no longer showing the file upload step
- Editing an accepted preprint will now no longer show the option to upload a new file version
[ENG-6434]: https://openscience.atlassian.net/browse/ENG-6434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6434] Show/hide file upload page on preprint submit workflow

- app/models/preprint.ts
- app/preprints/-components/preprint-tombstone/template.hbs
- app/preprints/detail/controller.ts
- app/preprints/detail/template.hbs
- mirage/factories/preprint.ts
- tests/acceptance/preprints/detail-test.ts
- translations/en-us.yml
-   Ticket: [ENG-6459] [ENG-6637] [ENG-6638]
- Add a new "Create new version" button to the preprint detail page
- Add a new `canCreateNewVersion` attr to preprint model
- Only admins can create a new version
- Only preprints that is the latest version can create a new version
- Only preprints that are were published at some point (whether they are withdrawn or not, doesn't matter)
- Update tombstone page for preprint versions
- Accepted
- Rejected (for pre-moderation providers)
- Withdrawn
[ENG-6459]: https://openscience.atlassian.net/browse/ENG-6459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-6637]: https://openscience.atlassian.net/browse/ENG-6637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> [ENG-6459][ENG-6637][ENG-6638] Add Create new preprint version button

- app/models/addon-operation-invocation.ts
- app/models/authorized-account.ts
- app/models/authorized-citation-account.ts
- app/models/authorized-storage-account.ts
- app/models/configured-addon.ts
- app/models/configured-citation-addon.ts
- app/models/configured-computing-addon.ts
- app/models/configured-storage-addon.ts
- app/packages/files/service-file.ts
- app/packages/files/service-provider-file.ts
- mirage/views/addons.ts
> [ENG-6630] Fix citation addons

- app/config/environment.d.ts
- app/institutions/dashboard/-components/object-list/component-test.ts
- app/institutions/dashboard/-components/object-list/component.ts
- app/institutions/dashboard/-components/object-list/template.hbs
- config/environment.js
- mirage/factories/root.ts
-   Ticket: []
-   Feature flag: `share_download`
- Move Institutional Dashboard Project/Registration/Preprint download button behind a feature flag
- Add new flag `share_download`
- Show/hide download buttons on Institutional Dashboard based on this feature flag
- With flag turned on
- With flag turned off
> Feature flag for SHARE download button

- app/adapters/user-message.ts
- app/institutions/dashboard/-components/institutional-users-list/component.ts
- app/institutions/dashboard/-components/institutional-users-list/styles.scss
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
- app/models/user-message.ts
- translations/en-us.yml
⚠️ Needs https://github.com/CenterForOpenScience/osf.io/pull/10824 for API usaage.
Adds a modal that allows an institutional admin to send a message through a text input as part of an email template.
- add user-message modal
- modifies component to allow for model logic
- Add modal to template with styling
> [ENG-6665] Add user messaging modal to user's tab on institutional dashboard

- app/models/addon-operation-invocation.ts
- app/models/configured-addon.ts
- app/models/configured-citation-addon.ts
- app/models/configured-storage-addon.ts
…orage-addon child classes
-   Ticket: []
> implement getFolderItems and getItemInfo in configurated-citiation/storage-addon child classes

- app/preprints/-components/submit/file/component.ts
- app/preprints/-components/submit/preprint-state-machine/component.ts
- app/preprints/-components/submit/preprint-state-machine/status-flow/styles.scss
- app/preprints/-components/submit/preprint-state-machine/status-flow/template.hbs
- app/preprints/-components/submit/preprint-state-machine/template.hbs
- app/preprints/-components/submit/submission-flow/template.hbs
- app/preprints/detail/controller.ts
- app/preprints/detail/route.ts
- app/preprints/detail/template.hbs
- app/preprints/new-version/controller.ts
- app/preprints/new-version/route.ts
- app/preprints/new-version/template.hbs
- app/router.ts
- mirage/config.ts
- mirage/factories/preprint.ts
- mirage/factories/review-action.ts
- mirage/scenarios/preprints.ts
- mirage/views/preprint.ts
- mirage/views/review-action.ts
- tests/acceptance/preprints/new-version-test.ts
- translations/en-us.yml
-   Ticket: [ENG-6460] [ENG-6640]
- Add a new workflow to create a new preprint version
- Add a new `preprint.new-version` route
- Add a new `newVersion` argument to the submission-flow component
- Invoke `submission-flow` component in the new-version route
[ENG-6460]: https://openscience.atlassian.net/browse/ENG-6460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-6640]: https://openscience.atlassian.net/browse/ENG-6640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6460] [ENG-6640] Add new preprint version workflow

- lib/osf-components/addon/components/addons-service/addon-account-setup/template.hbs
- translations/en-us.yml
> [ENG-6653] Fix configuration page text

- app/models/preprint.ts
- app/preprints/-components/preprint-doi/template.hbs
- app/preprints/detail/styles.scss
- app/preprints/detail/template.hbs
- mirage/factories/preprint.ts
- mirage/views/preprint.ts
- tests/acceptance/preprints/detail-test.ts
- translations/en-us.yml
-   Ticket: [ENG-6470]
- Add a version select dropdown to the tombstone page
- Add dropdown to tombstone page header to view prior versions
- Update tests
[ENG-6470]: https://openscience.atlassian.net/browse/ENG-6470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6470] Withdrawn version picker

- app/guid-node/addons/index/template.hbs
- app/models/configured-addon.ts
- app/packages/addons-service/provider.ts
- lib/osf-components/addon/components/addon-card/component.ts
- lib/osf-components/addon/components/addon-card/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- tests/acceptance/guid-node/addons-test.ts
- tests/integration/components/addon-card/component-test.ts
… 
-   Ticket: [ENG-6744]
-   Feature flag: gravy_waffle
- fixed configure button displayed when user won't be able to configure addon
- fixed user and resource reference reuest swarm
[ENG-6744]: https://openscience.atlassian.net/browse/ENG-6744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6744] FE: Contributors can "configure" others' addons

- app/models/preprint.ts
- app/preprints/-components/preprint-doi/component-test.ts
- app/preprints/-components/preprint-doi/component.ts
- app/preprints/-components/preprint-doi/styles.scss
- app/preprints/-components/preprint-doi/template.hbs
- app/preprints/detail/controller.ts
- app/preprints/detail/styles.scss
- app/preprints/detail/template.hbs
- tests/acceptance/preprints/detail-test.ts
- translations/en-us.yml
-   Ticket: [ENG-6471]
- Add version statuses for pending, rejected, and withdrawn versions
- Add version status to Version DOI selector
- Add version status to Withdrawn page's version selector dropdown
- Version DOI selector dropdown:
- Withdrawn version selector dropdown:
[ENG-6471]: https://openscience.atlassian.net/browse/ENG-6471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6471] Add status labels to version dropdowns

- app/guid-node/addons/index/template.hbs
- app/models/authorized-computing-account.ts
- app/models/configured-addon.ts
- app/models/configured-computing-addon.ts
- app/models/user-reference.ts
- app/packages/addons-service/provider.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- translations/en-us.yml
-   Ticket: [ENG-6774](https://openscience.atlassian.net/browse/ENG-6774)
The new Boa addon is trying to `POST` a relationship called `computing-service` rather than `external-computing-service`. After investigation, it looks like some of the naming conventions for computing have gone stale and need to be updated.
* Update computing model names to be consistent with their storage and citation brethren, i.e. `AuthorizedComputingAccount` => `AuthorizedComputingAccountModel`
* Update relationship reference names from `computingService` to `externalComputingService` to match the gv API.
* Fix a few spots for citations with the same issues.
* fix a misspelling in the en_us key translations
* set the default capabilities for computing addons
nope
still testing, will let …
> [ENG-6774] fix computing model / service names (and some citations, too!)

- app/preprints/-components/preprint-doi/component-test.ts
- app/preprints/-components/preprint-doi/component.ts
- app/preprints/-components/preprint-doi/styles.scss
- app/preprints/-components/preprint-doi/template.hbs
- app/preprints/-components/preprint-tombstone/template.hbs
- app/preprints/detail/template.hbs
-   Ticket: [ENG-6803]
- Indicate currently viewed version in the preprint DOI selection dropdown
- Add a `currentVersion` param to the preprint-doi component
- Have this version be the selected one by default
- Add bold font style to current version
- When viewing version 2 out of 3 possible versions (note the `_v2` in the URL)
- Upon opening dropdown, you can see that version2 is the currently viewed version
[ENG-6803]: https://openscience.atlassian.net/browse/ENG-6803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6803] Preprint-doi select dropdown should have current version selected by default

- app/preprints/-components/preprint-doi/component-test.ts
- app/preprints/-components/preprint-doi/template.hbs
- translations/en-us.yml
-   Ticket: [ENG-6804]
- Add a link to the version when selecting a different version in the DOI selection dropdown
- Add link to preprint DOI dropdown
- Update tests
[ENG-6804]: https://openscience.atlassian.net/browse/ENG-6804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6804] Add link to version in DOI select

- app/institutions/dashboard/-components/object-list/component-test.ts
- app/institutions/dashboard/-components/object-list/component.ts
- app/institutions/dashboard/-components/object-list/template.hbs
- app/institutions/dashboard/preprints/controller.ts
- app/institutions/dashboard/projects/controller.ts
- app/institutions/dashboard/registrations/controller.ts
-   Ticket: [ENG-6823]
- Tell SHARE what information to download when downloading institutional dashboard data
- Add a new `propertyPathKey` property to the object-list columns
- this is used to tell SHARE the format of each column
- Remove `sortKey` property from column, and replace it with `isSortable` boolean property since `sortKey` is the same as `propertyPathKey`
- Example links for Project download
- With all columns shown: 
```
https://share.osf.io/api/v2/index-card-search/55b755ce-3096-4db4-9640-277a95a8b9e8?
page[size]=10000&
acceptMediatype=text/csv&
withFileName=projects-search-results&
fields[Project]=title,dateCreated,dateModified,resourceIdentifier,storageRegion.prefLabel,storageByteCount,creator.name,usage.viewCount,resourceNature.displayLabel,rights.n …
```
> [ENG-6823] Explicitly list columns for SHARE download

- app/preprints/-components/preprint-doi/template.hbs
-   Ticket: [Not ticket]
- Fix bug where link to a version in the Preprint DOI section would not update
- Send proper params to OsfLink
- Fix issue where this link href was not updating correctly
> Fix bug where link in doi section would not update

- app/institutions/dashboard/preprints/controller.ts
- app/institutions/dashboard/projects/controller.ts
- app/institutions/dashboard/registrations/controller.ts
-   Ticket: []
- Fix DOI field on downloaded file
- Use `sameAs` key instead of `resourceIdentifier`
- NA
> Use proper key for DOI field download

- app/institutions/dashboard/registrations/controller.ts
-   Ticket: []
- Fix funder column propertyPathKey for Registrations tab
- `funders` -> `funder`
- Projects tab was implemented correctly and didn't need updating. Preprints don't have funders (yet) so this isn't a problem on that tab
> Fix funder column propertyPathKey

- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- tests/acceptance/guid-node/addons-test.ts
- tests/acceptance/settings/addons-test.ts
- tests/integration/components/addons-service/manager/component-test.ts
- tests/integration/components/addons-service/user-addons-manager/component-test.ts
> [ENG-6879] Disable cloud computing filter for addons

- config/environment.js
- translations/en-us.yml
Update policy links for https://github.com/CenterForOpenScience/osf.io/pull/10836
- Update links
None expected
> [Hotfix][ENG-6698] Policy links

- app/preprints/-components/preprint-status-banner/component.ts
- app/preprints/-components/preprint-status-banner/template.hbs
-   Ticket: [ENG-6822] [ENG-6871]
- Fix an issue where the preprint status banner doesn't update when selecting a different version
- Refactor status banner component to use arguments instead of a cached arg reference
[ENG-6822]: https://openscience.atlassian.net/browse/ENG-6822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-6871]: https://openscience.atlassian.net/browse/ENG-6871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6822] [ENG-6871] Fix bug where preprint status banner does not update

- app/adapters/node-request.ts
- app/adapters/user-message.ts
- app/institutions/dashboard/-components/institutional-users-list/component.ts
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
- app/institutions/dashboard/-components/object-list/component.ts
- app/institutions/dashboard/-components/object-list/contributors-field/component.ts
- app/institutions/dashboard/-components/object-list/contributors-field/styles.scss
- app/institutions/dashboard/-components/object-list/contributors-field/template.hbs
- app/institutions/dashboard/-components/object-list/styles.scss
- app/institutions/dashboard/-components/object-list/template.hbs
- app/models/node-request.ts
- app/models/user-message.ts
- translations/en-us.yml
⚠️ Needs `feature/instituional_access` branch and migrations to fully work.
-   Ticket: [https://openscience.atlassian.net/browse/ENG-6669]
https://openscience.atlassian.net/browse/ENG-6669
Allows institutional admins to request access to projects from the institutional dashboard projects tab. Also allows them to message thier institutional users.
- add node-request model
- add node-request adapter
- add two tabbed model with `Send Message` and `Request Access` tabs
- add css for style
- standardize casing and verbage for BccSender and MessageRecipent 
Request access disabled behavior
https://github.com/user-attachments/assets/c127e57d-cda1-466d-8967-1cd1d72ba4bd
I used mirage to simulate a SHARE locally here's a gist with all the unstaged files I needed to run this …
> [ENG-6669] Institutional Access project Request Modal

- app/models/addon-operation-invocation.ts
- app/models/authorized-citation-account.ts
- app/models/configured-citation-addon.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/template.hbs
-   Ticket: [ENG-6848]
[ENG-6848]: https://openscience.atlassian.net/browse/ENG-6848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6848] Fix folder icon

- app/preprints/-components/preprint-file-render/component.ts
- app/preprints/-components/preprint-file-render/template.hbs
-   Ticket: [ENG-6931]
- Update the file version shown in mfr window when changing preprint versions
- Don't use cached preprint or file-version in file renderer component
[ENG-6931]: https://openscience.atlassian.net/browse/ENG-6931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6931] Update file shown in MFR when changing versions

- app/adapters/user-message.ts
- app/institutions/dashboard/-components/object-list/contributors-field/component.ts
- app/models/user-message.ts
> IAC CR Fixes

- app/preprints/detail/route.ts
-   Ticket: []
- Fix bug which prevented users from seeing moderator feedback
- Decouple fetching the latest review-action to preprint-state
- Allow all preprint contributors to see moderator feedback
> Fix bug to allow any contributor to see preprint rejection comments

- app/preprints/-components/preprint-status-banner/component.ts
- app/preprints/detail/route.ts
-   Ticket: []
- Reimplement [this PR](https://github.com/CenterForOpenScience/ember-osf-web/pull/2482) but account for the fact that only admins have access to a preprint's `requests`
- Reimplement aforementioned PR but check that user has admin permission before fetching `requests` as only admins have access to a preprint's `requests` endpoint
> Reimplement bug fix and account for permissions when accessing preprint requests

- app/preprints/detail/template.hbs
-   Ticket: [ENG-7007]
- fix a11y issue with version select dropdown
- Remove nested button from version select dropdown
- No visual changes
[ENG-7007]: https://openscience.atlassian.net/browse/ENG-7007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7007] A11y issue for version dropdown

- app/adapters/node-request.ts
- app/institutions/dashboard/-components/object-list/component.ts
- app/institutions/dashboard/-components/object-list/template.hbs
- translations/en-us.yml
-   Ticket: [https://openscience.atlassian.net/browse/ENG-6991]
Do the IAC clean-up fixes 
- close modal during success: https://openscience.atlassian.net/browse/ENG-6991
- add missing aira label to textbox: https://openscience.atlassian.net/browse/ENG-6997
- change wording in pop-up warning modal https://openscience.atlassian.net/browse/ENG-7001
- change toast success messages to be distinct per tab https://openscience.atlassian.net/browse/ENG-7002
- remove import as per comment  https://github.com/CenterForOpenScience/ember-osf-web/pull/2471/files#r1924156289
> [ENG-6991][ENG-6997][ENG-7001][ENG-7002][IAC] Simple FE Fixes

- app/preprints/-components/submit/author-assertions/link-widget/link/component-test.ts
- app/preprints/-components/submit/author-assertions/link-widget/link/component.ts
- app/validators/url-with-protocol.ts
- translations/en-us.yml
-   Ticket: [ENG-5996]
Product requested that the error validation was more descriptive when entering urls for Public Data and Preregistration.
Added an optional parameter of 'validationType' to the validateUrlWithProtocols to ensure backward compatibility while allowing for variations in messages
It appears there is only one usage of the validator, so the optional parameter might not have been needed.
In the en-us.yml file there is already a `https_url` and it only covered https and not http. It appears not to be used. I didn't prune it and wanted to though.
Give it a look.
[ENG-5996]: https://openscience.atlassian.net/browse/ENG-5996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5996] Added a new optional variable when validating urls

- app/guid-node/files/provider/route.ts
- app/guid-node/files/provider/template.hbs
-   Ticket: []
Improve performance of files page
- Commented out a line in `fileProviderTask` that was for fetching enabled addons
- The reason we need to fetch enabled addons is because we need to know whether BOA is enabled. But since the upcoming release does not include BOA we can disable this task.
- Instead of having the route model hook return a `configuredStorageAddonTask`, we return the actual model instance.
- The reason this call is needed is because there is some weird race condition happening here. If we don't make this change, `configuredStorageAddonTask` itself would not finish running before its resolved value is used downstream.
> Remove a query to the addons endpoint to improve page load performance

- lib/osf-components/addon/modifiers/track-download.ts
-   Ticket: []
- Update `track-download` modifier to track downloads properly
- Tell which event to listen to when adding the event handler
- NA
> Update track-download modifier event listener

- app/models/preprint.ts
- app/preprints/detail/controller.ts
- app/serializers/preprint.ts
- mirage/serializers/preprint.ts
- types/osf-api.d.ts
-   Ticket: [ENG-7174]
- Update how the FE expects a preprint's versions to be serialized from the API
- stop using the `preprint_versions` link for preprint version fetching/creating
- API should return a normal `versions` relationship in the API, so no need to do any FE serializing shenanigans
- Add new versions relationship to mirage preprint response
- NA
[ENG-7174]: https://openscience.atlassian.net/browse/ENG-7174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7174] Update Preprint versions to be a relationship

- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
- lib/osf-components/addon/components/file-browser/template.hbs
-   Ticket: []
add `{{track-download ...}}` modifier to the buttons for download folders
> fix: add dcut tracking to folder-download buttons

- translations/en-us.yml
-   https://openscience.atlassian.net/browse/ENG-6141
Update the text for the "not applicable" option in the "Authors Assertions" section of Preprints
Update placeholder for Preprint -> Public Preregistration -> Not Applicable
> ENG-6141 update Public Preregistration NA placeholder

- app/packages/addons-service/provider.ts
- lib/osf-components/addon/components/addons-service/manager/component.ts
fixed resource-reference spam if ther is no resource-reference on backend
-   Ticket: [ENG-7292]
[ENG-7292]: https://openscience.atlassian.net/browse/ENG-7292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7292] Resource reference spam on nodes without resource references on GV

- app/models/related-property-path.ts
- lib/osf-components/addon/components/search-page/filter-facet/component.ts
- lib/osf-components/addon/components/search-page/filter-facet/template.hbs
-   Ticket: [https://openscience.atlassian.net/browse/ENG-6102]
Added context phrase to institutions filter modal on search pages
TBD
TBD
TBD
> [ENG-6102] Added context phrase to institutions filter modal on search pages

- app/adapters/contributor.ts
- lib/osf-components/addon/components/contributors/list/template.hbs
- lib/osf-components/addon/components/editable-field/title-manager/component.ts
- lib/osf-components/addon/components/editable-field/title-manager/template.hbs
- lib/osf-components/addon/components/node-metadata-form/styles.scss
- lib/osf-components/addon/components/node-metadata-form/template.hbs
- lib/osf-components/addon/components/node-metadata-manager/component.ts
- lib/osf-components/addon/components/node-metadata-manager/template.hbs
- lib/osf-components/app/components/editable-field/title-manager/component.js
- lib/osf-components/app/components/editable-field/title-manager/template.js
- lib/registries/addon/components/registries-metadata/styles.scss
- lib/registries/addon/components/registries-metadata/template.hbs
- lib/registries/addon/overview/-components/overview-header/styles.scss
- lib/registries/addon/overview/-components/overview-header/template.hbs
- tests/acceptance/guid-node/metadata-test.ts
- tests/engines/registries/acceptance/overview/index-test.ts
- tests/engines/registries/acceptance/overview/metadata-test.ts
- translations/en-us.yml
-   Ticket: [ENG-7267]
- Allow registration admins to update registration title and contributors
- Add logic to allow admin users to update registration title
- Add logic to allow admin users to update registration contributors
- On any registration page, title should be editable for admin users
- On registration metadata page, admins should be able to update the registration title
- On registration metadata page, contributors should be editable
- This will also allow admin users to update project/component contributors on the project metadata tab
[ENG-7267]: https://openscience.atlassian.net/browse/ENG-7267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7267] Allow updating registration title and contributors

- app/serializers/osf-serializer.ts
- lib/osf-components/addon/components/contributor-list/contributor/component.ts
- tests/integration/components/contributor-list/contributor/component-test.ts
-   Ticket: [ENG-5027]
- Show deleted user's names in contributor fields
- Add logic in osf-serializer to finagle deleted user data onto contributor model
- Update contributor-list/contributor component to look for deleted user data in case ContributorModel.user relationship is undefined
- Prevents deleted user names from showing up as blank on the preprint overview page
- _may_ be introducing a new error when setting head tags, specifically these lines where we try to sparse-load contributors and their users https://github.com/CenterForOpenScience/ember-osf-web/blob/master/app/preprints/detail/route.ts#L155-L158
- Verify that deleted users (probably via the admin app GDPR delete them?) have their names shown in preprint detail page
[ENG-5027]: …
> [ENG-5027] Pass deleted user info into contributor

- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
- mirage/factories/configured-storage-addon.ts
- tests/acceptance/guid-node/addons-test.ts
- tests/integration/components/addons-service/configured-addon-edit/component-test.ts
-   Ticket: [ENG-7025]
- Tighten criteria for when "Save" button on configured addon edit page is disabled
- Spent an embarrassing amount of time reasoning through these following conditions to disable save button:
- configured addon display name is empty
- configured addon needs a root folder and none is selected
- the display name has not been changed
- the root folder has not been changed
- Update mirage factory to assume folks are the account owner for configured-storage-addons
- When editing a node's configured account and neither the display name or root folder has been changed (not the "Save" button is disabled):
[ENG-7025]: https://openscience.atlassian.net/browse/ENG-7025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
> [ENG-7025] Enable save when name or root folder changes

- app/preprints/detail/controller.ts
- tests/acceptance/preprints/detail-test.ts
-   Ticket: https://openscience.atlassian.net/browse/ENG-7472
Make it possible to resubmit rejected preprint versions
Make it possible to resubmit rejected preprint versions
TBD
TBD
> [ENG-7472] fixed recent preprint rejected versions doesnt have option to resubmit

- app/models/preprint.ts
- app/preprints/detail/route.ts
- app/preprints/detail/template.hbs
- app/services/analytics.ts
-   Ticket: [ENG-7337]
- Send metrics for preprints with unverified DOIs
- Should be released in conjunction with this PR to avoid potential console errors https://github.com/CenterForOpenScience/ember-osf-web/pull/2517
- Remove check to see if preprint DOI has been verified (checked using the `PreprintModel. preprintDoiCreated` property as a proxy)
- Rename `verifiedDoi` property to `extractedDoi` to avoid misleading name
- NA
- Will likely lead to requests that will come back with a `422` code to datacite usage tracker while the DOI is not verified
- Verify that this fix is working by testing on a newly published and public preprint that does not have a `preprint_doi_created` in the API
- Viewing/downloading this preprint in the OSF should trigger a request to …
> [ENG-7337] Send metrics for unverified DOIs

- app/preprints/-components/preprint-file-render/template.hbs
-   Ticket: [ENG-7553]
- Fix bug where dropdown to download prior versions was removed
- Undo some bad find-and-replace done in this commit https://github.com/CenterForOpenScience/ember-osf-web/pull/2447/commits/a4535b7aa43b3e34c7b9e33f7c3955e6fa1a1cde
- Screenshot available in JIRA ticket
- This is to allow users to download previous *file versions* of a preprint (the old workflow for updating a preprint). This is *not* the same as the "preprint version".
[ENG-7553]: https://openscience.atlassian.net/browse/ENG-7553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Hotfix] [ENG-7553] Fix logic to show/hide file version download

- lib/osf-components/addon/components/subjects/manager/component.ts
-   Ticket: [ENG-7712]
- Prevent bug that prevents a write-user from updating registration metadata
- Remove subjects relationship data from PUT request payload
- Subjects are only editable by registration admins, so having this included in the request payload was preventing write users from editing metadata
- ember remove subjects in PATCH request payload
Before:
After:
[ENG-7712]: https://openscience.atlassian.net/browse/ENG-7712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7712] Write user subjects

- lib/osf-components/addon/components/node-metadata-form/template.hbs
- lib/osf-components/addon/components/node-metadata-manager/component.ts
- lib/osf-components/addon/components/node-metadata-manager/template.hbs
- lib/osf-components/addon/components/subjects/manager/component.ts
- translations/en-us.yml
-   Ticket: [ENG-7712]
- Fix issues with write-users not being able to update registration metadata due to subjects being added to request payloads
- Undo changes made in this PR https://github.com/CenterForOpenScience/ember-osf-web/pull/2534
- Update the node metadata form to show subject picker only for admin users
- Only show selected subjects for write and read users
- Write user and no subjects on the registration
- Write user and some subjects on the registration
- Admin users view (unchanged)
[ENG-7712]: https://openscience.atlassian.net/browse/ENG-7712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7712]  Redo write-user subjects handling

- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/styles.scss
- lib/osf-components/addon/components/addons-service/configured-addon-edit/template.hbs
- translations/en-us.yml
-   Ticket: [ENG-7714] [ENG-7025]
- Fix issue where Configure Addon page's Save button was enabled when users had not yet selected a root folder
- Improve UX so users will see their currently selected root folder at the top of the page and root folder will be selected when navigating back to a view that shows the current root folder selection
- Update logic for when Save button is disabled (`selectFolder` was an action, `selectedFolder` is the correct variable to use 😮‍💨 )
- Update confusing `hasRootFolder` property name to `requiresRootFolder`
- Add a "Selected folder:" display to help users know which folder is the currently selected root
- Add logic to pre-select radio button if the shown item is the currently selected root folder
- fix issue where Save button was …
> [ENG-7714] [ENG-7025] Configure addon page updates

- app/preprints/-components/submit/metadata/component.ts
- app/preprints/-components/submit/metadata/template.hbs
- lib/osf-components/addon/components/subjects/manager/component.ts
-   Ticket: [ENG-7712]
- Allow write users to update registration metadata without getting yelled at about how "Only admins can edit subjects"
- Remove unnecessary setting of node subjects in the subjects manager
- This was causing the node's subjects to get included into the PATCH request whenever the subjects::manager component was invoked (which wasn't good when a write-user was viewing a page with it)
- Remove other unneeded logic that was mucking things up
[ENG-7712]: https://openscience.atlassian.net/browse/ENG-7712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7712] Fix issue with write users editing registration metadata

- app/preprints/-components/submit/supplements/component.ts
-   Ticket: [ENG-6326]
Prevent supplements from caching on the review page after removal
Reviewed the preprint from the node which was reverse of what was happening
N/A
Likely and at this point, uncertain.
Should work now!
[ENG-6326]: https://openscience.atlassian.net/browse/ENG-6326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6326] Bug fix for supplements caching

- app/institutions/discover/controller.ts
Institutions preprints search page has `creator.affiliation` filter that is implicitly added to share request and results different number of preprints than dashboard and global search pages. On the other hand, dashboard and global searches add `affiliation` filter instead.
Use default `affiliation` key instead of replacing it by `creator.affiliation` for preprints
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145?selectedIssue=ENG-7555
> [ENG-7555] Use the same share filters for dashboard, institutions preprints and global searches

- lib/app-components/addon/components/branded-navbar/template.hbs
- lib/osf-components/addon/components/osf-navbar/preprint-links/component.ts
- lib/osf-components/addon/components/osf-navbar/preprint-links/template.hbs
- tests/integration/components/osf-navbar/component-test.ts
-   Ticket: [ENG-6267]
Updated the branded and non-branded preprint navbar to respect the `allowSubmission` attribute on a preprint provider
The Branded Navbar only needed an if statement (this demonstrated that the bug was for all providers and not just the OSF)
On the non-branded navbar for just OSF needed the theme service injected to have the if statement work.
Could be many issues.
Give it a try
[ENG-7799]: https://openscience.atlassian.net/browse/ENG-7799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-6267]: https://openscience.atlassian.net/browse/ENG-6267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6267] Add the ability to turn off the "add a preprint" feature based on the admin section

- app/preprints/-components/submit/file/upload-file/component.ts
- app/preprints/-components/submit/file/upload-file/template.hbs
-   Ticket: ### [ENG-7588]
There was the slightest chance of a race condition that I fixed using the "preUpload" called and a spinner.
I first tried to use "enabled=false" and it literally destroys the entire widget. So then I moved to the spinner
Add a variable and preUpload method to the component.
Added the variable to the spinner conditional statement to display the spinner once the file is uploaded.
N/A
None
Should be good to go.
[ENG-7588]: https://openscience.atlassian.net/browse/ENG-7588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7558] Fixed the file upload issue

- app/models/index-card-search.ts
- app/models/search-result.ts
- lib/osf-components/addon/components/search-page/component.ts
-   Ticket: [ENG-7937]
fix wrong text displaying on the search page when there are many results (shows `trove:ten-thousands-and-more`, should show something like "10,000+ results")
update literal IRIs to compact IRIs to align with the search api (`https://share.osf.io/vocab/2023/trove/...` and `https://osf.io/vocab/2022/...` are namespaces, given prefixes `trove:...` and `osf:...` respectively)
(yet todo: json-ld parsing that would handle either)
[ENG-7937]: https://openscience.atlassian.net/browse/ENG-7937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7937] fix: use compact IRIs to match the api

- lib/osf-components/addon/components/activity-log/component.ts
OSF Groups is being deprecated this PR removes it's use from the FE
- Don't embed `group` anymore
Speeds up log check
https://openscience.atlassian.net/browse/ENG-8178
> [ENG-8178] remove unnecessary group embed

- app/preprints/-components/submit/title-and-abstract/template.hbs
-   Ticket: [ENG-8146](https://openscience.atlassian.net/browse/ENG-8146)
Hide manual guid and doi fields for preprint edit flow
N/A
N/A
N/A
N/A
[ENG-8146]: https://openscience.atlassian.net/browse/ENG-8146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-8146] Follow-up Fix: Hide manual guid and doi fields for preprint edit flow

- app/guid-node/links/styles.scss
- app/guid-node/links/template.hbs
- lib/osf-components/addon/components/addons-service/file-manager/component.ts
- translations/en-us.yml
-   Ticket: [ENG-8078]
[ENG-8078]: https://openscience.atlassian.net/browse/ENG-8078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-8078] 2.4.7 FE: Show a dedicated empty linked services page when no LINK add-on is configured

- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
-   Ticket: [ENG-8236](https://openscience.atlassian.net/browse/ENG-8236)
Fix missing resource-type dropdown during linked service configuration
Fix missing resource-type dropdown during linked service configuration
https://github.com/user-attachments/assets/4253792b-dafe-481c-ba16-507df8e5f874
N/A
N/A
[ENG-8236]: https://openscience.atlassian.net/browse/ENG-8236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-8236] Fix missing resource-type dropdown during linked service configuration

- app/guid-node/addons/index/template.hbs
- app/models/configured-addon.ts
- app/models/configured-citation-addon.ts
- app/models/configured-link-addon.ts
- app/models/configured-storage-addon.ts
-   Ticket: [ENG-8235]
[ENG-8235]: https://openscience.atlassian.net/browse/ENG-8235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-8235] Fix link addon reconfiguration

- lib/osf-components/addon/components/addons-service/configured-addon-edit/template.hbs
- translations/en-us.yml
-   Ticket: [ENG-8266](https://openscience.atlassian.net/browse/ENG-8266)
When no dataverse, dataset or file is connected, "linked item" should say "no item selected" instead of "no folder selected".
When no dataverse, dataset or file is connected, "linked item" should say "no item selected" instead of "no folder selected".
N/A
N/A
[ENG-8266]: https://openscience.atlassian.net/browse/ENG-8266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-8266] Fix "linked item" for linked service configuration

- app/guid-node/addons/index/template.hbs
- app/guid-node/links/styles.scss
- app/guid-node/links/template.hbs
- app/helpers/instance-of.ts
- translations/en-us.yml
-   Ticket: [ENG-8244] [ENG-8255]
[ENG-8244]: https://openscience.atlassian.net/browse/ENG-8244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-8255]: https://openscience.atlassian.net/browse/ENG-8255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-8255][ENG-8244] Show item name when deleting linked service; fix linked service page for mobile

- app/decorators/check-auth.ts
- mirage/views/addons.ts
-   Ticket: [ENG-8174]
Users were experiencing errors when either a %2[fF] or / was at the end of the viewOnlyToken
Added a regex to remove %2[fF] or / from the end of the viewOnlyToken.
Also change a miscellaneous console.log to be console.info to make it easier to find and remove console.logs while debugging.
N/A
There could be other characters at the end of the viewOnlyToken added by the user or a rogue url parser that is not covered in this fix.
Super hard to duplicate. I wasn't able to. Good Luck
[ENG-8174]: https://openscience.atlassian.net/browse/ENG-8174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-8174] Updates to fix the viewOnlyToken in cases there is a / or %2fF at the end
