CenterForOpenScience/ember-osf-web

- app/index.html
- config/environment.js
- ember-cli-build.js
- package.json
- yarn.lock
> Changes to get ready for staging

- .eslintrc.js
- app/app.js
- app/application/controller.js
- app/file-detail/controller.js
- app/file-detail/route.js
- app/quickfiles/route.js
- app/router.js
- app/user-quickfiles/controller.js
- app/user-quickfiles/route.js
- config/environment.js
- ember-cli-build.js
- package.json
- testem.js
- tests/helpers/destroy-app.js
- tests/helpers/module-for-acceptance.js
- tests/helpers/resolver.js
- tests/helpers/start-app.js
- tests/test-helper.js
- tests/unit/application/controller-test.js
- tests/unit/application/route-test.js
- tests/unit/file-detail/controller-test.js
- tests/unit/quickfiles/route-test.js
- tests/unit/user-quickfiles/controller-test.js
- tests/unit/user-quickfiles/route-test.js
- yarn.lock
This PR adds the [COS ESLint Configuration](https://www.npmjs.com/package/@centerforopenscience/eslint-config) and resolves all errors and most warnings.
The majority of errors were resolved with [--fix](https://eslint.org/docs/user-guide/command-line-interface#--fix), but there were coupe of things that had to be resolved manually, which I did in a separate commit. I also resolved all but one warning, also in a separate commit.
Some of the fixes were just whitespace change. To ignore whitespace add `?w=1` to the end of the diff url.
> Add COS ESLint config

- package.json
- yarn.lock
> Use Baylee's ember-osf with all the things

- package.json
- yarn.lock
Use updated ember-osf with all the things for Quick Files
> Use latest baylee-d/ember-osf.git#feature/updated-versions-and-renderer

- package.json
- yarn.lock
Keep up-to-date with latest COS ESLint config
> [EOSF-767] Update to @centerforopenscience/eslint-config@^2.0.0

- app/file-detail/template.hbs
- app/styles/app.scss
https://openscience.atlassian.net/browse/EOSF-769
Small fixes for the file-detail page.
- Added placeholder for tags and styling for it.  Placeholder will now say `add a tag`
- Changed file-version component call to accommodate changes done to include closure actions
> [EOSF-769] Add tag placeholders and closure action for versions

- package.json
For consistency with other Ember apps.
> [EOSF-767] Added bugs url and homepage to package.json

- app/user-quickfiles/template.hbs
> [EOSF-767] Remove fullName's Quick Files header

- app/components/quickfile-nav/template.hbs
Use link-to in nav to stay in Ember app
> [EOSF-767] Use link-to in nav to stay in Ember app

- app/file-detail/route.js
Make sure the user is fully loaded when accessing the file-detail route.
Fore a reload on the user associated with the quick file.
This results in an API call that may be unnecessary if we refactor to use embedding.
https://openscience.atlassian.net/browse/EOSF-769
> [EOSF-769] Reload user on file detail route

- app/file-detail/controller.js
- app/file-detail/template.hbs
- package.json
- yarn.lock
There are some final tweaks to be done for parts of Quick Files before sending off to QA.  This PR handles some of the style and functionality changes.  
- Used the `outsideClick` function to determine if the user clicks outside of the popup (and toggles accordingly)
- Added bootstrap classes to the file versions table's columns to make them disappear when the screen is medium width or smaller.
None
> Styling changes for file versions and share popup

- app/file-detail/template.hbs
- app/styles/app.scss
To make the tags more consistent with OSF style tags.
- Changed the wording for new tags (from `add a tag` to `add a tag to enhance discoverability`
- Made the `width: 100%` to make the entire phrase readable (also makes it easier to add tags, since it's all on a single line)
https://openscience.atlassian.net/browse/EOSF-911
> [EOSF-911] Change style for tags

- package.json
- yarn.lock
To update ember-osf-web to the newest version of ember-osf.
None
> [EOSF-913, EOSF-919, EOSF-921, EOSF-922] Update to newest ember-osf

- ember-cli-build.js
Include Babel polyfill so that Quick Files works in IE 11
Added include babel polyfill option to ember-cli-build.js
Quick files should now work in IE 11
https://openscience.atlassian.net/browse/EOSF-938
> [EOSF-938] Include Babel polyfill for IE 11

- app/application/controller.js
- app/application/route.js
- app/application/template.hbs
Currently, sign in and sign up buttons on the navbar are not working in quick files.
Add properties for sign up and sign in buttons.
https://openscience.atlassian.net/browse/EOSF-920
> [EOSF-920] Add sign up/sign in functionality

- app/file-detail/controller.js
- app/file-detail/template.hbs
Make tags link to search
* Make each tag a links to search that tag
* DRY template refactor
* Make sure links work
* Make sure tags are still editable when they should be and not when they shouldn't
https://openscience.atlassian.net/browse/EOSF-930
> [EOSF-930] Make tags links to search

- app/index.html
- yarn.lock
There are errors in the current dropzone version we are using.  
Change dropzone version to earlier, safer version.
https://openscience.atlassian.net/browse/EOSF-939
> [EOSF-939] Change dropzone version

- app/file-detail/template.hbs
One of the translations on the file-detail page is looking in an undefined area for the translation.  
Change the translation so that it's calling the right place.
https://openscience.atlassian.net/browse/EOSF-880
> [EOSF-880] Fix call for version id translation

- package.json
- yarn.lock
To update to the latest ember-osf.
Update to latest.
https://openscience.atlassian.net/browse/EOSF-967
> [EOSF-967] Update to latest ember-osf

- package.json
- yarn.lock
Update to latest ember-osf@develop
`yarn use-ember-osf-develop`
N/A
N/A
> Use latest ember-osf@develop

- config/environment.js
- ember-cli-build.js
https://openscience.atlassian.net/browse/EOSF-
> Update ravenjs to 3.22.1, add releases configuration

- app/application/template.hbs
- app/index.html
Make page title for Quick Files consistent with other pages on the OSF
- Add "OSF | " prefix to QF title
- Make default title "OSF"
No ticket
> Fix page titles

- CHANGELOG.md
- app/components/file-share-button/component.js
Fix `file-share-button` dynamic iframe code
Inject jQuery properly in `file-share-button` dynamic iframe code
Should fix both extra characters and perpetual loading indicator
https://openscience.atlassian.net/browse/EMB-108
> [EMB-108] quick files share links on file detail page dont work

- app/components/feedback-button/component.js
- app/components/feedback-button/styles.scss
- app/components/feedback-button/template.hbs
- app/components/success-icon/styles.scss
- app/components/success-icon/template.hbs
- app/locales/en/translations.js
- app/user-quickfiles/controller.js
- app/user-quickfiles/template.hbs
- config/environment.js
Add feedback button to Quick Files page
Example JIRA issue: https://openscience.atlassian.net/browse/FEED-9
This replaces #67 
- Add feedback-button component
- Requires the following configuration (for staging and prod):
```js
microfeedback: {
url: 'https://microfeedback-osf.herokuapp.com/13209/3',
pageParams: {
QuickFiles: {
componentID: '13836',
priorityID: '10100',
},
},
},
```
https://openscience.atlassian.net/browse/EMB-119
close #67 
close #71
> [EMB-119] Add feedback button Ember component

- package.json
- yarn.lock
Get the work done in ember-osf onto the ember-osf-web project so we can test.
Change from the 0.14 tag of ember-osf to the github repo's latest dev tag
My environment isn't fully set up, so please make sure this works at all.
https://openscience.atlassian.net/browse/EMB-102
> [EMB-102] Upgrade to latest dev commit of ember-osf for adding in Move to File

- app/components/feedback-button/component.js
- app/components/feedback-button/template.hbs
- app/user-quickfiles/template.hbs
- config/environment.js
- Don't show "Contact me" if not logged in
- Add a flag to enable/disable feedback button
- Post current user--not quickfiles user--in issue
https://openscience.atlassian.net/browse/EMB-119
> [EMB-119] Feedback button fixes

- app/locales/en/translations.js
Language changes requested by Product.
https://openscience.atlassian.net/browse/EMB-119
> [EMB-119] Language changes to the feedback dialog

- app/components/feedback-button/template.hbs
- app/locales/en/translations.js
> Update dismiss button color and text

- app/locales/zh/translations.ts
> [No Ticket] Minor updates for zh

- package.json
Lint them templates!
Add `ember-template-lint` for .hbs files to lint-staged.
N/A
N/A
> Add template-lint to lint-staged

- app/mixins/osf-token-login-route.js
- config/environment.js
- package.json
The current config file is overly complex.
* Remove unnecessary knownBackends
* Use properties from merged environment variables with local file
N/A
> Cleanup ember config

- testem.js
Use Testem's dot reporter instead of the default TAP reporter for less noise.
Set reporter to `new DotReporter()` in testem.js
N/A
N/A
> Use testem dot reporter instead of default TAP

- app/models/guid.ts
Fix guid routing, which got messed up while responding to review.
Remove an orphan `foo`.
Guid routing (and the `zoom-to-guid` button) should work now.
https://openscience.atlassian.net/browse/EMB-6
> [EMB-6] Un-foo guid routing

- app/application/template.hbs
Styles in routes currently override things in the navbar and footer
Moves components in the application route outside the scoped div
> Move navbar maintenance banner, footer, etc outside the Application div

- app/components/new-navbar-auth-dropdown/styles.scss
- app/components/new-navbar-auth-dropdown/template.hbs
Fixes gravatar w/o border-radius
Follow-up from #119 🎩@baylee-d 
Adds required style to gravatar and rename the class to match conventions
N/A
https://openscience.atlassian.net/browse/EMB-154
> [EMB-154] Add gravatar style

- app/components/contributor-list/component.ts
- tsconfig.json
No ticket / quick fix
🎩 @alexschiller for finding and reporting.
Bonus: use decorators
> Fallback to fullName for contributors list and use decorators

- app/services/current-user.ts
> Call isRunning properly

- config/environment.js
> Use 'ember_home_page' as the flag for dashboard and home routes

- app/components/osf-navbar/auth-dropdown/component.ts
Gravatar needs to be showing
Fix computed property to wait on the proper attribute being populated on user
https://openscience.atlassian.net/browse/EMB-181
> [EMB-181] Make sure profile_image link is loaded by triggering computed on it

- app/components/file-browser/component.ts
- app/components/file-browser/template.hbs
- app/components/file-list/styles.scss
A few things to fix up h/t @icereval for the QA
> A few minor fixes from quickfiles typescript conversion

- app/dashboard/styles.scss
> Add button style back for more button on dashboard

- app/components/institution-carousel/component.ts
Institutions wasn't being initialized with the default value
> use defaults with institution-carousel to fix loading

- app/components/institution-carousel/template.hbs
- app/home/template.hbs
- app/locales/en/translations.ts
- app/locales/zh/translations.ts
- app/services/analytics.ts
- app/support/route.ts
Find some problem items from https://github.com/CenterForOpenScience/ember-osf-web/pull/99#pullrequestreview-108985258
Added onclicks to:
- Institution carousel items
- Home page 'explore activity'
- Home page 'sign up'
- Home page 'cos.io fundraising'
Other items
- Fix missing href on home page 'sign up'
- Fix private method on analytics
- Use decorator for support route action
- Sentence-case Help button on Quickfiles
No side effects anticipated.
Related to some changes from https://openscience.atlassian.net/browse/EMB-133
> Fix missing onclicks and other cleanup

- app/components/file-browser/component.ts
- app/guid-user/quickfiles/controller.ts
Handle move to project error by showing error and keeping dialog open
Return boolean from move file based on success / failure
https://openscience.atlassian.net/browse/EMB-194
> [EMB-194] Handle move to project error

- app/components/file-browser/component.ts
- app/locales/en/translations.ts
- app/locales/ja/translations.ts
- app/locales/zh/translations.ts
i18n
'A file has been added' toast message moved to translations
> Move bare string to translations

- app/dashboard/controller.ts
- app/dashboard/route.ts
- app/dashboard/template.hbs
Cause users with no projects to see the proper messaging
Adjusted the computed to check for things that exist.
The computed isn't being used by anything else, so shouldn't have side effects. I'm not sure what changed that caused meta to go away in that circumstance, because that looked to be the more correct way to do that, and I don't know why empty filter changed from being a null to a string. However, it works now and shouldn't interfere with anything else.
I'm looking forward to having tests.
https://openscience.atlassian.net/browse/EMB-200
> [EMB-200] Fix no node condition on dashboard

- app/components/file-browser/component.ts
Fix non-clickable dropzone when there are no files
https://openscience.atlassian.net/browse/EMB-199
> [EMB-199] Make clickable a computed to make body clickable when there are no items

- app/components/file-browser/component.ts
allow clickable upload
https://openscience.atlassian.net/browse/EMB-176
> [EMB-176] Remove isUploading as a computed requirement

- config/environment.js
Not a real error, needs to be ignored. It's the most prevalent error in Sentry.
Update sentryOptions in the config
https://docs.sentry.io/clients/javascript/config/
N/A
> Ignore TransitionAborted errors in Sentry emberjs/ember.js#12505

- app/locales/en/translations.ts
- app/locales/zh/translations.ts
Fix some additional text problems from QA
1. Capitalize Twitter
2. Change quickfiles to Quick Files
None
https://openscience.atlassian.net/browse/EMB-203
> [EMB-203] Quick text changes

- app/services/status-messages.ts
Efficiency / terseness
https://openscience.atlassian.net/browse/EMB-176
> [EMB-176] Refactor status-messages service

- app/services/analytics.ts
- app/services/current-user.ts
Fix TypeScript errors in existing services.
Minor refactors to fix TypeScript error.
Service should retain same functionality.
N/A
> Fix TypeScript errors in services

- app/guid-file/template.hbs
- app/guid-user/quickfiles/template.hbs
Fix the horizontal scrolling when viewing a Quick File.
This also fixes an alignment issue on the Quick Files list page.
* move `quickfile-nav` component inside container in `guid-file` template
* add row class to Quick Files content container
N/A
N/A
> Fix horizontal scrolling on guid file

- app/dashboard/controller.ts
- app/services/current-user.ts
Simplifies current-user service
Mostly code cleanup
No ticket
> Refactor current-user service

- app/components/file-browser/component.ts
- app/components/file-list/component.ts
- app/goodbye/route.ts
- app/guid-file/route.ts
- app/guid-node/route.ts
- app/guid-preprint/route.ts
- app/guid-registration/route.ts
- app/guid-user/route.ts
- app/home/route.ts
- app/quickfiles/route.ts
- app/resolve-guid/resolved-guid-route.ts
- app/support/controller.ts
Code consistency
Decorators, fix highlighting in file browser and file-list
https://openscience.atlassian.net/browse/EMB-207
> [EMB-207] Decorators for remaining routes/controllers

- CHANGELOG.md
- app/guid-file/route.ts
- app/locales/en/translations.ts
- app/locales/ja/translations.ts
- app/locales/zh/translations.ts
- app/services/meta-tags.ts
- app/templates/head.hbs
- app/utils/to-array.ts
- package.json
- tests/unit/services/meta-tags-test.ts
- tests/unit/utils/to-array-test.ts
- yarn.lock
Add meta tags to Quick Files.
* add a meta-tags service
* use meta-tags service for Quick File detail
Quick Files file detail should now have appropriate meta tags.
https://openscience.atlassian.net/browse/EMB-136
> [EMB-136] quick files missing meta tags for facebook and linked in descriptions

- app/services/meta-tags.ts
Add missing `og:title` metatag
Add `og:title` metatag
n/a
https://openscience.atlassian.net/browse/EMB-136
> [EMB-136] Add missing og:title metatag

- package.json
- yarn.lock
Stop the churn
Upgrade to [ember-cli-typescript@1.3.0-beta.2](https://github.com/typed-ember/ember-cli-typescript/releases/tag/v1.3.0-beta.2)
n/a
n/a
> Upgrade to ember-cli-typescript 1.3.0

- app/guid-file/template.hbs
Fix regression of https://github.com/CenterForOpenScience/ember-osf-web/pull/133
Show editor if not null (not just not falsy)
Should be able to edit empty files
https://openscience.atlassian.net/browse/EMB-127
> [EMB-127] Allow empty files to be edited

- app/components/file-browser/component.ts
Fix `file-browser` tsc errors
Fix `file-browser` tsc errors
n/a
n/a
> Fix file-browser tsc errors

- app/components/dropzone-widget/component.ts
- app/components/file-browser/component.ts
- app/components/file-browser/template.hbs
Make upload clickable again
Fix up dropzone-widget to only take an array for clickable
Use all of the required computed properties
> Better filter and computed clickable w/ dropzone

- app/components/file-browser/template.hbs
- app/components/project-selector/component.ts
- app/components/project-selector/template.hbs
Hitting enter on Quickfiles new project causes page refresh
Handle onsubmit event on the form in the project-selector component
Bonus: Close share popup on copy button click
https://openscience.atlassian.net/browse/EMB-243
> [EMB-243] Prevent default on form submission for project-selector

- app/components/dropzone-widget/component.ts
- app/locales/en/translations.ts
- app/locales/ja/translations.ts
- app/locales/zh/translations.ts
Fix bug where upload button allowed you to upload multiple files after the first time it was successfully used
1. Make prevent multiple a function
2. Call the function in the original place
3. Also call the function when dropzone's complete event fires
QA [requested we remove an exclamation point](https://openscience.atlassian.net/browse/EMB-65?focusedCommentId=67133&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-67133), so I have also removed that here rather than making a new ticket.
https://openscience.atlassian.net/browse/EMB-252
> [EMB-252] No multiple selects on Dropzone. Ever.

- app/locales/ja/translations.ts
- app/locales/zh/translations.ts
Keys are currently out of order, some moved around
N/A
> Remove unused keys and consistent order across translations

- app/locales/en/translations.ts
- app/locales/ja/translations.ts
- app/locales/zh/translations.ts
Support page was missing a colon, so this adds it in
Before
After
Should be good
https://openscience.atlassian.net/browse/EMB-72
> Add a missing colon

- app/guid-file/styles.scss
Long titles with no spaces get a little cramped. This gives them some breathing room.
Before
After
Nothing of note
https://openscience.atlassian.net/browse/EMB-248
> [EMB-248] Add some padding

- app/mixins/cas-authenticated-route.ts
Pass params and queryParams properly to urlFor so it doesn't error out.
spread params and nest queryParams in object with `queryParams` key
All other future CAS Authenticated Routes should work.
https://openscience.atlassian.net/browse/EMB-256
> [EMB-256] Pass params and queryParams properly to urlFor

- app/mixins/cas-authenticated-route.ts
Block render when redirecting to CAS so there's no FOUC
Return unresolvable promise to block render when redirecting to CAS
Should not see any content before the redirect
https://openscience.atlassian.net/browse/EMB-256
> [EMB-256] Block render when redirecting to CAS

- app/mixins/osf-authenticated-route.ts
- app/router.ts
- app/utils/auth.ts
- config/environment.d.ts
- tests/helpers/resolver.ts
- tsconfig.json
Actually use the config types defined in `config/environment.d.ts`
* Add config to tsc path so typedefs are actually used
* Add null/undefined checks where needed
* Use string index signatures in lookup objects
* Remove unnecessary type on feature flag name
* Remove unused `podModulePrefix` in test resolver
Types are now enforced for config. The only thing that could affect anything user-facing is the minor change in `app/utils/auth.ts`.
n/a
> Actually use config types

- app/guid-node/forks/styles.scss
> Fix long title cases for medium view

- app/institutions/styles.scss
- app/institutions/template.hbs
make `institutions/styles.scss and institutions/template.hbs` comply with how we are now doing styling
https://openscience.atlassian.net/browse/EMB-115
> [EMB-115] Fix institutions landing page styling 

- app/guid-node/forks/styles.scss
- app/guid-node/forks/template.hbs
- app/locales/en/translations.ts
- app/locales/ja/translations.ts
- app/locales/zh/translations.ts
- lib/osf-components/addon/components/node-blurb/styles.scss
Respond to QA on forks page
Fix small screen and dropdown css
Make "no forks" page look better
https://openscience.atlassian.net/browse/EMB-163
> [EMB-163] Forks fixes, css messed up by changes in how we do css, other improvements

- app/institutions/styles.scss
Make footer link color a11y compliant (more contrast)
> Make footer link color a11y compliant (more contrast)

- CHANGELOG.md
- app/components/tos-consent-banner/component.ts
- app/components/tos-consent-banner/template.hbs
- app/models/user.ts
- tests/integration/components/tos-consent-banner/component-test.ts
* Avoid premature validation of consent checkbox.
* Set acceptedTermsOfService to null if falsy
n/a
https://openscience.atlassian.net/browse/EMB-304
> [EMB-304] Avoid premature validation of consent checkbox

- app/guid-node/forks/controller.ts
- app/guid-node/forks/styles.scss
- app/guid-node/forks/template.hbs
- app/guid-registration/forks/controller.ts
- app/guid-registration/forks/styles.scss
- app/guid-registration/forks/template.hbs
- app/locales/en/translations.ts
- app/locales/ja/translations.ts
- app/locales/zh/translations.ts
- types/ember-toastr/index.d.ts
Fix qa-found issues with forks pages.
https://openscience.atlassian.net/browse/EMB-163
> [EMB-163] Add x to modal, better warning timing, wording for private forks

- README.md
- lib/handbook/addon/docs/contributing/template.md
- lib/handbook/addon/docs/conventions/template.md
- lib/handbook/addon/docs/dev-env/template.md
- lib/handbook/addon/docs/index/template.md
- lib/handbook/addon/docs/quickstart/template.md
- lib/handbook/addon/docs/resources/template.md
- lib/handbook/addon/docs/template.hbs
- lib/handbook/addon/docs/testing/template.md
- lib/handbook/addon/docs/visual-style/template.md
- lib/handbook/addon/docs/written-style/template.md
Add instructions for enabling the handbook to the README.
Also, make the handbook a little more useful.
> Add handbook instructions to the README

- config/targets.js
Speed up build/load time when running locally.
Add the [default `config/targets.js`](https://github.com/ember-cli/ember-new-output/blob/v3.1.4/config/targets.js). Excludes IE when building locally, so less has to be polyfilled (e.g. `async`/`await`, `class`, etc.). 
Should not affect deployments at all.
n/a
> Add config/targets.js to speed up local builds

- README.md
> Update readme for local development config

- lib/handbook/addon/docs/contributing/template.md
- lib/handbook/addon/docs/template.hbs
- lib/handbook/addon/docs/troubleshooting/template.md
- lib/handbook/addon/index/index-content/template.md
- lib/handbook/addon/index/styles.scss
- lib/handbook/addon/index/template.hbs
- lib/handbook/addon/routes.js
Add a troubleshooting page to the handbook.
> Add troubleshooting page to the handbook

- README.md
> Add watchman documentation link

- app/home/template.hbs
- app/institutions/template.hbs
Add the scheduled donate banner to institutions, remove from logged-out home
Add the scheduled donate banner to institutions, remove from logged-out home
n/a
https://openscience.atlassian.net/browse/EMB-314
> [EMB-314] Add banner to institutions, remove from logged-out home

- lib/handbook/addon/docs/components/loading-indicator/template.md
- lib/handbook/addon/docs/contributing/template.md
- lib/handbook/addon/docs/resources/template.md
- lib/handbook/addon/docs/template.hbs
Add some resources to the handbook.
Added resources to the resources page for Ember, TypeScript, and Ember + TypeScript and re-linked in navigation.
n/a
n/a
> Add some resources to handbook

- config/environment.d.ts
- config/environment.js
- lib/analytics-page/addon/services/keen.ts
Remove one of the duplicate Keen configs from `config/environment`, so it can be updated in only one place.
https://openscience.atlassian.net/browse/EMB-331
> [EMB-331] Remove duplicate keen config

- app/models/institution.ts
Logos went missing. This returns them to their rightful location
Before
After
Make the check for no 'assets' in the institutions model better
No, should be fine. Make sure we have logos again.
> Fix missing logos with better checks

- config/environment.d.ts
- config/environment.js
We define our footer links in the environment file, so google plus needed to be removed from there as well
* Remove from environment
* Remove from environment typedefs
No, although it highlights that maybe this is a little heavy for just footer links.
https://openscience.atlassian.net/browse/EMB-319
> [EMB-319] Google plus cleanup

- types/assertions.d.ts
- types/qunit.d.ts
Remove unneeded/unused type declarations.
* `rm types/assertions.d.ts` - these were for `ember-cli-custom-assertions`, which we are no longer using
* `rm types/qunit.d.ts` - this was an override of qunit's types for custom negative assertions
N/A
N/A
> Remove unneeded type declarations

- .github/PULL_REQUEST_TEMPLATE.md
Improve the Pull Request template to include feature flags and better instructions.
* separate `Side Effects` and `QA Notes`
* add `Feature Flags` section
* add instructions for each section
N/A *(no code change)*
Please review instructions for QA notes.
N/A
> PR template improvements

- package.json
- yarn.lock
Upgrade to ember-cli-mirage@0.4.8
`yarn upgrade ember-cli-mirage@latest`
N/A
N/A
> Upgrade to ember-cli-mirage@0.4.9

- .travis.yml
Fix the handbook deployed at https://centerforopenscience.github.io/ember-osf-web/handbook
Deploy the handbook with a dev build instead of a prod build, to avoid a bug in ember-cli-mirage.
Need to remember to revert when ember-cli-mirage [has been fixed](https://github.com/samselikoff/ember-cli-mirage/pull/1376)
n/a
n/a
n/a
> [no ticket] Deploy the handbook with a development build

- lib/osf-components/addon/components/hyper-link/component.ts
- lib/osf-components/addon/components/hyper-link/template.hbs
- lib/osf-components/addon/components/osf-navbar/template.hbs
- tests/integration/components/hyper-link/component-test.ts
> Properly yield navbar links and allow overriding `route`

- .travis.yml
Follow-up to #380 -- deploying the dev build of the handbook has a11y linting on by default. Turn that off.
> [no ticket] Disable a11y linting for the deployed handbook

- lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
Fix sign up link
Correct case of `_signupURL` in `auth-dropdown` template.
n/a
n/a
Sign Up link should work now!
n/a
> [no ticket] Fix sign up link

- config/environment.js
> Always enable app engines in prod builds

- lib/registries/addon/components/registries-recent-list/component.ts
- package.json
- yarn.lock
> [no ticket] Correct recent registration URLs

- lib/registries/README.md
> [No Ticket] Add useful links to the Registries README

- ember-cli-build.js
* Engines generates an environment.js file for fastboot compat
* By default environment.js is ignored from the engines assets manifest
* The regex in engines does not consider asset fingerprinting
> Don't fingerprint environment.js

- app/app.ts
- lib/app-components/addon/components/project-metadata/component.ts
- lib/collections/addon/components/collections-submission/template.hbs
- lib/collections/addon/engine.js
- Collections needs the `features` service
- `makePublicOnSave` option for making the node public in the project-metadata component
Add features service (used in osf-components).
N/A
- No new flags
Project is public after saving the metadata (so it can be indexed by search)
https://openscience.atlassian.net/browse/EMB-313
> [EMB-313] Feature/collections 

- app/models/node.ts
Tags are supposed to be optional
Disables validation for tags (Makes tags optional in submit/edit)
N/A
Should not make tags required on the collections submit/edit page in the Project Metadata section
https://openscience.atlassian.net/browse/EMB-313
> [EMB-313] Disable tags validation for collectable nodes (tags should be optional)

- app/models/registration-schema.ts
- lib/osf-components/addon/components/draft-registration-card/component.ts
Questions whose answer value is boolean questions were never counted as answered in the draft-registration-card progress bar.
* Add `boolean` and `string[]` as possible answer value types
* Only check length on arrays to determine if question is answered
n/a
n/a
Make sure the progress bar on the draft registrations tab works correctly for all registration schema.
https://openscience.atlassian.net/browse/EMB-186
> [EMB-186] handle boolean questions

- app/models/token.ts
- app/settings/tokens/x-token-form/styles.scss
Fix token name validation and safari checkboxen.
- Set token name max length to 100.
- Prevent checkboxes from shrinking next to long text in safari.
I still don't understand why the checkboxes would oscillate while resizing the page:
but regardless, they don't anymore.
n/a
n/a
- Trying to create token with name length > 100 should still not work, but in a friendly way.
- Safari. Checkboxes. All same.
https://openscience.atlassian.net/browse/EMB-341
> [EMB-341] Tokens page additional dev

- CHANGELOG.md
- config/environment.js
Remove `ember_project_forks_page` and `ember_project_analytics_page` feature flags, so the legacy version of those pages can be removed.
Delete flags.
n/a
n/a
Check that the forks and analytics pages load as expected for both projects and registrations. Other than that, not much to test.
https://openscience.atlassian.net/browse/EMB-364
https://openscience.atlassian.net/browse/EMB-365
> [EMB-364][EMB-365] Ignore analytics/forks feature flags

- mirage/factories/utils.ts
Make mirage guids more realistic.
Remove `01ilo` from the alphabet used to generate fake guids.
n/a
n/a
n/a
n/a
> [no ticket] Use the same guid alphabet in mirage as in real life

- lib/collections/addon/components/collection-item-picker/component.ts
> Add the s. It's plural.

- lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
#440 broke some links in the navbar auth dropdown. This fixes them.
Attach actions to the links using `onclick=` instead of plopping them in element space (which calls `preventDefault` automatically).
n/a
n/a
Click the navbar links, make sure they go where they should. Specifically, the broken ones were "My Profile" and "Settings" in the user/auth dropdown:
The changes in #440 should still work: When you click a link in an expanded menu, the menu should collapse.
> [EMB-377][8] Fix external links in the navbar auth dropdown

- CHANGELOG.md
- lib/handbook/addon/docs/components/loading-indicator/demo-dark/template.hbs
- lib/handbook/addon/docs/components/loading-indicator/demo-default/template.hbs
- lib/handbook/addon/docs/components/loading-indicator/demo-inline-dark/template.hbs
- lib/handbook/addon/docs/components/loading-indicator/demo-inline-default/styles.scss
- lib/handbook/addon/docs/components/loading-indicator/demo-inline-default/template.hbs
- lib/handbook/addon/docs/components/loading-indicator/template.md
- lib/osf-components/addon/components/loading-indicator/component.ts
- lib/osf-components/addon/components/loading-indicator/template.hbs
- tests/integration/components/loading-indicator/component-test.ts
To add an inline loading indicator to the app
- Added `inline` property to `loading-indicator` component
- Added tests
- Added to the handbook
N/A
N/A
N/A
N/A
> Add inline option for loading-indicator

- lib/registries/addon/components/registries-advisory-board/template.hbs
> Update advisory board

- lib/app-components/addon/components/search-paginator/template.hbs
- lib/registries/addon/discover/controller.ts
- lib/registries/addon/discover/template.hbs
- tests/engines/registries/integration/discover/discover-test.ts
> [Hotfix] Registries Discover: page reseting and scrolling fixes

- lib/registries/addon/components/registries-header/template.hbs
- lib/registries/addon/discover/controller.ts
- tests/engines/registries/integration/discover/discover-test.ts
> Reset to 1st page when typing a query

- package.json
- tests/engines/registries/acceptance/landing-page-test.ts
- types/ember-mockdate-shim.d.ts
- yarn.lock
Display the same date no matter when the test is run, to prevent confusing Percy.
Install ember-mockdate-shim, use it in the registries acceptance tests.
Makes it easy to mock dates elsewhere, if we need to.
> [no ticket] chore(tests): fix date in registries acceptance test

- app/settings/account/-components/security/template.hbs
Clean up some remaining double quotes.
Switch double to single quotes.
n/a
n/a
n/a
https://openscience.atlassian.net/browse/EMB-533
> [EMB-533] switch double to single quotes in settings > account > security component

- app/institutions/styles.scss
- app/institutions/template.hbs
- app/models/institution.ts
- lib/osf-components/addon/components/file-browser/component.ts
- lib/osf-components/addon/components/file-browser/styles.scss
- lib/osf-components/addon/components/file-browser/template.hbs
- lib/osf-components/addon/components/file-version/styles.scss
- lib/osf-components/addon/components/institution-carousel/template.hbs
- lib/osf-components/addon/components/new-project-modal/component.ts
- lib/osf-components/addon/components/new-project-modal/styles.scss
- lib/osf-components/addon/components/new-project-modal/template.hbs
- lib/osf-components/addon/components/osf-navbar/auth-dropdown/styles.scss
- lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
- lib/osf-components/addon/components/sort-button/styles.scss
- mirage/factories/user.ts
- mirage/scenarios/default.ts
- tests/acceptance/dashboard-test.ts
Fix problems found by QA.
1. Ensure background of buttons for versions in the list is transparent
2. Ensure that uploaded items get their padding
3. Remove the id in the share button which was preventing the onClick action from acting
4. Change the highlight color of the sort buttons to a standard OSF blue color
5. Rename the badly named action
6. Add user institutions to mirage
7. Add missing NewProjectModal test
8. Give sign-out button in auth dropdown the same style as all the other items
https://openscience.atlassian.net/browse/EMB-533
> [EMB-533] Fix style and click problems found by QA

- app/institutions/styles.scss
- app/institutions/template.hbs
- app/models/institution.ts
- lib/osf-components/addon/components/file-browser/component.ts
- lib/osf-components/addon/components/file-browser/styles.scss
- lib/osf-components/addon/components/file-browser/template.hbs
- lib/osf-components/addon/components/file-version/styles.scss
- lib/osf-components/addon/components/institution-carousel/template.hbs
- lib/osf-components/addon/components/new-project-modal/component.ts
- lib/osf-components/addon/components/new-project-modal/styles.scss
- lib/osf-components/addon/components/new-project-modal/template.hbs
- lib/osf-components/addon/components/osf-navbar/auth-dropdown/styles.scss
- lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
- lib/osf-components/addon/components/sort-button/styles.scss
- mirage/factories/user.ts
- mirage/scenarios/default.ts
- tests/acceptance/dashboard-test.ts
One small merge conflict resolved in `mirage/scenarios/default.ts`
> back-merge release/19.1.0 -> develop

- app/guid-file/template.hbs
- lib/osf-components/addon/components/file-version/template.hbs
- mirage/config.ts
- mirage/factories/registration.ts
- mirage/scenarios/default.ts
- mirage/views/wb.ts
- tests/acceptance/guid-node/registrations-test.ts
- tests/integration/components/file-version/component-test.ts
Fix broken versions table on guid-file detail page
1. Move data-analytics-scope div to outside of the table row
2. Upgrade mirage for file registrations, versions, file rename, and file delete.
First PR for https://openscience.atlassian.net/browse/EMB-408
> [EMB-408] Fix broken versions display

- CHANGELOG.md
- app/models/osf-model.ts
- app/serializers/comment-report.ts
- app/utils/get-self-href.ts
- lib/collections/addon/components/collections-submission/component.ts
- types/osf-api.d.ts
Add create, delete relationships `osfModel` helpers
> Add create, delete relationships helpers

- tests/helpers/index.ts
Caught the null element and raised a better error message.
> Give a more useful error when you try to click on an non-existent element

- lib/osf-components/addon/components/new-project-modal/template.hbs
- lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
- lib/registries/addon/components/registries-navbar/template.hbs
Make selenium testing easier
1. Put back a removed cancel button for the New Project modal
2. Add test selectors into Auth Dropdown of navbar and registries navbar
Here you go! Sorry for the trouble
> Add in some test selectors for QA

- app/locales/en/translations.ts
- app/models/node.ts
- app/transforms/node-category.ts
- lib/osf-components/addon/components/tags-widget/template.hbs
- lib/registries/addon/components/comments-list/template.hbs
- lib/registries/addon/components/gutters/styles.scss
- lib/registries/addon/components/registries-metadata/template.hbs
- lib/registries/addon/components/sharing-icons/dropdown/styles.scss
- lib/registries/addon/components/sharing-icons/dropdown/template.hbs
- lib/registries/addon/overview/template.hbs
Tidy up the overview page for a demo on staging.
Align some icons, add some missing translations, remove some hard-coded wrongnesses.
> [no ticket] Overview page demo tidying

- app/router.ts
- tests/acceptance/resolve-guid-test.ts
- types/ember-osf-web/@ember/routing/-private/transition.d.ts
Transitioning to a waffled-off route via `resolve-guid` doesn't check the waffle for the eventual target route, so you can end up on a blank page by accident. An example on prod is clicking a fork on a node's fork page:
Override the router's `_doURLTransition`, have it do the same things we added to `_doTransition`
> [hotfix] Check waffle on URL transitions

- app/locales/en/translations.ts
- app/utils/slugify.ts
- lib/registries/addon/components/registration-form-view/component.ts
- lib/registries/addon/components/registration-form-view/styles.scss
- lib/registries/addon/components/registration-form-view/template.hbs
- lib/registries/addon/components/responsive-dropdown/component.ts
- lib/registries/addon/components/responsive-dropdown/styles.scss
- lib/registries/addon/components/responsive-dropdown/template.hbs
- lib/registries/addon/overview/styles.scss
- tests/engines/registries/acceptance/overview/overview-test.ts
Add registration form navigation menu
N/A
[[EMB-477]](https://openscience.atlassian.net/browse/EMB-477)
> [EMB-477] Add form navigation menu

- app/dashboard/controller.ts
- app/guid-node/forks/controller.ts
- app/guid-registration/forks/controller.ts
- app/models/node.ts
- lib/analytics-page/addon/application/controller.ts
- lib/handbook/addon/docs/components/contributor-list/route.ts
- lib/osf-components/addon/components/contributor-list/component.ts
- lib/osf-components/addon/components/contributor-list/contributor/component.ts
- lib/osf-components/addon/components/contributor-list/contributor/template.hbs
- lib/osf-components/addon/components/dashboard-item/component.ts
- lib/osf-components/addon/components/node-list/component.ts
- lib/registries/addon/overview/route.ts
- mirage/config.ts
- mirage/factories/contributor.ts
- mirage/serializers/node.ts
- mirage/serializers/registration.ts
- tests/integration/components/contributor-list/component-test.ts
- tests/integration/components/dashboard-item/component-test.ts
- tests/integration/components/node-card/component-test.ts
- tests/integration/components/noteworthy-and-popular-project/component-test.ts
Non-bibliographic contributors shouldn't be included in lists of contributors, except on the contributors management page (which isn't emberized yet).
Going by commit:
- https://github.com/CenterForOpenScience/ember-osf-web/commit/c642fafe615328fe524837672ed4c4cec8b58d36: add `bibliographic_contributors` relationship to `Node`
- https://github.com/CenterForOpenScience/ember-osf-web/commit/9b0831e9357275de6d049468f24d7fb4d7e42941: update `<ContributorList>` to use `bibliographic_contributors`
- https://github.com/CenterForOpenScience/ember-osf-web/commit/0f38490fd11f64ea12fdebb2dc8cc6fe8a53a05f: go through the rest of the app, update `include: 'contributors'` to `include: 'bibliographic_contributors` and similar
The mirage implementation of `bibliographic_contributors` is kinda hacky and …
> [HOLD][EMB-392] Show only bibliographic contributors in contributor lists

- lib/registries/addon/components/registries-navbar/styles.scss
- lib/registries/addon/components/registries-navbar/template.hbs
- tests/engines/registries/integration/components/registries-navbar/component-test.ts
Add. dev. fixes to adress issues and bugs reported in QA testing
On mobile:
- Use services full name `OSF Registries` instead of `Registries`
- Show all links in a dropdown
- Show `donate` and `help` links on mobile
On tablet:
- Firefox: fix issue with help link overlapping with search input.
N/A
Please see if all issues reported in QA testing are addressed.
[EMB-433](https://openscience.atlassian.net/browse/EMB-433)
> [EMB-433] Fix: registries navbar bugs

- lib/handbook/addon/docs/components/validated-model-form/demo-edit/template.hbs
Fix the validated-model-form controller and route snippets for [demo-edit](https://centerforopenscience.github.io/ember-osf-web/handbook/docs/components/validated-model-form#demo-edit).
Update the referenced controller and route snippet names for the demo-edit validated-model-form handbook component.
n/a
n/a
n/a
n/a
> chore: fix VMF controller and route snippets

- tests/acceptance/dashboard-test.ts
Stop tests timing out all the time.
Disable that one slow test.
When [ENG-311](https://openscience.atlassian.net/browse/ENG-311) is complete, should re-enable it.
> [no ticket] disable a test to avoid timeouts

- lib/registries/addon/overview/route.ts
- lib/registries/addon/overview/template.hbs
Add registration's wikis count
- Request `wikis` related count
- Show related count on side navigation menu
Please make sure the wikis count show and is correct.
[ENG-167](https://openscience.atlassian.net/browse/ENG-167)
> [ENG-167] Show registration's wikis count

- CHANGELOG.md
> Update release/carbon changelog

- mirage/factories/collection.ts
- mirage/factories/comment.ts
- mirage/factories/registration.ts
Avoid percy jitter from fake dates that are generated relative to `now`.
Companion PR to #646 so we can get a clean visual diff between `develop` and `release/carbon`
Add a reference date to every `faker.date` usage in `mirage/` that didn't already have one.
n/a
n/a
n/a
n/a
> [fix][develop] Stable mirage dates for jitterless snapshots

- lib/registries/addon/components/registration-form-view/x-section/styles.scss
- lib/registries/addon/components/registration-form-view/x-text/styles.scss
Display reg form contents with a consistent font size that matches mockups.
> fix: correct font size on reg form

- app/settings/account/-components/request-deactivation/template.hbs
https://openscience.atlassian.net/browse/ENG-449
> [ENG-449] Close modal should trigger `closeDialogs()`

- lib/osf-components/addon/components/zoom-to-route/component.ts
In zoom-to-route filter out error, loading, and index routes.
In zoom-to-route filter out error, loading, and index routes.
None expected.
n/a
n/a
n/a
> In zoom-to-route filter out error, loading, and index routes

- CHANGELOG.md
- app/locales/en/translations.ts
- app/meetings/detail/-components/meeting-detail-header/component.ts
- app/meetings/detail/-components/meeting-detail-header/styles.scss
- app/meetings/detail/-components/meeting-detail-header/template.hbs
- app/meetings/detail/template.hbs
- app/models/meeting.ts
- tests/integration/routes/meetings/detail/-components/meeting-detail-header/component-test.ts
Add meeting detail page header.
New `meeting-detail-header` component and some tests.
https://openscience.atlassian.net/browse/ENG-475
> [ENG-475] Meeting detail header

- package.json
Babel 7 is a prereq for ember-cli-typescript 2
upgrade to babel 7
None expected.
n/a
No specific QA needed.
https://openscience.atlassian.net/browse/ENG-275
> [ENG-275] upgrade to babel 7

- lib/osf-components/addon/components/editable-field/institutions-manager/component.ts
- lib/osf-components/addon/components/editable-field/institutions-manager/template.hbs
- lib/osf-components/addon/components/institution-select-list/template.hbs
- tests/integration/components/institution-select-list/component-test.ts
- tests/integration/components/institutions-list/component-test.ts
Change the plus/minus icons in the affiliated institutions modal window into checkboxes
Modal window shown after a user clicks on the pencil icon for the affiliated institutions in the righthand metadata column now uses checkboxes instead of plus/minus icons. Box should be unchecked if the institution is not yet affiliated with the registry. Changing the affiliation status of institutions should be reflected in the metadata column after saving. These saved changes should be reflected when the user reopens the modal window.
No known side effects.
Please confirm the modal window is loading the proper institutions and appropriate affiliation status. 
Registry overview page. Righthand column, section Affiliated institutions. Click the pencil icon to edit the institutions and make sure the …
> [ENG-510]Edit affiliated institutions modal to use checkboxes instead of plus/minus icons

- lib/registries/addon/overview/-components/overview-header/template.hbs
Remove the header element in navigation bar (appears in mobile view) since it is broken and always says "Overview".
Removed the element from the template.
Should be fairly benign change.
Before:
After:
https://openscience.atlassian.net/browse/ENG-549
[EMB-123]: https://openscience.atlassian.net/browse/EMB-123
> [ENG-549]Remove broken header element in navigation bar

- lib/registries/addon/components/side-nav/x-link/template.hbs
Close overview sidenav on click
Fix typo
N/A
This only applies on mobile screens.
Please make sure that clicking on the `Components`, `Links`, `Comments` left sidenav links close collapses/closes it.
[ENG-648](https://openscience.atlassian.net/browse/ENG-648)
> [ENG-648] Close overview sidenav on click

- CHANGELOG.md
- app/index.html
For better accessibility.
Add `lang="en"` to html element in index.html
None expected.
n/a
No QA needed.
n/a
> [no ticket] add html lang attribute

- app/home/-components/testimonials/template.hbs
- config/environment.js
Add a flag for the user profile page.
- Add `ember_user_profile_page` flag
`N/A`
`N/A`
`N/A`
`N/A`
> [Hotfix] Add flag for user profile page

- .github/PULL_REQUEST_TEMPLATE.md
EMB is dead. Hail ENG!
`s/EMB/ENG/`
Less typing.
n/a
n/a
n/A
> [no ticket] Update PR template issue link to ENG

- .github/PULL_REQUEST_TEMPLATE.md
Update the PR template to better reflect how we use it.
- Move ticket number and feature flags to line items at the top
- Remove the largely unused "reviewer checklist"
n/a
n/a
n/a
https://openscience.atlassian.net/browse/EMB-123
[EMB-123]: https://openscience.atlassian.net/browse/EMB-123
> [no ticket] Update PULL_REQUEST_TEMPLATE.md

- lib/app-components/addon/components/branded-navbar/template.hbs
- lib/app-components/addon/components/error-page/component.ts
- lib/app-components/addon/components/error-page/template.hbs
- lib/app-components/addon/components/provider-logo/template.hbs
- lib/app-components/addon/components/theme-styles/template.hbs
- lib/collections/addon/index/template.hbs
Fixes to a number of random templates used in Collections.
Make the templates pass template lint and use angle bracket invocation.
None expected.
n/a
Should be tested as part of full regression test of Collections.
> [ENG-670] collections template fixes

- CHANGELOG.md
- lib/osf-components/addon/components/editable-field/styles.scss
- lib/osf-components/addon/components/editable-field/template.hbs
- lib/osf-components/addon/components/node-category-picker/template.hbs
- lib/osf-components/addon/components/node-publication-doi-editable/template.hbs
- lib/osf-components/addon/components/zoom-to-route/template.hbs
- lib/registries/addon/components/license-viewer/template.hbs
- lib/registries/addon/components/registries-license-picker/template.hbs
- tests/engines/registries/acceptance/overview/overview-test.ts
Use `osf-dialog` instead of `bs-modal` for dialog boxes on the registries overview page. 
- Use `osf-dialog` in `editable-field` and `license-viewer` components.
- Remove a handful of `@renderInPlace={{true}}`s -- ember-power-select had to be rendered in place to display correctly with `bs-modal`, but with `osf-dialog` it causes them to be completely contained in the modal, with any overflow hidden. This is well and good and means less hackery.
n/a
n/a
For each editable field on the registries overview page, check that clicking the edit button opens a dialog that behaves as you'd normally expect.
Also, bonus bug fix, free with osf-dialog! Viewing a registration's license now handles the variety of white-space strategies, so text will wrap in a way that looks normal, whether or not the …
> [ENG-513] Use osf-dialog in registries

- lib/handbook/addon/docs/components/subject-widget/demo/template.hbs
- lib/osf-components/addon/components/subjects/display/template.hbs
- lib/osf-components/addon/components/subjects/manager/single/component.ts
- lib/osf-components/addon/components/subjects/widget/template.hbs
- Ticket: https://openscience.atlassian.net/browse/ENG-973
Add analytics to subjects widget
Add analytics data attrs
> [ENG-973] Add analytics for subjects widget

- CHANGELOG.md
- app/serializers/osf-serializer.ts
- config/environment.js
- lib/osf-components/addon/components/osf-dialog/template.hbs
- lib/osf-components/addon/components/subjects/browse/animated-expand/template.hbs
- lib/osf-components/addon/components/subjects/browse/item/styles.scss
- lib/osf-components/addon/components/subjects/display/styles.scss
- lib/osf-components/addon/components/subjects/display/template.hbs
- lib/osf-components/addon/components/subjects/widget/styles.scss
- lib/osf-components/addon/components/subjects/widget/template.hbs
- Ticket: [ENG-835]
Respond to QA/UX feedback on the subject widget.
- Update to API version 2.16 to get the new subject relationships
- When a model is reloaded into the store, set `relatedCounts` only when the new payload has relationship counts (avoid clobbering previously loaded counts)
- Visual changes to the hierarchical subject browser:
- Faster expand/collapse animation (reduced from 200ms to 100ms)
- Apply `grayscale` filter to the checkboxes of subjects with selected children (if your OS/browser has blue checkboxes, the `invert` filter made for a distracting yellow)
- Small padding/margin tweaks:
- consistent vertical spacing between subjects
- a bit more space between text and icon/button
Before/after:
n/a
main things:
- hierarchical subject browsing *works* …
> [ENG-835] Subject widget updates

- CHANGELOG.md
- Ticket: []
Updated CHANGELOG with various additions and changes made with adding institutional-users to Mirage.
> [no ticket] Updated CHANGELOG with institutional users mirage changes

- CHANGELOG.md
- Ticket: []
To update the CHANGELOG with schemaBlockGroupRenderer changes.
- update CHANGELOG
`N/A`
`N/A`
> [no ticket] Update CHANGELOG

- CHANGELOG.md
- app/locales/en/translations.ts
- lib/osf-components/addon/components/registries/draft-registration-manager/component.ts
- lib/osf-components/addon/components/registries/draft-registration-manager/template.hbs
- lib/osf-components/app/components/registries/review-form-renderer/component.js
- lib/osf-components/package.json
- lib/registries/addon/drafts/draft/controller.ts
- lib/registries/addon/drafts/draft/route.ts
- lib/registries/addon/drafts/draft/styles.scss
- lib/registries/addon/drafts/draft/template.hbs
- mirage/scenarios/default.ts
- package.json
- tests/engines/registries/acceptance/draft/draft-test.ts
- yarn.lock
- Ticket: [ENG-1130](https://openscience.atlassian.net/browse/ENG-1130)
Add review page
- Use `Registries::ReviewFormRenderer`
- Add navigation tests
- Remove `ember-router-action-helper`
- Use route controller since we expect to add state over time.
- Move route actions to controller.
n/a
n/a
> [ENG-1130] Add review page

- app/institutions/dashboard/-components/departments-panel/component.ts
- app/institutions/dashboard/-components/departments-panel/template.hbs
- app/institutions/dashboard/-components/institutional-users-list/component.ts
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
- app/institutions/dashboard/-components/projects-panel/template.hbs
- app/institutions/dashboard/styles.scss
- app/institutions/dashboard/template.hbs
- app/locales/en/translations.ts
- app/models/institution.ts
- lib/osf-components/addon/components/paginated-list/base-data-component.ts
- Ticket: [ENG-1147]
- Feature flag: Institutional Dashboard
Add titles to Institutional Dashboard pages. Add empty states to side panels when no user stats are present. Fix issue with filtering on a paginated list.
[ENG-1147]: https://openscience.atlassian.net/browse/ENG-1147
> [ENG-1147] Add titles to pages, fix paginated list bug

- app/institutions/dashboard/-components/institutional-users-list/styles.scss
- Ticket: [no ticket]
- Feature flag: Institutional Dashboard
Change the font size of the items in the institutional dashboard table to 16px from 14px.
> [no ticket] Changed font size to 16px

- CHANGELOG.md
- app/locales/en/translations.ts
- lib/handbook/addon/docs/components/osf-dialog/template.md
- lib/osf-components/addon/components/osf-dialog/component.ts
- lib/osf-components/addon/components/osf-dialog/template.hbs
- lib/osf-components/addon/components/registries/draft-registration-manager/component.ts
- lib/osf-components/addon/components/registries/finalize-registration-modal/component.ts
- lib/osf-components/addon/components/registries/finalize-registration-modal/manager/component.ts
- lib/osf-components/addon/components/registries/finalize-registration-modal/manager/template.hbs
- lib/osf-components/addon/components/registries/finalize-registration-modal/template.hbs
- lib/osf-components/addon/components/registries/partial-registration-modal/component.ts
- lib/osf-components/addon/components/registries/partial-registration-modal/manager/component.ts
- lib/osf-components/addon/components/registries/partial-registration-modal/manager/template.hbs
- lib/osf-components/addon/components/registries/partial-registration-modal/template.hbs
- lib/registries/addon/drafts/draft/-components/register/component.ts
- lib/registries/addon/drafts/draft/-components/register/template.hbs
- lib/registries/addon/drafts/draft/controller.ts
- lib/registries/addon/drafts/draft/route.ts
- lib/registries/addon/drafts/draft/template.hbs
- mirage/config.ts
- mirage/factories/registration.ts
- mirage/scenarios/default.ts
- mirage/serializers/registration.ts
- mirage/views/registration.ts
- tests/engines/registries/acceptance/draft/draft-test.ts
- tests/integration/components/registries/finalize-registration-modal/component-test.ts
- tests/integration/components/registries/partial-registration-modal/component-test.ts
- Ticket: [ENG-1132](https://openscience.atlassian.net/browse/ENG-1132)
Add register component.
The modal dialog flickers a little when switching from the partial registration modal to finalize registration modal. This is a known issue. Will be addressed later.
> [ENG-1132] Add register component

- .eslintrc.js
- CHANGELOG.md
- app/guid-node/drafts/route.ts
- app/guid-node/registrations/controller.ts
- app/router.ts
- config/environment.js
- mirage/config.ts
- mirage/views/draft-registration.ts
- Ticket: https://openscience.atlassian.net/browse/ENG-1165
To add a feature flag for new drafts route
- Add new route for `guid-node.drafts`
- Add waffle flag for route
`N/A`
`N/A`
> [Feature][ENG-1165] Add draft feature flag

- lib/osf-components/addon/components/registries/schema-block-renderer/label/template.hbs
> fix helper text and show example lacement

- lib/osf-components/addon/components/editable-field/license-manager/component.ts
- lib/registries/addon/components/registries-license-picker/component.ts
- Ticket: [ENG-1136]
Update incorrect help desk docs describing licensing
Old help docs link to new zendesk-hosted link
[ENG-1136]: https://openscience.atlassian.net/browse/ENG-1136
> [ENG-1136] Update help docs link

- lib/osf-components/addon/components/files/upload-zone/component.ts
- lib/osf-components/addon/components/files/upload-zone/template.hbs
- tests/integration/components/files-widget/component-test.ts
Fix duplicate dropzone ID and file upload.
> Fix duplicate dropzoneId and fileUpload

- lib/registries/addon/drafts/draft/template.hbs
> Pass node to review form

- app/locales/en/translations.ts
- tests/engines/registries/integration/index/index-test.ts
- Ticket: [ENG-739]
Update the roadmap link for registries to point to the new roadmap page on cos.io
Google doc link to cos.io link; change words from 'the requirements and roadmap' to 'our public roadmap'
Update test
[ENG-739]: https://openscience.atlassian.net/browse/ENG-739
> [ENG-739] Update roadmap link

- lib/osf-components/addon/components/osf-layout/right-column/styles.scss
- lib/registries/addon/drafts/draft/-components/register/component.ts
- lib/registries/addon/drafts/draft/-components/register/styles.scss
- lib/registries/addon/drafts/draft/-components/register/template.hbs
- lib/registries/addon/drafts/draft/styles.scss
- lib/registries/addon/drafts/draft/template.hbs
- lib/registries/addon/overview/styles.scss
- Ticket: [ENG-1183](https://openscience.atlassian.net/browse/ENG-1183)
Style right nav buttons
- Style right nav buttons
- Change the osf-layout to give width control to the consumer.
n/a
> [ENG-1183] Style right nav buttons

- app/models/draft-registration.ts
- app/models/schema-block.ts
- app/transforms/registration-response-key.ts
- app/transforms/registration-responses.ts
> add transform

- app/adapters/registration.ts
- app/models/registration.ts
- config/environment.js
- lib/registries/addon/drafts/draft/-components/register/component.ts
- mirage/factories/registration.ts
POST to `/v2/nodes/<guid>/registrations/` instead of
`/v2/registrations/`. Revert once the root endpoint works.
- Ticket: []
> [no ticket] create registrations under their node

- lib/osf-components/addon/components/form-controls/template.hbs
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/text/template.hbs
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/textarea/template.hbs
> Fix default placeholders that says `Optional`

- app/locales/en/translations.ts
- app/utils/formatted-time-since.ts
- lib/osf-components/addon/components/registries/draft-registration-manager/component.ts
- lib/osf-components/addon/components/registries/draft-registration-manager/template.hbs
- lib/osf-components/addon/components/time-since/component.ts
- lib/osf-components/addon/components/time-since/template.hbs
- lib/osf-components/app/components/time-since/component.js
- lib/registries/addon/components/comment-card/component.ts
- lib/registries/addon/drafts/draft/styles.scss
- lib/registries/addon/drafts/draft/template.hbs
- tests/unit/utils/formatted-time-since-test.ts
Add the auto save message to the right nav
Using `draftRegistration.datetimeUpdated` to indicate when last autosaved occured.
Added logic to update `draftRegistration.datetimeUpdated` after successful autosave.
No message added for mobile view yet
> [No ticket] Add autosave message to right nav

- app/packages/registration-schema/validations.ts
- app/validators/validate-response-format.ts
- tests/unit/validators/validate-response-format-test.ts
> Fix file validations

- lib/osf-components/addon/components/gutters/styles.scss
- lib/osf-components/addon/components/osf-layout/registries-side-nav/styles.scss
Make left and right sidebars "stick" and stay in view when user scrolls away
Using position: sticky on the sidebar elements
> [No ticket] Make sidebars sticky

- lib/osf-components/addon/components/time-since/component.ts
Add a flag to ignore the time-since component so tests do not time out
> [No ticket]Add testing flag to the time-since component

- app/packages/registration-schema/page-manager.ts
- lib/osf-components/addon/components/registries/draft-registration-manager/component.ts
- lib/osf-components/addon/components/registries/draft-registration-manager/template.hbs
- lib/registries/addon/drafts/draft/-components/register/component.ts
- lib/registries/addon/drafts/draft/-components/register/styles.scss
- lib/registries/addon/drafts/draft/-components/register/template.hbs
- lib/registries/addon/drafts/draft/controller.ts
- lib/registries/addon/drafts/draft/styles.scss
- lib/registries/addon/drafts/draft/template.hbs
- Ticket: [ENG-1138]
To add a navigation bar on the registration submission page for mobile view
- Add navigation menu for mobile
- Add error message below navigation bar on mobile
None
None
[ENG-1138]: https://openscience.atlassian.net/browse/ENG-1138
> [ENG-1138] Mobile view navigation bar

- lib/osf-components/addon/components/osf-layout/registries-side-nav/icon/styles.scss
- lib/registries/addon/drafts/draft/styles.scss
Re-center save icon.
Use inline-block for save message
> [ENG-1212] Recenter icon on collapse and use block display for save message

- lib/osf-components/addon/components/registries/finalize-registration-modal/template.hbs
- lib/osf-components/addon/components/validated-input/date/component.ts
- lib/osf-components/addon/components/validated-input/date/template.hbs
- lib/registries/package.json
- package.json
- yarn.lock
[ENG-1211]
Use `ember-flatpickr` for `validated-input/date`
> [ENG-1211] Fix datepicker

- app/app.ts
- app/locations/history.ts
- app/services/osf-router.ts
- app/services/ready.ts
- lib/analytics-page/addon/engine.js
- lib/collections/addon/engine.js
- lib/handbook/addon/engine.js
- lib/osf-components/addon/components/osf-link/component.ts
- lib/registries/addon/engine.js
- tests/engines/registries/integration/components/page-link/component-test.ts
- tests/engines/registries/integration/components/registries-navbar/component-test.ts
- tests/engines/registries/integration/components/side-nav/component-test.ts
- tests/unit/locations/history-fragment-test.ts
- Ticket: []
Allow in-app transitions that include an element id in the url fragment, and will scroll to the id'd element when the transition completes.
- add `osf-router` service with `transitionTo`
- same as the ember router service's `transitionTo`, but with an additional `fragment` option
- e.g. `osfRouter.transitionTo('foo.route', { fragment: 'scroll-here' })`
- holds the target fragment so `HistoryLocation` can grab it later in the transition -- this is a dirty, dirty hack
- update `OsfLink` to use `osfRouter.transitionTo`, so the following works!
```hbs
<OsfLink @route='foo' @fragment='bar'>Smooth transition to `foo#bar`</OsfLink>
```
This essentially uses a global variable (`osfRouter.currentTransitionTargetFragment`) which could possibly be left around if the …
> [ENG-1211] Fragment transitions

- app/models/registration-schema.ts
- app/models/schema-block.ts
Add `pageRouteParam` and `elementId` to `schema-block` model.
> Add pageRouteParam and elementId

- lib/osf-components/addon/styles/headers.scss
- lib/registries/addon/components/navbar/styles.scss
- lib/registries/addon/components/registries-navbar/template.hbs
- lib/registries/addon/drafts/draft/styles.scss
- lib/registries/addon/drafts/draft/template.hbs
- lib/registries/addon/overview/-components/overview-header/styles.scss
- Ticket: [ENG-1211]
Update things that should be headers into headers and things that shouldn't be not into headers
- Update the page heading to be h1
- update the Help and Donate buttons to not be h4
`N/A`
`N/A`
> [ENG-1211]Change headings according to a11y audit

- lib/osf-components/addon/components/osf-layout/registries-side-nav/x-link/styles.scss
- Ticket: [ENG-1212]
Place sidenav icon at top of the label when in drawer view
`align-item: flex-start` for drawer view
`N/A`
`N/A`
[ENG-1212]: https://openscience.atlassian.net/browse/ENG-1212
> [ENG-1212]Place icon to top of label when in drawer mode

- lib/handbook/addon/docs/validators/validate-list/demo/component.ts
- Ticket: n/a
Fix validateList handbook demo.
Handle case when there are no validation errors.
None.
n/a
> docs(handbook): handle no errors in validateList demo

- app/locales/en/translations.ts
- lib/registries/addon/drafts/draft/page/styles.scss
- lib/registries/addon/drafts/draft/page/template.hbs
- Ticket: https://openscience.atlassian.net/browse/ENG-1211
To fix some of the accessibility issues on the mobile navbar
- Added aria-labels to buttons
- Updated the label text to be black instead of blue
N/A
N/A
> [ENG-1211][Feature] Make mobile nav accessible

- lib/registries/addon/drafts/draft/page/styles.scss
- lib/registries/addon/drafts/draft/page/template.hbs
- Ticket: [ENG-1244]
Add a link back to the original project to the header
Add Link to original project (`branchedFrom`)
Justify title and link to the left of the header
`n/a`
`n/a`
[ENG-1244]: https://openscience.atlassian.net/browse/ENG-1244
> [ENG-1244]Add link back to project

- app/styles/headers.scss
- lib/osf-components/addon/components/osf-layout/registries-side-nav/styles.scss
- lib/osf-components/addon/components/osf-layout/registries-side-nav/template.hbs
- lib/osf-components/addon/components/osf-layout/registries-side-nav/x-link/styles.scss
- lib/osf-components/addon/components/registries/schema-block-renderer/label/label-content/styles.scss
- lib/registries/addon/components/page-link/styles.scss
- lib/registries/addon/drafts/draft/page/styles.scss
- Ticket: n/a
Fix styles.
* add missing navigation connecting line
* use correct unvisited nav colors
* make right gutter same size as left and keep consistent
* outline-offset
> Registries submission style fixes

- lib/registries/addon/drafts/draft/-components/register/component.ts
> unload record after register

- .travis.yml
- ember-cli-build.js
- package.json
- testem.js
- yarn.lock
Fix mime-types import errors
- Add `ember-auto-import`
- Add config for `ember-auto-import`
- Remove manual imports.
> Fix mime-types import errors

- app/validators/validate-response-format.ts
- Ticket: []
Update language for files validation error
New error msg:
The file(s) "filename, filename" cannot be found on this "project or component".
> Update language for files validation error

- app/packages/registration-schema/page-manager.ts
- lib/osf-components/addon/components/registries/draft-registration-manager/component.ts
- lib/registries/addon/drafts/draft/page/template.hbs
> Page manager fix

- lib/registries/addon/drafts/draft/page/template.hbs
- Ticket: []
Fix infinite rendering bug caused by `ember-composable-helpers` `{{compute}}` helper
Use `did-update` render modifier from ember-render-modifiers.
> bug-fix: infinite-rendering

- lib/osf-components/addon/components/registries/draft-registration-manager/component.ts
- tests/integration/components/draft-registration-manager/component-test.ts
- Ticket: []
Make draft registration manager more readable.
Minor optimizations
> chore: cleanup draft registration manager

- CHANGELOG.md
- Ticket: n/a
Add tag link to changelog (missed during release).
Add tag link to changelog.
n/a
n/a
> [no ticket] chore: update release tag

- mirage/factories/draft-registration.ts
Add mirage factories for draft metadata.
No QA.
> Add factories for draft-registration

- tests/acceptance/logged-out-homepage-test.ts
- tests/integration/routes/settings/account/-components/connected-identities-test.ts
> Fix percy same name warninig

- lib/registries/addon/components/registries-tags-widget/component.ts
- lib/registries/addon/drafts/draft/-components/tags-manager/component.ts
- lib/registries/addon/drafts/draft/-components/tags-manager/template.hbs
- lib/registries/addon/drafts/draft/metadata/template.hbs
- Ticket: [ENG-1381]
Add tags field.
Add a new `TagsManager` component and use it with the `RegistriesTagsWidget`
Test as part of registration metadata.
[ENG-1381]: https://openscience.atlassian.net/browse/ENG-1381
> [ENG-1381] Add tags field

- app/authenticators/osf-cookie.ts
- Ticket: []
- Back-end: https://github.com/CenterForOpenScience/osf.io/pull/9287
Follow up ticket to the real backend fix.
ember-data pushPayload errors in our authenticator get eaten by ember-simple-auth.
Catch and re-throw pushPayload errors
NA
> [ENG-1462] Catch and throw pushPayload errors

- tests/integration/services/current-user-test.ts
- Ticket: [ENG-1453]
Add header test to check whether the header is set.
No QA needed.
[ENG-1453]: https://openscience.atlassian.net/browse/ENG-1453
> [ENG-1453] Add header test

- mirage/config.ts
- mirage/serializers/draft-registration.ts
Make mirage work for subjects.
> [No Ticket] Add self link to mirage serialize for subjects

- lib/osf-components/addon/components/form-controls/power-select/template.hbs
- lib/registries/addon/drafts/draft/metadata/controller.ts
- lib/registries/addon/drafts/draft/metadata/template.hbs
> Fix category picker and make use of NodeCategory component to show icons

- app/packages/registration-schema/validations.ts
- Ticket: [ENG-1603]
Remove validation for contributors-input blocks.
[ENG-1572]: https://openscience.atlassian.net/browse/ENG-1572
[ENG-1603]: https://openscience.atlassian.net/browse/ENG-1603
> [ENG-1603] Remove validation for contributors-input

- app/packages/registration-schema/validations.ts
- lib/osf-components/addon/components/subjects/manager/component.ts
- lib/registries/addon/drafts/draft/route.ts
Make the validation of subjects more robust.
[ENG-1572]: https://openscience.atlassian.net/browse/ENG-1572
> [ENG-1572] Change validation function of subjects to synchronous

- app/packages/registration-schema/validations.ts
- tests/engines/registries/acceptance/overview/overview-test.ts
- translations/en-us.yml
- Ticket: []
- Improve validation error message for subjects, nodeLicense.
> [ENG-1572] Improve validation error language

- app/guid-node/registrations/controller.ts
Fix how we pass query param to the `query` method.
> [Hotfix] Fix query parameter.

- lib/osf-components/addon/components/registries/finalize-registration-modal/manager/component.ts
- lib/registries/addon/drafts/draft/-components/register/template.hbs
- Ticket: [ENG-1597]
Toast error message returned from API so that user knows when a file is missing.
[ENG-1597]: https://openscience.atlassian.net/browse/ENG-1597
> [ENG-1597] Toast error msg returned from API upon submission error

- lib/registries/addon/components/hero-overlay/component.ts
- lib/registries/addon/components/hero-overlay/styles.scss
- lib/registries/addon/components/hero-overlay/template.hbs
- lib/registries/addon/drafts/draft/-components/right-nav/styles.scss
- lib/registries/addon/drafts/draft/-components/right-nav/template.hbs
- lib/registries/addon/drafts/draft/controller.ts
- lib/registries/addon/drafts/draft/styles.scss
- lib/registries/addon/drafts/draft/template.hbs
- Ticket: []
Branded Draft submission workflow
* Wrapping the draft template with a `<div {{with-branding}}...>` element
* Adding a hero overlay
* Using `Button` for the next/prev buttons
> Branded draft submission workflow

- app/styles/_branding.scss
- lib/registries/addon/components/registries-navbar/template.hbs
- Ticket: []
Fix navbar logo image not showing when a brand is not present
> Fix logo img not showing on non branded navbar

- translations/en-us.yml
- Ticket: [ENG-1799]
Update the wording for the description of OSF Institutions
Description updated in the english translations yml file
None
This is the wording change for Institutions. If there are other places that mentions that OSF Institutions is a free service, those should be addressed too.
[ENG-1799]: https://openscience.atlassian.net/browse/ENG-1799
> [ENG-1799] Update wording of OSFInstitutions

- app/institutions/index/template.hbs
- translations/en-us.yml
- Ticket: [ENG-1799]
The link to the institutions service was not updated when doing the wording change in an earlier PR. Link is updated in this PR
Change link destination
`NA`
`NA`
[ENG-1799]: https://openscience.atlassian.net/browse/ENG-1799
> [ENG-1799] Update link to institutions

- app/app.ts
- lib/app-components/addon/components/project-contributors/list/component.ts
- lib/app-components/addon/components/project-contributors/list/item/styles.scss
- lib/app-components/addon/components/project-contributors/list/item/template.hbs
- lib/app-components/addon/components/project-contributors/list/styles.scss
- lib/app-components/addon/components/project-contributors/list/template.hbs
- lib/osf-components/addon/components/contributors/card/editable/styles.scss
- lib/osf-components/addon/components/contributors/card/editable/template.hbs
- lib/osf-components/addon/components/contributors/card/styles.scss
- lib/osf-components/addon/components/contributors/list/component.ts
- lib/osf-components/addon/components/contributors/list/styles.scss
- lib/osf-components/addon/components/contributors/list/template.hbs
- lib/osf-components/addon/components/contributors/manager/component.ts
- lib/osf-components/addon/components/contributors/manager/template.hbs
- lib/registries/addon/drafts/draft/metadata/template.hbs
- lib/registries/package.json
- package.json
- tests/integration/components/contributors/component-test.ts
- translations/en-us.yml
- types/ember-sortable.d.ts
- yarn.lock
- Ticket: [ENG-638]
Upgrade `ember-sortable` to 2.2. Use the new version for editable contributor mgmt widget. Modify the collections contributor widget to use the new version of `ember-sortable`.
Make sure the collections contributor widget still works.
[ENG-638]: https://openscience.atlassian.net/browse/ENG-638
> [ENG-638]Reorder contributors through dragging and dropping.

- app/adapters/subscription.ts
- app/models/subscription.ts
- app/serializers/subscription.ts
- lib/osf-components/addon/components/subscriptions/list-row/component.ts
- lib/osf-components/addon/components/subscriptions/list-row/styles.scss
- lib/osf-components/addon/components/subscriptions/list-row/template.hbs
- lib/osf-components/addon/components/subscriptions/list/component.ts
- lib/osf-components/addon/components/subscriptions/list/styles.scss
- lib/osf-components/addon/components/subscriptions/list/template.hbs
- lib/osf-components/addon/components/subscriptions/manager/component.ts
- lib/osf-components/addon/components/subscriptions/manager/template.hbs
- lib/osf-components/app/components/subscriptions/list-row/component.js
- lib/osf-components/app/components/subscriptions/list/component.js
- lib/osf-components/app/components/subscriptions/manager/component.js
- lib/registries/addon/branded/moderation/notifications/controller.ts
- lib/registries/addon/branded/moderation/notifications/template.hbs
- lib/registries/addon/branded/moderation/template.hbs
- lib/registries/package.json
- mirage/config.ts
- mirage/factories/subscription.ts
- package.json
- tests/integration/components/subscriptions/component-test.ts
- translations/en-us.yml
- yarn.lock
- Ticket: [ENG-2181]
Adds a notifications widget for changing notification settings.
- Added a `subscription` model.
- Added `ember-cli-strings-helper` as a dependency so that we can `humanize()` a string.
- This is needed to un-underscore the `eventName` of a `subscription`.
- Added a `Subscriptions::List`, a `Subscriptions::ListRow` and a `Subscriptions::Manager` component.
- Modified mirage config to add a top level `/subscriptions` endpoint.
- Added some nice integration tests.
[ENG-2181]: https://openscience.atlassian.net/browse/ENG-2181
> [ENG-2181] Notifications widget.

- lib/osf-components/addon/components/form-controls/power-select/template.hbs
- lib/osf-components/addon/components/form-controls/template.hbs
- lib/osf-components/addon/components/moderators/add-modal/component.ts
- lib/osf-components/addon/components/moderators/add-modal/template.hbs
- lib/osf-components/addon/components/moderators/list/component.ts
- lib/osf-components/addon/components/moderators/list/template.hbs
- lib/osf-components/addon/components/moderators/manager/component.ts
- lib/osf-components/addon/components/moderators/manager/template.hbs
- lib/osf-components/app/components/moderators/add-modal/component.js
- lib/registries/package.json
- mirage/config.ts
- mirage/factories/moderator.ts
- mirage/serializers/user.ts
- mirage/views/addModerator.ts
- tests/integration/components/moderators/component-test.ts
- translations/en-us.yml
- Ticket: [ENG-2188]
[ENG-2188]: https://openscience.atlassian.net/browse/ENG-2188
> [ENG-2188] Add moderator modal

- app/adapters/review-action.ts
- app/models/review-action.ts
- mirage/config.ts
- mirage/factories/review-action.ts
- mirage/views/review-action.ts
- tests/unit/models/review-action-test.ts
- Ticket: [ENG-2175]
[ENG-2175]: https://openscience.atlassian.net/browse/ENG-2175
> [ENG-2175] Add review-actions endpoint

- lib/osf-components/addon/components/file-browser/file-move-messages/template.hbs
- translations/en-us.yml
- Ticket: [NA]
Update some wording on the Quickfiles page re: storage cap
- `Storage limit` -> `Storage cap`
- Added link to help doc when past the storage cap
NA
- Please test that the help docs go to  the right place
> [No ticket] Update quickfile modal message

- lib/registries/addon/components/make-decision-dropdown/component.ts
- lib/registries/addon/components/make-decision-dropdown/styles.scss
- lib/registries/addon/components/make-decision-dropdown/template.hbs
- lib/registries/addon/overview/-components/overview-topbar/template.hbs
- translations/en-us.yml
- Ticket: [ENG-2183]
Added the functionality for moderators to make a decision on registrations through a dropdown on overview page.
- Added `make-decision-dropdown` component.
- Updated `overview-topbar` component to make use of this component.
- Added translation strings.
[ENG-2183]: https://openscience.atlassian.net/browse/ENG-2183
> [ENG-2183] Make decision dropdown

- app/serializers/moderator.ts
- lib/osf-components/addon/components/moderators/add-modal/component.ts
> [No ticket] Fix adding moderators

- lib/registries/addon/components/make-decision-dropdown/component.ts
> Fix comment payload.

- lib/registries/addon/components/registries-navbar/template.hbs
- translations/en-us.yml
> Change My Reviewing to Moderation, rearrange order

- app/models/review-action.ts
- lib/registries/addon/components/review-actions-list/review-action/component.ts
- translations/en-us.yml
- Ticket: [ENG-2415]
[ENG-2415]: https://openscience.atlassian.net/browse/ENG-2415
> [ENG-2415] Fix review action list translation.

- lib/registries/addon/components/make-decision-dropdown/styles.scss
- lib/registries/addon/components/make-decision-dropdown/template.hbs
- Ticket: [NA]
- Have the `Make decision` dropdown take up the full space on the topbar
- adjust some CSS stuff
`NA`
`NA`
> [No ticket] Adjust make-decision button size

- lib/registries/addon/overview/-components/overview-header/component.ts
- lib/registries/addon/overview/controller.ts
> Fix computed property

- lib/registries/addon/components/review-actions-list/component.ts
- lib/registries/addon/components/review-actions-list/styles.scss
- lib/registries/addon/components/review-actions-list/template.hbs
- mirage/factories/registration-provider.ts
- mirage/scenarios/default.ts
- Ticket: [ENG-2411]
- change the way the Review Action toggle is done
- Remove the caret, and replace it with a link-button that says `Show full history` and `Hide`
- Update Registration Provider factory trait to handle permissions array
`NA`
[ENG-2411]: https://openscience.atlassian.net/browse/ENG-2411
> [ENG-2411] Update review action toggler

- tests/engines/registries/acceptance/branded/moderation/moderators-test.ts
- Ticket: [ENG-2391]
[ENG-2391]: https://openscience.atlassian.net/browse/ENG-2391
> [ENG-2391] Add moderators acceptance tests.

- lib/registries/addon/components/make-decision-dropdown/template.hbs
- mirage/config.ts
- tests/engines/registries/acceptance/overview/moderator-mode-test.ts
> Overview page acceptance tests

- lib/osf-components/addon/components/registries/review-actions-list/review-action/component.ts
- lib/registries/addon/components/registries-metadata/template.hbs
- tests/integration/components/registries/review-actions-list/review-action/component-test.ts
- translations/en-us.yml
- Ticket: [ENG-2474]
[ENG-2474]: https://openscience.atlassian.net/browse/ENG-2474
> [ENG-2474] Add Embargo end date to registries-metadata component

- lib/registries/addon/drafts/draft/-components/register/component.ts
Fix register button not opening finalize-registration modal for project with no components
Will be tested with release/21.1.0
> [ENG-2641] Fix register button

- app/models/registration.ts
- mirage/factories/registration.ts
- mirage/scenarios/default.ts
- Ticket: [ENG-2553]
Add `poviderSpecificMetadata` field to `Registration` model. Add mirage setups.
[ENG-2553]: https://openscience.atlassian.net/browse/ENG-2553
> [ENG-2553] add field and mirage factory

- lib/osf-components/addon/components/contributors/manager/template.hbs
- lib/osf-components/addon/components/contributors/user-search/list/template.hbs
- lib/osf-components/addon/components/contributors/user-search/widget/component.ts
- lib/osf-components/addon/components/contributors/user-search/widget/template.hbs
Reset page number on user input. Otherwise when user search for new keyword, the page starts from where the last search term left off.
Added `resetPage()` action and invoke action when user inputs, clicks the search button or hits enter.
> [ENG-2641] Reset page on input

- translations/en-us.yml
Reverts CenterForOpenScience/ember-osf-web#1145
> Revert "[IMLS/IA][ENG-2608] Update message in new registration creation modal"

- lib/registries/addon/my-registrations/route.ts
Requires auth for my-registrations route.
> Use requireAuth decorator for my-registrations route

- lib/osf-components/addon/components/draft-registration-card/template.hbs
- translations/en-us.yml
> Add placeholder text to draft card for drafts with empty string as titles.

- lib/osf-components/addon/components/registries/my-registrations-list/drafts/component.ts
- lib/osf-components/addon/components/registries/my-registrations-list/drafts/template.hbs
- lib/osf-components/addon/components/registries/my-registrations-list/registrations/component.ts
- lib/osf-components/addon/components/registries/my-registrations-list/registrations/template.hbs
- lib/osf-components/app/components/registries/my-registrations-list/drafts/component.js
> Add embed query param to my-registration-list components to prevent 429s

- lib/registries/addon/components/registries-states/component.ts
> [HOLD] Fix registration overview page status

- lib/osf-components/addon/components/registries/my-registrations-list/drafts/component.ts
> Embed initiators

- lib/collections/addon/components/discover-page/component.ts
"Clear filters" on collection discover page never actually worked. This PR fixes the problem by initializing `lockedActiveFilter` to an empty array instead of a empty object.
> [ENG-2898] Fix clear filters

- lib/osf-components/addon/components/files/menu/component.ts
> [ENG-2898]Fix folder validation msg

- app/models/collected-metadatum.ts
- app/models/collection.ts
- lib/collections/addon/components/discover-page/active-filters/school-type/component.ts
- lib/collections/addon/components/discover-page/active-filters/school-type/template.hbs
- lib/collections/addon/components/discover-page/active-filters/study-design/component.ts
- lib/collections/addon/components/discover-page/active-filters/study-design/template.hbs
- lib/collections/addon/components/discover-page/facets/school-type/component.ts
- lib/collections/addon/components/discover-page/facets/study-design/component.ts
- lib/collections/addon/discover/controller.ts
- mirage/factories/collected-metadatum.ts
- mirage/factories/collection.ts
- mirage/views/collection-search.ts
- tests/engines/collections/acceptance/submit/submit-test.ts
- translations/en-us.yml
- Ticket: [ENG-2917]
- Add new fields for Character Lab ( Study Design and School Type) on Collections Discover page and Collection Submission page
- Users should be able to filter by these new fields and see them visible on Collection search cards on the discover page
- Add new fields and their choices to collection and collected metadata model
- Added new filter/facet components for the new fields
- Updates to mirage to support new fields filtering
- Discover page (osf.io/collections/<collection_id>/discover)
- Submission page  (osf.io/collections/<collection_id>/submit)
- NA
- This PR adds Study Design and School Type to Collections in preparation for Character Lab's new collection going live. Users should be able to add these new fields when they submit a project …
> [Hotfix] [ENG-2917]Add new metadata types for Character Lab

- lib/analytics-page/addon/components/analytics-charts/x-chart-wrapper/component.ts
> [HOTFIX][ENG-2924] Don't load keen in didInsertElement

- app/packages/registration-schema/validations.ts
- lib/osf-components/addon/components/editable-field/license-manager/component.ts
- lib/osf-components/addon/components/editable-field/license-manager/template.hbs
- lib/osf-components/addon/components/registries/review-metadata-renderer/template.hbs
- lib/osf-components/addon/components/validated-input/base-component.ts
- lib/registries/addon/components/registries-license-picker/component.ts
- lib/registries/addon/components/registries-license-picker/template.hbs
- lib/registries/addon/drafts/draft/-components/managers/license-picker-manager/component.ts
- lib/registries/addon/drafts/draft/-components/managers/license-picker-manager/template.hbs
- lib/registries/addon/drafts/draft/draft-registration-manager.ts
- lib/registries/addon/drafts/draft/metadata/styles.scss
- lib/registries/addon/drafts/draft/route.ts
- tests/acceptance/settings/profile/names-test.ts
- tests/engines/registries/acceptance/draft/draft-test.ts
- tests/engines/registries/acceptance/overview/overview-test.ts
- translations/en-us.yml
Fix issues with validating draft/registration license/nodeLicense.
> [ENG-2898] Revert license & nodeLicense validations updates + fixes

- package.json
-   Ticket: []
Keep ember engines from duplicating code unnecessarily across engines. According to research done by @fabmiz,
1. Change the start command in package.json to include the environment variable
Anything this breaks should break big. Between selenium and percy, I think we'll catch whatever errors might come from this.
> [no-ticket] Dedupe ember engines

- tests/engines/registries/acceptance/branded/moderation/settings-test.ts
- translations/en-us.yml
> Add more error message

- lib/osf-components/addon/components/node-card/template.hbs
- translations/en-us.yml
> Remove Latest Update label for node-card

- app/models/registration.ts
- lib/osf-components/addon/components/node-card/template.hbs
- lib/registries/addon/edit-revision/controller.ts
- lib/registries/addon/overview/-components/diff-manager/component.ts
- mirage/factories/registration.ts
- mirage/serializers/registration.ts
- mirage/views/registration.ts
- translations/en-us.yml
> Fix some bugs

- lib/osf-components/addon/components/node-card/component.ts
> Hotfix continue update

- app/application/styles.scss
> Fix weird whitepasce to the right side of ember pages.

- app/guid-file/controller.ts
- app/guid-file/route.ts
- app/guid-file/styles.scss
- app/guid-file/template.hbs
- app/packages/files/file.ts
- lib/osf-components/addon/components/file-version/component.ts
- lib/osf-components/addon/components/file-version/styles.scss
- lib/osf-components/addon/components/file-version/template.hbs
- lib/osf-components/app/components/file-version/template.js
- tests/integration/components/file-version/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3533]
- Add file revision content to the file-detail page
- Rewrite `file-version` component to match this new implementation
- Use newly revamped `file-revision` component in guid-file route
- Allow MFR to accept different versions of the file
- TODO: Rewrite `file-version` test and update file-detail acceptance test
Desktop:
Mobile:
- None
- TODO
[ENG-3533]: https://openscience.atlassian.net/browse/ENG-3533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3533] File detail revisions

- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/styles.scss
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
> Fix long name behavior

- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
- tests/integration/components/file-browser/file-item/component-test.ts
- tests/integration/components/file-browser/folder-item/component-test.ts
> Add tests for file and folder items

- translations/en-us.yml
Change text of Download All action per discussion with Product
1. Text modified
Not unless someone else is using that translation key, which they aren't yet.
Just a text change
> [ENG-3649] Change text of 'download all' action

- lib/osf-components/addon/components/file-browser/styles.scss
- lib/osf-components/addon/components/file-browser/template.hbs
> Fix button for long filenames

- app/styles/_components.scss
- app/styles/_variables.scss
- lib/osf-components/addon/components/file-browser/styles.scss
- lib/osf-components/addon/components/file-browser/template.hbs
- translations/en-us.yml
-   Ticket: [None]
- Add explicit labels to filter textbox and sort dropdown
- wrap filter textbox and file sort dropdown in label elements
- update placeholder text for filter textbox
Desktop:
Mobile:
- none
> [No ticket] Add labels to files list filter and sort

- lib/osf-components/addon/components/file-browser/folder-item/styles.scss
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
-   Ticket: []
- Remove nested interactible element (button within link)
- Remove button within link
- style changes
- no visible changes
> Remove nested interactable elemenets

- app/packages/files/file.ts
Reverts CenterForOpenScience/ember-osf-web#1450
> Revert "[ENG-3649] Fix versions feature in VOL"

- config/environment.d.ts
- config/environment.js
- lib/registries/addon/overview/controller.ts
- lib/registries/addon/overview/template.hbs
- tests/engines/registries/acceptance/overview/index-test.ts
> Fix overview tests

- app/packages/files/file.ts
Reverts CenterForOpenScience/ember-osf-web#1456
> Revert "[ENG-3649] Sort by date_modified rather than modified"

- lib/osf-components/addon/components/file-browser/component.ts
- lib/osf-components/addon/components/file-browser/help-modal/styles.scss
- lib/osf-components/addon/components/file-browser/help-modal/template.hbs
- lib/osf-components/addon/components/file-browser/template.hbs
- lib/osf-components/app/components/file-browser/help-modal/template.js
- translations/en-us.yml
-   Ticket: [ENG-3530]
- Add help modal to files page
- help modal for files page
[ENG-3530]: https://openscience.atlassian.net/browse/ENG-3530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3530] Add file help modal

- app/guid-node/controller.ts
- app/guid-node/files/index/route.ts
- app/guid-node/files/provider/route.ts
- app/guid-node/files/provider/styles.scss
- app/guid-node/files/provider/template.hbs
- app/guid-node/template.hbs
- app/router.ts
> Add guid-node.files and guid-node.files.provider routes

- app/support/template.hbs
- Fix a typo to the help guide
- typo
> [No ticket] Fix typo for help link

- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
> Fix file actions menu

- app/guid-file/controller.ts
- app/guid-file/template.hbs
- app/packages/files/file.ts
- lib/osf-components/addon/components/file-actions-menu/component.ts
- lib/osf-components/addon/components/file-actions-menu/delete-modal/component.ts
- lib/osf-components/addon/components/file-actions-menu/delete-modal/template.hbs
- lib/osf-components/addon/components/file-actions-menu/styles.scss
- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- lib/osf-components/app/components/file-actions-menu/component.js
- lib/osf-components/app/components/file-actions-menu/delete-modal/component.js
- lib/osf-components/app/components/file-actions-menu/delete-modal/template.js
- translations/en-us.yml
> [ENG-3730] Delete file on list view and detail view

- lib/osf-components/addon/components/file-actions-menu/delete-modal/template.hbs
- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/component.ts
- lib/osf-components/addon/components/file-browser/folder-item/styles.scss
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
- lib/osf-components/app/components/file-browser/folder-item/component.js
- translations/en-us.yml
> [ENG-3788]Delete folder

- app/packages/files/file.ts
- app/packages/files/provider-file.ts
- lib/osf-components/addon/components/file-browser/delete-file-modal/component.ts
- lib/osf-components/addon/components/file-browser/delete-file-modal/styles.scss
- lib/osf-components/addon/components/file-browser/delete-file-modal/template.hbs
- lib/osf-components/addon/components/file-browser/template.hbs
- lib/osf-components/app/components/file-browser/delete-file-modal/component.js
- lib/osf-components/app/components/file-browser/delete-file-modal/template.js
- translations/en-us.yml
> [ENG-3724] Delete multiple files

- app/packages/files/osf-storage-file.ts
- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- translations/en-us.yml
-   Ticket: [ENG-3729]
- Add checkout file icon and logic to show/hide stuff based on it
- Add isCheckedOut property for osf-storage-files
- Add checkedOut logic for showing/hiding file operations (hide rename, delete, move)
- hover lock icon
- file action dropdown options
[ENG-3729]: https://openscience.atlassian.net/browse/ENG-3729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3729] Add file checkout icon and logic;

- app/guid-node/files/provider/route.ts
- app/packages/files/bitbucket-provider-file.ts
- app/packages/files/box-provider-file.ts
- app/packages/files/dataverse-provider-file.ts
- app/packages/files/dropbox-provider-file.ts
- app/packages/files/figshare-provider-file.ts
- app/packages/files/file.ts
- app/packages/files/github-provider-file.ts
- app/packages/files/gitlab-provider-file.ts
- app/packages/files/google-drive-provider-file.ts
- app/packages/files/one-drive-provider-file.ts
- app/packages/files/osf-storage-provider-file.ts
- app/packages/files/own-cloud-provider-file.ts
- app/packages/files/provider-file.ts
- app/packages/files/s3-provider-file.ts
- lib/osf-components/addon/components/storage-provider-manager/storage-manager/component.ts
- translations/en-us.yml
Reverts CenterForOpenScience/ember-osf-web#1507
> Revert "[ENG-3811] Handle fetching errors"

- lib/osf-components/addon/components/dropzone-widget/component.ts
- lib/osf-components/addon/components/file-browser/add-new/upload/component.ts
- lib/osf-components/addon/components/file-browser/add-new/upload/styles.scss
- lib/osf-components/addon/components/file-browser/add-new/upload/template.hbs
- lib/osf-components/addon/components/file-browser/component.ts
- lib/osf-components/addon/components/file-browser/styles.scss
- lib/osf-components/addon/components/file-browser/template.hbs
- package.json
- translations/en-us.yml
- yarn.lock
> Fix upload

- app/guid-node/files/provider/controller.ts
- app/guid-node/files/provider/template.hbs
- translations/en-us.yml
> Add side nav toggle

- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/folder-item/styles.scss
> Add a 5px outline offset

- app/packages/files/file.ts
- app/packages/files/github-file.ts
- app/packages/files/github-provider-file.ts
- app/packages/files/provider-file.ts
- lib/osf-components/addon/components/file-browser/add-new/upload/component.ts
- lib/osf-components/addon/components/file-browser/delete-file-modal/component.ts
- lib/osf-components/addon/components/file-browser/delete-file-modal/styles.scss
- lib/osf-components/addon/components/file-browser/delete-file-modal/template.hbs
- translations/en-us.yml
> Add parallelUploads limit for Github

- app/guid-file/template.hbs
- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
> Disable rename on detail view

- lib/osf-components/addon/components/file-browser/folder-item/component.ts
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
> Allow renaming of folders

- lib/osf-components/addon/components/gutters/styles.scss
> Increase gutter z-index

- app/guid-file/-components/file-detail-layout/styles.scss
> Add z-index to main column

- lib/osf-components/addon/components/move-file-modal/component.ts
- Actually cancel moves when closing move modal
> [ENG-3811] Cancel moves

- app/helpers/floor.ts
- app/helpers/get-anything.ts
- lib/osf-components/addon/components/file-browser/add-new/upload/component.ts
- lib/osf-components/addon/components/file-browser/add-new/upload/styles.scss
- lib/osf-components/addon/components/file-browser/add-new/upload/template.hbs
…behaviors; I hate dropzone.
-   Ticket: []
> Add progress indicators, specify size limits, and moar

- lib/osf-components/addon/components/file-browser/add-new/upload/component.ts
> Set timeout to null

- lib/osf-components/addon/components/file-browser/add-new/upload/styles.scss
- lib/osf-components/addon/components/file-browser/add-new/upload/template.hbs
> Add column-gap; remove width

- lib/osf-components/addon/components/file-renderer/component.ts
> Tracked isLoading; set to true when parameter refreshes

- lib/osf-components/addon/components/file-actions-menu/template.hbs
- lib/osf-components/addon/components/file-browser/add-new/create-folder-modal/template.hbs
- lib/osf-components/addon/components/file-browser/file-rename-modal/component.ts
- lib/osf-components/addon/components/file-browser/file-rename-modal/template.hbs
- lib/osf-components/addon/components/file-browser/folder-item/template.hbs
> Add enter behavior for rename and create folder modals; Reload list after renaming

- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/folder-item/styles.scss
> Improve selected item highlight contrast

- lib/osf-components/addon/components/file-browser/add-new/upload/styles.scss
- lib/osf-components/addon/components/file-browser/add-new/upload/template.hbs
- translations/en-us.yml
> Add exceeds storage limit error message

- lib/osf-components/addon/components/move-file-modal/component.ts
> Set maxConcurrency for move and copy tasks to 1

- lib/osf-components/addon/components/file-browser/help-modal/template.hbs
- lib/osf-components/addon/components/file-browser/template.hbs
- translations/en-us.yml
- Update help link depending on  viewing registration files or project files
- Add condition to help modal
- Add translation
Project:
Registrations:
> [ENG-3811] File help modal link

- app/models/file.ts
- lib/osf-components/addon/components/file-browser/add-new/create-folder-modal/component.ts
- lib/osf-components/addon/components/file-browser/add-new/create-folder-modal/styles.scss
- lib/osf-components/addon/components/file-browser/add-new/create-folder-modal/template.hbs
- lib/osf-components/addon/components/file-browser/add-new/template.hbs
- lib/osf-components/addon/components/file-browser/file-rename-modal/component.ts
- lib/osf-components/addon/components/file-browser/file-rename-modal/styles.scss
- lib/osf-components/addon/components/file-browser/file-rename-modal/template.hbs
- lib/registries/addon/components/hero-overlay/styles.scss
- mirage/serializers/file-provider.ts
- mirage/serializers/file.ts
- mirage/views/file.ts
- tests/integration/components/file-browser/component-test.ts
- tests/integration/components/file-browser/file-rename-modal/component-test.ts
- translations/en-us.yml
-   Ticket: [n/a]
Once again, I accidentally merged develop into the feature branch on one of my PRs. Let's update the base branch so CR isn't such a pain.
> Merge develop into feature/output-reporting

- config/environment.d.ts
- config/environment.js
- lib/osf-components/addon/components/new-feature-popover/component.ts
- lib/osf-components/addon/components/new-feature-popover/styles.scss
- lib/osf-components/addon/components/new-feature-popover/template.hbs
- lib/osf-components/app/components/new-feature-popover/component.js
- lib/osf-components/app/components/new-feature-popover/template.js
- lib/registries/addon/overview/controller.ts
- lib/registries/addon/overview/template.hbs
- tests/integration/components/new-feature-popover/component-test.ts
- translations/en-us.yml
> [ENG-3911] New feature popover

- lib/osf-components/addon/components/expandable-preview/component.ts
- lib/osf-components/addon/components/expandable-preview/styles.scss
- lib/osf-components/addon/components/expandable-preview/template.hbs
- lib/osf-components/addon/components/resources-list/component.ts
- lib/osf-components/addon/components/resources-list/resource-card/component.ts
- lib/osf-components/addon/components/resources-list/resource-card/styles.scss
- lib/osf-components/addon/components/resources-list/resource-card/template.hbs
- lib/osf-components/addon/components/resources-list/styles.scss
- lib/osf-components/addon/components/resources-list/template.hbs
- lib/osf-components/app/components/expandable-preview/component.js
- lib/osf-components/app/components/expandable-preview/template.js
- lib/osf-components/app/components/resources-list/component.js
- lib/osf-components/app/components/resources-list/resource-card/component.js
- lib/osf-components/app/components/resources-list/resource-card/template.js
- lib/osf-components/app/components/resources-list/template.js
- lib/registries/addon/overview/resources/route.ts
- lib/registries/addon/overview/resources/template.hbs
- tests/integration/components/expandable-preview/component-test.ts
- tests/integration/components/resources-list/component-test.ts
- tests/integration/components/resources-list/resource-card/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3912]
- Create new resource-list component
- Create new resource-list component
- Create nested resource-card component
- Use this component in registries.resource route
- None
[ENG-3912]: https://openscience.atlassian.net/browse/ENG-3912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3912] Add new resource-list component

- lib/osf-components/addon/components/resources-list/resource-card/template.hbs
- lib/osf-components/addon/components/resources-list/template.hbs
- translations/en-us.yml
-   Ticket: [ENG-3950]
- Add aria-labels
- Add aria-labels, and translations
None
[ENG-3950]: https://openscience.atlassian.net/browse/ENG-3950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3950] Add/Edit resource aria label

- app/models/resource.ts
- lib/osf-components/addon/components/resources-list/edit-resource/component.ts
- lib/osf-components/addon/components/resources-list/edit-resource/template.hbs
- mirage/config.ts
- mirage/views/resource.ts
- tests/integration/components/resources-list/edit-resource/component-test.ts
> Add tests for edit-resource

- lib/osf-components/addon/components/resources-list/edit-resource/template.hbs
- lib/osf-components/addon/components/resources-list/resource-card/template.hbs
- lib/osf-components/addon/components/validated-input/text/styles.scss
- lib/osf-components/addon/components/validated-input/text/template.hbs
- mirage/factories/resource.ts
- mirage/views/resource.ts
- tests/integration/components/resources-list/edit-resource/component-test.ts
- tests/integration/components/resources-list/resource-card/component-test.ts
> Handle DOI as non-URI

- lib/osf-components/addon/components/resources-list/delete-resource/component.ts
- lib/osf-components/addon/components/resources-list/delete-resource/template.hbs
- lib/osf-components/addon/components/resources-list/resource-card/component.ts
- lib/osf-components/addon/components/resources-list/resource-card/styles.scss
- lib/osf-components/addon/components/resources-list/resource-card/template.hbs
- lib/osf-components/addon/components/resources-list/template.hbs
- lib/osf-components/app/components/resources-list/delete-resource/component.js
- lib/osf-components/app/components/resources-list/delete-resource/template.js
- tests/integration/components/resources-list/delete-resource/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-3949]
[ENG-3949]: https://openscience.atlassian.net/browse/ENG-3949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3949] Delete resource

- lib/osf-components/addon/components/resources-list/component.ts
- lib/osf-components/addon/components/resources-list/template.hbs
-   Ticket: [Notion ticket](https://www.notion.so/cos/Infinite-scrolling-doesn-t-work-7f917d688dd240c1a0e5720ddd8a00d9)
Make the infinite scroller work
1. Create an action for loading pages
2. Pass the action to the component rather than the task
> Fix infinite scroller

- app/models/resource.ts
> Make resource types consistent in dropdowns

- lib/registries/addon/overview/template.hbs
> Fix duplicate resource links; hide badges when !resourcesVisible

- lib/osf-components/addon/components/resources-list/component.ts
> Reload registration on resource updates

- lib/osf-components/addon/components/file-browser/file-item/styles.scss
- lib/osf-components/addon/components/file-browser/file-item/template.hbs
- translations/en-us.yml
> [ENG-3970] Add file download count to file list view

- mirage/factories/registration-provider.ts
This is a quick fix which prevents the osf from loading in debug mode on port 4200
> Fixed an error preventing the osf to load in debug mode

- lib/app-components/addon/components/branded-navbar/template.hbs
- lib/collections/addon/application/controller.ts
- lib/collections/addon/application/template.hbs
- translations/en-us.yml
> Add moderation button to branded-navbar

- config/environment.js
> Update environment variables for mirage server

- app/models/collection-submission.ts
- mirage/scenarios/collections.ts
- mirage/scenarios/default.ts
Feature - added an accepted collection moderation to mirage
> Feature - added an accepted collection moderation to mirage

- config/environment.js
-   Ticket: None
- Revert the environment config variables to their default values. Hoping the mirage server doesn't break
- disable mirage by default
- disable collections by default
> Revert environment config

- lib/osf-components/addon/components/make-decision-dropdown/component.ts
- lib/osf-components/addon/components/make-decision-dropdown/styles.scss
- lib/osf-components/addon/components/make-decision-dropdown/template.hbs
- tests/engines/collections/acceptance/moderation/all-submissions-test.ts
- tests/engines/registries/acceptance/overview/moderator-mode-test.ts
- translations/en-us.yml
-   Ticket: [ENG-2431]
- Require moderator justification for certain actions
- Add changeset and validations to MakeDecisionDropdown
Invalid:
Valid:
Mobile:
Comment optional:
- Comments should only be required for the following actions:
- Registrations:
- Reject pending, Reject withdraw, Force withdraw
- Registration revisions:
- Moderator reject revision
- Collections:
- Reject, Moderator remove
[ENG-2431]: https://openscience.atlassian.net/browse/ENG-2431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-2431] Require moderator comment

- CHANGELOG.md
- package.json
-   Ticket: [ENG-4065]
[ENG-4065]: https://openscience.atlassian.net/browse/ENG-4065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4065] Update Changelog and version number

- app/settings/account/-components/affiliated-institutions/component.ts
- app/settings/account/-components/affiliated-institutions/styles.scss
- app/settings/account/-components/affiliated-institutions/template.hbs
- app/settings/account/template.hbs
- translations/en-us.yml
> [ENG-4209] Institution affiliation management

- app/models/custom-item-metadata-record.ts
- lib/osf-components/addon/components/funding-metadata/component.ts
> funder_identifier_type instead of funder_identifierType

- lib/osf-components/addon/components/node-metadata-manager/component.ts
> Fix cancel bug

- lib/osf-components/addon/components/funding-metadata/styles.scss
- lib/osf-components/addon/components/funding-metadata/template.hbs
- lib/osf-components/addon/components/node-metadata-form/styles.scss
- lib/osf-components/addon/components/node-metadata-form/template.hbs
Add some basic styling to the funders widget.
1. Clean up some css
2. Style funders widget
3. Re-arrange some buttons
> Guid-Metadata / Style funders widget

- lib/osf-components/addon/components/node-metadata-form/template.hbs
Fix accessibility problem with institutions list
1. Re-work data list around institutions
> guid metadata / Fix a11y error with institutions

- app/guid-file/-components/resource-help-dialog/template.hbs
- app/guid-file/controller.ts
- app/guid-file/template.hbs
- lib/osf-components/addon/components/node-metadata-form/component.ts
- lib/osf-components/addon/components/node-metadata-form/funding-help-dialog/template.hbs
- lib/osf-components/addon/components/node-metadata-form/resource-help-dialog/template.hbs
- lib/osf-components/addon/components/node-metadata-form/template.hbs
- lib/osf-components/addon/components/node-metadata-manager/component.ts
- lib/osf-components/app/components/node-metadata-form/component.js
- lib/osf-components/app/components/node-metadata-form/funding-help-dialog/template.js
- lib/osf-components/app/components/node-metadata-form/resource-help-dialog/template.js
- translations/en-us.yml
-   Ticket: [ENG-4306]
- add help modals for resource information and funding information to the node metadata form and to the file metadata form
- Add help icons to node metadata form for resource information and funding information
- add component to display node resource information based on read/write permission
- add component to display node funder information based on read/write permission
- Add help icons to file metadata form for resource information
- add component to display file resource information based on read/write permission
TODO: The help-links are still not the proper links, so we will need to update those links before release
- Node help icons
- Resource information (write-permission)
- Resource information (read-only)
- Funder information …
> [ENG-4306] Metadata help text

- lib/osf-components/addon/components/node-metadata-manager/component.ts
- tests/acceptance/guid-node/metadata-test.ts
- translations/en-us.yml
> Add validation error toast message

- .github/workflows/CI.yml
> Use Percy Cli instead of percy/exec-action

- .percy.yml
> Add .percy.yml config file

- lib/analytics-page/addon/services/keen.ts
-   Ticket: []
fix analytics page until we can do a more proper update (to the new metrics api)
> [hotfix] temporary fix for analytics page

- lib/osf-components/addon/components/subjects/manager/single/component.ts
-   Ticket: [ENG-4389]
- Alphabetize nested subjects
- explicitly ask for an alphabetized list when fetching child subjects
- Unalphabetized results for nested subjects before in registration metadata page
- Alphabetized results for nested subjects after
- None
[ENG-4389]: https://openscience.atlassian.net/browse/ENG-4389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4389] Sort nested subjects

- .github/workflows/CI.yml
- .percy.yml
- package.json
- tests/integration/components/registries/registries-services-list/component-test.ts
- yarn.lock
-   Ticket: [ENG-3542]
Upgrade Percy from 1.x to 3.0
Ran the `$ npx @percy/migrate` script and followed the prompts and did not update imports.
None
No testing needed
[ENG-3542]: https://openscience.atlassian.net/browse/ENG-3542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-3542] Percy 3.0 upgrade

- .github/workflows/CI.yml
- .percy.yml
- app/dashboard/template.hbs
- app/home/-components/support-section/template.hbs
- config/deprecation-workflow.js
- config/optional-features.json
- lib/collections/addon/components/discover-page/component.ts
- lib/collections/addon/components/discover-page/template.hbs
- lib/osf-components/addon/components/delete-node-modal/template.hbs
- lib/osf-components/addon/components/file-metadata-manager/component.ts
- lib/osf-components/addon/components/subjects/manager/single/component.ts
- lib/registries/addon/components/registries-metadata/template.hbs
- lib/registries/addon/components/registries-states/component.ts
- lib/registries/addon/overview/-components/overview-topbar/template.hbs
- package.json
- tests/acceptance/guid-file/registration-file-detail-test.ts
- tests/engines/registries/acceptance/overview/topbar-test.ts
- tests/index.html
- tests/integration/components/link-to/component-test.ts
- tests/integration/components/registries/registries-services-list/component-test.ts
- translations/en-us.yml
- yarn.lock
> Merge basket branch into develop for Antimony release

- Dockerfile
> Back merge master into develop.

- .github/workflows/CI.yml
> Do not run `finalize_percy` task if there is no PERCY_TOKEN

- app/router.ts
- app/search/route.ts
- app/search/template.hbs
-   Ticket: [ENG-4449]
- Add route for new search
- Define new route `/search` in router
- Add dummy template for new route
[ENG-4449]: https://openscience.atlassian.net/browse/ENG-4449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4449] Add new route for search

- lib/registries/addon/components/registries-discover-results-header/styles.scss
- lib/registries/addon/components/registries-discover-results-header/template.hbs
- lib/registries/addon/components/registries-discover-search/x-results/component.ts
- lib/registries/addon/components/registries-discover-search/x-sidebar/component.ts
- lib/registries/addon/components/registries-discover-search/x-sidebar/styles.scss
- lib/registries/addon/components/registries-discover-search/x-sidebar/template.hbs
- lib/registries/addon/components/registries-header/styles.scss
- lib/registries/addon/components/registries-header/template.hbs
- lib/registries/addon/components/registries-recent-list/styles.scss
- lib/registries/addon/components/registries-recent-list/template.hbs
- lib/registries/addon/components/registries-search-result/component.ts
- lib/registries/addon/components/registries-search-result/styles.scss
- lib/registries/addon/components/registries-search-result/template.hbs
- lib/registries/addon/components/registries-services-list/component.ts
- lib/registries/addon/components/registries-services-list/styles.scss
- lib/registries/addon/components/registries-services-list/template.hbs
- lib/registries/addon/discover/controller.ts
- lib/registries/addon/discover/styles.scss
- lib/registries/addon/discover/template.hbs
- lib/registries/addon/index/styles.scss
- lib/registries/addon/index/template.hbs
- lib/registries/addon/page-not-found/styles.scss
- lib/registries/addon/page-not-found/template.hbs
-   Ticket: [ENG-4407]
Refactor bootstrap out of the registries components
Removed all the container, row, col-* from the registries components
**Updates after comments**
**Registries Search - Before**
**Registries Search - After**
**No Results - Before**
**No Results - After**
**Registries - See More - Before**
**Registries - See More - After**
**Pagination - Before**
**Pagination - After**
**Error and Loading - Before**
Error and Loading - After
**Services - Before**
**Services - After**
Overwhelming chaos
Either review the images or browse to the pages.
[ENG-4407]: https://openscience.atlassian.net/browse/ENG-4407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4407] Finished the refactoring of bootstrap for registries

- tests/acceptance/settings/tokens-page-test.ts
To get the token edit test to pass consistently
1. Add waitFor in another place
2. Increase timeout for waitFors
> Add more waitfor with longer potential timeout

- app/dashboard/styles.scss
- app/styles/_components.scss
- app/styles/_global.scss
- lib/app-components/addon/components/branded-navbar/styles.scss
- lib/app-components/addon/components/branded-navbar/template.hbs
- lib/collections/addon/components/collections-submission/styles.scss
- lib/osf-components/addon/components/button/component.ts
- lib/osf-components/addon/components/button/styles.scss
- lib/osf-components/addon/components/new-project-modal/template.hbs
- lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
- lib/osf-components/addon/components/osf-navbar/styles.scss
- lib/osf-components/addon/components/osf-navbar/template.hbs
- lib/osf-components/addon/components/registries/schema-block-renderer/helper-text-icon/styles.scss
- lib/osf-components/addon/components/registries/schema-block-renderer/helper-text-icon/template.hbs
- lib/osf-components/addon/components/responsive-dropdown/styles.scss
- lib/osf-components/addon/components/sort-button/styles.scss
- lib/registries/addon/components/registries-navbar/styles.scss
- lib/registries/addon/components/registries-navbar/template.hbs
Let's fix a bunch of bugs. I think the easiest way to review is to go through the commits.
See commit list
> [ENG-4551] Cesium/first batch of bug fixes

- app/dashboard/styles.scss
- app/home/-components/support-section/learn-more-button/styles.scss
- app/settings/account/-components/change-password/styles.scss
- app/settings/account/-components/change-password/template.hbs
- app/settings/account/-components/security/styles.scss
- app/settings/account/-components/security/template.hbs
- app/settings/developer-apps/-components/app-form/styles.scss
- app/settings/developer-apps/-components/app-form/template.hbs
- app/settings/styles.scss
- app/settings/tokens/-components/create-form/component.ts
- app/styles/_components.scss
- app/styles/_global.scss
- lib/app-components/addon/components/submit-section-buttons/styles.scss
- lib/app-components/addon/components/submit-section-buttons/template.hbs
- lib/osf-components/addon/components/copyable-text/styles.scss
- lib/osf-components/addon/components/copyable-text/template.hbs
- lib/osf-components/addon/components/node-card/template.hbs
- lib/osf-components/addon/components/node-navbar/styles.scss
- lib/osf-components/addon/components/node-navbar/template.hbs
- lib/osf-components/addon/components/sign-up-form/styles.scss
More small bug fixes for the cesium release. Best reviewed commit-by-commit, I believe.
See commit list. 
> [ENG-4551] Cesium/second batch of bug fixes

- app/adapters/index-card-search.ts
- app/adapters/index-card.ts
- app/adapters/index-property-search.ts
- app/adapters/index-value-search.ts
- app/adapters/share-adapter.ts
- mirage/config.ts
- Update SHAREAdapter to point to correct locations
- Update SHAREAdapter parent class to point use config variable for share-url
- Update SHAREAdapter parent class to point use api/v3 endpoints
- Update search-related adapters to point to singularized endpoint names (e.g. api/v3/index-card-search**es** -> api/v3/index-card-search
- Update mirage endpoints to reflect these changes
- NA
- None
> [No ticket] Update SHARE endpoints

- app/institutions/dashboard/-components/institutional-users-list/component.ts
- lib/osf-components/addon/components/node-card/styles.scss
- lib/osf-components/addon/components/node-card/template.hbs
The title on the registration node card was wrapping with multiple stati
added css flex-row wrapping
Hopefully none
Visual or automated testing
> [ENG-4551] Fixed title wrapping on the registration node

- app/institutions/dashboard/-components/panel/styles.scss
- app/institutions/dashboard/-components/panel/template.hbs
- app/settings/account/-components/request-deactivation/styles.scss
- app/settings/account/-components/request-deactivation/template.hbs
- app/styles/_accessibility.scss
- lib/osf-components/addon/components/copyable-text/template.hbs
- lib/osf-components/addon/components/osf-navbar/auth-dropdown/styles.scss
- lib/osf-components/addon/components/osf-navbar/auth-dropdown/template.hbs
- lib/osf-components/addon/components/panel/template.hbs
- lib/osf-components/addon/components/panel/x-body/template.hbs
- lib/osf-components/addon/components/panel/x-footer/template.hbs
- lib/osf-components/addon/components/panel/x-heading/template.hbs
- lib/registries/addon/components/registries-header/component.ts
- lib/registries/addon/components/registries-header/styles.scss
- lib/registries/addon/components/registries-header/template.hbs
- lib/registries/addon/components/registries-recent-list/styles.scss
Fix some more things found by QA. Best reviewed commit-by-commit.
See commit list
> [ENG-4551] Cesium/third batch of bug fixes

- app/models/preprint-provider.ts
> [ENG-4569] Add brand relationship to preprint provider model

- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
- tests/acceptance/search/search-help-test.ts
- translations/en-us.yml
-   Ticket: https://openscience.atlassian.net/browse/ENG-4535
-   Git branch: feature/help-feature
The purpose of these changes is to provide the Search page with a three-part help tutorial introducing users to the new Search page's highlighted functionality.
1. The EmberPopover component was used to populate the tutorial's content and rendering.
2. Boolean values to show or hide tooltip were implemented for the TS logic. The individual panels of the tutorial will show or hide themselves based on their true/false values applied by the tutorial's button navigation.
3. CSS was applied to the popover to give it a more native OSF user interface.
Note: This PR is a result of the search page componentization and may be referenced by its other PR here: …
> [ENG-4535] Search help feature - componentized

- app/institutions/discover/controller.ts
- app/preprints/discover/controller.ts
- app/preprints/discover/template.hbs
- app/search/controller.ts
- lib/osf-components/addon/components/search-page/component.ts
- lib/osf-components/addon/components/search-page/template.hbs
- lib/registries/addon/branded/discover/controller.ts
- lib/registries/addon/branded/discover/template.hbs
- tests/acceptance/search/search-query-params-test.ts
> [No Ticket] Change queryparam passed to SHARE when filtering by resourceType

- lib/osf-components/addon/components/search-page/component.ts
- Explicitly as for specific resource types when selecting the "All" filter in search
- Ask for every resource type supported when "All" option is selected when querying SHARE
N/A
> [No ticket] Explicitly ask for resource-types when selecting All

- app/models/search-result.ts
- lib/osf-components/addon/components/search-result-card/registration-secondary-metadata/template.hbs
> Add registration template info to search result card

- app/models/search-result.ts
- lib/osf-components/addon/components/search-result-card/file-secondary-metadata/template.hbs
> Add nodeLicense and nodeFunders to file card

- app/models/search-result.ts
- lib/osf-components/addon/components/search-page/template.hbs
> Fix resourceNature and cardSearchText

- lib/osf-components/addon/components/search-result-card/file-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/project-secondary-metadata/template.hbs
- lib/osf-components/addon/components/search-result-card/registration-secondary-metadata/template.hbs
-   Ticket: []
- Use dl, dt, and dd for search-result card's secondary metadata panels
> Use dl,dt,dd for search-result-card secondary-metadata

- app/models/search-result.ts
- lib/osf-components/addon/components/search-result-card/template.hbs
> Add file parent and contributors; make contributors show up as links

- app/models/search-result.ts
- lib/osf-components/addon/components/search-result-card/registration-secondary-metadata/template.hbs
- translations/en-us.yml
> Fix registration provider label. Fix DOI and License.

- app/models/search-result.ts
- lib/osf-components/addon/components/search-result-card/project-secondary-metadata/template.hbs
- translations/en-us.yml
> Fix language field

- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-result-card/template.hbs
> Fix styling for open resources badges

- app/models/search-result.ts
- lib/osf-components/addon/components/search-result-card/styles.scss
- lib/osf-components/addon/components/search-result-card/template.hbs
- translations/en-us.yml
-   Ticket: [Notion card](https://www.notion.so/cos/FE-Special-Tagging-For-Withdrawn-Registrations-8f7fa0a051b44ab98e58e4cfd0c34000)
- Add withdrawn label
- Detect withdrawn things
- Label withdrawn things
- Style withdrawn things
- Registration
- Preprint
- Users (margin for orcid id)
> Add Withdrawn label to withdrawn things

- tests/engines/registries/acceptance/landing-page-test.ts
Remove test that accidentally merged in
> Fix barium test

- config/deprecation-workflow.js
> Fix `argument less helper paren less invocation` deprecation

- config/deprecation-workflow.js
Fix deprecation route-render-template
1. Unsilence the deprecation
> [No ticket] Barium/route render template

- lib/osf-components/addon/components/search-page/component.ts
-   Ticket: []
- Remove accessService query-param to SHARE requests as files and users don't have them
> Remove accessService qp to SHARE

- app/institutions/discover/controller.ts
- app/preprints/discover/controller.ts
> Change query param name from cardSearchText to q

- app/preprints/discover/controller.ts
- app/preprints/discover/route.ts
- app/preprints/discover/template.hbs
> Fix query param

- lib/osf-components/addon/components/search-page/filter-facet/template.hbs
- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-result-card/template.hbs
- translations/en-us.yml
-   Ticket: [Notion Card](https://www.notion.so/cos/Accessibility-Issues-With-Search-Page-2defbcd2d3ee4666a9b80f64d6cadb2c?pvs=4)
- Address some accessibility issues on the search page
- Update `id`s used on the filter facet dropdowns to always be valid (no spaces in the ID names)
- Add aria-label, aria-controls, and aria-expanded attrs to search result card toggle button
- Add `id` to the CpPanel
- Use darker color for object type filter links
> Search a11y

- lib/osf-components/addon/components/search-page/styles.scss
- lib/osf-components/addon/components/search-page/template.hbs
- tests/acceptance/institutions/discover-test.ts
-   Ticket: Notion Cards in Summary of Changes section
- Address bugs for mobile search page
1.  Use CSS globals for provider descriptions: Notion Cards: [First one](https://www.notion.so/cos/New-Branded-Registration-Discover-Page-Does-Not-Use-HTML-Formatting-for-Description-d2cd6bf0b19745b583a15772b9af956a?pvs=4) and [second one](https://www.notion.so/cos/Not-using-the-color-classes-e79f2303fbd44320a66ad20ba81264d7?pvs=4)
a. Add global classes for use by product folks when modifying a provider's description (re-implementation of this PR: https://github.com/CenterForOpenScience/ember-osf-web/pull/1181/files)
3. Use institution's banner image for all screen sizes: [Notion Card](https://www.notion.so/cos/Institutions-Bug-Logos-are-too-small-in-mobile-view-9993fd4733a046 …
> Search: Mobile fixes

- lib/app-components/addon/components/branded-navbar/styles.scss
> Fix sign up button a11y issue

- app/models/identifier.ts
- app/models/preprint.ts
-   Ticket: []
- Resolve identifier relationship
- Lie
> [HOTFIX] Fix identifier relationships (sort of)

- app/preprints/detail/controller.ts
- app/preprints/detail/route.ts
- app/preprints/detail/template.hbs
> [Hotfix]Wait until after headTags are set to render plaudit

- app/preprints/detail/route.ts
- app/preprints/detail/template.hbs
> [ENG-5009] Stop loading node in route model hook

- app/preprints/detail/template.hbs
> not show the links if supplemental node is private

- app/preprints/detail/template.hbs
-   Ticket: [ENG-5013]
- Link to contributor pages for preprint contributors
- Update `ContributorList` component invocation
- On the preprint detail page, registered contributors names should be links
[ENG-5013]: https://openscience.atlassian.net/browse/ENG-5013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5013] Link preprint contributors

- app/packages/addons-service/provider.ts
- lib/osf-components/addon/components/addons-service/manager/component.ts
-   Ticket: [ENG-5031]
- Add addon service methods to manager and provider class
- 
- NA
[ENG-5031]: https://openscience.atlassian.net/browse/ENG-5031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5031] Service methods

- app/models/configured-storage-addon.ts
- app/packages/addons-service/provider.ts
- mirage/config.ts
- mirage/scenarios/dashboard.ts
- mirage/serializers/addon-service-serializer.ts
- mirage/serializers/authorized-storage-account.ts
- mirage/serializers/configured-storage-addon.ts
- mirage/serializers/internal-resource.ts
- mirage/serializers/internal-user.ts
- mirage/views/addons.ts
- tests/unit/packages/addons-service/provider-test.ts
-   Ticket: [ENG-5109]
- Add test for new Addon Provider class
- Add the test
- Update some logic in the Provider class
- Update some models and mirage stuff
- NA
[ENG-5109]: https://openscience.atlassian.net/browse/ENG-5109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5109] Add tests for Addon Provider Class

- app/guid-node/template.hbs
- config/environment.js
-   Ticket: [ENG-5162]
Waffle the rest of the app that we'll be modifying
1. Added feature flag to `guid-node.addons` page
2. Added feature flag to the tab link to the node addons page
[ENG-5162]: https://openscience.atlassian.net/browse/ENG-5162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5162] Add waffling to guid-node.addons page and link

- app/guid-node/addons/index/controller.ts
- app/guid-node/addons/index/styles.scss
- app/guid-node/addons/index/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/manager/template.hbs
- tests/integration/components/addons-service/manager/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-5160]
-   Feature flag: gravy_waffle
- Allow users to filter addon types and names
- Add `FilterTypes` enum for addons
- Use enum to create buttons to filter by
- Use enum to control which list of addon providers is shown (hypothetically)
- Add textbox to control filtering by name
- Style :nail_care:
- Desktop
- Mobile
[ENG-5160]: https://openscience.atlassian.net/browse/ENG-5160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5160] Add ability to filter

- app/config/environment.d.ts
- config/environment.js
> Add terminologyIntegratedSearchUrl

- app/guid-file/metadata/add/route.ts
- app/guid-node/metadata/add/route.ts
- lib/osf-components/addon/components/cedar-metadata-renderer/template.hbs
- lib/osf-components/addon/components/metadata/metadata-select/template.hbs
- lib/registries/addon/overview/metadata/add/route.ts
> Change `findAll` to `query` to hide inactive templates

- app/adapters/resource-reference.ts
- app/adapters/user-reference.ts
- app/models/authorized-storage-account.ts
- app/models/configured-storage-addon.ts
- app/models/internal-user.ts
- app/models/resource-reference.ts
- app/models/user-reference.ts
- app/packages/addons-service/provider.ts
- app/serializers/resource-reference.ts
- app/serializers/user-reference.ts
- lib/osf-components/addon/components/addons-service/manager/component.ts
- mirage/config.ts
- mirage/factories/resource-reference.ts
- mirage/factories/user-reference.ts
- mirage/scenarios/dashboard.ts
- mirage/serializers/authorized-storage-account.ts
- mirage/serializers/configured-storage-addon.ts
- mirage/serializers/resource-reference.ts
- mirage/serializers/user-reference.ts
- mirage/views/addons.ts
- tests/integration/components/addons-service/manager/component-test.ts
- tests/unit/packages/addons-service/provider-test.ts
-   Ticket: [ENG-5256]
- Rename `internal-user` and `internal-resource` to `user-reference` and `resource-reference` respectively
- Update file names, model names, variable names etc
- NA
- None if I did this right
- NA
[ENG-5256]: https://openscience.atlassian.net/browse/ENG-5256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5256] Refactor internal model names

- package.json
- yarn.lock
> Upgrade CEE to 1.0.16

- app/guid-node/route.ts
- app/resolve-guid/guid-route.ts
- lib/registries/addon/overview/route.ts
> Go to page not found when encountering errors.

- lib/osf-components/addon/components/cedar-metadata-editor/template.hbs
- package.json
- yarn.lock
> Upgrade cee version to 1.2.1. Listen to more events to trigger validation

- app/preprints/submit/controller.ts
- app/preprints/submit/route.ts
- app/preprints/submit/styles.scss
- app/preprints/submit/template.hbs
- app/router.ts
- translations/en-us.yml
-   Ticket: [ENG-4888]
Add the initial submit route and files
Added the initial route, controller and template for the submit route
It's rather vanilla since a few items are just placeholders
[ENG-4888]: https://openscience.atlassian.net/browse/ENG-4888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4888] Added the initial route, controller and template for the submit route

- app/router.ts
- ember-cli-build.js
- lib/osf-components/addon/components/metadata/metadata-detail/template.hbs
- lib/registries/addon/routes.ts
- package.json
- yarn.lock
> [Do not merge] disable CEDAR embeddable editor and artifact viewer

- app/adapters/authorized-citation-service-account.ts
- app/adapters/authorized-cloud-computing-account.ts
- app/adapters/configured-citation-service-addon.ts
- app/adapters/configured-cloud-computing-addon.ts
- app/models/authorized-citation-service-account.ts
- app/models/authorized-cloud-computing-account.ts
- app/models/configured-citation-service-addon.ts
- app/models/configured-cloud-computing-addon.ts
- app/models/resource-reference.ts
- app/models/user-reference.ts
- app/serializers/authorized-citation-service-account.ts
- app/serializers/authorized-cloud-computing-account.ts
- app/serializers/configured-citation-service-addon.ts
- app/serializers/configured-cloud-computing-addon.ts
- mirage/config.ts
- mirage/factories/authorized-citation-service-account.ts
- mirage/factories/authorized-cloud-computing-account.ts
- mirage/factories/configured-citation-service-addon.ts
- mirage/factories/configured-cloud-computing-addon.ts
- mirage/serializers/authorized-citation-service-account.ts
- mirage/serializers/authorized-cloud-computing-account.ts
- mirage/serializers/configured-citation-service-addon.ts
- mirage/serializers/configured-cloud-computing-addon.ts
- mirage/serializers/resource-reference.ts
- mirage/serializers/user-reference.ts
- mirage/views/addons.ts
- Add extra models needed to support other addon types (citation managers and remote computing services)
- Add authorized account models for other types
- Add configured account models for other types
- updates to mirage and other existing models
- NA
> Extra addon models

- app/settings/addons/template.hbs
- lib/osf-components/addon/components/addons-service/addon-account-setup/styles.scss
- lib/osf-components/addon/components/addons-service/addon-account-setup/template.hbs
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/template.hbs
- package.json
- translations/en-us.yml
- yarn.lock
-   Ticket: [ENG-5582]
Make changes based on user feedback. Details in the Jira ticket.
1. Update ember aria tabs
2. After adding an account, switch tabs to the connected accounts tab
3. Change wording from 'authorize' to 'connect'
4. Make forms look right (stacked labels with instructions between label and field)
5. Add in temporary text for the display name field
Could have broken tabs with the new version of ember-aria-tabs. Tests pass, though.
[ENG-5582]: https://openscience.atlassian.net/browse/ENG-5582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5582] Make changes based on user feedback

- app/packages/addons-service/provider.ts
- app/settings/addons/template.hbs
- lib/osf-components/addon/components/addons-service/addon-account-setup/template.hbs
- lib/osf-components/addon/components/addons-service/terms-of-service/component.ts
- lib/osf-components/addon/components/addons-service/terms-of-service/template.hbs
- mirage/serializers/authorized-citation-account.ts
- mirage/serializers/authorized-computing-account.ts
- mirage/serializers/authorized-storage-account.ts
- mirage/views/addons.ts
- tests/acceptance/settings/addons-test.ts
-   Ticket: [ENG-5172]
Test the user settings addons page.
1. Add tests
2. Add test selectors
3. Fix problem with accountOwner
[ENG-5172]: https://openscience.atlassian.net/browse/ENG-5172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5172] User settings addons tests

- app/guid-node/addons/index/template.hbs
- app/models/addon-operation-invocation.ts
- app/models/configured-citation-addon.ts
- app/models/configured-computing-addon.ts
- app/models/configured-storage-addon.ts
- app/packages/addons-service/provider.ts
- lib/osf-components/addon/components/addons-service/file-manager/component.ts
- lib/osf-components/addon/components/addons-service/file-manager/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/manager/template.hbs
- lib/osf-components/addon/components/addons-service/root-folder-picker/component.ts
- lib/osf-components/addon/components/addons-service/root-folder-picker/styles.scss
- lib/osf-components/addon/components/addons-service/root-folder-picker/template.hbs
- lib/osf-components/app/components/addons-service/file-manager/component.js
- lib/osf-components/app/components/addons-service/file-manager/template.js
- lib/osf-components/app/components/addons-service/root-folder-picker/component.js
- lib/osf-components/app/components/addons-service/root-folder-picker/template.js
- mirage/scenarios/dashboard.ts
- mirage/serializers/authorized-citation-account.ts
- mirage/serializers/authorized-computing-account.ts
- mirage/serializers/authorized-storage-account.ts
- mirage/serializers/configured-citation-addon.ts
- mirage/serializers/configured-computing-addon.ts
- mirage/serializers/configured-storage-addon.ts
- mirage/views/addons.ts
- tests/integration/components/addons-service/root-rolder-picker/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-5173]
- Create root-folder-picker for configured storage addons
- Make updates to mirage to support root-folder-picker
[ENG-5173]: https://openscience.atlassian.net/browse/ENG-5173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5173] Root folder picker

- lib/osf-components/addon/components/addons-service/user-addons-manager/template.hbs
- tests/integration/components/addons-service/user-addons-manager/component-test.ts
-   Ticket: [ENG-5171]
- Add tests for user-addons-manager component
- Add tests for user-addons-manager component
- Remove an unused part of user-addons-manager
- NA
[ENG-5171]: https://openscience.atlassian.net/browse/ENG-5171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5171] Add tests for user-addons-manager

- app/models/addon-operation-invocation.ts
- app/models/configured-storage-addon.ts
- app/models/external-service.ts
- app/transforms/object.ts
- app/utils/map-keys.ts
- lib/osf-components/addon/components/addons-service/file-manager/component.ts
- lib/osf-components/addon/components/addons-service/manager/component.ts
- mirage/views/addons.ts
- tests/unit/utils/map-keys-test.ts
-   Ticket: []
get addons frontend working with gravyvalet on staging
- update CredentialsFormat values to match backend (should fix incorrect `initiate_oauth: false`)
- camelize snake-case keys in invocation kwargs and results (avoid backend error on `itemId` (expecting `item_id`))
- stop creating credentials objects with all possible keys (avoid backend error when using the account form a second time)
> assorted fixes for gravyvalet staging

- app/preprints/my-preprints/template.hbs
- app/router.ts
-   Ticket: [https://openscience.atlassian.net/browse/ENG-6008]
Add My Preprints route and page template
- Added a New Route for My Preprints accessible at /preprints/my-preprints.
- Added a new template.hbs file within the app/preprints/my-preprints/ directory.
> [ENG-6008]: Add My Preprints route and page template

- app/models/institution-user.ts
- mirage/factories/institution-user.ts
Make sure the institutional dashboard can display all relevant information. 
- add fields to user model
- adds fields to mirage factories
https://openscience.atlassian.net/browse/ENG-6115
> [ENG-6115] Update Institutions User Model

- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
- lib/osf-components/addon/components/addons-service/file-manager/component.ts
> Don't send kwargs when its fetching root items

- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
- lib/osf-components/addon/components/addons-service/file-manager/component.ts
> Fix get root items again

- app/models/configured-citation-addon.ts
- app/models/external-service.ts
- app/packages/addons-service/provider.ts
> fix a bunch of things

- app/packages/files/service-provider-file.ts
- lib/osf-components/addon/components/storage-provider-manager/storage-manager/component.ts
> fix ServiceProviderFile getFolderItems

- app/preprints/-components/preprint-institutions/institution-manager/component-test.ts
-   Ticket: [ENG-5919]
Fix some typos in comments in tests
Fix some typos in comments in tests
[ENG-5919]: https://openscience.atlassian.net/browse/ENG-5919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5919] Fixed some typos

- lib/app-components/addon/components/branded-navbar/template.hbs
-   Ticket: [https://openscience.atlassian.net/browse/ENG-6011]
Update link for branded preprints
Change the link of the My Preprints button on the branded preprints navbar
> [ENG-6011] Update link for branded preprints

- lib/app-components/addon/components/branded-navbar/template.hbs
- lib/osf-components/addon/components/osf-navbar/preprint-links/template.hbs
-   Ticket: []
Revert changes to the my-preprint link on the nav bar
- Change to link back to the My Projects page
> Revert changes to the my-preprint link on the nav bar

- app/models/authorized-account.ts
- lib/osf-components/addon/components/addons-service/addon-account-setup/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- mirage/views/addons.ts
- tests/acceptance/guid-node/addons-test.ts
> Underscore accessKey and secretKey

- app/institutions/dashboard/-components/object-list/contributors-field/component.ts
- app/institutions/dashboard/-components/object-list/contributors-field/template.hbs
- app/institutions/dashboard/projects/controller.ts
- app/models/index-card.ts
- app/models/search-result.ts
- lib/app-components/addon/components/project-contributors/list/item/template.hbs
- lib/osf-components/addon/components/contributors/add-unregistered-modal/template.hbs
- lib/osf-components/addon/components/contributors/card/editable/template.hbs
- lib/osf-components/addon/components/contributors/card/readonly/template.hbs
- lib/osf-components/addon/components/contributors/user-search/card/template.hbs
- mirage/views/search.ts
- tests/integration/components/contributors/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-6246] [ENG-6269] [ENG-6275]
- Add new metadata fields to mirage and update project list to get new properties
- Add new properties to mirage/views/search.ts based on these [proposed changes](https://docs.google.com/spreadsheets/d/1L2qVpIW4EUwqAQcP9kriCm8MngMgISxRlE8IFt99dnc/edit?gid=1787178252#gid=1787178252) 
- Registrations:
- `hasOsfAddon`
- `qualifiedAttribution`
- `agent`
- `hadRole`
- `storageByteCount`
- `storageRegion`
- `usage`
- Projects:
- `funder`
- `hasOsfAddon`
- `qualifiedAttribution`
- `agent`
- `hadRole`
- `resourceNature`
- `storageByteCount`
- `storageRegion`
- `usage`
- Preprpints:
- `funder`
- `qualifiedAttribution`
- `agent`
- `hadRole`
- `usage`
- Add new getters for these new metadata properties to the search-result model
- …
> [ENG-6246][ENG-6269][ENG-6275]  Add new property fields to mirage

- app/institutions/dashboard/-components/institutional-users-list/template.hbs
- lib/osf-components/addon/components/adjustable-paginator/component.ts
- lib/osf-components/addon/components/adjustable-paginator/styles.scss
- lib/osf-components/addon/components/adjustable-paginator/template.hbs
- lib/osf-components/addon/components/paginated-list/has-many/component.ts
- lib/osf-components/addon/components/paginated-list/has-many/template.hbs
- lib/osf-components/addon/components/paginated-list/layout/component.ts
- lib/osf-components/addon/components/paginated-list/layout/styles.scss
- lib/osf-components/addon/components/paginated-list/layout/template.hbs
- lib/osf-components/app/components/adjustable-paginator/component.js
- translations/en-us.yml
-   Ticket: [https://openscience.atlassian.net/browse/ENG-6367]
Add pagination button that allow to set the number of items as well as jumping the first previous, next and last page.
- adds AdjustablePaginator component
- add styling css and template
> [ENG-6367] Add Adjustable Pagination Buttons For User Table

- app/institutions/dashboard/-components/institutional-dashboard-wrapper/styles.scss
- app/institutions/dashboard/-components/institutional-users-list/styles.scss
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
-   Ticket: [https://openscience.atlassian.net/browse/ENG-6402]
Fix problems where the `apply` button was hidden for andriod users and the preprint tab was being cut off.
- css to keep the dropdown panel visible in the center of the screen
- css to prevent the Preprint tab from being hidden, making it wrap instead.
> [ENG-6402] Insti dashboard mobile fixes

- app/institutions/dashboard/-components/institutional-users-list/styles.scss
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
- translations/en-us.yml
-   Ticket: [https://openscience.atlassian.net/browse/ENG-6513]
Improve some minor problems on the user tab, involving scrolling and placeholder text.
- Use `N/A` instead of `Invalid Date` default from moment
- move css so pagination buttons down scroll
> [ENG-6513] Dashboard Demo Feedback Improvements

- app/institutions/dashboard/projects/controller.ts
- app/institutions/dashboard/registrations/controller.ts
-   Ticket: []
- Only fetch top level projects and registrations for institutional dashboard
- Explicitly fetch only `Project` or `Registration` resourceTypes
> Only fetch top-level project and registrations

- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
> Fetch authorized citation accounts upon filter change on user settings page

- lib/osf-components/addon/components/addons-service/manager/component.ts
> Make sure rootFolder is set

- app/config/environment.d.ts
- app/institutions/dashboard/-components/chart-kpi-wrapper/component-test.ts
- app/institutions/dashboard/-components/chart-kpi-wrapper/component.ts
- app/institutions/dashboard/-components/institutional-users-list/component.ts
- app/institutions/dashboard/-components/institutional-users-list/styles.scss
- app/institutions/dashboard/-components/institutional-users-list/template.hbs
- app/institutions/dashboard/-components/object-list/component-test.ts
- app/institutions/dashboard/-components/object-list/component.ts
- app/institutions/dashboard/-components/object-list/styles.scss
- app/institutions/dashboard/-components/object-list/template.hbs
- app/institutions/dashboard/index/styles.scss
- app/institutions/dashboard/index/template.hbs
- app/institutions/dashboard/route.ts
- app/institutions/dashboard/users/styles.scss
- app/institutions/dashboard/users/template.hbs
- app/models/index-card-search.ts
- app/models/institution-summary-metric.ts
- app/models/institution-user.ts
- app/serializers/index-card-search.ts
- config/environment.js
- lib/osf-components/addon/components/index-card-searcher/component.ts
- lib/osf-components/addon/components/index-card-searcher/template.hbs
- mirage/factories/institution-summary-metric.ts
- mirage/factories/institution-user.ts
- mirage/factories/root.ts
- mirage/views/search.ts
- tests/acceptance/institutions/dashboard-test.ts
- tests/integration/routes/institutions/dashboard/-components/institutional-users-list/component-test.ts
- translations/en-us.yml
-   Ticket: [ENG-5024]
-   Feature flag: `share_download` for downloading projects, registrations, and preprint data
- Add download functionality to Institutional Dashboard
- Add date of report to Summary and Users tab of Institutional Dashboard
- Update language and styling
[ENG-5024]: https://openscience.atlassian.net/browse/ENG-5024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5024] Feature/dashboard b and i

- app/packages/files/service-file.ts
- app/packages/files/service-provider-file.ts
> [ENG-6676] [ENG-6688] Check for whether the provider allows add/update

- lib/osf-components/addon/components/addons-service/manager/component.ts
-   Ticket: [ENG-6527]
Toast during configuration error not being informative
Added error detail from response to toast
[ENG-6527]: https://openscience.atlassian.net/browse/ENG-6527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6527] added response detail to configuration error toast

- app/packages/files/service-provider-file.ts
- lib/osf-components/addon/components/file-browser/breadcrumbs/crumb/template.hbs
-   Ticket: [ENG-6311]
Fixed icon url access in ember code, fixed size of displayed svg icons for files page
[ENG-6311]: https://openscience.atlassian.net/browse/ENG-6311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6311] Fix GV provider icons on files page

- lib/osf-components/addon/components/addons-service/addon-account-setup/component.ts
-   Ticket: [ENG-6613]
[ENG-6613]: https://openscience.atlassian.net/browse/ENG-6613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6613] FE: Gitlab: API token is displayed as plain text during add-on account setup, creating a security concern.

- app/guid-node/addons/index/template.hbs
- lib/osf-components/addon/components/addons-service/addon-account-setup/template.hbs
- lib/osf-components/addon/components/addons-service/configured-addon-edit/template.hbs
> [ENG-6424][ENG-6425] Enforce max length for displayName inputs

- lib/osf-components/addon/components/addons-service/configured-addon-edit/styles.scss
- lib/osf-components/addon/components/addons-service/configured-addon-edit/template.hbs
> [ENG-6541] White space normal on item names

- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/template.hbs
-   Ticket: [ENG-6633]
**To resolve this issue:**
`FE: Configuration Page: Display name errors immediately on page load`
Fixed **display name on page load** error
[ENG-6633]: https://openscience.atlassian.net/browse/ENG-6633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6633] |  fixed display name on page load error

- app/guid-node/addons/index/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/manager/template.hbs
-   Ticket: [ENG-6583]
[ENG-6583]: https://openscience.atlassian.net/browse/ENG-6583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6583] FE: Addons Configuration: "Back" button should take user to previous step

- app/guid-node/addons/index/template.hbs
- app/models/configured-addon.ts
> [ENG-6584] Use render modifiers to invoke getRootFolderName task; add tracked property to ConfiguredAddonModel

- lib/osf-components/addon/components/addons-service/addon-account-setup/component.ts
- lib/osf-components/addon/components/addons-service/addon-account-setup/template.hbs
-   Ticket: [ENG-6615]
[ENG-6615]: https://openscience.atlassian.net/browse/ENG-6615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6615] FE: Connect button should be disabled if required fields are empty

- lib/osf-components/addon/components/addons-service/manager/component.ts
-   Ticket: [ENG-6824]
Resolve blank screen error after clicking `Back` button on **Addon Configuration Page**
Fixed `Back` button
[ENG-6824]: https://openscience.atlassian.net/browse/ENG-6824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6824] | fixed blank screen Back button error

- app/packages/files/service-file.ts
-   Ticket: [ENG-6771]
[ENG-6771]: https://openscience.atlassian.net/browse/ENG-6771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6771] Add draft/published suffix to displayName

- app/models/external-service.ts
- lib/osf-components/addon/components/addons-service/addon-account-setup/component.ts
-   Ticket: [ENG-6007]
[ENG-6007]: https://openscience.atlassian.net/browse/ENG-6007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6007] Add apiBaseUrlOptions

- app/models/configured-addon.ts
- lib/osf-components/addon/components/move-file-modal/component.ts
- lib/osf-components/addon/components/move-file-modal/list-item/styles.scss
- lib/osf-components/addon/components/move-file-modal/list-item/template.hbs
-   Ticket: [ENG-6851]
Fix loading other providers during copy/move with gv enabled
[ENG-6851]: https://openscience.atlassian.net/browse/ENG-6851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6851] BE: Copy/Move to other storage addons not working

- app/institutions/dashboard/-components/institutional-users-list/component.ts
- app/institutions/dashboard/-components/object-list/component.ts
-   Ticket: []
Fix broken user messaging tabs by refactoring to correct kwargs.
- simple change to standardize the message recipient as `messageRecipient` instead of `user` to match node request tab language.
> [IAC][Bug] Fix User Messaging Tab Adapter Bug

- app/institutions/dashboard/-components/institutional-users-list/template.hbs
- app/institutions/dashboard/-components/object-list/contributors-field/template.hbs
- app/models/institution.ts
-   Ticket: [https://openscience.atlassian.net/browse/ENG-6781]
This makes the IAC feature visible/invisible to the user.
- changes to institution model and template
> [ENG-6781][IAC] Add FE Feature Flipping

- app/models/institution.ts
> fix feature flip bug

- app/institutions/dashboard/-components/object-list/component.ts
- app/institutions/dashboard/-components/object-list/contributors-field/component.ts
- app/institutions/dashboard/-components/object-list/contributors-field/styles.scss
- app/institutions/dashboard/-components/object-list/contributors-field/template.hbs
- app/models/node-request.ts
-   Ticket: []
- allows 409 to be displayed as error messages
- makes button inline
- makes button only display on Project Tab
- makes `message_recipient` be sent in payload
> [IAC][ENG-6947][ENG-6948] Integration fixes 

- app/institutions/dashboard/-components/institutional-users-list/component.ts
- app/institutions/dashboard/-components/object-list/component.ts
-   Ticket: []
I seem to have forgotten some spaces and proper http codes along the way.
- change http code to match what exists
- fix space to meet synax conventions
> fix typo and fix issue preventing pop-up modal from popping up

- app/institutions/dashboard/-components/object-list/component.ts
> fix issue with not including error response codes in payload

- translations/en-us.yml
> update translation to remove html tag

- app/preprints/-components/preprint-doi/component.ts
- app/preprints/-components/submit/preprint-state-machine/component.ts
- app/preprints/new-version/route.ts
-   Ticket: []
- Address CR comments found in the PR for the feature branch https://github.com/CenterForOpenScience/ember-osf-web/pull/2447
- Remove unused services and commented out code
- NA
> Clean up unused/commented code

- lib/osf-components/addon/components/addons-service/file-manager/component.ts
-   Ticket: [ENG-7094]
-   Feature flag: gravy-waffle
[ENG-7094]: https://openscience.atlassian.net/browse/ENG-7094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7094] Load more misbehaves for root items

- lib/osf-components/addon/components/contributor-list/template.hbs
- lib/osf-components/addon/components/contributors/card/readonly/component.ts
- lib/osf-components/addon/components/contributors/card/readonly/template.hbs
- lib/osf-components/addon/components/contributors/manager/component.ts
- lib/osf-components/addon/components/contributors/manager/template.hbs
- translations/en-us.yml
-   Ticket: [ENG-6112]
Fixed draft registration being shown istead of preprint
[ENG-6112]: https://openscience.atlassian.net/browse/ENG-6112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6112] Correct Confirmation Prompt When Removing Self from a Preprint

- app/models/search-result.ts
-   Ticket: [ENG-5137]
[ENG-5137]: https://openscience.atlassian.net/browse/ENG-5137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5137] Preprint and project author on search cards does not reflect author order on preprint or project

- app/adapters/addon-service.ts
- app/guid-node/controller.ts
- app/guid-node/template.hbs
-   Ticket: [ENG-7317]
[ENG-7317]: https://openscience.atlassian.net/browse/ENG-7317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7317] Added VOL support to Gv requests

- lib/osf-components/addon/components/move-file-modal/component.ts
-   Ticket: [ENG-7318]
[ENG-7318]: https://openscience.atlassian.net/browse/ENG-7318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7318] Off-AddOns-Release: Cannot move or copy files between related nodes

- app/guid-node/template.hbs
-   Ticket: []
Removed the code I commented out because I thought it would be used later.
Deleted unnecessary code.
N.A.
None. Just code clean-up
Nothing to see here  ...  not the droids you are looking for.
> Removed commented code that is no longer useful after a hot-fix

- lib/osf-components/addon/components/move-file-modal/component.ts
…e any addons configured
-   Ticket: [ENG-7318]
[ENG-7318]: https://openscience.atlassian.net/browse/ENG-7318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7318] Fixed not being able to copy to related node if this node doesn't have any addons configured

- app/guid-node/addons/index/template.hbs
- app/settings/addons/styles.scss
- app/settings/addons/template.hbs
-   Ticket: [ENG06927]
Issues with css. I thought the default "display: flex" was column???
Add "flex-direction: column" to the main wrapper and removed it from the mobile class.
It might pass this time?
Pavlo verified it before I committed this PR. If there are any additional issues, Pavlo needs to fix them. :)
> [ENG-6927] Fixed some issues with css

- app/guid-node/addons/index/controller.ts
- app/guid-node/addons/index/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- tests/integration/components/addons-service/manager/component-test.ts
-   Ticket: [ENG-7739](https://openscience.atlassian.net/browse/ENG-7739)
Add query params for routing
Add query params for routing
N/A
N/A
N/A
[ENG-7739]: https://openscience.atlassian.net/browse/ENG-7739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7739] Add query params for routing

- app/guid-file/route.ts
- app/preprints/detail/route.ts
- app/services/meta-tags.ts
- lib/osf-components/addon/components/contributors/user-search/widget/styles.scss
- lib/registries/addon/overview/route.ts
- tests/engines/registries/acceptance/overview/overview-test.ts
- tests/unit/services/meta-tags-test.ts
-   Ticket: [ENG-6331] [ENG-7802]
Update the meta tags
Changes author to be contributors
Updated the "contributor" to be first name, given name to match the spec
Add a json-ld attribute for all the contributors
N/A
N/A
Just look at the meta tags in the headers
[ENG-6331]: https://openscience.atlassian.net/browse/ENG-6331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-7802]: https://openscience.atlassian.net/browse/ENG-7802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7802] [ENG-6331] Bug fix/eng 6331 - Added Updated Meta Tags

- app/models/search-result.ts
- mirage/views/search.ts
-   Ticket: [ENG-7800]
fix missing search-result highlight text (currently shows "undefined" on stagings)
- remove explicit `@type` check; instead duck-type by attribute presence
- update mirage to match backend changes (e.g. `@type` iri expressed in compact form)
- update highlight label to use `propertyPathKey` instead of only the last property in the path
at `osf.example/search`, enter text in the search box and check that each search result displays highlighted text matches by field (and not "undefined")
[ENG-7800]: https://openscience.atlassian.net/browse/ENG-7800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7800] fix: search-result context text

- app/adapters/authorized-link-account.ts
- app/adapters/configured-link-addon.ts
- app/adapters/external-link-service.ts
- app/models/addon-operation-invocation.ts
- app/models/authorized-link-account.ts
- app/models/configured-link-addon.ts
- app/models/external-link-service.ts
- app/models/resource-reference.ts
- app/models/user-reference.ts
- app/serializers/authorized-link-account.ts
- app/serializers/configured-link-addon.ts
- app/serializers/external-link-service.ts
-   Ticket: [ENG-7781]
[ENG-7781]: https://openscience.atlassian.net/browse/ENG-7781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7781] Add VRL models

- app/preprints/detail/route.ts
-   Ticket: [ENG-7941]
Enabled the metrics for downloads and views on a preprint
Removed the comments around the code to include the metrics.
N/A
N/A
Verify
[ENG-7941]: https://openscience.atlassian.net/browse/ENG-7941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7941] Enabled the metrics for downloads and views on a preprint

- app/guid-node/addons/index/controller.ts
- app/guid-node/addons/index/template.hbs
- app/models/configured-addon.ts
- app/models/configured-link-addon.ts
- app/packages/addons-service/provider.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/component.ts
- lib/osf-components/addon/components/addons-service/configured-addon-edit/styles.scss
- lib/osf-components/addon/components/addons-service/configured-addon-edit/template.hbs
- lib/osf-components/addon/components/addons-service/file-manager/component.ts
- lib/osf-components/addon/components/addons-service/file-manager/template.hbs
- lib/osf-components/addon/components/addons-service/manager/component.ts
- lib/osf-components/addon/components/addons-service/terms-of-service/component.ts
- lib/osf-components/addon/components/addons-service/user-addons-manager/component.ts
- tests/acceptance/guid-node/addons-test.ts
- tests/integration/components/addons-service/configured-addon-edit/component-test.ts
- translations/en-us.yml
> [ENG-7576] Linked service settings page

- app/guid-node/links/template.hbs
- app/guid-node/template.hbs
- app/router.ts
- translations/en-us.yml
-   Ticket: [ENG-7783]
[ENG-7783]: https://openscience.atlassian.net/browse/ENG-7783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7783] Add leftnav link for linked services

- app/models/preprint.ts
- app/models/registration.ts
- app/preprints/-components/submit/title-and-abstract/component.ts
- app/preprints/-components/submit/title-and-abstract/template.hbs
- config/environment.js
- lib/osf-components/addon/components/registries/finalize-registration-modal/manager/component.ts
- lib/osf-components/addon/components/registries/finalize-registration-modal/manager/template.hbs
- lib/osf-components/addon/components/registries/finalize-registration-modal/template.hbs
- lib/osf-components/package.json
- translations/en-us.yml
-   Ticket: [ENG-8146]
[ENG-8146]: https://openscience.atlassian.net/browse/ENG-8146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-8146] Add manual doi and guid fields to  preprint and registration submission workflow

- translations/en-us.yml
> Fix small copy-pasta for tos page

- translations/en-us.yml
-   Ticket: [ENG-8243](https://openscience.atlassian.net/browse/ENG-8243)
Update language for add-ons on the user settings page
Update language for add-ons on the user settings page
N/A
N/A
[ENG-8243]: https://openscience.atlassian.net/browse/ENG-8243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-8243] Update language for add-ons on the user settings page - Ember FE

- lib/osf-components/addon/components/addons-service/manager/component.ts
-   Ticket: [ENG-8242]
[ENG-8242]: https://openscience.atlassian.net/browse/ENG-8242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-8242] M2 QA - FE: Display name cannot be changed

- lib/osf-components/addon/components/addons-service/manager/component.ts
- mirage/serializers/addon-operation-invocation.ts
-   Ticket: [ENG-8233]
[ENG-8233]: https://openscience.atlassian.net/browse/ENG-8233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-8233] Fix "unresponsive" "Link" button when the connected Dataverse account is empty

- app/serializers/collection-submission.ts
-   Ticket: [eng-8159]
Quick fix to get this release and prevent major merging issues
Copied the changes from an old PR that I failed to merge.
> [eng-8159] Allow collections without metadata to be submitted

- app/preprints/-components/preprint-metrics/component.ts
> apiMetrics -> apiMeta
